<?php 
	defined('BASE_URL')	|| define('BASE_URL', Zend_Controller_Front::getInstance()->getBaseUrl());
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$form=$this->form;
	$url_submit =  $this->url(array('module'=>'product','controller'=>'index','action'=>'add'));
    $url_cencel =  $this->url(array('module'=>'product','controller'=>'index','action'=>'index'));
    $url_check =  $this->url(array('module'=>'product','controller'=>'index','action'=>'check'));
    $url_new = $this->url(array('module'=>'product','controller'=>'index','action'=>'add'));
	$user_info = new Application_Model_DbTable_DbGetUserInfo();
	$result = $user_info->getUserInfo();
	$session_user=new Zend_Session_Namespace('auth');
	$request=Zend_Controller_Front::getInstance()->getRequest();
	$level = $result["level"];
?>						 
<title><?php echo $tr->translate("ADD_NEW_PRODUCT");?></title>
<style>
.table>tbody>tr>td, .table>tfoot>tr>td, .table>thead>tr>td {
    padding: 2px 2px;
}
</style>
<div class="card pb-10 pt-10 pl-10 pr-10">
	<div class="card-content">
		<div class="card-box">
            <div class="col-sm-12 border-botom">
		    	<div class="col-sm-8 pd-0">
		    		<h4 class="m-b-0"><i class="fa fa-cube" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('ADD_NEW_PRODUCT');?></h4>
    			</div>
    			<div class="col-sm-4 text-right">
    			</div>
    		</div>
    	</div>
		<div class="card-box">
			<form dojoType="dijit.form.Form" id="frm" method="post" action="<?php echo $url_submit;?>" enctype="multipart/form-data" autocomplete="off" >				
				 <script type="dojo/method" event="onSubmit">			
					if(this.validate()) {
						category = dijit.byId("category").get('value');
   	 					if(category==''){
       					 	alert("សូមជ្រើសរើស ប្រភេទផលិតផល! ");
        					dijit.byId("category").focus();
        					return false;
    					}
    					identity = $("#identity").val();
    					if(identity==''){
	 						alert("សូមបញ្ចូលបរិមាណទំនិញ");
	 						addProLocation();
	   						return false;
     					}
               			loadingBlock();
						return true;
					}else{
						return false;
					}
				</script>
				<div class="col-md-5">
					<div class="form-group">
	                   <label class="control-label col-md-12 col-sm-12 col-xs-12 title-blog bold" ><i class="fa fa-hand-o-right" aria-hidden="true"></i> <?php echo $tr->translate("PRODUCT_INFO");?> 
	                   </label>
	                </div>
					<div class="form-group">
						<label class="col-md-4 control-label"><?php echo $tr->translate("TYPE");?>*</label>
						<div class="col-md-8"><?php echo $form->getElement('type');?></div>
					</div>
					<div class="form-group">
						<label class="col-md-4 control-label"><strong><?php echo $tr->translate("PRODUCT_NAME");?>*</strong></label>
						<div class="col-md-8"><?php echo $form->getElement('name');?></div>
					</div>
					<div class="form-group">
						<label class="col-md-4 control-label"><?php echo $tr->translate("PRODUCT_CODE");?></label>
						<div class="col-md-8"><?php echo $form->getElement('pro_code');?></div>	
					</div>
					<div class="form-group">
						<label class="col-md-4 control-label"><?php echo $tr->translate("BARCODE");?></label>
						<div class="col-md-8"><?php echo $form->getElement('barcode');?></div>
					</div>
					<div class="form-group">
						<label class="col-md-4 control-label"><?php echo $tr->translate("BRAND_NAME");?></label>
						<div class="col-md-8">
							<?php echo $form->getElement('brand');?>
						</div>
					</div>
					<div class="form-group">
						<label class="col-md-4 control-label"><?php echo $tr->translate("PRODUCT_CATEGORY");?>*</label>
						<div class="col-md-8"><?php echo $form->getElement('category');?></div>
					</div>
					<div class="form-group">
						<label class="col-md-4 control-label"><?php echo $tr->translate("COLOR");?></label>
						<div class="col-md-8">
							<?php echo $form->getElement('color');?>
						</div>
					</div>
					<div class="form-group">
						<label class="col-md-4 control-label"><?php echo $tr->translate("MEASURE");?></label>
						<div class="col-md-2">
							<?php echo $form->getElement('unit');?>
						</div>
						<div class="col-md-6">
							<?php echo $form->getElement('measure');?>
						</div>
					</div>
					<div class="form-group">
						<label class="col-md-3 control-label" id="lb_measure" style="text-align: center;"></label>
						<label class="col-md-1 control-label" style="text-align: center;">=</label>
						<div class="col-md-4">
							<?php echo $form->getElement('qty_unit');?>
						</div>
						<div class="col-md-4">
							<?php echo $form->getElement('label');?>
						</div>
					</div>
				</div>
				<div class="col-md-5">
					<div class="form-group">
	                   <label class="control-label col-md-12 col-sm-12 col-xs-12 title-blog bold" ><i class="fa fa-money" aria-hidden="true"></i> <?php echo $tr->translate("PRICE_SETTING");?></label>
	                </div>
					<div class="form-group">
						<label class="col-md-4 control-label"><strong><?php echo $tr->translate("COST_PRICE");?>*</strong></label>
						<div class="col-md-8">
							<?php echo $form->getElement('price');?>
						</div>
					</div>		
					<div class="form-group">
						<label class="col-md-4 control-label"><?php echo $tr->translate("PRODUCT_PRICE_INFO");?></label>
						<label class="col-md-8 control-label"><?php echo $form->getElement('price_type');?></label>
					</div>
					<div class="form-group">
						<div class="col-md-4"></div>
						<div class="col-md-8">
							<table class="table table-bordered" style="font-size: 11px;">
								<thead>
									<tr>
										<th>#</th>
										<th><?php echo $tr->translate("TYPE_NAME");?></th>
										<th><?php echo $tr->translate("SOLD_PRICE");?></th>
										<th><?php echo $tr->translate("ACTION");?></th>
									</tr>
								</thead>
								<tbody id="tr_price_type"></tbody>
							</table>
						</div>
					</div>
					<div class="form-group">
						<label class="col-md-4 control-label"><?php echo $tr->translate("NOTE");?></label>
						<div class="col-md-8">
							<?php echo $form->getElement('description');?>
						</div>
					</div>
				</div>
				<div class="col-md-2">
					<div class="form-group">
	                   <label class="control-label col-md-12 col-sm-12 col-xs-12 title-blog bold" ><i class="fa fa-picture-o" aria-hidden="true"></i> <?php echo $tr->translate("PHOTO");?></label>
	                </div>
					<div class="form-group">
						<div class="col-md-12">
							<div class="imgBlog">
							<img class="image_view bd" id="image_viewbg" src="<?php echo $this->baseUrl().'/images/no-image.png';?>" alt=""  />
							<div class="button_browse">
								<span>Upload Imags &nbsp;&nbsp;<span><i class="fa fa-camera" aria-hidden="true"></i></span></span>
								<input class="btn_borwse_image"  type="file" id="photo" name="photo">
							</div>
						</div>
						</div>
					</div>
			</div>
			<div class="card-box">
	            <div class="col-sm-12 border-botom">
			    	<div class="col-sm-8 pd-0">
			    		<h4 class="m-b-0"><i class="fa fa-cube" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('PRODUCT_LOCATION');?></h4>
	    			</div>
	    			<div class="col-sm-4 text-right">
	    			</div>
	    		</div>
	    	</div>
			<div class="col-md-6">
                <div class="portlet box blue">
					<div class="portlet-title">
						<div class="caption" style="width:100%">
							<?php echo $form->getElement('branch');?>
						</div>
					</div>
				</div>
				<div class="table-responsive">
					<table class="table table-bordered" style="font-size:12px !important;">
						<thead>
							<tr>
								<th>#</th>
								<th><?php echo $tr->translate("LOCATION_NAME");?></th>
								<th><?php echo $tr->translate("UNIT_QTY");?></th>
								<th><?php echo $tr->translate("QTY_PER_UNIT");?></th>
								<th><?php echo $tr->translate("TOTAL_QTY");?></th>
								<th><?php echo $tr->translate("QTY_WARNING");?></th>
								<th><?php echo $tr->translate("ACTION");?>
									<input type="hidden" name="identity" id="identity" value="<?php //echo $identity;?>" >
								</th>
							</tr>
						</thead>
						<tbody id="tr_location"></tbody>
					</table>
				</div>
			</div>
			<div class="portlet-body">
				<div class="table-responsive"></div>
				<input type="hidden" name="identity_price" id="identity_price" value="<?php //echo $identity;?>" >
			</div>
			<div class="card-box">
				<div class="border-top">
					<div class="col-md-4"></div>
					<div class="col-md-5" class='center'>
						<input type="submit" value="save_new" id="save_close" name="save_close" label="<?php echo $tr->translate("SAVE_CLOSE")?>" dojoType="dijit.form.Button" 
							iconClass="dijitEditorIcon dijitEditorIconSave" />
						<input type="submit" value="btnsavenew" id="btnsavenew" name="save_close" label="<?php echo $tr->translate("SAVE_NEW")?>" dojoType="dijit.form.Button" 
							iconClass="dijitEditorIcon dijitEditorIconSave" />
					</div>
					<div class="col-md-3"></div>
				</div>
			</div>
			</form>	
		</div>
	</div>
</div>
<!--Popup Form Brand-->
<?php $formBrand = $this->frmBrand; ?>
<div id="brandpopup" class="modal fade" tabindex="-1" data-width="1200">
       <div class="modal-dialog">
      <div class="modal-content">
      <div class="modal-header">   
		<div class="row">
		<div class="col-md-12">
			<div class="portlet box blue">
			<div class="portlet-title">
				<div class="caption">
					<i class="icon-home"></i><?php echo $tr->translate("ADD_NEW_BRAND");?>
				</div>
				<div class="caption pull-right">
					<a href="<?php echo $url_new;?>" >
						 <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
					</a>
				</div>
			</div>
			<div class="portlet-body form">
				<form id="frmbrand" name="frmcustomer" class="form-horizontal" enctype="multipart/form-data" method="post">
						<div class="form-body">
							<div class="form-group">
								<label class="col-md-2 control-label"><?php echo $tr->translate("PARENT");?></label>
								<div class="col-md-4">
									<?php echo $formBrand->getElement('parent');?>
								</div>
								<label class="col-md-2 control-label"><?php echo $tr->translate("BRAND_NAME");?></label>
								<div class="col-md-4">
									<?php echo $formBrand->getElement('brand_name');?>
								</div>
							</div>
							<div class="form-group">
								<label class="col-md-2 control-label"><?php echo $tr->translate("STATUS");?></label>
								<div class="col-md-4">
									<?php echo $formBrand->getElement('status');?>
								</div>
												
								<label class="col-md-2 control-label"><?php echo $tr->translate("REMARK");?></label>
								<div class="col-md-4">
									<?php echo $formBrand->getElement('remark');?>
								</div>
						</div>
						<div class="form-group">
							<label  class="col-md-12 col-md-offset-4 col-md-8">
								<button type="button" name="btnsavenew" onclick="addNewBrand();" class="btn btn-primary"><i class="fa fa-save"></i> <?php echo $tr->translate("SAVE_CLOSE")?> </button>
							</label>
						</div>
					</div>
				</form>
			</div>
		</div>
	</div>
</div>
          </div>
        </div>
    </div>
 </div>	

<!-- CATEGORY Popup -->
<?php $formcat = $this->frmCat; ?>
<div id="categorypopup" class="modal fade" tabindex="-1" data-width="1200">
       <div class="modal-dialog">
      <div class="modal-content">
      <div class="modal-header">   
		<div class="row">
		<div class="col-md-12">
			<div class="portlet box blue">
			<div class="portlet-title">
				<div class="caption">
					<i class="icon-home"></i><?php echo $tr->translate("ADD_PRODUCT_CATEGORY");?>
				</div>
				<div class="caption pull-right">
					<a href="<?php echo $url_new;?>" >
						 <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
					</a>
				</div>
			</div>
			<div class="portlet-body form">
				<form id="frmCat" name="frmcustomer" class="form-horizontal" enctype="multipart/form-data" method="post">
				<div class="form-body">
					<div class="form-group">
								<label class="col-md-2 control-label"><?php echo $tr->translate("PARENT");?></label>
								<div class="col-md-4">
									<?php echo $formcat->getElement('parent');?>
								</div>
								<label class="col-md-2 control-label"><?php echo $tr->translate("CATEGORY_NAME");?></label>
								<div class="col-md-4">
									<?php echo $formcat->getElement('cat_name');?>
								</div>
												
							</div>
							<div class="form-group">
												
								<label class="col-md-2 control-label"><?php echo $tr->translate("STATUS");?></label>
								<div class="col-md-4">
									<?php echo $formcat->getElement('status');?>
								</div>
								<label class="col-md-2 control-label"><?php echo $tr->translate("REMARK");?></label>
								<div class="col-md-4">
									<?php echo $formcat->getElement('remark');?>
								</div>
							</div>
							<div class="form-group">
								<label  class="col-md-12 col-md-offset-4 col-md-8">
									<button type="button" name="btnsavenew" onclick="addNewCategory();" class="btn btn-primary"><i class="fa fa-save"></i> <?php echo $tr->translate("SAVE_CLOSE")?> </button>
								</label>
							</div>
				</div>
				</form>
			</div>
		</div>
	</div>
</div>
          </div>
        </div>
    </div>
 </div>	

<!-- MEASURE Popup-->
<?php $frmMesure = $this->frmMesure; ?>
<div id="measurepopup" class="modal fade" tabindex="-1" data-width="1200">
       <div class="modal-dialog">
      <div class="modal-content">
      <div class="modal-header">   
		<div class="row">
		<div class="col-md-12">
			<div class="portlet box blue">
			<div class="portlet-title">
				<div class="caption">
					<i class="icon-home"></i><?php echo $tr->translate("ADD_MEASURE_NAME");?>
				</div>
				<div class="caption pull-right">
					<a href="<?php echo $url_new;?>" >
						 <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
					</a>
				</div>
			</div>
			<div class="portlet-body form">
				<form id="frmMesure" name="frmcustomer" class="form-horizontal" enctype="multipart/form-data" method="post">
				<div class="form-body">
					<div class="form-group">
								<label class="col-md-4 control-label"><?php echo $tr->translate("MESUER_NAME");?></label>
								<div class="col-md-6">
									<?php echo $frmMesure->getElement('measure_name');?>
								</div>
												
							</div>
							<div class="form-group">
												
								<label class="col-md-4 control-label"><?php echo $tr->translate("STATUS");?></label>
								<div class="col-md-6">
									<?php echo $frmMesure->getElement('status');?>
								</div>
							</div>
							<div class="form-group">
												
								<label class="col-md-4 control-label"><?php echo $tr->translate("REMARK");?></label>
								<div class="col-md-6">
									<?php echo $frmMesure->getElement('remark');?>
								</div>
							</div>
					
					<div class="form-group">
						<label  class="col-md-12 col-md-offset-4 col-md-8">
							<button type="button" name="btnsavenew" onclick="addNewMeasure();" class="btn btn-primary"><i class="fa fa-save"></i> <?php echo $tr->translate("SAVE_CLOSE")?> </button>
						</label>
					</div>
				</div>
				</form>
			</div>
		</div>
	</div>
</div>
          </div>
        </div>
    </div>
 </div>	
<!-- Color Model Size Popup -->
<?php $frmOther = $this->frmOther; ?>
<div id="otherpopup" class="modal fade" tabindex="-1" data-width="1200">
       <div class="modal-dialog">
      <div class="modal-content">
      <div class="modal-header">   
		<div class="row">
		<div class="col-md-12">
			<div class="portlet box blue">
			<div class="portlet-title">
				<div class="caption">
					<i class="icon-home"></i><?php echo $tr->translate("ADD_NEW_COLOR");?>
				</div>
				<div class="caption pull-right">
					<a href="<?php echo $url_new;?>" >
						 <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
					</a>
				</div>
			</div>
			<div class="portlet-body form">
				<form id="frmOther" name="frmOther" class="form-horizontal" enctype="multipart/form-data" method="post">
				<div class="form-body">
					<div class="form-group">
									<label class="col-md-4 control-label"><?php echo $tr->translate("TITLE");?></label>
									<div class="col-md-6">
										<?php echo $frmOther->getElement('title_en');?>
									</div>
													
								</div>
								<div class="form-group">
									<label class="col-md-4 control-label"><?php echo $tr->translate("TYPE");?></label>
									<div class="col-md-6">
										<?php echo $frmOther->getElement('type');?>
									</div>
													
								</div>
								<div class="form-group">
													
									<label class="col-md-4 control-label"><?php echo $tr->translate("STATUS");?></label>
									<div class="col-md-6">
										<?php echo $frmOther->getElement('status');?>
									</div>
								</div>
					
					<div class="form-group">
						<label  class="col-md-12 col-md-offset-4 col-md-8">
							<button type="button" id="savecolor"name="btnsavenew" onclick="addNewColor();" class="btn btn-primary"><i class="fa fa-save"></i> <?php echo $tr->translate("SAVE_CLOSE")?> </button>
							<button type="button" id="savemodel" name="btnsavenew" onclick="addNewModel();" class="btn btn-primary"><i class="fa fa-save"></i> <?php echo $tr->translate("SAVE_CLOSE")?> </button>
							<button type="button"id="savesize" name="btnsavenew" onclick="addNewSize();" class="btn btn-primary"><i class="fa fa-save"></i> <?php echo $tr->translate("SAVE_CLOSE")?> </button>
						</label>
					</div>
				</div>
				</form>
			</div>
		</div>
	</div>
</div>
          </div>
        </div>
    </div>
 </div>
<script>
$( document ).ready(function() {
	$('#price_type').val(1);
	addProLocation();
	addNewPriceType();
	$('#product_id').on('keyup keypress', function(e) {
		var keyCode = e.keyCode || e.which;
	  if (keyCode === 13) { 
		e.preventDefault();
		return false;
	  }
	});
});
function getMeasureLabel(){
	var sel = $("#measure");
	var text = $("option:selected",sel).text();
	document.getElementById('lb_measure').innerHTML = text; 
}
	index = 0;
function addProLocation(){
		<?php if(!empty($this->branch)){foreach ($this->branch as $key=> $rs){?>
		index++;
		id = '<?php echo $rs["id"];?>';
		inx = '<?php echo $key+1;?>';
			template='<tr id="row_location_<?php echo $key+1;?>">';
			template+='<td><?php echo $key+1;?></td>';
			template+='<td style="min-width:100px;"><?php echo $rs["name"];?><input type="hidden" id="branch_id_<?php echo $key+1;?>" name="branch_id_<?php echo $key+1;?>" value="'+id+'"</td>';
			template+='<td><input type="text" dojoType="dijit.form.NumberTextBox" required="true" id="current_qty_<?php echo $key+1;?>" onKeyup="totalQty(<?php echo $key+1;?>)" name="current_qty_<?php echo $key+1;?>" value="0" class="form-control"></td>'; 
			template+='<td><input type="text" dojoType="dijit.form.NumberTextBox" required="true" id="other_qty_<?php echo $key+1;?>" onKeyup="totalQty(<?php echo $key+1;?>)" name="other_qty_<?php echo $key+1;?>" value="0" class="form-control"></td>'; 
			template+='<td><input readonly dojoType="dijit.form.NumberTextBox" required="true" type="text" id="total_qty_<?php echo $key+1;?>" name="total_qty_<?php echo $key+1;?>" value="0" class="form-control"></td>'; 
			template+='<td><input type="text" dojoType="dijit.form.NumberTextBox" required="true" id="qty_warning_<?php echo $key+1;?>" name="qty_warnning_<?php echo $key+1;?>" value="0" class="form-control"></td>';
			template+='<td><button type="button" onClick="deleteRecord(<?php echo $key+1;?>,1)" name="save_close" class="btn default"><?php echo $tr->translate("DELETE");?></button></td>';
			template+='</tr>';
			$('#tr_location').append(template);
			if($('#identity').val()!="") {
				var identity = $('#identity').val();
				$('#identity').val(identity+','+inx);
			} else {$('#identity').val(inx);}
		<?php }}?>
}
	
function totalQty(index){
	o_measure = $('#qty_unit').val();
	unit_qty = $('#current_qty_'+index).val();
	other_qty = $('#other_qty_'+index).val();
	total_other_qty = parseFloat(other_qty)/parseFloat(o_measure);
	total_qty = parseFloat(unit_qty)+ total_other_qty;
	$('#total_qty_'+index).val(total_qty);
}
	
function doTotalQty(){
	o_measure = $('#qty_unit').val();
	if(o_measure=="" || o_measure==0){
		$('#qty_unit').val(1);
	}
	var identity = $('#identity').val();
	if(identity!=""){
		var arrays = identity.split(',');
		for(var index=0;index<arrays.length;index++) {
			o_measure = $('#qty_unit').val();
			unit_qty = $('#current_qty_'+index).val();
			other_qty = $('#other_qty_'+index).val();
			total_other_qty = parseFloat(other_qty)/parseFloat(o_measure);
			total_qty = parseFloat(unit_qty)+ total_other_qty;
			$('#total_qty_'+index).val(total_qty);
		}
	}
	var strings = arrays.join(',');
}
function addNewProLocation(){
		index++;
		var branch_text = $("#branch");
		var txt_br = $("option:selected",branch_text).text();
		var branch_id = $("#branch").val();
		template='<tr id="row_location_'+index+'">';
		template+='<td>'+index+'</td>';
		template+='<td>'+txt_br+'<input type="hidden" id="branch_id_'+index+'" name="branch_id_'+index+'" value="'+branch_id+'" </td>';
		template+='<td><input type="text" dojoType="dijit.form.NumberTextBox" required="true" id="current_qty_'+index+'" onKeyup="totalQty('+index+')" name="current_qty_'+index+'" value="0" class="form-control"></td>'; 
		template+='<td><input type="text" dojoType="dijit.form.NumberTextBox" required="true" id="other_qty_'+index+'" onKeyup="totalQty('+index+')" name="other_qty_'+index+'" value="0" class="form-control"></td>'; 
		template+='<td><input type="text" dojoType="dijit.form.NumberTextBox" required="true" id="total_qty_'+index+'" name="total_qty_'+index+'" value="0" class="form-control"></td>'; 
		template+='<td><input type="text" dojoType="dijit.form.NumberTextBox" required="true" id="qty_warning_'+index+'" name="qty_warnning_'+index+'" value="0" class="form-control"></td>';
		template+='<td><button type="button" onClick="deleteRecord('+index+',1)" name="save_close" class="btn default"><?php echo $tr->translate("DELETE");?></button></td>';
		template+='</tr>';
		$('#tr_location').append(template);
		if($('#identity').val()!="") {
			var identity = $('#identity').val();
			$('#identity').val(identity+','+index);
		} else {$('#identity').val(index);}
		
}	
indexs=0;
function addNewPriceType(){
		indexs++;
		var price_text = $("#price_type");
		var txt_pr = $("option:selected",price_text).text();
		var price_id = $("#price_type").val();
		template='<tr id="row_price_'+indexs+'">';
		template+='<td >'+indexs+'</td>';
		template+='<td style="white-space:nowrap">'+txt_pr+'<input type="hidden" id="price_type_'+indexs+'" name="price_type_'+indexs+'" value="'+price_id+'" </td>';
		template+='<td><input type="text" required="true" dojoType="dijit.form.NumberTextBox" id="price_'+indexs+'" name="price_'+indexs+'" value="0" class="form-control"></td>'; 
		template+='<td><button type="button" onClick="deleteRecord('+indexs+',2)" name="save_close" class="btn default"><?php echo $tr->translate("DELETE");?></button></td>';
		template+='</tr>';
		$('#tr_price_type').append(template);
		if($('#identity_price').val()!="") {
			var identity_price = $('#identity_price').val();
			$('#identity_price').val(identity_price+','+indexs);
		} else {$('#identity_price').val(indexs);}
		
}
function deleteRecord(index,type) {
	if(type==1){
		var identity = $('#identity').val();
		var arrays = identity.split(',');
	}else{
		var identity = $('#identity_price').val();
		var arrays = identity.split(',');
	}
	
	for(var i=0;i<arrays.length;i++) {
		if(arrays[i] == index) arrays.splice(i,1);
	}
	var strings = arrays.join(',');
	
	if(type==1){
		$('#identity').val(strings);
		$("#row_location_"+index).remove();
	}else{
		$('#identity_price').val(strings);
		$("#row_price_"+index).remove();
	}
}
function getPopupBrand(){
	val = $('#brand').val();
	if(val==-1){
		$('#brandpopup').modal('show');
	}
}

function getPopupCategory(){
	val = $('#category').val();
	if(val==-1){
		$('#categorypopup').modal('show');
	}
}

function getPopupMeasure(){
	val = $('#measure').val();
	if(val==-1){
		$('#measurepopup').modal('show');
	}
}

function getPopupColor(){
	val = $('#color').val();
	if(val==-1){
		$('#otherpopup').modal('show');
		$('#type').val(4);
		$('#type').attr('readOnly',true);
		$('#savemodel').hide();
		$('#savesize').hide();
		$('#savecolor').show();
	}
}

function getPopupModel(){
	val = $('#model').val();
	if(val==-1){
		$('#otherpopup').modal('show');
		$('#type').val(2);
		$('#type').attr('readOnly',true);
		$('#savecolor').hide();
		$('#savesize').hide();
		$('#savemodel').show();
	}
}

function getPopupSize(){
	val = $('#size').val();
	if(val==-1){
		$('#otherpopup').modal('show');
		$('#type').val(3);
		$('#type').attr('readOnly',true);
		$('#savemodel').hide();
		$('#savecolor').hide();
		$('#savesize').show();
	}
}

<?php $url_add_brand =  $this->url(array('module'=>'product','controller'=>'index','action'=>'add-brand')); ?>
function addNewBrand(){
	var brand_name  = $("#brand_name").val();
	if(brand_name==''){$("#brand_name").focus();return false;}
	$.ajax({
		url: "<?php echo $url_add_brand;?>",
		type: "post",
		data: $('#frmbrand').serialize(),
		success: function(data){
			rs = $.parseJSON(data);
			 $('#brand').append($("<option></option>").attr("value",rs['brand_id']).attr("selected",true).text(brand_name));                       
			 $("#brand").select2();
			$('#brandpopup').modal('hide');
		},
		error:function(err){
			alert("faile insert");
		   
		}
	});
}
<?php $url_add_category =  $this->url(array('module'=>'product','controller'=>'index','action'=>'add-category')); ?>
function addNewCategory(){
	var cat_name  = $("#cat_name").val();
	if(cat_name==''){$("#cat_name").focus();return false;}
	$.ajax({
		url: "<?php echo $url_add_category;?>",
		type: "post",
		data: $('#frmCat').serialize(),
		success: function(data){
			rs = $.parseJSON(data);
			 $('#category').append($("<option></option>").attr("value",rs['cat_id']).attr("selected",true).text(cat_name));                       
			 $("#category").select2();
			$('#categorypopup').modal('hide');
		},
		error:function(err){
			alert("faile insert");
		   
		}
	});
}
<?php $url_add_measure =  $this->url(array('module'=>'product','controller'=>'index','action'=>'add-measure')); ?>
function addNewMeasure(){
	var measure_name  = $("#measure_name").val();
	if(measure_name==''){$("#measure_name").focus();return false;}
	$.ajax({
		url: "<?php echo $url_add_measure;?>",
		type: "post",
		data: $('#frmMesure').serialize(),
		success: function(data){
			rs = $.parseJSON(data);
			 $('#measure').append($("<option></option>").attr("value",rs['measure_id']).attr("selected",true).text(measure_name));                       
			 $("#measure").select2();
			$('#measurepopup').modal('hide');
			document.getElementById('lb_measure').innerHTML = measure_name; 
		},
		error:function(err){
			alert("faile insert");
		}
	});
}

<?php $url_add_color =  $this->url(array('module'=>'product','controller'=>'index','action'=>'add-other')); ?>
function addNewColor(){
	var title  = $("#title_en").val();
	if(title==''){$("#title_en").focus();return false;}
	$.ajax({
		url: "<?php echo $url_add_color;?>",
		type: "post",
		data: $('#frmOther').serialize(),
		success: function(data){
			rs = $.parseJSON(data);
			 $('#color').append($("<option></option>").attr("value",rs['other_id']).attr("selected",true).text(title));                       
			 $("#color").select2();
			$('#otherpopup').modal('hide');
		},
		error:function(err){
			alert("faile insert");
		   
		}
	});
}

function addNewModel(){
	var title  = $("#title_en").val();
	if(title==''){$("#title_en").focus();return false;}
	$.ajax({
		url: "<?php echo $url_add_color;?>",
		type: "post",
		data: $('#frmOther').serialize(),
		success: function(data){
			rs = $.parseJSON(data);
			 $('#model').append($("<option></option>").attr("value",rs['other_id']).attr("selected",true).text(title));                       
			 $("#model").select2();
			$('#otherpopup').modal('hide');
		},
		error:function(err){
			alert("faile insert");
		   
		}
	});
}
function addNewSize(){
		var title  = $("#title_en").val();
		$.ajax({
			url: "<?php echo $url_add_color;?>",
			type: "post",
			data: $('#frmOther').serialize(),
			success: function(data){
				rs = $.parseJSON(data);
				 $('#size').append($("<option></option>").attr("value",rs['other_id']).attr("selected",true).text(title));                       
				 $("#size").select2();
				$('#otherpopup').modal('hide');
			},
			error:function(err){
				alert("faile insert");
			   
			}
		});
	}
function readURL(input) {
    if (input.files && input.files[0]) {
        var reader = new FileReader();
        
        reader.onload = function (e) {
            $('#image_viewbg').attr('src', e.target.result);
        }
        reader.readAsDataURL(input.files[0]);
    }
}
var maxSize = 0;
$("#photo").change(function(){
	var iSize = ($("#photo")[0].files[0].size / 1024); 
    if (iSize / 1024 > 1) 
    { 
       if (((iSize / 1024) / 1024) > 1) 
       { 
           iSize = (Math.round(((iSize / 1024) / 1024) * 100) / 100);
           maxSize = 0;
       }else{ 
           iSize = (Math.round((iSize / 1024) * 100) / 100);
           if(iSize>5){
               alert('<?php echo $tr->translate("Image size more than 5Mb can not upload");?>');
               maxSize = 1;
               $('#image_viewbg').attr('src', "<?php echo $this->baseUrl().'/images/no-image.png';?>");
               return false;
           }
       } 
    } 
    else 
    {
       iSize = (Math.round(iSize * 100) / 100);
       maxSize = 0;
    }    
    
    readURL(this);
});
dojo.require("dijit.form.NumberTextBox");
</script>		