<?php 
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$form=$this->form;
	$images=$this->baseUrl().'/images/no-image.png';
	if(!empty($this->rs['photo'])){
		$images=$this->baseUrl().'/images/product/'.$this->rs['photo'];
	}
?>						 
<title><?php echo $tr->translate("EDIT_PRODUCT");?></title>
<div class="card pb-10 pt-10 pl-10 pr-10">
	<div class="card-content">
		<div class="card-box">
            <div class="col-sm-12 border-botom">
		    	<div class="col-sm-8 pd-0">
		    		<h4 class="m-b-0"><i class="fa fa-cube" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('EDIT_PRODUCT');?></h4>
    			</div>
    			<div class="col-sm-4 text-right">
    			</div>
    		</div>
    	</div>
    	<div class="card-box">
			<form dojoType="dijit.form.Form" class="form-horizontal"  method="post"  enctype="multipart/form-data" autocomplete="off"  >				
				 <script type="dojo/method" event="onSubmit">			
					if(this.validate()) {
						category = dijit.byId("category").get('value');
   	 					if(category==''){
       					 	alert("សូមជ្រើសរើស ប្រភេទផលិតផល! ");
        					dijit.byId("category").focus();
        					return false;
    					}
    					identity = $("#identity").val();
    					if(identity==''){
	 						alert("សូមបញ្ចូលបរិមាណទំនិញ");
	 						addProLocation();
	   						return false;
     					}
               			loadingBlock();
						return true;
					}else{
						return false;
					}
				</script>
				<div class="col-md-5">
					<div class="form-group">
	                   <label class="control-label col-md-12 col-sm-12 col-xs-12 title-blog bold" ><i class="fa fa-hand-o-right" aria-hidden="true"></i> <?php echo $tr->translate("PRODUCT_INFO");?> 
	                   </label>
	                </div>
					<div class="form-group">
							<label class="col-md-4 control-label"><?php echo $tr->translate("TYPE");?>*</label>
							<div class="col-md-8"><?php echo $form->getElement('type');?></div>
					</div>
					<div class="form-group">
							<label class="col-md-4 control-label"><strong><?php echo $tr->translate("PRODUCT_NAME");?>*</strong></label>
							<div class="col-md-8"><?php echo $form->getElement('name');?></div>
					</div>
					<div class="form-group">
						<label class="col-md-4 control-label"><?php echo $tr->translate("PRODUCT_CODE");?></label>
						<div class="col-md-8"><?php echo $form->getElement('pro_code');?></div>	
					</div>
					<div class="form-group">
						<label class="col-md-4 control-label"><?php echo $tr->translate("BARCODE");?></label>
						<div class="col-md-8"><?php echo $form->getElement('barcode');?></div>
					</div>
					<div class="form-group">
						<label class="col-md-4 control-label"><?php echo $tr->translate("BRAND_NAME");?></label>
						<div class="col-md-5">
							<?php echo $form->getElement('brand');?>
						</div>
						<div class="col-md-3">
							<input class='fullside' iconClass="dijitIconUndo" type="button" label="Refresh" dojoType="dijit.form.Button" onclick="AllRefresh();"/>
						</div>
					</div>
					<div class="form-group">
						<label class="col-md-4 control-label"><?php echo $tr->translate("PRODUCT_CATEGORY");?>*</label>
						<div class="col-md-8"><?php echo $form->getElement('category');?></div>
					</div>
					<div class="form-group">
						<label class="col-md-4 control-label"><?php echo $tr->translate("COLOR");?></label>
						<div class="col-md-8">
							<?php echo $form->getElement('color');?>
						</div>
					</div>
					<div class="form-group">
					<label class="col-md-4 control-label"><?php echo $tr->translate("MEASURE");?></label>
					<div class="col-md-2">
						<?php echo $form->getElement('unit');?>
					</div>
					<div class="col-md-6">
						<?php echo $form->getElement('measure');?>
					</div>
					</div>
					<div class="form-group">
						<label class="col-md-3 control-label" id="lb_measure" style="text-align: center;color:red;"></label>
						<label class="col-md-1 control-label" style="text-align: center;">=</label>
						<div class="col-md-4">
							<?php echo $form->getElement('qty_unit');?>
						</div>
						<div class="col-md-4">
							<?php echo $form->getElement('label');?>
						</div>
					</div>
				</div>
				<div class="col-md-5">
					<div class="form-group">
	                   <label class="control-label col-md-12 col-sm-12 col-xs-12 title-blog bold" ><i class="fa fa-money" aria-hidden="true"></i> <?php echo $tr->translate("PRICE_SETTING");?></label>
	                </div>
					<div class="form-group">
						<label class="col-md-4 control-label"><strong><?php echo $tr->translate("COST_PRICE");?>*</strong></label>
						<div class="col-md-8">
							<?php echo $form->getElement('price');?>
						</div>
					</div>		
					<div class="form-group">
						<label class="col-md-4 control-label"><?php echo $tr->translate("PRODUCT_PRICE_INFO");?></label>
						<label class="col-md-8 control-label"><?php echo $form->getElement('price_type');?>
							<input type="hidden" name="identity_price" id="identity_price" value="" >
						</label>
					</div>
					<div class="form-group">
						<div class="col-md-4"></div>
						<div class="col-md-8">
							<table class="table table-bordered" style="font-size: 11px;">
								<thead>
									<tr>
										<th>#</th>
										<th><?php echo $tr->translate("TYPE_NAME");?></th>
										<th><?php echo $tr->translate("SOLD_PRICE");?></th>
										<th></th>
									</tr>
								</thead>
								<tbody id="tr_price_type">
								</tbody>
							</table>
						</div>
					</div>
					<div class="form-group">
						<label class="col-md-4 control-label"><?php echo $tr->translate("NOTE");?></label>
						<div class="col-md-8">
							<?php echo $form->getElement('description');?>
						</div>
					</div>
					<div class="form-group">
						<label class="col-md-4 control-label"><?php echo $tr->translate("STATUS");?></label>
						<div class="col-md-8">
							<?php echo $form->getElement('status');?>
						</div>
					</div>
				</div>
				<div class="col-md-2">
					<h4 class="underline" >
						<i class="fa fa-hand-o-right" aria-hidden="true"></i>
						<?php echo $tr->translate("PHOTO");?></h4>
					<div class="imgBlog">
						<img style="border:1px solid #ccc;" class="image_view bd" id="image_viewbg" src="<?php echo $images;?>" alt=""  />
						<div class="button_browse">
							<span>Upload Imags &nbsp;&nbsp;<span><i class="fa fa-camera" aria-hidden="true"></i></span></span>
							<input class="btn_borwse_image"  type="file" id="photo" name="photo">
						</div>
					</div>	
				</div>
				<div class="card-box">
		            <div class="col-sm-12 border-botom">
				    	<div class="col-sm-8 pd-0">
				    		<h4 class="m-b-0"><i class="fa fa-cube" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('PRODUCT_LOCATION');?></h4>
		    			</div>
		    			<div class="col-sm-4 text-right">
		    			</div>
		    		</div>
		    	</div>
				<div class="card-box">
					<div class="col-md-6">
						<div class="portlet box blue">
							<div class="portlet-title">
								<div class="caption" style="width:100%">
									<?php echo $form->getElement('branch');?>
								</div>
							</div>
						</div>
						<div class="table-responsive">
							<table class="table table-bordered" style="font-size:12px !important;">
								<thead style="background:#cecece">
									<tr>
										<th>#</th>
										<th><?php echo $tr->translate("LOCATION_NAME");?></th>
										<th><?php echo $tr->translate("UNIT_QTY");?></th>
										<th><?php echo $tr->translate("QTY_PER_UNIT");?></th>
										<th><?php echo $tr->translate("TOTAL_QTY");?></th>
										<th style="white-space: nowrap;"><?php echo $tr->translate("QTY_WARNING");?></th>
										<th></th>
									</tr>
								</thead>
								<tbody id="tr_location"></tbody>
							</table>
						</div>
						<input type="hidden" name="identity" id="identity" value="" >
					</div>
				</div>
				<div class="card-box">
					<div class="border-top">
						<div class="col-md-4"></div>
						<div class="col-md-5" class='center'>
							<input type="submit" value="btnsavenew" id="btnsavenew" name="save_close" label="<?php echo $tr->translate("GO_EDIT")?>" dojoType="dijit.form.Button" 
								iconClass="dijitEditorIcon dijitEditorIconSave" />
						</div>
						<div class="col-md-3"></div>
					</div>
				</div>
			</form>
		</div>
	</div>
</div>
<script src="<?php echo $this->baseUrl();?>/js/help.js"  type="text/javascript"></script>
<script>
dojo.require("dojo.data.ItemFileWriteStore");
$( document ).ready(function() {
	addProLocation();
	addPriceType();
	$('#product_id').on('keyup keypress', function(e) {
		var keyCode = e.keyCode || e.which;
	  if (keyCode === 13) { 
		e.preventDefault();
		return false;
	  }
	});
});
function getMeasureLabel(){
	var measur_label = dijit.byId("measure").attr("displayedValue");
	document.getElementById('lb_measure').innerHTML = measur_label; 
}
index = 0;
function addProLocation(){
	template='';
	<?php if(!empty($this->rs_location)){foreach ($this->rs_location as $key=> $rs){?>
	index++;
	o_measure = $('#qty_unit').val();
	raw_qty = '<?php echo $rs['qty'];?>';
	var arrays = raw_qty.split('.');
	unit_qty=parseFloat(arrays[0]);
	other_qty=Math.round((parseFloat(raw_qty)*parseFloat(o_measure))-(parseFloat(arrays[0])*o_measure));
	
	id = '<?php echo $rs["location_id"];?>';
	inx = '<?php echo $key+1;?>';
		template+='<tr id="row_location_<?php echo $key+1;?>">';
		template+='<td><?php echo $key+1;?></td>';
		template+='<td style="min-width:100px;"><?php echo $rs["name"];?><input type="hidden" id="branch_id_<?php echo $key+1;?>" name="branch_id_<?php echo $key+1;?>" value="'+id+'"</td>';
		template+='<td><input type="text" dojoType="dijit.form.NumberTextBox" id="current_qty_<?php echo $key+1;?>" onKeyup="totalQty(<?php echo $key+1;?>)" name="current_qty_<?php echo $key+1;?>"  value="'+unit_qty+'" ></td>'; 
		template+='<td><input type="text" dojoType="dijit.form.NumberTextBox" id="other_qty_<?php echo $key+1;?>" onKeyup="totalQty(<?php echo $key+1;?>)" name="other_qty_<?php echo $key+1;?>" value="'+other_qty+'" ></td>'; 
		template+='<td><input type="text" dojoType="dijit.form.NumberTextBox" id="total_qty_<?php echo $key+1;?>" name="total_qty_<?php echo $key+1;?>" value="<?php echo $rs['qty'];?>" ></td>'; 
		template+='<td><input type="text" dojoType="dijit.form.NumberTextBox" id="qty_warning_<?php echo $key+1;?>" name="qty_warnning_<?php echo $key+1;?>" value="<?php echo $rs['qty_warning'];?>" ></td>';
		template+='<td style="width:20px;"><img onClick="deleteRecord(<?php echo $key+1;?>,1)" src="<?php echo $this->baseUrl();?>/images/Delete_16.png" /></td>';
		template+='</tr>';
		
		if($('#identity').val()!="") {
			var identity = $('#identity').val();
			$('#identity').val(identity+','+inx);
		} else {$('#identity').val(inx);}
	<?php }}?>
	dojo.html.set(dojo.byId("tr_location"),template , {
	     parseContent: true,
	});
}
	
function addNewProLocation(){
	var branch_id = dijit.byId("branch").get('value');
	if(branch_id==''){return false;}
	var iden = $("#identity").val();
	var arrays = iden.split(',');
	if(arrays!=""){
		 for(var i=0;i< arrays.length;i++) {
			 readychoose = $('#branch_id_'+arrays[i]).val();
			 if(readychoose==branch_id){
				alert("បានជ្រើសរើសរួចហើយ");
			 	return false;
			 }
		}
	}
	
	index++;
	var branch_text = $("#branch");
	var branch_text = dijit.byId("branch").attr('displayedValue');
	template='<td>'+index+'</td>';
	template+='<td>'+branch_text+'<input type="hidden" id="branch_id_'+index+'" name="branch_id_'+index+'" value="'+branch_id+'" </td>';
	template+='<td><input required="true" class="fullside" dojoType="dijit.form.NumberTextBox" type="text" id="current_qty_'+index+'" onKeyup="totalQty('+index+')" name="current_qty_'+index+'" value="0" ></td>'; 
	template+='<td><input required="true" class="fullside" dojoType="dijit.form.NumberTextBox" type="text" id="other_qty_'+index+'" onKeyup="totalQty('+index+')" name="other_qty_'+index+'" value="0" ></td>'; 
	template+='<td><input class="fullside" dojoType="dijit.form.NumberTextBox" type="text" id="total_qty_'+index+'" name="total_qty_'+index+'" value="0" ></td>'; 
	template+='<td><input class="fullside" dojoType="dijit.form.NumberTextBox" type="text" id="qty_warning_'+index+'" name="qty_warnning_'+index+'" value="0" ></td>';
	template+='<td style="width:20px;"><img onClick="deleteRecord('+index+',1)" src="<?php echo $this->baseUrl();?>/images/Delete_16.png" /></td>';

	tmp='<tr id="row_location_'+index+'">';
	tmp+="</tr>";
	$('#tr_location').append(tmp);
	dojo.html.set(dojo.byId('row_location_'+index),template , {
	     parseContent: true,
	});
	
	if($('#identity').val()!="") {
		var identity = $('#identity').val();
		$('#identity').val(identity+','+index);
	} else {$('#identity').val(index);}
			
}
function totalQty(index){
	o_measure = $('#qty_unit').val();
	unit_qty = $('#current_qty_'+index).val();
	other_qty = $('#other_qty_'+index).val();
	total_other_qty = parseFloat(other_qty)/parseFloat(o_measure);
	total_qty = parseFloat(unit_qty)+ total_other_qty;
	$('#total_qty_'+index).val(total_qty);
}	
function doTotalQty(){
	o_measure = $('#qty_unit').val();
	if(o_measure=="" || o_measure==0){
		$('#qty_unit').val(1);
	}
	var identity = $('#identity').val();
	if(identity!=""){
		var arrays = identity.split(',');
		for(var index=0;index<arrays.length;index++) {
			o_measure = $('#qty_unit').val();
			unit_qty = $('#current_qty_'+index).val();
			other_qty = $('#other_qty_'+index).val();
			total_other_qty = parseFloat(other_qty)/parseFloat(o_measure);
			total_qty = parseFloat(unit_qty)+ total_other_qty;
			$('#total_qty_'+index).val(total_qty);
		}
	}
}
function addPriceType(){
	<?php if(!empty($this->rs_price)){foreach ($this->rs_price as $key=> $rs){?>
	indexs++;
	id_price = '<?php echo $rs["type_id"];?>';
	inx_price = '<?php echo $key+1;?>';
		template='<td><?php echo $key+1;?></td>';
		template+='<td style="width:100px;"><?php echo $rs["name"];?><input type="hidden" id="price_type_<?php echo $key+1;?>" name="price_type_<?php echo $key+1;?>" value="'+id_price+'"</td>';
		template+='<td><input dojoType="dijit.form.NumberTextBox" type="text" id="price_<?php echo $key+1;?>" name="price_<?php echo $key+1;?>" value="<?php echo $rs["price"];?>" class="form-control"></td>'; 
		template+='<td style="width:20px;"><img onClick="deleteRecord(<?php echo $key+1;?>,2)" src="<?php echo $this->baseUrl();?>/images/Delete_16.png" /></td>';

		tmp='<tr id="row_price_'+<?php echo $key+1;?>+'">';
		tmp+="</tr>";
		$('#tr_price_type').append(tmp);
		
		dojo.html.set(dojo.byId('row_price_'+<?php echo $key+1;?>),template , {
		     parseContent: true,
		});
		
		if($('#identity_price').val()!="") {
			var identity_price = $('#identity_price').val();
			$('#identity_price').val(identity_price+','+inx_price);
		} else {$('#identity_price').val(inx_price);}
	<?php }}?>
}
indexs=0;
function addNewPriceType(){
	indexs++;
	var price_id = dijit.byId("price_type").get('value');
	if(price_id=='' || price_id==-1){
		return false;
	}
	var iden = $("#identity_price").val();
	var arrays = iden.split(',');
	if(arrays!=""){
		 for(var i=0;i< arrays.length;i++){
			 readychoose = $('#price_type_'+arrays[i]).val();
			 if(readychoose==price_id){
				alert("បានជ្រើសរើសរួចហើយ");
			 	return false;
			 }
		}
	}
	var price_text = dijit.byId("price_type").attr("displayedValue");
	template='<td>'+indexs+'</td>';
	template+='<td>'+price_text+'<input type="hidden" id="price_type_'+indexs+'" name="price_type_'+indexs+'" value="'+price_id+'" </td>';
	template+='<td><input required="true" dojoType="dijit.form.NumberTextBox" type="text" id="price_'+indexs+'" name="price_'+indexs+'" class="form-control"></td>'; 
	template+='<td><img onClick="deleteRecord('+indexs+',2)" src="<?php echo $this->baseUrl();?>/images/Delete_16.png" /></td>';

	tmp='<tr id="row_price_'+indexs+'">';
	tmp+="</tr>";
	$('#tr_price_type').append(tmp);
	
	dojo.html.set(dojo.byId('row_price_'+indexs),template , {
	     parseContent: true,
	});
	
	if($('#identity_price').val()!="") {
		var identity_price = $('#identity_price').val();
		$('#identity_price').val(identity_price+','+indexs);
	} else {$('#identity_price').val(indexs);}
			
}
function deleteRecord(index,type) {
	if(type==1){
		var identity = $('#identity').val();
		var arrays = identity.split(',');
	}else{
		var identity = $('#identity_price').val();
		var arrays = identity.split(',');
	}
	
	for(var i=0;i<arrays.length;i++) {
		if(arrays[i] == index) arrays.splice(i,1);
	}
	var strings = arrays.join(',');
	if(type==1){
		$('#identity').val(strings);
		$("#row_location_"+index).remove();
	}else{
		$('#identity_price').val(strings);
		$("#row_price_"+index).remove();
	}
}
function getPopupBrand(){
	val = dijit.byId("brand").get('value');
	if(val==-1){
		window.open('<?php echo $this->baseUrl();?>/product/brand/add?rightclick=true','_blank');
	}
}
function getPopupCategory(){
	val = dijit.byId("category").get('value');
	if(val==-1){
		window.open('<?php echo $this->baseUrl();?>/product/category/add?rightclick=true','_blank');
	}
}
function getPopupMeasure(){
	val = dijit.byId("measure").get('value');
	if(val==-1){
		window.open('<?php echo $this->baseUrl();?>/product/measure/add?rightclick=true','_blank');
	}
}
function getPopupColor(){
	val = dijit.byId("color").get('value');
	if(val==-1){
		window.open('<?php echo $this->baseUrl();?>/product/other/add?rightclick=true','_blank');
	}
}
function getPopupColor(){
	val = dijit.byId("color").get('value');
	if(val==-1){
		window.open('<?php echo $this->baseUrl();?>/product/other/add?rightclick=true','_blank');
	}
}
function AllRefresh(){
	loadingBlock();
	filtterCategory();
	fillterBrand();
	fillterMeasure();
	fillterColor();
}
get_urlbrand = '<?php echo $this->url(array('module'=>'product','controller'=>'index','action'=>'get-brand'));?>';
function fillterBrand(){
	brand = dijit.byId('brand').get('value');
	if(brand==-1){
		return false;
	}
	dojo.xhrPost({
		url:get_urlbrand,	
		content:{ 
			'get_data':1
		},
		handleAs:"json",
		load: function(data) {	
			brand_store  = getDataStorefromJSON('id','name', data);		
		    dijit.byId('brand').set('store', brand_store);
		},
		error: function(err) {
		}
	});	
}
url_getcategory = '<?php echo $this->url(array('module'=>'product','controller'=>'index','action'=>'get-category')); ?>';
function filtterCategory(){
	category = dijit.byId('category').get('value');
	if(category==-1){
		return false;
	}
	dojo.xhrPost({
		url:url_getcategory,	
		content:{ 
			'get_data':1
		},
		handleAs:"json",
		load: function(data) {	
			cate_store  = getDataStorefromJSON('id','name', data);		
		    dijit.byId('category').set('store', cate_store);
		    document.getElementsByClassName("overlay")[0].style.display="none";	
		},
		error: function(err) {
		}
	});	
}
get_mesure = '<?php echo $this->url(array('module'=>'product','controller'=>'index','action'=>'get-measure')); ?>'
function fillterMeasure(){
	measure_id = dijit.byId('measure').get('value');
	if(measure_id==-1){
		return false;
	}
	dojo.xhrPost({
		url:get_mesure,	
		content:{ 
			'get_data':1
		},
		handleAs:"json",
		load: function(data) {	
			measure_store  = getDataStorefromJSON('id','name', data);		
		    dijit.byId('measure').set('store', measure_store);
		    document.getElementsByClassName("overlay")[0].style.display="none";	
		},
		error: function(err) {
		}
	});	
}
url_getcolur = '<?php echo  $this->url(array('module'=>'product','controller'=>'index','action'=>'get-other')); ?>'
function fillterColor(){
	color = dijit.byId('color').get('value');
	if(color==-1){
		return false;
	}
	dojo.xhrPost({
		url:url_getcolur,	
		content:{ 
			'get_data':1
		},
		handleAs:"json",
		load: function(data) {	
			color_store  = getDataStorefromJSON('id','name', data);		
		    dijit.byId('color').set('store', color_store);
		    document.getElementsByClassName("overlay")[0].style.display="none";	
		},
		error: function(err) {
		}
	});	
}
var maxSize = 0;
function readURL(input) {
  if (input.files && input.files[0]) {
      var reader = new FileReader();
      reader.onload = function (e) {
          $('#image_viewbg').attr('src', e.target.result);
      }
      reader.readAsDataURL(input.files[0]);
  }
}
$("#photo").change(function(){
	var iSize = ($("#photo")[0].files[0].size / 1024); 
  if (iSize / 1024 > 1) 
  { 
     if (((iSize / 1024) / 1024) > 1) 
     { 
         iSize = (Math.round(((iSize / 1024) / 1024) * 100) / 100);
         maxSize = 0;
     }else{ 
         iSize = (Math.round((iSize / 1024) * 100) / 100);
         if(iSize>5){
             alert('<?php echo $tr->translate("Image size more than 5Mb can not upload");?>');
             maxSize = 1;
             $('#image_viewbg').attr('src', "<?php echo $this->baseUrl().'/images/no-image.png';?>");
             return false;
         }
     } 
  } 
  else 
  {
     iSize = (Math.round(iSize * 100) / 100);
     maxSize = 0;
  }
  readURL(this);
});
dojo.require("dijit.form.NumberTextBox");
</script>		