<?php 
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$formFilter = $this->formFilter;
	$rs = $this->product;
?>
<div class="card pb-10 pt-10 pl-10 pr-10">
	<div class="card-content">
		<div class="card-box">
			<form method="post" action="<?php echo $formFilter->getAction(); ?>" autocomplete="off">
				<div class="form-group">
					<label class="col-md-3">
						<?php echo $formFilter->getElement('ad_search');?>
					</label>
					<label class="col-md-3">
						<?php echo $formFilter->getElement('branch');?>
					</label>
					<label class="col-md-3">
						<?php echo $formFilter->getElement('brand');?>
					</label>
					<label class="col-md-3">
						<?php echo $formFilter->getElement('category');?>
					</label>
				</div>
				<div class="form-group">
					<label class="col-md-3">
						<?php echo $formFilter->getElement('model');?>
					</label>
					<label class="col-md-3">
						<?php echo $formFilter->getElement('color');?>
					</label>
					<label class="col-md-3">
						<?php echo $formFilter->getElement('status');?>
					</label>
					<label class="col-md-3">
						<input type="submit" value="btnsavenew" id="btnsavenew" name="save_close" label="<?php echo $tr->translate("REFRESH")?>" dojoType="dijit.form.Button" 
							iconClass="dijitIconSearch" />
					</label>
				</div>				
			</form> 
			</div>
			<div class="card-box">
			<?php echo $this->list;?>
		</div>
	</div>
</div>