<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$url_getProduct =  $this->url(array('module'=>'product','controller'=>'adjust','action'=>'getproduct'));
	$formFilter = $this->formFilter;
?>
<title><?php echo $tr->translate("TRANSFER_STOCK");?></title>
<div class="card pb-10 pt-10 pl-10 pr-10">
	<div class="card-content">
		<div class="card-box">
            <div class="col-sm-12 border-botom">
		    	<div class="col-sm-8 pd-0">
		    		<h4 class="m-b-0"><i class="fa fa-cube" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('EDIT_TRANSFER');?></h4>
    			</div>
    			<div class="col-sm-4 text-right">
    			</div>
    		</div>
    	</div>
			<form dojoType="dijit.form.Form" class="form-horizontal" method="post" action="" >
				<script  type="dojo/method" event="onSubmit">			
					if(this.validate()) {
						from_loc = dijit.byId("from_loc").get('value');
						to_loc = dijit.byId("to_loc").get('value');
	 					if(from_loc=='' || to_loc==''){
							("Please Select From and To Location");
		 					return false;
						}
   			 			if(from_loc==to_loc){
        					dijit.byId('to_loc').focus();
        					return false;
   		 				}
    					identity = $("#identity").val();
    					if(identity==''){
	 						alert("សូមបញ្ចូលបរិមាណទំនិញ");
	 	 					dijit.byId('pro_name').focus();
	   						return false;
     					}
					}
				</script>	
					<div class="form-group">
						<label class="col-md-2 control-label"><?php echo $tr->translate("TRANSFER_NUM");?></label>
						<div class="col-md-4">
							<?php echo $formFilter->getElement('tran_num');?>
							<?php echo $formFilter->getElement('id');?>
						</div>
						<label class="col-md-2 control-label"><?php echo $tr->translate("TRANSFER_DATE");?></label>
						<div class="col-md-4">
							<?php echo $formFilter->getElement('tran_date');?>
						</div>	
					</div>
					<div class="form-group">
						<label class="col-md-2 control-label"><?php echo $tr->translate("FROM_BRANCH");?></label>
						<div class="col-md-4">
							<?php echo $formFilter->getElement('from_loc');?>
						</div>
						<label class="col-md-2 control-label"><span id="lb_br"></span><?php echo $tr->translate("TO_BRANCH");?></label>
						<div class="col-md-4">
							<?php echo $formFilter->getElement('to_loc');?>
						</div>
					</div>
					<div class="form-group">
						<label class="col-md-2 control-label"><?php echo $tr->translate("REMARK");?></label>
						<div class="col-md-4">
							<?php echo $formFilter->getElement('remark');?>
						</div>	
						<label class="col-md-2 control-label"><?php echo $tr->translate("STATUS");?></label>
						<div class="col-md-4">
							<?php echo $formFilter->getElement('status');?>
						</div>
					</div>
					<div class="portlet box blue">
						<div class="portlet-title">
							<div class="caption" style="width:100%">
								<?php echo $formFilter->getElement('pro_name');?>
							</div>
						</div>
					</div>
					<div class="form-group">
	                   <label class="control-label col-md-12 col-sm-12 col-xs-12 title-blog bold" ><i class="fa fa-hand-o-right" aria-hidden="true"></i> <?php echo $tr->translate("PRODUCT_LIST");?> 
	                   </label>
	                </div>
					<div class="form-group">
						<table class="table table-bordered">
							<thead>
								<tr>
									<th>#</th>
									<th><?php echo $tr->translate("PRODUCT_NAME");?></th>
									<th><?php echo $tr->translate("CURRENT_QTY");?></th>
									<th><?php echo $tr->translate("QTY_TRANSFER");?></th>
									<th><?php echo $tr->translate("REMARK");?></th>
									<th><?php echo $tr->translate("ACTION");?></th>
								</tr>
							</thead>
							<tbody id="table_row" style="font-size:12px;">
							</tbody>
						</table>
					</div>
					<div class="card-box">
						<div class="border-top">
							<div class="col-md-4"></div>
							<div class="col-md-5" class='center'>
								<input type="hidden" name="identity" id="identity" value="" />
								<input type="submit" value="btnsavenew" id="btnsavenew" name="save_close" label="<?php echo $tr->translate("SAVE_NEW");?>" dojoType="dijit.form.Button" 
								iconClass="dijitEditorIcon dijitEditorIconSave" />
							</div>
							<div class="col-md-3"></div>
						</div>
				</div>
		</form>
	</div>
</div>
<script type="text/javascript">
jQuery(document).ready(function(){
	oldRow();
});
var index=0;
col = 0;
function oldRow(){
	<?php if(!empty($this->rs_detail)){
			foreach( $this->rs_detail as $rs){
	?>
		template='';
		index++;
		col++;
		template+='<td>'+index+'</td>';
		template+='<td style="white-space: nowrap;"><?php echo $rs["item_name"];?><input type="hidden" id="pro_id_'+index+'" name="pro_id_'+index+'" value="<?php echo $rs["pro_id"]?>" </td>';
		template+='<td style="width:90px;"><input type="hidden" name="qty_'+index+'" id="qty_'+index+'" value="<?php echo $rs['qty_loc']?>" /></td>'; 
		template+='<td style="width:90px;"><input type="text" class="fullside" dojoType="dijit.form.NumberTextBox" id="qty_tran_'+index+'" onKeyup="checkQTY('+index+')" name="qty_tran_'+index+'" value="<?php echo $rs['qty']?>" class="form-control"></td>'; 
		template+='<td><input type="text" class="fullside" dojoType="dijit.form.TextBox" id="remark_'+index+'" name="remark_'+index+'" ></td>';
		template+='<td><button type="button" onClick="deleteRecord('+index+')" name="save_close" class="btn default"><?php echo $tr->translate("DELETE");?></button></td>';
		tmp='<tr id="row'+col+'">';
		tmp+="</tr>";
		$('#table_row').append(tmp);
		
		if($('#identity').val()!="") {
			var identity = $('#identity').val();
			$('#identity').val(identity+','+index);
		} else {$('#identity').val(index);}
		
		dojo.html.set(dojo.byId("row"+col),template , {
		     parseContent: true,
		});
	<?php }}?>
	
}
function addNew(){
	id = dijit.byId("pro_name").get('value');
	branch_id = dijit.byId("from_loc").get('value');	
	if(branch_id==''){
		return false;
	}
	index++;
	$.ajax({
        url: "<?php echo $url_getProduct;?>",
        type: "post",
        data: {'id':id,'location_ids':branch_id},
        success: function(val){
			for(i=1; i<index; i++){
				new_item=parseInt(id);
				items = parseInt($("#pro_id_"+i).val());
				if(new_item==items){		
					newqty = parseInt($("#qty_tran_"+i).val());
					newqty = newqty+1;
					$("#qty_tran_"+i).val(newqty);
					checkQTY(i);
					return false;
				}
			}
			col++;
			data = $.parseJSON(val);
			template='<td>'+index+'</td>';
			template+='<td style="white-space: nowrap;">'+data.item_name+'<input type="hidden" id="pro_id_'+index+'" name="pro_id_'+index+'" value="'+id+'" </td>';
			template+='<td style="width:90px;"><input class="fullside" readonly="readonly" dojoType="dijit.form.NumberTextBox" type="text" name="qty_'+index+'" id="qty_'+index+'" value="'+data.qty+'" /></td>'; 
			template+='<td style="width:90px;"><input class="fullside" dojoType="dijit.form.NumberTextBox" type="text" id="qty_tran_'+index+'" onKeyup="checkQTY('+index+')" name="qty_tran_'+index+'" value="1" ></td>'; 
			template+='<td><input class="fullside" dojoType="dijit.form.TextBox" type="text" id="remark_'+index+'" name="remark_'+index+'"></td>';
			template+='<td><button type="button" onClick="deleteRecord('+index+')" name="save_close" class="btn default"><?php echo $tr->translate("DELETE");?></button></td>';
			tmp='<tr id="row'+col+'">';
			tmp+="</tr>";
			$('#table_row').append(tmp);
			
			dojo.html.set(dojo.byId("row"+col),template , {
			     parseContent: true,
			});
			if($('#identity').val()!="") {
				var identity = $('#identity').val();
				$('#identity').val(identity+','+index);
			} else {$('#identity').val(index);}
        },
        error:function(e){
        }
    });
}	
function checkQTY(index){
	qty = parseFloat($('#qty_'+index).val());
	qty_tran = parseFloat($('#qty_tran_'+index).val());
	translate = "This Product is remain "+qty+" Only";
	if(qty_tran>qty){
		alert("This Product is remain "+qty+" Only");
		$('#qty_tran_'+index).val(qty)
	}
}
function transferType(){
	var type= $('#type').val();
	if(type==1){
		document.getElementById('lb_br').innerHTML = "From ";
	}else if(type==2){
		document.getElementById('lb_br').innerHTML = "To ";
	}
}
function deleteRecord(index) {
	var identity = $('#identity').val();
	var arrays = identity.split(',');
	
	for(var i=0;i<arrays.length;i++) {
		if(arrays[i] == index) arrays.splice(i,1);
	}
	var strings = arrays.join(',');
	$('#identity').val(strings);
	$("#row"+index).remove();
}
dojo.require("dijit.form.DateTextBox");
dojo.require("dijit.form.NumberTextBox");
</script>
