<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$url_cancel =  $this->url(array('module'=>'product','controller'=>'transfer','action'=>'index'),null,true);
	$url_getProduct =  $this->url(array('module'=>'product','controller'=>'adjust','action'=>'get-product'));
	$formFilter = $this->formFilter;
?>
<title><?php echo $tr->translate("TRANSFER_STOCK");?></title>
<div class="card pb-10 pt-10 pl-10 pr-10">
	<div class="card-content">
		<div class="card-box">
            <div class="col-sm-12 border-botom">
		    	<div class="col-sm-8 pd-0">
		    		<h4 class="m-b-0"><i class="fa fa-cube" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('EDIT_TRANSFER');?></h4>
    			</div>
    			<div class="col-sm-4 text-right">
    			</div>
    		</div>
    	</div>
			<form dojoType="dijit.form.Form" class="form-horizontal" method="post" action="" >
				<script  type="dojo/method" event="onSubmit">			
					if(this.validate()) {
						from_loc = dijit.byId("from_loc").get('value');
						to_loc = dijit.byId("to_loc").get('value');
	 					if(from_loc=='' || to_loc==''){
							("Please Select From and To Location");
		 					return false;
						}
   			 			if(from_loc==to_loc){
        					dijit.byId('to_loc').focus();
        					return false;
   		 				}
    					identity = $("#identity").val();
    					if(identity==''){
	 						alert("សូមបញ្ចូលបរិមាណទំនិញ");
	 	 					dijit.byId('pro_name').focus();
	   						return false;
     					}
					}
				</script>	
					<div class="form-group">
						<label class="col-md-2 control-label"><?php echo $tr->translate("TRANSFER_NUM");?></label>
						<div class="col-md-4">
							<?php echo $formFilter->getElement('tran_num');?>
							<?php echo $formFilter->getElement('id');?>
						</div>
						<label class="col-md-2 control-label"><?php echo $tr->translate("TRANSFER_DATE");?></label>
						<div class="col-md-4">
							<?php echo $formFilter->getElement('tran_date');?>
						</div>	
					</div>
					<div class="form-group">
						<label class="col-md-2 control-label"><?php echo $tr->translate("FROM_BRANCH");?></label>
						<div class="col-md-4">
							<?php echo $formFilter->getElement('from_loc');?>
						</div>
						<label class="col-md-2 control-label"><span id="lb_br"></span><?php echo $tr->translate("TO_BRANCH");?></label>
						<div class="col-md-4">
							<?php echo $formFilter->getElement('to_loc');?>
						</div>
					</div>
					<div class="form-group">
						<label class="col-md-2 control-label"><?php echo $tr->translate("REMARK");?></label>
						<div class="col-md-4">
							<?php echo $formFilter->getElement('remark');?>
						</div>	
						<label class="col-md-2 control-label"><?php echo $tr->translate("STATUS");?></label>
						<div class="col-md-4">
							<?php echo $formFilter->getElement('status');?>
						</div>
					</div>
					<div class="portlet box blue">
						<div class="portlet-title">
							<div class="caption" style="width:100%">
								<?php echo $formFilter->getElement('pro_name');?>
							</div>
						</div>
					</div>
					<div class="form-group">
	                   <label class="control-label col-md-12 col-sm-12 col-xs-12 title-blog bold" ><i class="fa fa-hand-o-right" aria-hidden="true"></i> <?php echo $tr->translate("PRODUCT_LIST");?> 
	                   </label>
	                </div>
					<div class="form-group">
						<table class="table table-bordered">
							<thead>
								<tr>
									<th>#</th>
									<th><?php echo $tr->translate("PRODUCT_NAME");?></th>
									<th><?php echo $tr->translate("QTY_TRANSFER");?></th>
									<th><?php echo $tr->translate("REMARK");?></th>
									<th><?php echo $tr->translate("ACTION");?></th>
								</tr>
							</thead>
							<tbody id="tr_location" style="font-size:12px;">
							</tbody>
						</table>
					</div>
					<div class="form-group" style="">
						<label  class="col-md-12 col-md-offset-4 col-md-8">
							<input type="hidden" name="identity" id="identity" value="" />
							<button type="submit" name="save_close" class="btn btn-primary"><?php echo $tr->translate("SAVE_CLOSE");?></button>
						</label>
					</div>
		</form>
	</div>
</div>
<script type="text/javascript">
$('#frm').submit(function() {
	from_loc = $("#from_loc").val();
	to_loc = $("#to_loc").val();
	 if(from_loc=='' || to_loc==''){
		 alert("Please Select From and To Location");
		 return false;
	}
    if(from_loc==to_loc){
        $('#to_loc').select2('open');
        return false;
    }
    identity = $("#identity").val();
    if(identity==''){
	 	alert("សូមបញ្ចូលបរិមាណទំនិញ");
	 	 $('#pro_name').select2('open');
	   return false;
     }
	var r = confirm("សូមត្រួតពិនិត្យទិន្នន័យ អោយបានត្រឹមត្រូវ !\nតើលោកអ្នកពិតជាចង់រក្សាទុកទិន្នន័យនេះមែនឫទេ?");
	if (r == true) {
	    return true;
	} else {
	   return false;
	    
	}
});
jQuery(document).ready(function(){
	oldRow();
});
var index=0;
function oldRow(){
	<?php if(!empty($this->rs_detail)){
			foreach( $this->rs_detail as $rs){
	?>
			index++;
			template='<tr id="row_location_'+index+'">';
			template+='<td>'+index+'</td>';
			template+='<td style="white-space: nowrap;"><?php echo $rs["item_name"];?><input type="hidden" id="pro_id_'+index+'" name="pro_id_'+index+'" value="<?php echo $rs["pro_id"]?>" </td>';
			template+='<td><input type="text" required="1" id="qty_tran_'+index+'" onKeyup="checkQTY('+index+')" name="qty_tran_'+index+'" value="<?php echo $rs['qty']?>" class="form-control"><input type="hidden" name="qty_'+index+'" id="qty_'+index+'" value="<?php echo $rs['qty_loc']?>" /></td>'; 
			template+='<td><input type="text" id="remark_'+index+'" name="remark_'+index+'" class="form-control"></td>';
			template+='<td><button type="button" onClick="deleteRecord('+index+',1)" name="save_close" class="btn default"><?php echo $tr->translate("DELETE");?></button></td>';
			template+='</tr>';
			$('#tr_location').append(template);
			if($('#identity').val()!="") {
				var identity = $('#identity').val();
				$('#identity').val(identity+','+index);
			} else {$('#identity').val(index);}
	<?php }}?>
}
function addNew(){
	id = $("#pro_name").val();
	index++;
	$.ajax({
        url: "<?php echo $url_getProduct;?>",
        type: "post",
        data: {'id':id},
        success: function(val){
			for(i=1; i<index; i++){
				new_item=parseInt(id);
				items = parseInt($("#pro_id_"+i).val());
				if(new_item==items){		
					newqty = parseInt($("#qty_tran_"+i).val());
					newqty = newqty+1;
					$("#qty_tran_"+i).val(newqty);
					checkQTY(i);
					return false;
					
				}
			}
			 data = $.parseJSON(val);
			template='<tr id="row_location_'+index+'">';
			template+='<td>'+index+'</td>';
			template+='<td style="white-space: nowrap;">'+data.item_name+" "+data.brand+" "+data.size+" "+data.color+'<input type="hidden" id="pro_id_'+index+'" name="pro_id_'+index+'" value="'+id+'" </td>';
			template+='<td><input type="text" id="qty_tran_'+index+'" onKeyup="checkQTY('+index+')" name="qty_tran_'+index+'" value="1" class="form-control"><input type="hidden" name="qty_'+index+'" id="qty_'+index+'" value="'+data.qty+'" /></td>'; 
			template+='<td><input type="text" id="remark_'+index+'" name="remark_'+index+'" class="form-control"></td>';
			template+='<td><button type="button" onClick="deleteRecord('+index+',1)" name="save_close" class="btn default"><?php echo $tr->translate("DELETE");?></button></td>';
			template+='</tr>';
			$('#tr_location').append(template);
			if($('#identity').val()!="") {
				var identity = $('#identity').val();
				$('#identity').val(identity+','+index);
			} else {$('#identity').val(index);}
        },
        error:function(){
            $("#result").html('There is error while submit');
        }
    });
}	
function checkQTY(index){
	qty = parseFloat($('#qty_'+index).val());
	qty_tran = parseFloat($('#qty_tran_'+index).val());
	translate = "This Product is remain "+qty+" Only";
	if(qty_tran>qty){
		alert("This Product is remain "+qty+" Only");
		$('#qty_tran_'+index).val(qty)
	}
}
function transferType(){
	var type= $('#type').val();
	if(type==1){
		document.getElementById('lb_br').innerHTML = "From ";
	}else if(type==2){
		document.getElementById('lb_br').innerHTML = "To ";
	}
}
function deleteRecord(index,type) {
	if(type==1){
		var identity = $('#identity').val();
		var arrays = identity.split(',');
	}else{
		var identity = $('#identity_price').val();
		var arrays = identity.split(',');
	}
	
	for(var i=0;i<arrays.length;i++) {
		if(arrays[i] == index) arrays.splice(i,1);
	}
	var strings = arrays.join(',');
	
	if(type==1){
		$('#identity').val(strings);
		$("#row_location_"+index).remove();
	}else{
		$('#identity_price').val(strings);
		$("#row_price_"+index).remove();
	}
}
</script>
	<script>
dojo.require("dijit.form.DateTextBox");
</script>