<?php 
	$url_edit = $this->url(array('module'=>'product','controller'=>'transfer','action'=>'edit',));
	$url_delete = $this->url(array('module'=>'product','controller'=>'transfer','action'=>'delete',));
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$formFilter = $this->formFilter;
	$rs = $this->product;
?>
<title><?php echo $tr->translate("TRANSFER_LIST");?></title>
<div class="card pb-10 pt-10 pl-10 pr-10">
	<div class="card-content">
		<div class="card-box">	
			<form class="form-horizontal" method="post" action="" >
				<div class="form-body">
					<div class="form-group">
						<div class="col-md-2">
							<?php echo $formFilter->getElement('avd_search');?>
						</div>
						<div class="col-md-2">
							<?php echo $formFilter->getElement('start_date');?>
						</div>
						<div class="col-md-2">
							<?php echo $formFilter->getElement('end_date');?>
						</div>
						<div class="col-md-2">
							<?php echo $formFilter->getElement('status');?>
						</div>
						<div class="col-md-2">
							<input type="submit" value="btnsavenew" id="btnsavenew" name="save_close" label="<?php echo $tr->translate("REFRESH")?>" dojoType="dijit.form.Button" 
							iconClass="dijitIconSearch" />
						</div>
					</div>
				</div>
			</form>
		</div>
		<div class="card-box">
			<table class="table table-striped table-bordered table-hover" id="sample_2" style="font-size:11px">
				<thead style="font-size:11px">
					<tr>
						<th><?php echo $tr->translate("NO");?></th>
						<th><?php echo $tr->translate("TRANSFER_NUM");?></th>
						<th><?php echo $tr->translate("BRANCH");?></th>
						<th><?php echo $tr->translate("TRANSFER_DATE");?></th>
						<th><?php echo $tr->translate("GET_IN_DATE");?></th>
						<th><?php echo $tr->translate("TRANSFER_BY");?></th>
						<th><?php echo $tr->translate("STATUS");?></th>
						<th><?php echo $tr->translate("ACTION");?></th>
					</tr>
				</thead>
				<tbody>
					<?php if(!empty($rs)){ foreach ($rs as $key => $row){?>
					<tr class="odd gradeX">
						<td class="center"><?php echo $key+1;?></td>
						<td><?php echo $row["tran_no"]?></td>
						<td><?php echo $row["tran_location"]?></td>
						<td><?php echo $row["date"]?></td>
						<td><?php echo $row["date"]?></td>
						<td><?php echo $row["user_tran"]?> </td>
						<td class="center">
							<?php if($row["status"] == 1){?>
							<span class="label label-sm label-success"><?php echo $tr->translate("ACTIVE");?> </span>
							<?php }else{?>
							<span class="label label-sm label-danger"><?php echo $tr->translate("DEACTIVE");?> </span>
							<?php }?>
						</td>
						<td>
							<a href="<?php echo $url_edit;?>/id/<?php echo $row["id"]?>"><?php echo $tr->translate("EDIT");?></a>
						</td>
					</tr>
					<?php }}?>
				</tbody>
			</table>
		</div>
	</div>
</div>
<script>
	dojo.require("dijit.form.DateTextBox");
</script>