<?php
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
$url_submit =  $this->url(array('module'=>'product','controller'=>'transfer','action'=>'transferlist'),null,true);
$formFilter = $this->formFilter;
?>
<title><?php echo $tr->translate("Make Transfer");?></title>
<div class="portlet box blue">
		<div class="portlet-title">
			<div class="caption">
					<i class="fa fa-globe"></i><?php echo $tr->translate("EDIT_TRANSFER");?>
			</div>
			<div class="tools">
				<a href="<?php echo $url_submit;?>"><button type="button" name="calcel" class="btn red"><?php echo $tr->translate("GO_BACK");?></button></a>
			</div>
		</div>
		<div class="portlet-body form">
			<form id="frm" class="form-horizontal" method="post" action="" >
				<div class="form-body">	
					<div class="form-group">
						<label class="col-md-2 control-label"><?php echo $tr->translate("REQUET_TO_FROM");?></label>
						<div class="col-md-4">
							<?php echo $formFilter->getElement('from_loc');?>
						</div>
						
						<label class="col-md-2 control-label"><?php echo $tr->translate("REQUET_TO_BRANCH");?></label>
						<div class="col-md-4">
							<?php echo $formFilter->getElement('to_loc');?>
						</div>
					</div>
					<div class="form-group">
						<label class="col-md-2 control-label"><?php echo $tr->translate("TRANSFER_NUM");?></label>
						<div class="col-md-4">
							<?php echo $formFilter->getElement('tran_num');?>
						</div>
						
						<label class="col-md-2 control-label"><?php echo $tr->translate("REQUEST_NUM");?></label>
						<div class="col-md-4">
							<?php echo $formFilter->getElement('re_num');?>
						</div>
					</div>
					<div class="form-group">
						<label class="col-md-2 control-label"><?php echo $tr->translate("REQUEST_DATE");?></label>
						<div class="col-md-4">
							<?php echo $formFilter->getElement('re_date');?>
						</div>
						
						<label class="col-md-2 control-label"><span id="lb_br"></span><?php echo $tr->translate("TRANSFER_DATE");?></label>
						<div class="col-md-4">
							<?php echo $formFilter->getElement('tran_date');?>
						</div>
					</div>
					<div class="form-group">
						<label class="col-md-2 control-label"><?php echo $tr->translate("REMARK");?></label>
						<div class="col-md-4">
							<?php echo $formFilter->getElement('remark');?>
						</div>	
						
						<label class="col-md-2 control-label"><?php echo $tr->translate("STATUS");?></label>
						<div class="col-md-4">
							<?php echo $formFilter->getElement('status');?>
						</div>
					</div>
					<div class="portlet box blue">
						<div class="portlet-title">
							<div class="caption">
								<i class="fa fa-cogs"></i><?php echo $tr->translate("PRODUCT_LIST");?>
							</div>
						</div>	
							<div class="portlet-body">
								<div class="table-responsive">
									<table class="table table-bordered">
										<thead>
											<tr>
												<th>#</th>
												<th><?php echo $tr->translate("PRODUCT_NAME");?></th>
												<th><?php echo $tr->translate("QTY_TRANSFER");?></th>
												<th><?php echo $tr->translate("UNIT_QTY");?></th>
												<th><?php echo $tr->translate("QTY_PER_UNIT");?></th>
												<th><?php echo $tr->translate("QTY_TRANSFER");?></th>
												<th><?php echo $tr->translate("REMARK");?></th>
												<th><?php echo $tr->translate("ACTION");?></th>
											</tr>
										</thead>
										<tbody id="tr_location" style="font-size:12px;">
										</tbody>
									</table>
								</div>
								<input type="hidden" name="identity" id="identity" value="" >
								<div class="form-group" style="padding-top: 6px;">
									<div class="col-md-12 col-md-offset-4 col-md-8">
										<a href="<?php echo $this->baseUrl();?>/product/transfer/transferlist"><button type="button" class="btn red"><i class="fa fa-times"></i> <?php echo $tr->translate("EXIT")?></button></a>
										<!--<button type="submit" name="save_new" class="btn btn-primary"><?php echo $tr->translate("SAVE_NEW");?></button>-->
										<button type="submit" name="save_close" class="btn btn-primary"><?php echo $tr->translate("SAVE_CLOSE");?></button>
									</div>
								</div>
							</div>
					</div>
				</div>
			</form>
		</div>
</div>
<script type="text/javascript">
$('#frm').submit(function() {
    identity = $("#identity").val();
    if(identity==''){
	 	alert("សូមបញ្ចូលបរិមាណទំនិញ");
	    return false;
     }
	var r = confirm("សូមត្រួតពិនិត្យទិន្នន័យ អោយបានត្រឹមត្រូវ !\nតើលោកអ្នកពិតជាចង់រក្សាទុកទិន្នន័យនេះមែនឫទេ?");
	if (r == true) {
	    return true;
	} else {
	   return false;
	}
});
jQuery(document).ready(function(){
	oldRow();
});
var index=0;
function oldRow(){
	qty_request=0;
	<?php if(!empty($this->rs_detail)){
			foreach( $this->rs_detail as $rs){
				
	?>
		qty_unit = '<?php echo number_format($rs["qty_unit"],0);?>';
		qty_per_unit = '<?php echo number_format($rs["qty_per_unit"],0);?>';
		if(parseFloat(qty_unit)>0 && parseFloat(qty_per_unit)>0){
			qty_request = qty_unit+" <?php echo $rs["measure"]?> & "+qty_per_unit+" <?php echo $rs["unit_label"]?>";
		}else if(parseFloat(qty_unit)<=0 && parseFloat(qty_per_unit)>0){
			qty_request = qty_per_unit+" <?php echo $rs["unit_label"]?>";
		}else if(parseFloat(qty_unit)>0 && parseFloat(qty_per_unit)<=0){
			qty_request=qty_unit+" <?php echo $rs["measure"]?>";
		}
			index++;
			template='<tr id="row_location_'+index+'">';
			template+='<td>'+index+'</td>';
			template+='<td style="white-space: nowrap;"><?php echo $rs["item_name"];?><input type="hidden" id="pro_id_'+index+'" name="pro_id_'+index+'" value="<?php echo $rs["pro_id"]?>" </td>';
			template+='<td>'+qty_request+'<input type="hidden" id="qty_request_'+index+'" readOnly="readOnly" name="qty_request_'+index+'" value="<?php echo $rs['qty']?>" class="form-control"></td>'; 
			template+='<td><input type="text" id="qty_unit_'+index+'" onKeyup="TotalQty('+index+')" name="qty_unit_'+index+'" value="<?php echo $rs['qty_unit']?>" class="form-control" /></td>'; 
			template+='<td><input type="text" id="qty_per_unit_'+index+'" onKeyup="TotalQty('+index+')" name="qty_per_unit_'+index+'" value="<?php echo $rs['qty_per_unit']?>" class="form-control" /></td>'; 
			template+='<td><input type="text" id="qty_tran_'+index+'" readOnly="readOnly" name="qty_tran_'+index+'" value="<?php echo $rs['qty']?>" class="form-control"> <input type="hidden" name="qty_measure_'+index+'" id="qty_measure_'+index+'" value="<?php echo $rs['qty_measure']?>"/></td>'; 
			template+='<td><input type="text" id="remark_'+index+'" name="remark_'+index+'" class="form-control"></td>';
			template+='<td><button type="button" onClick="deleteRecord('+index+',1)" name="save_close" class="btn default"><?php echo $tr->translate("DELETE");?></button></td>';
			template+='</tr>';
			$('#tr_location').append(template);
			if($('#identity').val()!="") {
				var identity = $('#identity').val();
				$('#identity').val(identity+','+index);
			} else {$('#identity').val(index);}
	<?php }}?>
}
function TotalQty(index){
		main_qty =$("#qty_unit_"+index).val();
		detail_qty =  $("#qty_per_unit_"+index).val();
		qty_measure = $("#qty_measure_"+index).val();
		if(qty_measure==0){
			qty_measure=1;
		}else{
			qty_measure = qty_measure;
		}
		total_qty = parseFloat(main_qty) + (parseFloat(detail_qty)/parseFloat(qty_measure));
		$("#qty_tran_"+index).val(total_qty.toFixed(3));
}

<?php $url_no =  $this->url(array('module'=>'product','controller'=>'transfer','action'=>'get-transfer-no')); ?>
function gettransferNo(){
	var id = $("#from_loc").val();
	$.ajax({
        url: "<?php echo $url_no;?>",
        type: "post",
        data: {'id':id},
        success: function(data){
           val = $.parseJSON(data);
		   $("#tran_num").val(val);
        },
        error:function(){
            alert("faile insert");
            $("#result").html('There is error while submit');
        }
    });
}
</script>