<?php 
$tr=Application_Form_FrmLanguages::getCurrentlanguage();
?>
<title>Purchase Report</title>
<div class="card pb-10 pt-10 pl-10 pr-10">
	<div class="card-content">
		<div class="card-box">
			<div id="divPrint" style="width: 100%; margin-top:15px">
			<style>
				.style{
					line-height: 20px;font-size: 9px !important;
					font-family: 'Khmer OS Battambang';
				}
				ul{margin: 0;padding:0;}
				table tr td ul li{text-align: center;list-style: none;line-height: 25px;}
				th{}
				ul.pur_info li{line-height:18px; 
						font-weight: normal !important;}
				ul.pur_info li strong{font-weight: bold;}
		       .hover:hover{background: #ccc;}
			   .center{text-align:center;}
			</style>
				<table style="font-family: 'Khmer OS Content'; width:100%;">
					<tbody>
					<tr>
				    	<td align="center">
				        	<table width="100%" style="font-family: 'Khmer OS Battambang';" cellpadding="0" cellpadding="0">
				            	<tbody>
									<tr style="margin-bottom:10px;"> 
										<td width="20%" valign="top"></td>
										<td width="60%" valign="top" style="line-height:30px">
											<ul>
												<li style="text-align:center; font-size:20px; font-family:'Khmer OS Muol Light'"><?php echo $this->title_reprot["branch_code"]?></li>
												<li style="text-align:center; font-size:18px; font-family:serif,header-font; font-weight:600;"><?php //echo $this->title_reprot["title_report_en"]?></li>
												<li style="text-align:center; font-size:15px; margin-top:25px; font-family:'Khmer OS Muol Light';">ប័ណ្ណស្នើផ្ទេរទិញទំនិញ</li>
											</ul>
										</td>
										<td width="20%" style="text-align:center; font-size: 11px;white-space: nowrap;">
										</td>
								</tr>
				                <tr>
				                	<td colspan="3" valign="top">
				                		<table width="100%" cellpadding="0" cellspacing="0">
				                			<tbody>
				                			<tr>
												<td width="70%"></td>
				                				<td width="30%" style="text-align: left;font-size: 12px;" valign="top">
													<table width="100%" style="font-size: 12px; font-weight:600;">
														
														<tr style="line-height:20px;">
															<td style="text-align: right;white-space: nowrap;"><?php echo $tr->translate("TRANSFER_FROM");?> :</td>
															<td style="text-align: right;"><?php //echo $this->product[0]['tran_location'];?></td>
														</tr>
														<tr style="line-height:20px;">
															<td style="text-align: right;white-space: nowrap;"><?php echo $tr->translate("TRANSFER_NO");?> :</td>
															<td style="text-align: right;white-space: nowrap;"><?php //echo $this->product[0]['tran_no'];?></td>
														</tr>
														<tr style="line-height:20px;">
															<td style="text-align: right;white-space: nowrap;"><?php echo $tr->translate("TRANSFER_TO");?> :</td>
															<td style="text-align: right;"><?php //echo $this->product[0]['tran_to_location'];?></td>
														</tr>
														<tr style="line-height:20px;">
															<td style="text-align: right;white-space: nowrap;"><?php echo $tr->translate("REQUEST_NO");?> :</td>
															<td style="text-align: right;white-space: nowrap;"><?php //echo $this->product[0]['req_no'];?></td>
														</tr>
														<tr style="line-height:20px;">
															<td style="text-align: right;white-space: nowrap;"><?php echo $tr->translate("REQUEST_DATE");?> :</td>
															<td style="text-align: right;white-space: nowrap;"><?php echo date("d/m/Y",strtotime($this->product[0]['date_tran']));?></td>
														</tr>
													</table>
				                				</td>
				                			</tr>
						                </tbody></table>
						              </td>
						           </tr>   
				            </tbody></table>
				        </td>
				    </tr>
				    <tr>
				    	<td>
				            <table border="1" class="collape tablesorter" style="border-collapse:collapse;border:1px solid #000; font-size:12px !important; margin-top:10px;" width="100%" cellspacing="0">
				                 <tbody>
								 <tr style="background:#ccc;font-size:13px !important; line-height:40px;">
									<th class="tdheader" width="5%">&nbsp;<?php echo $tr->translate("NUM");?></th>
									<th class="tdheader"><?php echo $tr->translate("ITEM_CODE");?></th>
									<th class="tdheader"><?php echo $tr->translate("ITEM_NAME");?></th>
									<th class="tdheader">&nbsp;<?php echo $tr->translate("QTY_REQUEST");?></th>
									<th class="tdheader">&nbsp;<?php echo $tr->translate("QTY_TRANSFER");?></th>
									<th class="tdheader">&nbsp;<?php echo $tr->translate("NOTE");?></th>
								</tr>
								
								<?php 
								$qty_tran=0;$index=0;
								$count_i=0;$count=0;
									if(!empty($this->product)){ $total = 0;  foreach($this->product as $key=>$rs){$index = $key+1; 
									$count = count($this->product);
									$qty_unit = number_format($rs["qty_unit"],0);;
									$qty_per_unit = number_format($rs["qty_per_unit"],0);
									if($qty_unit>0 && $qty_per_unit>0){
										$qty_tran = $qty_unit." ".$rs["measure"]." ".$qty_per_unit." ".$rs["unit_label"];
									}else if($qty_unit<=0 && $qty_per_unit>0){
										$qty_tran = $qty_per_unit." ".$rs["unit_label"];
									}else if($qty_unit>0 && $qty_per_unit<=0){
										$qty_tran= $qty_unit." ".$rs["measure"];
									}
									
									
									$raw_qty = $rs["qty_request"];
									$array = explode(".",$rs["qty_request"]);
									$qty = $array[0];
									$qty_unit = ($raw_qty*$rs["qty_measure"]) - ($rs["qty_measure"]*$array[0]);
									$l_qty = 0;
									if(abs($raw_qty)>0){
										if(abs($qty)>0 and $qty_unit>0){
											$l_qty = $qty." ".$rs["measure"]." & ".round($qty_unit)." ".$rs["unit_label"];
										}elseif(abs($qty)==0 and $qty_unit>0){
											$l_qty = round($qty_unit)." ".$rs["unit_label"];
										}elseif(abs($qty)>0 and $qty_unit==0){
											$l_qty =  $qty." ".$rs["measure"];
										}
									}else{
										$l_qty = 0;
									}
								?>
									<tr>
										<td class="center"><?php echo $index;?></td>
										<td>&nbsp;&nbsp;<?php echo $rs["item_code"];?>&nbsp;&nbsp;</td>
										<td>&nbsp;&nbsp;<?php echo $rs["item_name"];?>&nbsp;&nbsp;</td>
										<td class="center"><?php echo $l_qty;?></td>
										<td class="center"><?php echo $qty_tran;?></td>
										<td>&nbsp;&nbsp;<?php echo $rs["remark"];?>&nbsp;&nbsp;</td>
									</tr>
								<?php }}?>
								<?php if($count<10){
										$count_i = 10-$count;
										for($i=1;$i<=$count_i;$i++){
								?>
									<tr>
										<td class="center"><?php echo $index+$i; ?></td>
										<td></td>
										<td></td>
										<td></td>
										<td></td>
										<td></td>
									</tr>
								<?php }}?>
				                </tbody>
				           </table>
				              <br>
				              <table align="center" width="100%" >
								   <tbody>
								   <tr style="font-size: 12px;">
								        <td style="width:20%;text-align:center; font-family:'Khmer OS Muol Light'">អ្នកប្រគល់</td>
								        <th></th>
								        <td style="width:20%;text-align:center; font-family:'Khmer OS Muol Light'"></td>
								        <th></th>
								        <td style="width:20%;text-align:center; font-family:'Khmer OS Muol Light'"></td>
										<th></th>
								        <td style="width:20%;text-align:center; font-family:'Khmer OS Muol Light'">អ្នកទទួល</td>
								   </tr>
								    <tr style="font-size: 12px; height: 75px;">
								        <td valign="bottom" style="width:20%;text-align:center;  font-family:'Khmer OS Muol Light'; white-space: nowrap;border-bottom:1px solid #000;"></td>
								        <td></td>
								        <td valign="bottom" style="width:20%;text-align:center; font-family:'Khmer OS Muol Light';white-space: nowrap; "></td>
								        <td></td>
								        <td valign="bottom" style="width:20%;text-align:center;font-family:'Khmer OS Muol Light';white-space: nowrap;"></td>
										<td></td>
								        <td valign="bottom" style="width:20%;text-align:center;font-family:'Khmer OS Muol Light';white-space: nowrap;border-bottom:1px solid #000;"></td>
								   </tr>
								</tbody>
							</table>	
				    		</td>
				    	</tr>
					</tbody>
				</table>
			</div>
  		</div>		
	</div>
</div>
<iframe name=print_frame width=0 height=0 frameborder=0 src=about:blank></iframe>
<script>
function doPrint() {
	window.frames["print_frame"].document.body.innerHTML=document.getElementById('divPrint').innerHTML;
    window.frames["print_frame"].window.focus();
    window.frames["print_frame"].window.print();
}
</script>