<?php 
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$frm = $this->form_agent;
?>
<title><?php echo $tr->translate("PRICE_LEVEL");?></title>
<div class="card pb-10 pt-10 pl-10 pr-10">
	<div class="card-content">
		<div class="card-box">
            <div class="col-sm-12 border-botom">
		    	<div class="col-sm-8 pd-0">
		    		<h4 class="m-b-0"><i class="fa fa-cube" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('PRICE_LEVEL');?></h4>
    			</div>
    			<div class="col-sm-4 text-right">
    			</div>
    		</div>
    	</div>
		<div class="card-box">			
			<form dojoType="dijit.form.Form" id="form_sample_2" class="form-horizontal" enctype="multipart/form-data" method="post">
				 <script type="dojo/method" event="onSubmit">			
					if(this.validate()) {
               			loadingBlock();
						return true;
					}else{
						return false;
					}
				</script>
				<div class="col-md-6">
					<div class="form-group">
						<label class="control-label col-md-4">
							<?php echo $tr->translate("PRICE_LEVEL");?>
							</label>
							<div class="col-md-8">
									<?php echo $frm->getElement("price_name");?>
							</div>
					</div>
					<div class="form-group">
						<label class="control-label col-md-4"><?php echo $tr->translate("REMARK");?></label>
						<div class="col-md-8">
							<?php echo $frm->getElement("price_decs");?>
						</div>
					</div>
					<div class="form-group">
						<label class="control-label col-md-4"><?php echo $tr->translate("STATUS");?></label>
						<div class="col-md-8">
							<?php echo $frm->getElement("status");?>
						</div>
					</div>
					<div class="form-group">
						<label  class="col-md-12 col-md-offset-4 col-md-8">
							<button type="submit" name="saveclose" value="saveclose" class="btn btn-primary" ><i class="glyphicon glyphicon-log-in"></i> <?php echo $tr->translate("SAVE_CLOSE")?></button>
						</label>
					</div>
				</div>
			</form>
		</div>
	</div>
</div>