<?php 
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$formFilter = $this->formFilter;
?>
<title><?php echo $tr->translate("PRODUCT_PRICE");?></title>
<div class="card pb-10 pt-10 pl-10 pr-10">
	<div class="card-content">
		<div class="card-box">					
			<form method="post" action="<?php echo $formFilter->getAction(); ?>">
				<div class="form-group" style="padding-top: 6px;">
					<label class="control-label col-md-3"><?php echo $formFilter->getElement('price_type');?></label>
					<label class="control-label col-md-3"><?php echo $formFilter->getElement('status');?></label>
					<label class="control-label col-md-2">
						<input type="submit" value="btnsavenew" id="btnsavenew" name="save_close" label="<?php echo $tr->translate("REFRESH")?>" dojoType="dijit.form.Button" 
							iconClass="dijitIconSearch" />
					</label>
				</div>		
			</form> 
		</div>
		<div class="card-box">
			<?php echo $this->list;?>
		</div>
	</div>
</div>