<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('COMMENT_CUSTOMER'));
$user_id = Application_Model_DbTable_DbGlobal::GlobalgetUserId();		
?>
<?php  $dailywork= $this->frm_comment;?>
<div class="card pb-10 pt-10 pl-10 pr-10">
	<div class="card-content">
		<div class="card-box">
			<form dojoType="dijit.form.Form" class="form-horizontal" method="post" action="<?php echo $this->url(array('module'=>'sales','controller'=>'comment','action'=>'edit')); ?>" >
				<script type="dojo/method" event="onSubmit">			
					if(this.validate()) {
						customer_id=dijit.byId("customer_id").get('value');
						if(customer_id==0 || customer_id==-1){
							alert("Please select customer type");
							dijit.byId("customer_id").focus();
							return false;	
						}
               			loadingBlock();
						return true;
					}else{
						return false;
					}
				</script>
				<div class="form-group">
					<div class="col-md-2 control-label"><?php echo $tr->translate("CUSTOMER_NAME")?></div>
					<div class="col-md-8">
						<?php echo $dailywork->getElement("customer_id");?>
					</div>
				</div>
				<div class="form-group">
					<div class="col-md-2 control-label"><?php echo $tr->translate("DATE")?></div>
					<div class="col-md-8">
							<?php echo $dailywork->getElement("start_date");?>
							<?php echo $dailywork->getElement("id");?>
					</div>
				</div>
				<div class="form-group">
					<div class="col-md-2 control-label"><?php echo $tr->translate("Status")?></div>
					<div class="col-md-8">
						<?php echo $dailywork->getElement("status");?>
					</div>
				</div>
				<div class="form-group">
					<div class="col-md-2 control-label"><?php echo $tr->translate("COMMENT")?></div>
					<div class="col-md-8">
						<?php echo $dailywork->getElement("description");?>
					</div>
				</div>
				<div class="form-group">
					<div class="col-md-4">
					</div>
					<div class="col-md-4">
						<input type="submit" value="btnsavenew" id="btnsavenew" name="save_close" label="<?php echo $tr->translate("SAVE_NEW")?>" dojoType="dijit.form.Button" 
							iconClass="dijitIconSearch" />
					</div>
					<div class="col-md-4">
						
					</div>
				</div>
			</form>
		</div>
	</div>
</div>
 <script>
function getCustomerInfo(){
}
dojo.require("dijit.form.DateTextBox");
</script>	