<?php
	$url_edit = $this->url(array('module'=>'sales','controller'=>'comment','action'=>'edit'));
	$row_rs = $this->row_rs;
?>
<?php $tr = Application_Form_FrmLanguages::getCurrentlanguage(); ?>
<?php $formFilter =  $this->frm_search;?>
<div class="card pb-10 pt-10 pl-10 pr-10">
	<div class="card-content">
		<div class="card-box">
			<form method="post" action="<?php echo $formFilter->getAction(); ?>" autocomplete="off">
					<div class="form-group">
						<label class=" col-md-2"><input dojoType="dijit.form.TextBox" class="fullside" id="adv_search" name="adv_search" value="<?php echo $this->row['adv_search']?>" type="text" ></label>
						<label class=" col-md-2"><?php echo $formFilter->getElement("customer_id");?></label>
						<label class=" col-md-2"><input dojoType="dijit.form.DateTextBox" id="start_date" name="start_date" type="text"   value="<?php echo date("m/d/Y",strtotime($this->row['start_date']));?>"  ></label>
						<label class=" col-md-2"><input dojoType="dijit.form.DateTextBox" id="end_date" name="end_date" value="<?php echo date("m/d/Y",strtotime($this->row['end_date']));?>" type="text" ></label>
						<label class=" col-md-2">
							<input type="submit" value="btnsavenew" id="btnsavenew" name="save_close" label="<?php echo $tr->translate("REFRESH")?>" dojoType="dijit.form.Button" 
							iconClass="dijitIconSearch" />
						</label>
					</div>		
				</form> 
			</div>
			<div class="card-box">
			<?php echo $this->list;?>
		</div>
	</div>
</div>
<script>
dojo.require("dijit.form.DateTextBox");
</script>