<?php 
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$url_save=$this->url(array("module"=>"sales","controller"=>"saleagent","action"=>"add"));
	$frm_agent = $this->form_agent;
?>
<title><?php echo $tr->translate("ADD_STAFF");?></title>
<div class="card pb-10 pt-10 pl-10 pr-10">
	<div class="card-content">
		<div class="card-box">
			<form dojoType="dijit.form.Form"  action="<?php echo $url_save;?>" class="form-horizontal" enctype="multipart/form-data" method="post">
				<script type="dojo/method" event="onSubmit">			
					if(this.validate()) {
               			loadingBlock();
						return true;
					}else{
						return false;
					}
				</script>
				<div class="col-md-4">
					<div class="form-group">
	                   <label class="control-label col-md-12 col-sm-12 col-xs-12 title-blog bold" ><i class="fa fa-hand-o-right" aria-hidden="true"></i>
	                   	<?php echo $tr->translate("STAFF_INFO");?> 
	                   </label>
	                </div>
					<div class="form-group">
						<div class="col-md-4">
							<?php echo $tr->translate("LOCATION_NAME");?>
						</div>
						<div class="col-md-8">
							<?php echo $frm_agent->getElement("branch_id");?>
						</div>
					</div>
					<div class="form-group">
						<div class="col-md-4">
							<?php echo $tr->translate("AGENT_CODE");?>
						</div>
						<div class="col-md-8">
							<?php echo $frm_agent->getElement("code");?>
						</div>
					</div>
					<div class="form-group">
						<label class="col-md-4">
							<?php echo $tr->translate("STAFF_NAE");?>
						</label>
						<div class="col-md-8">
							<?php echo $frm_agent->getElement("name");?>
						</div>
					</div>
					<div class="form-group">
						<div class="col-md-4">
							<?php echo $tr->translate("CON_NUM");?>
						</div>
						<div class="col-md-8">
							<?php echo $frm_agent->getElement("phone");?>
						</div>
					</div>
					<div class="form-group">
						<div class="col-md-4">
							<?php echo $tr->translate("DOB");?>
						</div>
						<div class="col-md-8">
							<?php echo $frm_agent->getElement('dob'); ?>
						</div>
					</div>
					<div class="form-group">
						<div class="col-md-4">
							<?php echo $tr->translate("POB");?>
						</div>
						<div class="col-md-8">
							<?php echo $frm_agent->getElement("pob");?>
						</div>
					</div>
					<div class="form-group">
						<div class="col-md-4">
						<?php echo $tr->translate("CURRENT_ADD");?>
						</div>
						<div class="col-md-8">
							<?php echo $frm_agent->getElement("address");?>
						</div>
					</div>
					<div class="form-group">
						<div class="col-md-4">
							<?php echo $tr->translate("EMAIL_ADD");?>
						</div>
						<div class="col-md-8">
							<?php echo $frm_agent->getElement("email");?>
						</div>
					</div>
					<div class="form-group">
						<div class="col-md-4">
							<?php echo $tr->translate("POSITION");?>
						</div>
						<div class="col-md-8">
							<?php echo $frm_agent->getElement("job_title");?>
						</div>
					</div>
					<div class="form-group">
						<div class="col-md-4">
							<?php echo $tr->translate("DESC");?>
						</div>
						<div class="col-md-8">
							<?php echo $frm_agent->getElement("description");?>
						</div>
					</div>
				</div>
				<div class="col-md-4">
					<div class="form-group">
	                   <label class="control-label col-md-12 col-sm-12 col-xs-12 title-blog bold" ><i class="fa fa-hand-o-right" aria-hidden="true"></i> <?php echo $tr->translate("USER_INFO");?> 
	                   </label>
	                </div>
					<div class="form-group">
						<div class="col-md-4">
							<?php echo $tr->translate("USER_NAME");?>
						</div>
						<div class="col-md-8">
							<?php echo $frm_agent->getElement("user_name");?>
						</div>
					</div>
					<div class="form-group">
						<div class="col-md-4">
							<?php echo $tr->translate("PASSWORD");?>
						</div>
						<div class="col-md-8">
							<?php echo $frm_agent->getElement('password'); ?>
						</div>
					</div>
					<div class="form-group">
						<div class="col-md-4">
							<?php echo $tr->translate("USER_TYPE");?>
						</div>
						<div class="col-md-8">
							<?php echo $frm_agent->getElement("user_type");?>
						</div>
					</div>
					<div class="form-group">
						<div class="col-md-4">
							<?php echo $tr->translate("MANAGED_BY");?>
						</div>
						<div class="col-md-8">
							<?php echo $frm_agent->getElement("manage_by");?>
						</div>
					</div>
					<div class="form-group">
	                   <label class="control-label col-md-12 col-sm-12 col-xs-12 title-blog bold" ><i class="fa fa-hand-o-right" aria-hidden="true"></i> <?php echo $tr->translate("USER_DOCUMENT_INFO");?> 
	                   </label>
	                </div>
					<div class="form-group">
						<div class="col-md-4">
							<?php echo $tr->translate("BACN_ACCOUNT");?>
						</div>
						<div class="col-md-8">
							<?php echo $frm_agent->getElement("bank_acc");?>
						</div>
					</div>
					<div class="form-group">
						<div class="col-md-4">
							<?php echo $tr->translate("START_WORKING_DATE");?>
						</div>
						<div class="col-md-8">
							<?php echo $frm_agent->getElement("start_working_date");?>
						</div>
					</div>
					<div class="form-group">
						<div class="col-md-4">
							<?php echo $tr->translate("REFER_NAME");?>
						</div>
						<div class="col-md-8">
							<?php echo $frm_agent->getElement("refer_name");?>
						</div>
					</div>
					<div class="form-group">
						<div class="col-md-4">
							<?php echo $tr->translate("REFER_PHONE");?>
						</div>
						<div class="col-md-8">
							<?php echo $frm_agent->getElement("refer_phone");?>
						</div>
					</div>
					<div class="form-group">
						<div class="col-md-4">
							<?php echo $tr->translate("REFER_ADDRESS");?>
						</div>
						<div class="col-md-8">
							<?php echo $frm_agent->getElement("refer_address");?>
						</div>
					</div>
				</div>
				<div class="col-md-4">
					<div class="form-group">
	                   <label class="control-label col-md-12 col-sm-12 col-xs-12 title-blog bold" ><i class="fa fa-hand-o-right" aria-hidden="true"></i>
	                   	<?php echo $tr->translate("DOCUMENT");?> 
	                   </label>
	                </div>
	                <div class="form-group">
						<div class="col-md-4">
							<?php echo $tr->translate("PHOTO");?>
						</div>
						<div class="col-md-8">
							<?php echo $frm_agent->getElement("photo");?>
						</div>
					</div>
					<div class="form-group">
						<div class="col-md-4">
							<?php echo $tr->translate("DOCUMENT");?>
						</div>
						<div class="col-md-8">
							<?php echo $frm_agent->getElement("document");?>
						</div>
					</div>
					<div class="form-group">
						<div class="col-md-4">
							<?php echo $tr->translate("SIGNATURE");?>
						</div>
						<div class="col-md-8">
							<?php echo $frm_agent->getElement("signature");?>
						</div>
					</div>
	            </div>
				<div class="card-box">
					<div class="border-top">
						<div class="col-md-4"></div>
						<div class="col-md-5" class='center'>
							<input type="submit" value="btnsavenew" id="btnsavenew" name="save_close" label="<?php echo $tr->translate("ADD_NEW");?>" dojoType="dijit.form.Button" 
							iconClass="dijitEditorIcon dijitEditorIconSave" />
						</div>
						<div class="col-md-3"></div>
					</div>
				</div>
			</form>
		</div>	
	</div>
</div>
<script>
dojo.require("dijit.form.DateTextBox");
<?php $url_code =  $this->url(array('module'=>'sales','controller'=>'sale-agent','action'=>'get-sale-agent-code')); ?>
function getSaleCode(){
	id=$("#branch_id").val();
	$.ajax({
		url:"<?php echo $url_code;?>",
		type:"post",
		data:{'id':id},
		success: function(data){
			value = $.parseJSON(data);
		},
		error:function(e){
		}
	});
}
</script>