<?php 
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$changepassword = $this->url(array("module"=>"rsvacl","controller"=>"user","action"=>"changepassword"));
	$frm_agent = $this->form_agent;
?>
<title><?php echo $tr->translate("EDIT_STAFF");?></title>
<div class="card pb-10 pt-10 pl-10 pr-10">
	<div class="card-content">
		<div class="card-box">
			<form dojoType="dijit.form.Form"  class="form-horizontal" enctype="multipart/form-data" method="post">
				<script type="dojo/method" event="onSubmit">			
					if(this.validate()) {
               			loadingBlock();
						return true;
					}else{
						return false;
					}
				</script>
				<div class="col-md-4">
					<div class="form-group">
	                   <label class="control-label col-md-12 col-sm-12 col-xs-12 title-blog bold" ><i class="fa fa-hand-o-right" aria-hidden="true"></i>
	                   	<?php echo $tr->translate("STAFF_INFO");?> 
	                   </label>
	                </div>
					<div class="form-group">
						<div class="col-md-4">
							<?php echo $tr->translate("LOCATION_NAME");?>
						</div>
						<div class="col-md-8">
							<?php echo $frm_agent->getElement("branch_id");?>
						</div>
					</div>
					<div class="form-group">
						<div class="col-md-4">
							<?php echo $tr->translate("AGENT_CODE");?>
						</div>
						<div class="col-md-8">
							<?php echo $frm_agent->getElement("code");?>
						</div>
					</div>
					<div class="form-group">
						<label class="col-md-4">
							<?php echo $tr->translate("STAFF_NAE");?>
						</label>
						<div class="col-md-8">
							<?php echo $frm_agent->getElement("name");?>
						</div>
					</div>
					<div class="form-group">
						<div class="col-md-4">
							<?php echo $tr->translate("CON_NUM");?>
						</div>
						<div class="col-md-8">
							<?php echo $frm_agent->getElement("phone");?>
						</div>
					</div>
					<div class="form-group">
						<div class="col-md-4">
							<?php echo $tr->translate("DOB");?>
						</div>
						<div class="col-md-8">
							<?php echo $frm_agent->getElement('dob'); ?>
						</div>
					</div>
					<div class="form-group">
						<div class="col-md-4">
							<?php echo $tr->translate("POB");?>
						</div>
						<div class="col-md-8">
							<?php echo $frm_agent->getElement("pob");?>
						</div>
					</div>
					<div class="form-group">
						<div class="col-md-4">
						<?php echo $tr->translate("CURRENT_ADD");?>
						</div>
						<div class="col-md-8">
							<?php echo $frm_agent->getElement("address");?>
						</div>
					</div>
					<div class="form-group">
						<div class="col-md-4">
							<?php echo $tr->translate("EMAIL_ADD");?>
						</div>
						<div class="col-md-8">
							<?php echo $frm_agent->getElement("email");?>
						</div>
					</div>
					<div class="form-group">
						<div class="col-md-4">
							<?php echo $tr->translate("POSITION");?>
						</div>
						<div class="col-md-8">
							<?php echo $frm_agent->getElement("job_title");?>
						</div>
					</div>
					<div class="form-group">
						<div class="col-md-4">
							<?php echo $tr->translate("DESC");?>
						</div>
						<div class="col-md-8">
							<?php echo $frm_agent->getElement("description");?>
						</div>
					</div>
				</div>
				<div class="col-md-4">
					<div class="form-group">
	                   <label class="control-label col-md-12 col-sm-12 col-xs-12 title-blog bold" ><i class="fa fa-hand-o-right" aria-hidden="true"></i> <?php echo $tr->translate("USER_INFO");?> 
	                   </label>
	                </div>
					<div class="form-group">
						<div class="col-md-4">
							<?php echo $tr->translate("USER_NAME");?>
						</div>
						<div class="col-md-8">
							<?php echo $frm_agent->getElement("user_name");?>
							<?php echo $frm_agent->getElement("user_id");?>
						</div>
					</div>
					<div class="form-group">
						<div class="col-md-12">
							<a target="_blank" href="<?php echo $changepassword?>/id/<?php echo $this->user_id;?>">Change Password</a>
						</div>
					</div>
					<div class="form-group"></div>
					<div class="form-group">
						<div class="col-md-4">
							<?php echo $tr->translate("PASSWORD");?>
						</div>
						<div class="col-md-8">
							<?php echo $frm_agent->getElement('password'); ?>
						</div>
					</div>
					<div class="form-group">
						<div class="col-md-4">
							<?php echo $tr->translate("USER_TYPE");?>
						</div>
						<div class="col-md-8">
							<?php echo $frm_agent->getElement("user_type");?>
						</div>
					</div>
					<div class="form-group">
						<div class="col-md-4">
							<?php echo $tr->translate("MANAGED_BY");?>
						</div>
						<div class="col-md-8">
							<?php echo $frm_agent->getElement("manage_by");?>
						</div>
					</div>
					<div class="form-group">
	                   <label class="control-label col-md-12 col-sm-12 col-xs-12 title-blog bold" ><i class="fa fa-hand-o-right" aria-hidden="true"></i> <?php echo $tr->translate("USER_DOCUMENT_INFO");?> 
	                   </label>
	                </div>
					<div class="form-group">
						<div class="col-md-4">
							<?php echo $tr->translate("BACN_ACCOUNT");?>
						</div>
						<div class="col-md-8">
							<?php echo $frm_agent->getElement("bank_acc");?>
						</div>
					</div>
					<div class="form-group">
						<div class="col-md-4">
							<?php echo $tr->translate("START_WORKING_DATE");?>
						</div>
						<div class="col-md-8">
							<?php echo $frm_agent->getElement("start_working_date");?>
						</div>
					</div>
					<div class="form-group">
						<div class="col-md-4">
							<?php echo $tr->translate("REFER_NAME");?>
						</div>
						<div class="col-md-8">
							<?php echo $frm_agent->getElement("refer_name");?>
						</div>
					</div>
					<div class="form-group">
						<div class="col-md-4">
							<?php echo $tr->translate("REFER_PHONE");?>
						</div>
						<div class="col-md-8">
							<?php echo $frm_agent->getElement("refer_phone");?>
						</div>
					</div>
					<div class="form-group">
						<div class="col-md-4">
							<?php echo $tr->translate("REFER_ADDRESS");?>
						</div>
						<div class="col-md-8">
							<?php echo $frm_agent->getElement("refer_address");?>
						</div>
					</div>
				</div>
				<div class="col-md-4">
					<div class="form-group">
	                   <label class="control-label col-md-12 col-sm-12 col-xs-12 title-blog bold" ><i class="fa fa-hand-o-right" aria-hidden="true"></i>
	                   	<?php echo $tr->translate("DOCUMENT");?> 
	                   </label>
	                </div>
	                <div class="form-group">
						<div class="col-md-4">
							<?php echo $tr->translate("PHOTO");?>
						</div>
						<div class="col-md-8">
							<?php echo $frm_agent->getElement("photo");?>
								<?php echo $frm_agent->getElement("old_photo");?>
								<?php if(!empty($this->row["photo"])){?>
									<img alt="" src="<?php echo $this->baseUrl();?>/images/stuffdocument/<?php echo $this->row["photo"];?>" style="width:30%">
								<?php }?>
						</div>
					</div>
					<div class="form-group">
						<div class="col-md-4">
							<?php echo $tr->translate("DOCUMENT");?>
						</div>
						<div class="col-md-8">
							<?php echo $frm_agent->getElement("document");?>
							<?php echo $frm_agent->getElement("old_document");?>
							<?php if(!empty($this->row["document"])){?>
								<img alt="" src="<?php echo $this->baseUrl();?>/images/stuffdocument/<?php echo $this->row["document"];?>" style="width:30%">
							<?php }?>
						</div>
					</div>
					<div class="form-group">
						<div class="col-md-4">
							<?php echo $tr->translate("SIGNATURE");?>
						</div>
						<div class="col-md-8">
							<?php echo $frm_agent->getElement("signature");?>
							<?php echo $frm_agent->getElement("old_signature");?>
							<?php if(!empty($this->row["signature"])){?>
								<img alt="" src="<?php echo $this->baseUrl();?>/images/stuffdocument/<?php echo $this->row["signature"];?>" style="width:30%">
							<?php }?>
						</div>
					</div>
					<div class="form-group">
						<div class="col-md-4">
							<?php echo $tr->translate("STATUS");?>
						</div>
						<div class="col-md-8">
							<?php echo $frm_agent->getElement("status");?>
						</div>
					</div>
	            </div>
				<div class="card-box">
					<div class="border-top">
						<div class="col-md-4"></div>
						<div class="col-md-5" class='center'>
							<input type="submit" value="btnsavenew" id="btnsavenew" name="save_close" label="<?php echo $tr->translate("GO_EDIT");?>" dojoType="dijit.form.Button" 
							iconClass="dijitEditorIcon dijitEditorIconSave" />
						</div>
						<div class="col-md-3"></div>
					</div>
				</div>
			</form>
		</div>	
	</div>
</div>
<script>
function AddLocation(){
	var location_id= $("#main_stock_id").val();
	if(location_id==-1){
		     AddNewLocation(true);
			 e.preventDefault();
	  }	
}
<?php $url_add_location =  $this->url(array('module'=>'product','controller'=>'index','action'=>'add-new-location')); ?>
function addNewLocation(){
	var location_name = $("#StockName").val();
	var ContactName   = $("#ContactName").val();
	var ContactNumber = $("#ContactNumber").val();
	var location_add  = $("#location_add").val();
	var remark_add    = $("#description").val();
	validate_text('#StockName');
	$.ajax({
        url: "<?php echo $url_add_location;?>",
        type: "post",
        data: {'location_name':location_name,'ContactName':ContactName,'ContactNumber':ContactNumber,'location_add':location_add,'remark_add':remark_add},
        success: function(data){
           val = $.parseJSON(data);
           $('#main_stock_id').append($("<option></option>").attr("value",data).attr("selected",true).text(location_name)); 
           $('#main_stock_id').next().val(location_name);
           document.getElementById("frm-location").reset();
            HideDialoglocation();
        },
        error:function(){
            alert("faile insert");
            $("#result").html('There is error while submit');
        }
    });
 
}
<?php $url_code =  $this->url(array('module'=>'sales','controller'=>'sale-agent','action'=>'get-sale-agent-code')); ?>
function getSaleCode(){
	id=$("#branch_id").val();
	$.ajax({
			url:"<?php echo $url_code;?>",
			type:"post",
			data:{'id':id},
			success: function(data){
				value = $.parseJSON(data);
					//$("#code").val(value);
			},
			error:function(e){
				alert(e);
			}
		});
	
}
dojo.require("dijit.form.DateTextBox");
</script>