<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
    $form=$this->form_search;
?>

<style>
.hover:hover{ background: #ddd;}
</style>
<title><?php echo $tr->translate("RPT_INCOME_EXPENSE");?></title>
<div class="card pb-10 pt-10 pl-10 pr-10">
	<div class="card-content">
		<div class="card-box">
			<form method="post" autocomplete="off">
				<div class="form-group" >
					<?php $formFilter = $this->formFilter; ?>
					<div class="col-md-2"><?php echo $form->getElement("adv_search");?></div>
					<div class="col-md-2"><?php echo $form->getElement("branch_id");?></div>
					<div class="col-md-2"><?php echo $form->getElement("cate_income");?></div>
					<div class="col-md-2"><?php echo $form->getElement("start_date");?></div>
					<div class="col-md-2"><?php echo $form->getElement("end_date");?></div>
					<div class="col-md-2">
						<input type="submit" value="btnsavenew" id="btnsavenew" name="save_close" label="<?php echo $tr->translate("REFRESH")?>" dojoType="dijit.form.Button" 
							iconClass="dijitIconSearch" />
					</div>
				</div>
			</form> 
	<div id="divPrint"  >
		<style>
			.style{
				line-height: 25px;font-size: 12px !important;
				font-family: 'Khmer OS Battambang';
			}	
		</style>
		<table class="table2excel" style="background:#fff; margin: 0 auto; width: 100%; padding: 0px 2px 1cm 2px;font-family: 'Hanuman';">
		<tr style="font-size: 13px;">
			<td colspan="3" align="center">
				<strong style="font-family: Arial Black;color:#000; font-size: 14px;font-family:'Khmer OS Muol Light';"><?php echo $tr->translate("COMPANY_CUSTOMER");?></strong><br />
				<strong style="font-family: Arial Black;color:#000; font-size: 14px;font-family:'Khmer OS Muol Light';"><?php echo $tr->translate("RPT_INCOME_EXPENSE");?></strong><br />
				<strong style="font-family: Arial Black;color:#000; font-size: 14px;font-family:'Khmer OS Muol Light';"><?php if(!empty($this->search["start_date"])){echo date("d-M-Y",strtotime($this->search["start_date"]))?> to <?php } echo date("d-M-Y",strtotime($this->search["end_date"]));?></strong>
			</td>
		</tr>
		<tr>
			<td width="20%" align="left">
			</td>
			<td align="center">
				<strong style="font-weight:bold;font-family: Arial Black;color:#000; font-size: 13px;font-family:'Khmer OS Muol Light';"></strong>
			</td>
			<td align="right" width="20%">&nbsp;</td>
		</tr>
		<?php 
			$total_cash=0;
			$total_bank=0;
			$total_cheque=0;
			$total_expense_dollar=0;
		?>
		<tr>
			<td colspan="3">
				<table border="1" style="border-collapse:collapse;border:1px solid #000; font-size:12px;font-family:Khmer OS Battambang;" width="100%" cellspacing="0">
                    
					
            		<tr class="style" style="font-size:12px; height: 20px;border: 1px solid #000;white-space: nowrap;background:#ccd9ff;line-height:30px;font-weight: bold;" align="center" >
									<td><?php echo $tr->translate('N_O')?></td>
									<td><?php echo $tr->translate('BRANCH')?></td>
									<td><?php echo $tr->translate('INCOME_CATEGORY')?></td>
									<td><?php echo $tr->translate('INCOME_TITLE')?></td>
									<td><?php echo $tr->translate('RECEIPT_NO')?></td>
									<td><?php echo $tr->translate('PAYMENT_METHOD')?></td>
									<td><?php echo $tr->translate('CHEQUE_NO')?></td>
									<td><?php echo $tr->translate('TOTAL')?></td>
									<td><?php echo $tr->translate('DATE')?></td>
									<td><?php echo $tr->translate('USER')?></td>
									<td><?php echo $tr->translate('STATUS')?></td>
					</tr>
					 <style> td{padding:0 3px; }</style>
				<?php $i=0;foreach($this->income as $row){ $i++;?>

					<?php if($row['status']==0) {?>
						<tr class="hover" style="font-size:12px; height: 20px;border: 1px solid #000; white-space: nowrap; background:#FFB6C1;" align="center" >
							<td style="border: 1px solid #000;"><?php echo $i;?></td>
							<td style="border: 1px solid #000;"><?php echo $row['branch_name'];?></td>
							<td align="left" style="border: 1px solid #000;"><span style="white-space:normal !important;width:120px;!important;"><?php echo $row['cate_income'];?></span></td>
							<td style="border: 1px solid #000;text-align: left;"><span style="white-space:normal !important;font-family:'Khmer OS Content';line-height:17px;width:180px;!important; display: block;padding-left: 1px; padding: 2px 1px;"><?php echo $row['title'];?></span></td>
							<td style="border: 1px solid #000; color:red; "><?php echo $row['invoice'];?></td>
							<td style="border: 1px solid #000;"><?php echo $tr->translate($row['paymentmethod']) ;?></td>
							<td style="border: 1px solid #000;"><?php echo $row['cheqe_no'];?></td>
							<td style="border: 1px solid #000;">$<?php echo number_format($row['total_amount'],2);?></td>
							<td style="border: 1px solid #000;"><?php echo date('d-m-Y',strtotime($row['date']));?></td>
							<td style="border: 1px solid #000;font-size: 10px;"><?php echo $row['user_name'];?></td>
							<?php if($row['status']==0){?>
								<td style="border: 1px solid #000;font-size: 10px; color:red;">មិនប្រើប្រាស់</td>
							<?php }else{?>
								<td style="border: 1px solid #000;font-size: 10px;">ប្រើប្រាស់</td>

								<?php }?>
						</tr>

					<?php }else{?>
						<tr class="hover" style="font-size:12px; height: 20px;border: 1px solid #000; white-space: nowrap; " align="center" >
							<td style="border: 1px solid #000;"><?php echo $i;?></td>
							<td style="border: 1px solid #000;"><?php echo $row['branch_name'];?></td>
							<td align="left" style="border: 1px solid #000;"><span style="white-space:normal !important;width:120px;!important;"><?php echo $row['cate_income'];?></span></td>
							<td style="border: 1px solid #000;text-align: left;"><span style="white-space:normal !important;font-family:'Khmer OS Content';line-height:17px;width:180px;!important; display: block;padding-left: 1px; padding: 2px 1px;"><?php echo $row['title'];?></span></td>
							<td style="border: 1px solid #000; color:red;"><?php echo $row['invoice'];?></td>
							<td style="border: 1px solid #000;"><?php echo $tr->translate($row['paymentmethod']) ;?></td>
							<td style="border: 1px solid #000;"><?php echo $row['cheqe_no'];?></td>
							<td style="border: 1px solid #000;background:#c6e2fb">$<?php echo number_format($row['total_amount'],2);?></td>
							<td style="border: 1px solid #000;"><?php echo date('d-m-Y',strtotime($row['date']));?></td>
							<td style="border: 1px solid #000;font-size: 10px;"><?php echo $row['user_name'];?></td>
							<?php if($row['status']==0){?>
								<td style="border: 1px solid #000;font-size: 10px; color:red;">មិនប្រើប្រាស់</td>
							<?php }else{?>
								<td style="border: 1px solid #000;font-size: 10px;">ប្រើប្រាស់</td>

								<?php }?>
						</tr>


					<?php }?>
						<?php 
						    
							if($row['status']!=0){
								$total_expense_dollar = $total_expense_dollar + $row['total_amount'];

							}
							

							if($row['payment_method']==1 AND $row['status']!=0){
								$total_cash = $total_cash + $row['total_amount'];
							}
							if($row['payment_method']==2 AND $row['status']!=0){
								$total_cheque = $total_cheque + $row['total_amount'];
							}
							if($row['payment_method']==4 AND $row['status']!=0){
								$total_bank = $total_bank + $row['total_amount'];
							}
							
						?> 
					 <?php } ?>
					 
					 <tr class="hover" style="height: 30px; font-weight:bold; text-align: left;font-size: 14px;" align="left" >
						<td style="border: 1px solid #fff;border-right: 1px solid #000;" colspan="9"></td>
						<td style="border: 1px solid #000; white-space: nowrap;font-weight: bolder; background:#87acff;">សាច់ប្រាក់/Cash</td>
						<td style="border: 1px solid #000;font-weight: bolder; color:red;">$<?php echo number_format($total_cash,2);?></td>
					</tr>
					<tr class="hover" style="height: 30px; font-weight:bold; text-align: left;font-size: 14px;" align="left" >
						<td style="border: 1px solid #fff;border-right: 1px solid #000;" colspan="9"></td>
						<td style="border: 1px solid #000; white-space: nowrap;font-weight: bolder;">ធនាការ/BanK Transfer</td>
						<td style="border: 1px solid #000;font-weight: bolder; color:red;">$<?php echo number_format($total_bank,2);?></td>
					</tr>
					<tr class="hover" style="height: 30px; font-weight:bold; text-align: left;font-size: 14px;" align="left" >
						<td style="border: 1px solid #fff;border-right: 1px solid #000;" colspan="9"></td>
						<td style="border: 1px solid #000; white-space: nowrap;font-weight: bolder;">សែក/Cheque </td>
						<td style="border: 1px solid #000;font-weight: bolder; color:red;">$<?php echo number_format($total_cheque,2);?></td>
					</tr>
					<tr class="hover" style="height: 30px; font-weight:bold; text-align: left;font-size: 14px;" align="left" >
						<td style="border: 1px solid #fff;border-right: 1px solid #000;" colspan="9"></td>
						<td style="border: 1px solid #000; white-space: nowrap;background:#87acff;font-weight: bolder;">សរុបរួម/Grand Total</td>
						<td style="border: 1px solid #000;background:#87acff;font-weight: bolder;">$<?php echo number_format($total_expense_dollar,2);?></td>
					</tr>
					</table>
				</td>
			</tr>
		</table>
			<?php echo $this->getFooter;?>
			</div>	
		</div>
	</div>
</div>
<iframe name=print_frame width=0 height=0 frameborder=0 src=about:blank></iframe>
<script type="text/javascript">
function doPrint() {var divToPrint = document.getElementById('divPrint');var htmlToPrint = '' +'<style type="text/css">' +'</style>';htmlToPrint += divToPrint.outerHTML;window.document.write(htmlToPrint);window.print();window.close();}
dojo.require("dijit.form.DateTextBox");
</script>
