<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
    $form=$this->form_search;
?>

<style>
.hover:hover{ background: #ddd;}
</style>
<title><?php echo $tr->translate("RPT_INCOME_EXPENSE");?></title>
<div class="card pb-10 pt-10 pl-10 pr-10">
	<div class="card-content">
		<div class="card-box">
			<form method="post" autocomplete="off">
				<div class="form-group" >
					<?php $formFilter = $this->formFilter; ?>
					<div class="col-md-2"><?php echo $form->getElement("adv_search");?></div>
					<div class="col-md-2"><?php echo $form->getElement("cate_income");?></div>
					<div class="col-md-2"><?php echo $form->getElement("start_date");?></div>
					<div class="col-md-2"><?php echo $form->getElement("end_date");?></div>
					<div class="col-md-2">
						<input type="submit" value="btnsavenew" id="btnsavenew" name="save_close" label="<?php echo $tr->translate("REFRESH")?>" dojoType="dijit.form.Button" 
							iconClass="dijitIconSearch" />
					</div>
				</div>
			</form> 
	<div id="divPrint"  >
		<style>
			S

			tr td.border_bottom{border-bottom: solid 1px #000;}
			tr td.border_double{border-bottom: double #000;}
			.border{border:1px solid #000;}
			.style{
					line-height: 20px;font-size: 14px !important;
					font-family: 'Khmer OS Battambang';
								}
					th{padding: 5px;}
			.border-bottom{border-bottom: 1px dotted #000; vertical-align:  middle;}
		</style>
		<table class="table2excel" style="background:#fff; margin: 0 auto; width: 100%; padding: 0px 2px 1cm 2px;font-family: 'Hanuman';">
		<tr style="font-size: 13px;">
			<td colspan="3" align="center">
				<strong style="font-family: Arial Black;color:#000; font-size: 14px;font-family:'Khmer OS Muol Light';"><?php echo $tr->translate("COMPANY_CUSTOMER");?></strong><br />
				<strong style="font-family: Arial Black;color:#000; font-size: 14px;font-family:'Khmer OS Muol Light';"><?php echo $tr->translate("RPT_INCOME_EXPENSE");?></strong><br />
				<strong style="font-family: Arial Black;color:#000; font-size: 14px;font-family:'Khmer OS Muol Light';"><?php if(!empty($this->search["start_date"])){echo date("d-M-Y",strtotime($this->search["start_date"]))?> to <?php } echo date("d-M-Y",strtotime($this->search["end_date"]));?></strong>
			</td>
		</tr>
		<tr>
			<td width="20%" align="left">
			</td>
			<td align="center">
				<strong style="font-weight:bold;font-family: Arial Black;color:#000; font-size: 13px;font-family:'Khmer OS Muol Light';"></strong>
			</td>
			<td align="right" width="20%">&nbsp;</td>
		</tr>
			
		</table>

		<table  width="100%" style="border-collapse:collapse; font-size: 14px; line-height: 25px;" >  

		
	             			<tr>
	             				<td colspan="5" style=" font-size:14px; font-family:'Khmer OS Muol Light'"> <?php echo $tr->translate("ប្រភេទចំណូល");?> </td>
	             				<td align="right">&nbsp;&nbsp;</td>
	             			</tr>
	             				<?php 
									$total_income_kh=0;
									$total_income_dollar=0;
									$total =0;
									$total_paid =0;
									$total_income=0;
								?>
								<?php $i=0;
								  if(!empty($this->incomebycate))foreach($this->incomebycate as $row){ $i++;?>
								  
	             				<?php
								
	             					$total_income = $total_income + $row['total_income'];
	             				?>
	             			<tr height="21px">
	             				<td style="font-family:khmer os battambang;">&nbsp;<?php echo $row['cate_income'];?>&nbsp;</td>
	             				<td colspan="2" class="border-bottom" valign="bottom"></td>
	             				<td class="" align="right">&nbsp;<?php echo number_format($row['total_income'],2);?>&nbsp;</td>
	             				<td >&nbsp;</td>
	             				<td>&nbsp;</td>
	             			</tr>
	             			<?php }?>
	             			<tr height="25px">
	             				<td>&nbsp;</td>
	             				<td colspan="2" style="text-align:right;font-size:14px; font-family:'Khmer OS Muol Light'"> <?php echo $tr->translate("ចំណូលសរុប");?> </td>
	             				<td align="right">&nbsp;<strong style="font-family: Helvetica;border-bottom: 2px solid #000;"><?php echo number_format($total_income,2);?>&nbsp;</strong></td>
	             				<td >&nbsp;</td>
	             				<td>&nbsp;</td>
	             			</tr>
	             			
	             			
	             		</table>
			<?php echo $this->getFooter;?>
			</div>	
		</div>
	</div>
</div>
<iframe name=print_frame width=0 height=0 frameborder=0 src=about:blank></iframe>
<script type="text/javascript">
function doPrint() {var divToPrint = document.getElementById('divPrint');var htmlToPrint = '' +'<style type="text/css">' +'</style>';htmlToPrint += divToPrint.outerHTML;window.document.write(htmlToPrint);window.print();window.close();}
dojo.require("dijit.form.DateTextBox");
</script>
