<?php 
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$user_info = new Application_Model_DbTable_DbGetUserInfo();
	$result = $user_info->getUserInfo();
	$db = new Application_Model_DbTable_DbUsers();
	$report_url = $db->getArrAclReport($result['level'],'product');
?>
  <div class="card">
	<div class="card-content collapse show">
		<div class="card-box report-list">
		  	<div class="row top_tiles">
				 <?php
			   	   if(!empty($report_url)){
			   	   foreach($report_url as $url){
			   	   if($url['action']=='index' OR $url['action']=='receipt' OR $url['action']=='rpt-updatepayment' OR $url['action']=='updatereceipt' or $url['action']=='quotadetail'){continue;}
			   	   	?>
			   	   	<div class="animated flipInY col-lg-3 col-md-3 col-sm-6 col-xs-12">
						<a href="<?php echo $this->url(array('module'=>$url['module'],'controller'=>$url['controller'],'action'=>$url['action'])); ?>">
							<div title="<?php echo $tr->translate($url['label']);?>" class="tile-stats report-list">
								<div class="icon"><i class="fa fa-book"></i></div>
								<div class="count">&nbsp;</div>
				                 	<h3><?php echo $tr->translate($url['label']);?></h3>
							</div>
						</a>
			        </div> 
			        <?php }
				}?>
			</div>
		  </div>
		</div>
	</div>
  <div style="clear: both;"></div>