<?php 
	$tr=Application_Form_FrmLanguages::getCurrentlanguage();
	$formFilter = $this->formFilter;
?>
<title><?php echo $tr->translate("RPT_ADJUSTSTOCK");?></title>
<div class="card pb-10 pt-10 pl-10 pr-10">
	<div class="card-content">
		<div class="card-box">
			<form method="post" >
				<div class="form-body">
					<div class="form-group">
						<div class="control-label col-md-3">
							<?php echo $formFilter->getElement('ad_search');?>
						</div>
						<div class="control-label col-md-3">
							<?php echo $formFilter->getElement('brand');?>
						</div>
						<div class="control-label col-md-3">
							<?php echo $formFilter->getElement('category');?>
						</div>
						<div class="control-label col-md-3">
							<?php echo $formFilter->getElement('model');?>
						</div>
					</div>
					<div class="form-group">
						<div class="control-label col-md-3">
							<?php echo $formFilter->getElement('size');?>
						</div>
						<div class="control-label col-md-3">
							<?php echo $formFilter->getElement('color');?>
						</div>
						<div class="control-label col-md-3">
							<?php echo $formFilter->getElement('status');?>
						</div>
						<div class="control-label col-md-3">
							<input type="submit" value="btnsavenew" id="btnsavenew" name="save_close" label="<?php echo $tr->translate("REFRESH")?>" dojoType="dijit.form.Button" 
							iconClass="dijitIconSearch" />
						</div>
					</div>		
				</div>
				<div style="clear:both;"></div>	
			</form> 
	<div id="divPrint" style="width: 100%;">
	<style>
		.style{
			line-height: 20px;font-size: 12px !important;
			font-family: 'Khmer OS Battambang';
		}
		ul{margin: 0;padding:0;}
		table tr td ul li{text-align: center;list-style: none;line-height: 25px; font-weight: bold;}
		th{padding: 5px;}
		.hover:hover{background: #ccc;}
	</style>
		<table style="font-family: 'Khmer OS Content'; width:100%;">
			<tbody>
			<tr>
		    	<td align="center">
                	<ul>
                		<li style="text-align:center; font-size:14px; font-family:'Khmer MEF2'"><?php echo $tr->translate("COMPANY_CUSTOMER");?></li>
                		<li style="text-align:center; font-size:14px; font-family:'Khmer MEF2'"><?php echo $tr->translate("RPT_ADJUSTSTOCK");?></li>
                	</ul>
		        </td>
		    </tr>
		    <tr>
		    	<td id="exportExcel">
			            <table class="table2excel" border="1" style="border-collapse:collapse;border:1px solid #000; font-size:12px;" width="100%" cellspacing="0">
			                 <tbody>
			                 <tr class="style" align="center" style="background:#b0bdfd;font-weight:bold; line-height: 25px; font-size:12px; padding:1px 0px; white-space: nowrap; ">
			                    <td>&nbsp;<?php echo $tr->translate("NUM");?></td>
								<td><?php echo $tr->translate("ITEM_CODE");?></ts>
								<td><?php echo $tr->translate("ITEM_NAME");?></td>
								<td><?php echo $tr->translate("BARCODE");?></td>
								<td><?php echo $tr->translate("MEASURE");?></td>
								<td><?php echo $tr->translate("QTY_BEFORE");?></td>
								<td><?php echo $tr->translate("NEW_QTY");?></td>
								<td><?php echo $tr->translate("DIFFER_QTY");?></td>
								<td><?php echo $tr->translate("BY_USER");?></td>
								<td><?php echo $tr->translate("DATE");?></td>
			                </tr>
			                <?php $num=1; 
			                if(!empty($this->product))foreach ($this->product AS $index => $row){?>
								<tr height="30" class='row-format<?php echo $num++; ?>' id="item_<?php echo $index; ?>">
									<td align="center">&nbsp;<?php echo $index+1 ?></td>
									<td><?php echo $row["item_code"]?></td>
									<td><?php echo $row["item_name"]."(".$row["cat"]." ".$row["brand"]." ".$row["model"]." ".$row["size"]." ".$row["color"].")"?></td>
									<td><?php echo $row["barcode"]?></td>
									<td class="center"><?php echo $row["measure"]?></td>
									<td class="center"><?php echo $row["before_qty"]?></td>
									<td class="center"><?php echo $row["qty_after"]?></td>
									<td class="center"><?php echo $row["differ_qty"]?></td>
									<td class="center"><?php echo $row["username"]?></td>
									<td class="center"><?php echo $row["date"]?></td>
								</tr>
							  <?php }?> 
			                </tbody>
			           </table>
			            <br>
			          </td>
			         </tr>
		              <?php echo $this->getFooter;?>		
					</tbody>
				</table>
			</div>
  		</div>		
	</div>
</div>
<iframe name=print_frame width=0 height=0 frameborder=0 src=about:blank></iframe>
<script>
	function doPrint() {var divToPrint = document.getElementById('divPrint');var htmlToPrint = '' +'<style type="text/css">' +'</style>';htmlToPrint += divToPrint.outerHTML;window.document.write(htmlToPrint);window.print();window.close();}
</script>