<?php 
$tr=Application_Form_FrmLanguages::getCurrentlanguage();
$brach_name =  $this->branch;
$formFilter = $this->formFilter;
?>
<title>Product List Report</title>
<div class="card pb-10 pt-10 pl-10 pr-10">
	<div class="card-content">
		<div class="card-box">
			<form method="post" action="">
				<div class="form-group">
					<div class="col-md-2">
						<?php echo $formFilter->getElement('tran_num');?>
					</div>
					<div class="col-md-2">
						<?php echo $formFilter->getElement('to_loc');?>
					</div>
					<div class="col-md-2">
						<?php echo $formFilter->getElement('tran_date');?>
					</div>
					<div class="col-md-2">
						<?php echo $formFilter->getElement('type');?>
					</div>
					<div class="col-md-2">
						<?php echo $formFilter->getElement('status');?>
					</div>
					<div class="col-md-2">
						<button type="submit" class="btn green"><?php echo $tr->translate("SEARCH");?></button>
					</div>
				</div>
			</form> 
	<div id="divPrint" style="width: 100%;">
	<style>
		.style{
			line-height: 20px;font-size: 9px !important;
			font-family: 'Khmer OS Battambang';
		}
		ul{margin: 0;padding:0;}
		table tr td ul li{text-align: center;list-style: none;line-height: 25px; font-weight: bold;}
		th{padding: 5px;}
		.hover:hover{background: #ccc;}
	</style>
		<table style="font-family: 'Khmer OS Content'; width:100%;">
			<tbody>
			<tr>
		    	<td align="center">
		        	<table width="100%" style="font-family: 'Khmer OS Battambang';" cellpadding="0" cellpadding="0">
		            	<tbody><tr>
		                	<td width="20%" valign="top"><img src="<?php echo $this->baseUrl();?>/images/logo.jpg" height="55px"></td>
		                	<td width="60%" valign="top">
		                		<ul>
		                			<li style="text-align:center; font-size:16px; font-family:'Khmer MEF2'"><?php echo $tr->translate("COMPANY_CUSTOMER");?></li>
		                			<li style="text-align:center; font-size:13px; font-family:'Khmer MEF2'">របាយការណ៏ បញ្ជី​ Transfer ផលិតផល</li>
		                			<li style="text-align:center; font-size:13px;"><?php echo date("d/m/Y",strtotime($this->rssearch['start_date']));?> ដល់ <?php echo date("d/m/Y",strtotime($this->rssearch['end_date']));?></li>
		                		</ul>
		                	</td>
		                    <td width="20%"></td>
		                </tr> 
		                  
		            </tbody></table>
		        </td>
		    </tr>
		    <tr>
		    	<td class="table2excel" id="exportExcel">
		            <table border="1" &#8203;="" style="border-collapse:collapse;border:1px solid #000; font-size:10px;" width="100%" cellspacing="0">
		                 <tbody><tr bgcolor="#ccc" class="style" align="center" style="font-weight:bold; line-height: 20px; font-size:12px; padding:1px 0px; white-space: nowrap; ">
		                    <td>&nbsp;<?php echo $tr->translate("NUM");?></td>
							<th><?php echo $tr->translate("TRANSFER_NO");?></td>
							<td><?php echo $tr->translate("TRANSFER_TO");?></td>
							<td><?php echo $tr->translate("DATE_TRANSFER");?></td>
							<td><?php echo $tr->translate("TRANSFER_BY");?></td>
							<td><?php echo $tr->translate("STATUS");?></td>
		                </tr>
		                <?php $num=1; 
		                if(!empty($this->product))foreach ($this->product AS $index => $row){?>
						<tr height="30" class='row-format<?php echo $num; ?>' id="item_<?php echo $index; ?>">
							<td align="center">&nbsp;<?php echo $index ?></td>
							<td><?php echo $row["tran_no"]?></td>
							<td><?php echo $row["tran_location"]?></td>
							<td><?php echo $row["date"]?> </td>
							<td><?php echo $row["user_tran"]?> </td>
							<td class="center">
							<?php if($row["status"] == 1){?>
							<span class="label label-sm label-success"><?php echo $tr->translate("ACTIVE");?> </span>
							<?php }else{?>
							<span class="label label-sm label-danger"><?php echo $tr->translate("DEACTIVE");?> </span>
							<?php }?>
							</td>
						</tr>
						  <?php }?> 
		                </tbody>
		           </table>
		            <br>
		              <br>
		              <table align="center" width="100%">
						   <tbody><tr style="font-size: 11px;">
						        <th style="width:20%;text-align:center;  font-family:'Khmer MEF2'">យល់ព្រមដោយ</th>
						        <th></th>
						        <th style="width:20%;text-align:center; font-family:'Khmer MEF2'">ត្រួតពិនិត្យដោយ</th>
						        <th></th>
						        <th style="width:20%;text-align:center;font-family:'Khmer MEF2'">រៀបចំដោយ</th>
						   </tr>
						</tbody>
					</table>	
		    		</td>
		    	</tr>
			</tbody>
		</table>
		</div>
	  </div>		
	</div>
 </div>
<iframe name=print_frame width=0 height=0 frameborder=0 src=about:blank></iframe>
<script>
function doPrint() {var divToPrint = document.getElementById('divPrint');var htmlToPrint = '' +'<style type="text/css">' +'</style>';htmlToPrint += divToPrint.outerHTML;window.document.write(htmlToPrint);window.print();window.close();}
</script>
