<?php 
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$form=$this->form_sale;
	$url_submit = $this->url(array('module'=>'purchase','controller'=>'payment','action'=>'add'));
?>
<title><?php echo $tr->translate("Customer Payment");?></title>
<div class="card pb-10 pt-10 pl-10 pr-10">
	<div class="card-content">
		<div class="card-box">
            <div class="col-sm-12 border-botom">
		    	<div class="col-sm-8 pd-0">
		    		<h4 class="m-b-0"><i class="fa fa-cube" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('Suppliyer Payment');?></h4>
    			</div>
    			<div class="col-sm-4 text-right">
    			</div>
    		</div>
    	</div>
		<div class="card-box">
			<form id="frm" autocomplete="off" action="<?php echo $url_submit; ?>" class="form-horizontal" enctype="multipart/form-data" method="post">
				<div class="col-md-4">	
					<div class="form-group">
						<div class="col-md-4">
							<?php echo $tr->translate("VENDOR_NAME");?>
						</div>
						<div class="col-md-8">
							<?php echo $form->getElement("customer_id");?>
						</div>
					</div>
					<div class="form-group">
						<div class="col-md-4">
							<?php echo $tr->translate("Invoice");?>
						</div>
						<div class="col-md-8">
							<?php echo $form->getElement('invoice_id');?>
						</div>
					</div>
					<div class="form-group">
						<div class="col-md-4">
							<?php echo $tr->translate("Expense Date");?>
						</div>
						<div class="col-md-8">
							<?php echo $form->getElement("expense_date");?>
						</div>
					</div>
					<div class="form-group">
						<div class="col-md-4">
							<?php echo $tr->translate("PAYMENT_TYPE");?>
						</div>
						<div class="col-md-8">
							<?php echo $form->getElement("payment_name");?>
						</div>
					</div>
					<div class="form-group">
						<div class="col-md-4">
							<?php echo $tr->translate("CHEQUE");?>
						</div>
						<div class="col-md-4">
							<?php echo $form->getElement("cheque");?>
						</div>
						<div class="col-md-4">
							<?php echo $form->getElement("bank_name");?>
						</div>	
					</div>
					<div class="form-group">
						<div class="col-md-4">
							<?php echo $tr->translate("ឈ្មោះអ្នកដកសែក");?>
						</div>
						<div class="col-md-8">
							<?php echo $form->getElement("holder_name"); ?>
						</div>
					</div>
					<div class="form-group">
						<div class="col-md-4">
							<?php echo $tr->translate("ថ្ងៃចេញសែក");?>
						</div>
						<div class="col-md-8">
							<?php echo $form->getElement("cheque_issuedate"); ?>
						</div>
					</div>
					<div class="form-group">
						<div class="col-md-4">
							<?php echo $tr->translate("ថ្ងៃបើកសែក");?>
						</div>
						<div class="col-md-8">
							<?php echo $form->getElement("cheque_withdrawdate"); ?>
						</div>
					</div>
					<div class="form-group">
						<div class="col-md-4">
							<?php echo $tr->translate("ជំពាក់សរុប​ :");?>
						</div>
						<div class="col-md-8">
							<?php echo $form->getElement("all_total");?>
						</div>
					</div>
					<div class="form-group">
						<div class="col-md-4">
							<?php echo $tr->translate("ប្រាក់បានបង់សរុប");?> 
						</div>
						<div class="col-md-8">
							<?php echo $form->getElement("paid");?>
						</div>	
					</div>
					<div class="form-group">
						<div class="col-md-4">
							ប្រាក់នៅសល់  :
						</div>
						<div class="col-md-8">
							<?php echo $form->getElement("balance");?>
						</div>
					</div>
					<div class="form-group">
						<div class="col-md-4">
							<?php echo $tr->translate("REMARK");?>
						</div>
						<div class="col-md-8">
							<?php echo $form->getElement("remark");?>
						</div>
					 </div>
				</div>
				<div class="col-md-8">
						<table class="table table-striped table-bordered table-hover" id="table_order" style="font-size:12px;">
							<tr height="33px">
								<th><?php echo $tr->translate("DEL");?></th>
								<th><?php echo $tr->translate("NUM");?></th>
								<th style="white-space:nowrap;"><?php echo $tr->translate("ថ្ងៃ/ខែ/ឆ្នាំ");?></th>
								<th><?php echo $tr->translate("វិក័យបត្រ");?></th>
								<th><?php echo $tr->translate("ចំនួនទឹកប្រាក់");?></th>
								<th><?php echo $tr->translate("បញ្ចុះតម្លៃ");?></th>
								<th><?php echo $tr->translate("ទឹកប្រាក់បានបង់");?></th>
								<th><?php echo $tr->translate("ទឹកប្រាក់នៅខ្វះ");?></th>
							</tr>
						 </table>
						 <input type="hidden" id="identity" name="identity" />
					</div>
					<div class="form-group">
						<label  class="col-md-12 col-md-offset-4 col-md-8">
							<button type="button" name="btnsavenew" onclick="addNewBrand();" class="btn btn-primary"><i class="fa fa-save"></i> <?php echo $tr->translate("SAVE_CLOSE")?> </button>
						</label>
					</div>
			</form>
		</div>
	</div>
</div>
<script>
$('#frm').submit(function() {
	paid=$("#paid").val();
	if(paid=='' || paid==0){
		alert("សូមបញ្ចុលទឹកប្រាក់ដែលបានបង់");
		$('#paid').focus;
		return false;	
	}
	identity =$("#identity").val();
	if(identity=='' || identity==-1){
		alert("សូមជ្រើសលេខវិក្កយបត្រដែលចង់បង់!");
		return false;
	}
	var r = confirm("សូមត្រួតពិនិត្យទិន្នន័យ អោយបានត្រឹមត្រូវ !\nតើលោកអ្នកពិតជាចង់រក្សាទុកទិន្នន័យនេះមែនឫទេ?");
	if (r == true) {
	    return true;
	} else {
	   return false;	    
	}
});
function paidtotal(type){
	doRemain();
}
function checkpayment(){
	payment_id = $("#payment_name").val();
	if(payment_id==2){
		$( "#bank_name" ).attr( "readOnly", false );
		$( "#cheque" ).attr( "readOnly", false );
	}else{
		$( "#bank_name" ).attr( "readOnly", true );
		$( "#cheque" ).attr( "readOnly", true );}
}
function checkControll(){
	$("#table_order").html("");
	$('#balance').val(0);$('#all_total').val(0);//$('#paid').val(0);
	payment_method = $("#payment_method").val();
	if(payment_method==1){
		$( "#invoice_id" ).attr( "readOnly", true );
		
		$( "#customer_id" ).attr( "readOnly", false );
	}else{
		$( "#customer_id" ).attr( "readOnly", true );
		$( "#invoice_id" ).attr( "readOnly", false );
    }
}
<?php $urlgetinvoice =  $this->url(array('module'=>'purchase','controller'=>'payment','action'=>'getinvoice')); ?>
function getInvoice(type){
	if(type==1){
		post_id=$("#customer_id").val();
		$( "#invoice_id" ).attr( "readonly", true );
		$( "#customer_id" ).attr( "readOnly", false );
	}else{
		post_id=$("#invoice_id").val();
		$( "#customer_id" ).attr( "readonly", true );
		$( "#invoice_id" ).attr( "readOnly", false );
	}
	$.ajax({
			url:"<?php echo $urlgetinvoice;?>",
			type:"post",
			data:{'post_id':post_id,'type_id':type},
			success: function(data){	
				$("#table_order").html("");
				template='<tr height="33px">';
					template+='<th><?php echo $tr->translate("DEL");?></th>';
					template+='<th><?php echo $tr->translate("NUM");?></th>';
					template+='<th style="white-space:nowrap;"><?php echo $tr->translate("ថ្ងៃ/ខែ/ឆ្នាំ");?></th>';
					template+='<th><?php echo $tr->translate("វិក័យបត្រ");?></th>';
					template+='<th><?php echo $tr->translate("ចំនួនទឹកប្រាក់");?></th>';
					template+='<th><?php echo $tr->translate("បញ្ចុះតម្លៃ");?></th>';
					template+='<th><?php echo $tr->translate("ទឹកប្រាក់បានបង់");?></th>';
					template+='<th><?php echo $tr->translate("ទឹកប្រាក់នៅខ្វះ");?></th>';
				template+='</tr>';
				
				$('#identity').val("");
				data = $.parseJSON(data);
				
				for(i=0;i<data.length;i++){
					if(i==0){
						$("#customer_id").val(data[i].vendor_id);
						$("#customer_id").select2();
					}
					index=i+1;
					template+='<tr style="height:30px;" id="row_order_'+index+'">';
			            template+='<td ><img onClick="deleteRecord('+index+')" src="<?php echo BASE_URL; ?>/images/icon/delete.gif" /></td>';
						template+='<td >'+index+'</td>';
						template+='<td >'+data[i].date_order+'</td>';
						template+='<td >'+data[i].invoice_no+'<input type="hidden" value='+data[i].id+' id="invoice_no'+index+'" name="invoice_no'+index+'"/></td>';
						template+='<td >'+data[i].net_total+'<input type="hidden" value='+data[i].net_total+' id="subtotal'+index+'" name="subtotal'+index+'"/></td>';
						template+='<td >'+data[i].discount_after+'<input type="hidden" value='+data[i].discount_after+' id="discount'+index+'" name="discount'+index+'"/></td>';
						template+='<td >'+data[i].paid+'<input type="hidden" value='+data[i].paid+' id="paid_amount'+index+'" name="paid_amount'+index+'"/></td>';
						template+='<td >'+data[i].balance_after+'<input type="hidden" value='+data[i].balance_after+' id="balance_after'+index+'" name="balance_after'+index+'"/></td>';
				    template+="</tr>";
					if($('#identity').val()!="") {
						var identity = $('#identity').val();
						$('#identity').val(identity+','+index);
					} else {$('#identity').val(index);}
				}
				$('#table_order').append(template);
				if(data.length>0){netTotal();}else{$('#balance').val(0);$('#all_total').val(0);$('#paid').val(0); alert("No invoice to make payment");}				
			},
			error:function(e){
			}
		});	
}

function deleteRecord(index) {
	var identity = $('#identity').val();
	var arrays = identity.split(',');
	for(var i=0;i<arrays.length;i++) {
		if(arrays[i] == index) arrays.splice(i,1);
	}
	var strings = arrays.join(',');
	$('#identity').val(strings);
	$("#row_order_"+index).remove();
	netTotal();
}
function netTotal() {//use
	var subtotal=0;
	var paid = 0;
	discount=0;
	var rowId = $('#identity').val();
	var rowIDArray = rowId.split(',');
	for(var n = 0; n < rowIDArray.length; n++) {
		subtotal += Number($('#balance_after'+rowIDArray[n]).val());
	}
	$('#all_total').val(subtotal);
	doRemain();
}
function doRemain() {
	var all_total = Number($('#all_total').val());
	var paid = Number($('#paid').val());
	if(paid > all_total){
		var paid = $('#paid').val(all_total);
		 $('#remain').val(0);
   }else{
	   remain = all_total-paid;
	   $('#balance').val(remain.toFixed(2));
	}	
}

	dojo.require("dijit.form.DateTextBox");
	dojo.require("dijit.form.NumberTextBox");
</script>