<?php 
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$form=$this->form_sale;
	$url_submit = $this->url(array('module'=>'sales','controller'=>'payment','action'=>'add'));
?>
<title><?php echo $tr->translate("Customer Payment");?></title>
<div class="card pb-10 pt-10 pl-10 pr-10">
	<div class="card-content">
		<div class="card-box">
		<div class="card-box">
            <div class="col-sm-12 border-botom">
		    	<div class="col-sm-8 pd-0">
		    		<h4 class="m-b-0"><i class="fa fa-cube" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('Customer Payment');?></h4>
    			</div>
    			<div class="col-sm-4 text-right"></div>
    		</div>
    	</div>
			<form id="frm" action="<?php echo $url_submit; ?>" class="form-horizontal" enctype="multipart/form-data" method="post">
				<div class="col-md-4">	
					<div class="form-group">
						<div class="col-md-4">
							<?php echo $tr->translate("CUSTOMER_NAME");?>
						</div>
						<div class="col-md-8">
								<?php echo $form->getElement("customer_id");?>
						</div>
					</div>
					<div class="form-group">
	                   <label class="control-label col-md-12 col-sm-12 col-xs-12 title-blog bold" ><i class="fa fa-hand-o-right" aria-hidden="true"></i> <?php echo $tr->translate("CUSTOMER_INFO");?> 
	                   </label>
	                </div>
					<div class="form-group">
						<div class="col-md-4">
							<?php echo $tr->translate("Receipt No.");?>
						</div>
						<div class="col-md-8">
							<?php echo $form->getElement("receipt"); ?>
						</div>
					</div>
					<div class="form-group">
						<div class="col-md-4">
							<?php echo $tr->translate("DATE");?>
						</div>
						<div class="col-md-8">
							<?php echo $form->getElement("date_in");?>
						</div>
					</div>
					<div class="form-group">
	                   <label class="control-label col-md-12 col-sm-12 col-xs-12 title-blog bold" ><i class="fa fa-hand-o-right" aria-hidden="true"></i> <?php echo $tr->translate("PAYMENT_INFO");?> 
	                   </label>
	                </div>
					<div class="form-group">
						<div class="col-md-4">
								<?php echo $tr->translate("EXCHANGE_RATE");?>
						</div>
						<div class="col-md-8">
								<?php echo $form->getElement("exchange_rate");?>
						</div>
					</div>
					<div class="form-group">
						<div class="col-md-4">
							<?php echo $tr->translate("ជំពាក់សរុប​ :");?>
						</div>
						<div class="col-md-8">
							<?php echo $form->getElement("all_total");?>
						</div>
					</div>
					<div class="form-group">
						<div class="col-md-4">
							<?php echo $tr->translate("ប្រាក់ទទួលសរុប");?>
						</div>
						<div class="col-md-4">
								<?php echo $form->getElement("paid_dollar");?>
						</div>	
						<div class="col-md-4">
								<?php echo $form->getElement("paid_riel");?>
						</div>
					</div>
					<div class="form-group">
						<div class="col-md-4">
							<?php echo $tr->translate("PAYMENT_TYPE");?>
						</div>
						<div class="col-md-8">
							<?php echo $form->getElement("payment_name");?>
						</div>
					</div>
					<div class="form-group">
						<div class="col-md-4">
						</div>
						<div class="col-md-4">
							<?php echo $form->getElement("cheque");?>
						</div>
						<div class="col-md-4">
							<?php echo $form->getElement("bank_name");?>
						</div>
					</div>
					<div class="form-group">
						<div class="col-md-4">
							<?php echo $tr->translate("ប្រាក់បានបង់សរុប");?>
						</div>
						<div class="col-md-8">
							<?php echo $form->getElement("paid");?>
						</div>	
					</div>
					<div class="form-group">
						<div class="col-md-4">
							ប្រាក់នៅសល់ : 
						</div>
						<div class="col-md-8">
							<?php echo $form->getElement("balance");?>
						</div>
					</div>
					<div class="form-group">
						<div class="col-md-4">
							<?php echo $tr->translate("REMARK");?>
						</div>
						<div class="col-md-8">
							<?php echo $form->getElement("remark");?>
						</div>
						<div class="col-md-4">
						</div>
						<div class="col-md-8">
						</div>
					</div>
				</div>
				<div class="col-md-8">
					<div class="form-group">
						<table class="table table-striped table-bordered table-hover" style="font-size:12px;">
							<tr height="33px">
								<th><?php echo $tr->translate("DEL");?></th>
								<th><?php echo $tr->translate("NUM");?></th>
								<th style="white-space:nowrap;"><?php echo $tr->translate("ថ្ងៃ/ខែ/ឆ្នាំ");?></th>
								<th><?php echo $tr->translate("វិក័យបត្រ");?></th>
								<th><?php echo $tr->translate("ចំនួនទឹកប្រាក់");?></th>
								<th><?php echo $tr->translate("បញ្ចុះតម្លៃ");?></th>
								<th><?php echo $tr->translate("ទឹកប្រាក់បានបង់");?></th>
								<th><?php echo $tr->translate("ទឹកប្រាក់នៅខ្វះ");?></th>
							</tr>
							<tbody id="table_row" style="font-size:12px;">
					 		</tbody>
					 </table>
					 <input type="hidden" id="identity" name="identity" />
					</div>
				</div>
				<div class="form-group">
				    <div class="card-box">
						<div class="border-top" >
							<div class="col-md-4"></div>
							<div class="col-md-5" class='center'>
								<input type="submit" value="btnsavenew" id="btnsavenew" name="save_close" label="<?php echo $tr->translate("SAVE_NEW")?>" dojoType="dijit.form.Button" 
								iconClass="dijitIconSearch" />
							</div>
							<div class="col-md-4"></div>
						</div>
					</div>
				</div>
			</form>
		</div>
	</div>
</div>
<script src="<?php echo $this->baseUrl();?>/js/help.js"  type="text/javascript"></script>
<script>
function paidtotal(type){//1=dollar,2=riel
	paid_dollar = dijit.byId("paid_dollar").get('value');
	paid_riel = dijit.byId("paid_riel").get('value');
	
	if(isNaN(paid_riel)){paid_riel=0;};
	
	dollar_fromriel = parseFloat(paid_riel/dijit.byId("exchange_rate").get('value'));
	all_paid =  parseFloat(paid_dollar) + parseFloat(dollar_fromriel);
	all_paid = (all_paid).toFixed(2);
	dijit.byId("paid").attr('value',all_paid);
	doRemain();
}
function checkpayment(){
	payment_id = dijit.byId("payment_name").get('value');
	/*if(payment_id==2){
		dijit.byId('bank_name').set('readonly',false);
		dijit.byId("cheque").set("readonly",false);
	}else{
		dijit.byId("bank_name").set("readonly",true);
		dijit.byId("cheque").set("readonly",true);
	}*/
}
<?php $urlgetinvoice =  $this->url(array('module'=>'sales','controller'=>'payment','action'=>'getinvoice')); ?>
function getInvoice(type){
	dijit.byId('balance').attr('value',0);
	dijit.byId('all_total').attr('value',0);
	dijit.byId('paid').attr('value',0); 
	type=1;
	post_id=dijit.byId("customer_id").get('value');
	$.ajax({
			url:"<?php echo $urlgetinvoice;?>",
			type:"post",
			data:{
				'post_id':post_id,
				'type_id':type
			},
			success: function(data){	
				$('#identity').val("");
				data = $.parseJSON(data);
				for(i=0;i<data.length;i++){
					if(i==0){
						dijit.byId("customer_id").attr('value',data[i].customer_id);
					}
					index=i+1;
			        template='<td><img onClick="deleteRecord('+index+')" src="<?php echo BASE_URL; ?>/images/icon/delete.gif" /></td>';
					template+='<td>'+index+'</td>';
					template+='<td>'+data[i].date_sold+'</td>';
					template+='<td>'+data[i].sale_no+'<input type="hidden" value='+data[i].id+' id="invoice_no'+index+'" name="invoice_no'+index+'"/></td>';
					template+='<td>'+data[i].net_total+'<input type="hidden" value='+data[i].net_total+' id="subtotal'+index+'" name="subtotal'+index+'"/></td>';
					template+='<td>'+data[i].discount_value+'<input type="hidden" value='+data[i].discount_value+' id="discount'+index+'" name="discount'+index+'"/></td>';
					if(data[i].paid==null){
						data[i].paid=0;
					}
					template+='<td>'+data[i].paid+'<input type="hidden" value='+data[i].paid+' id="paid_amount'+index+'" name="paid_amount'+index+'"/></td>';
					template+='<td>'+data[i].all_totalafter+'<input type="hidden" value='+data[i].all_totalafter+' id="balance_after'+index+'" name="balance_after'+index+'"/></td>';
					
					if($('#identity').val()!="") {
						var identity = $('#identity').val();
						$('#identity').val(identity+','+index);
					} else {$('#identity').val(index);}
					
					tmp='<tr id="row_order_'+index+'">';
					tmp+="</tr>";
					$('#table_row').append(tmp);
					
					dojo.html.set(dojo.byId('row_order_'+index),template , {
					     parseContent: true,
					});
				}
				netTotal();
			},
			error:function(e){
			}
		});	
}
function deleteRecord(index) {
	var identity = $('#identity').val();
	var arrays = identity.split(',');
	for(var i=0;i<arrays.length;i++) {
		if(arrays[i] == index) arrays.splice(i,1);
	}
	var strings = arrays.join(',');
	$('#identity').val(strings);
	$("#row_order_"+index).remove();
	netTotal();
}
function netTotal() {//use
	var subtotal=0;
	var paid = 0;
	discount=0;
	var rowId = $('#identity').val();
	var rowIDArray = rowId.split(',');
	for(var n = 0; n < rowIDArray.length; n++) {
		subtotal += Number($('#balance_after'+rowIDArray[n]).val());
	}
	dijit.byId('all_total').attr('value',subtotal);
	dijit.byId('paid').attr('value',0);
	doRemain();
}
function doRemain() {
	var all_total = Number(dijit.byId('all_total').get('value'));
	var paid = Number(dijit.byId('paid').get('value'));
	if(paid > all_total){
		
		dijit.byId('paid').attr('value',all_total);
		dijit.byId('balance').attr('value',0);
   }else{
	   remain = all_total-paid;
	   dijit.byId('balance').attr('value',remain.toFixed(2));
	}	
}
	dojo.require("dijit.form.NumberTextBox");
	dojo.require("dijit.form.DateTextBox");
</script>	