<?php 
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$form=$this->form_sale;
	$url_cancel = $this->url(array('module'=>'sales','controller'=>'payment','action'=>'index',null));
?>
<title><?php echo $tr->translate("Edit Customer Payment");?></title>
<div class="card pb-10 pt-10 pl-10 pr-10">
	<div class="card-content">
		<div class="card-box">
		<div class="card-box">
            <div class="col-sm-12 border-botom">
		    	<div class="col-sm-8 pd-0">
		    		<h4 class="m-b-0"><i class="fa fa-cube" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('Edit Customer Payment');?></h4>
    			</div>
    		</div>
    	</div>
		<form action="" class="form-horizontal" enctype="multipart/form-data" method="post">
			<div class="col-md-4">
				<div class="form-group">
					<label class="col-md-4">
						<?php echo $tr->translate("CUSTOMER_NAME");?>
					</label>
					<div class="col-md-8">
						<?php echo $form->getElement("customer_id");?>
					</div>
				</div>
				<div class="form-group">
					<label class="col-md-4">
						<?php echo $tr->translate("Invoice");?>
					</label>
					<div class="col-md-8">
						<?php echo $form->getElement('invoice_id');?>
					</div>
				</div>
				<div class="form-group">
					<label class="col-md-4">
						<?php echo $tr->translate("Receipt No.");?>
					</label>
					<div class="col-md-8">
						<?php echo $form->getElement("receipt"); ?>
					</div>
				</div>
				<div class="form-group">
					<label class="col-md-4">
						<?php echo $tr->translate("DATE");?>
					</label>
					<div class="col-md-8">
						<?php echo $form->getElement("date_in");?>
					</div>
				</div>
				<div class="form-group">
					<label class="col-md-4">
						<?php echo $tr->translate("PAYMENT_TYPE");?>
					</label>
					<div class="col-md-8">
						<?php echo $form->getElement("payment_name");?>
					</div>
				</div>
				<div class="form-group">
					<label class="col-md-4">
						<?php echo $tr->translate("REMARK");?>
					</label>
					<div class="col-md-8">
						<?php echo $form->getElement("remark");?>
					</div>
				</div>
				<div class="form-group">
					<label class="col-md-4">
						<?php echo $tr->translate("ជំពាក់សរុប​ :");?>
					</label>
					<div class="col-md-8">
						<?php echo $form->getElement("all_total");?>
					</div>
				</div>
				<div class="form-group">
					<label class="col-md-4">
						<?php echo $tr->translate("ប្រាក់បានបង់សរុប");?>
					</label>
					<div class="col-md-8">
						<?php echo $form->getElement("paid");?>
					</div>	
				</div>
				<div class="form-group">
					<label class="col-md-4">
						ប្រាក់នៅសល់ (Balance)​ :
					</label>
					<div class="col-md-8">
						<?php echo $form->getElement("balance");?>
					</div>
				</div>
			</div>
			<div class="col-md-8">
				<div class="form-group">
					<table class="table table-striped table-bordered table-hover" id="table_order" style="font-size:12px;">
						<tr height="33px">
							<th><?php echo $tr->translate("DEL");?></th>
							<th><?php echo $tr->translate("NUM");?></th>
							<th style="white-space:nowrap;"><?php echo $tr->translate("ថ្ងៃ/ខែ/ឆ្នាំ");?></th>
							<th><?php echo $tr->translate("វិក័យបត្រ");?></th>
							<th><?php echo $tr->translate("ចំនួនទឹកប្រាក់");?></th>
							<th><?php echo $tr->translate("បញ្ចុះតម្លៃ");?></th>
							<th><?php echo $tr->translate("ទឹកប្រាក់បានបង់");?></th>
							<th><?php echo $tr->translate("ទឹកប្រាក់នៅខ្វះ");?></th>
						</tr>
				 	</table>
					<input type="hidden" id="identity" name="identity" />
				</div>
			</div>
			</form>
		</div>
	</div>
</div>
<script>
$( document ).ready(function() {
	initialize();
});
function checkControll(){
	$("#table_order").html("");
	$('#balance').val(0);$('#all_total').val(0);$('#paid').val(0); alert("No invoice to make payment");
	payment_method = $("#payment_method").val();
	if(payment_method==1){
		$( "#invoice_id" ).attr( "readOnly", true );
		$( "#customer_id" ).attr( "readOnly", false );
	}else{
		$( "#customer_id" ).attr( "readOnly", true );
		$( "#invoice_id" ).attr( "readOnly", false );
    }
}
function initialize(){
	$("#table_order").html("");
	template='<tr height="33px">';
		template+='<th><?php echo $tr->translate("DEL");?></th>';
		template+='<th><?php echo $tr->translate("NUM");?></th>';
		template+='<th style="white-space:nowrap;"><?php echo $tr->translate("ថ្ងៃ/ខែ/ឆ្នាំ");?></th>';
		template+='<th><?php echo $tr->translate("វិក័យបត្រ");?></th>';
		template+='<th><?php echo $tr->translate("ចំនួនទឹកប្រាក់");?></th>';
		template+='<th><?php echo $tr->translate("បញ្ចុះតម្លៃ");?></th>';
		template+='<th><?php echo $tr->translate("ទឹកប្រាក់បានបង់");?></th>';
		template+='<th><?php echo $tr->translate("ទឹកប្រាក់នៅខ្វះ");?></th>';
	template+='</tr>';
	
	$('#identity').val("");
	var i=0;
	<?php if (!empty($this->reciept_detail)) foreach ($this->reciept_detail as $row){?>
		index=i+1;
		template+='<tr style="height:30px;">';
            template+='<td><img onClick="deleteRecord('+index+')" src="<?php echo BASE_URL; ?>/images/icon/delete.gif" /></td>';
			template+='<td>'+index+'</td>';
			template+='<td><?php echo $row['date_input'];?></td>';
			template+='<td><?php echo $row['invoice_no'];?><input type="hidden" value="'+<?php echo $row['invoice_id'];?>+'" id="invoice_no'+index+'" name="invoice_no'+index+'"/></td>';
			template+='<td><?php echo $row['total'];?><input type="hidden" value="<?php echo $row['total'];?>" id="subtotal'+index+'" name="subtotal'+index+'"/></td>';
			template+='<td><?php echo $row['discount'];?><input type="hidden" value="<?php echo $row['discount'];?>" id="discount'+index+'" name="discount'+index+'"/></td>';
			template+='<td><?php echo $row['paid'];?><input type="hidden" value="<?php echo $row['paid'];?>" id="paid_amount'+index+'" name="paid_amount'+index+'"/></td>';
			template+='<td><?php echo $row['balance'];?><input type="hidden" value="<?php echo $row['balance'];?>" id="balance_after'+index+'" name="balance_after'+index+'"/></td>';
	    template+="</tr>";
		i++;
		if($('#identity').val()!="") {
			var identity = $('#identity').val();
			$('#identity').val(identity+','+index);
		} else {$('#identity').val(index);}
	<?php }?>
	$('#table_order').append(template);
}
function deleteRecord(index) {
	var identity = $('#identity').val();
	var arrays = identity.split(',');
	for(var i=0;i<arrays.length;i++) {
		if(arrays[i] == index) arrays.splice(i,1);
	}
	var strings = arrays.join(',');
	$('#identity').val(strings);
	$("#row_order_"+index).remove();
	netTotal();
}
function netTotal() {//use
	var subtotal=0;
	var paid = 0;
	discount=0;
	var rowId = $('#identity').val();
	var rowIDArray = rowId.split(',');
	for(var n = 0; n < rowIDArray.length; n++) {
		subtotal += Number($('#balance_after'+rowIDArray[n]).val());
	}
	dijit.byId('all_total').attr('value',subtotal);
	dijit.byId('paid').attr('value',0);
	doRemain();
}
function doRemain() {
	var all_total = Number(dijit.byId('all_total').get('value'));
	var paid = Number(dijit.byId('paid').get('value'));
	if(paid > all_total){
		
		dijit.byId('paid').attr('value',all_total);
		dijit.byId('balance').attr('value',0);
   }else{
	   remain = all_total-paid;
	   dijit.byId('balance').attr('value',remain.toFixed(2));
	}	
}
	dojo.require("dijit.form.NumberTextBox");
	dojo.require("dijit.form.DateTextBox");
</script>	