<?php 
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
?>
<title><?php echo $tr->translate("STOCK_DAMAGED");?></title>
<?php 
	$formFilter = $this->formFilter;
?>
<div class="card pb-10 pt-10 pl-10 pr-10">
	<div class="card-content">
		<div class="card-box">
			<form  method="post" action="" >
				<div class="form-group">
					<div class="col-md-3">
						<?php echo $formFilter->getElement('ad_search');?>
					</div>
					<div class="col-md-3">
						<?php echo $formFilter->getElement('start_date');?>
					</div>
					<div class="col-md-3">
						<?php echo $formFilter->getElement('end_date');?>
					</div>
					<div class="col-md-3">
						<input type="submit" value="btnsavenew" id="btnsavenew" name="save_close" label="<?php echo $tr->translate("REFRESH")?>" dojoType="dijit.form.Button" 
							iconClass="dijitIconSearch" />
					</div>
				</div>		
			</form> 
		</div>
		<div class="card-box">
			<?php echo $this->list;?>
		</div>
	</div>
</div>
<script>
dojo.require("dijit.form.DateTextBox");
</script>