<?php 					
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$session_user=new Zend_Session_Namespace('auth');
	$username = $session_user->fullname;
	$branch_id = $session_user->location_id;
?>
<style>

.fullside{ width:100%; height: 35px;}
.fullblog{ width:100%; height: 30px;font-size: 15px !important;}
td{padding: 1px !important;}
.aligncenter{text-align: center;background:#eaeaea;
white-space: nowrap;font-size: 12px;line-height:33px;}
.hover:hover{background: #eee;}
.full_width{width:100%;}

</style>
<title>POS STOCK</title>
<div class="card pb-10 pt-10 pl-10 pr-10">
	<div class="card-content">
		<div class="card-box">
<form id='office_receipt' dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
	<script type="dojo/method" event="onSubmit">   
   	if(this.validate()) {
		branch_id = dijit.byId("branch_id").get("value");
		if(branch_id==-1){
			alert("សូមជ្រើសរើសសាខា !");
			dijit.byId('branch_id').focus();
			return false;
		}
		identity = $("#identity").val();
		if(identity==''){
			dijit.byId('product_id').focus();
			return false;
		}
		loadingBlock();
    	return true;
   }else {
    	return false;
   }
</script>
				<div class="col-md-9">
                   <div class="form-group">
	                   <label class="control-label col-md-12 col-sm-12 col-xs-12 title-blog bold" ><i class="fa fa-hand-o-right" aria-hidden="true"></i>
	                   	<?php echo $tr->translate("ទំនិញដែលបានទិញ");?> 
                   </label>
                </div>
               <div class="form-group" style="background: #cccccc;">
		    		<input id="product_id" />
		    		<input type="hidden" name="identity" id="identity" />
    				<input type="hidden" name="identity_term" id="identity_term" />
    				<input type="hidden" name="invoice" id="invoice" value="<?php echo $this->invoice;?>" /> 
				</div>
				<div class="form-group">
                    <table id="table_row" border="1px" style="border-collapse: collapse; border:1px solid #ccc;width:100%;">
					<thead>
						<tr id="head-title" class="table table-bordered" align="right" style="">
							<th class="aligncenter">#</th>
							<th class="aligncenter">ឈ្មោះមុខទំនិញ</th>
							<th class="aligncenter">ពណ៍នា</th>
							<th class="aligncenter">ជាង</th>
							<th class="aligncenter">ស្តុក</th>
							<th class="aligncenter">បរិ.ដុំ</th>
							<th class="aligncenter">បរិ.រាយ</th>
							<th class="aligncenter">បរិមាណ</th>
							<th class="aligncenter">តម្លៃលក់</th>
							<th class="aligncenter">បញ្ចុះតម្លៃ</th>
							<th class="aligncenter">សរុប</th>
							<th class="aligncenter">លុប</th>
						</tr>
						<tr>
							<td colspan="12" id="lbl_noproduct" align="center">មិនមាន ទំនិញ ក្នុងកន្រ្តក</td>
						</tr>
					</thead>
				</table>
			</div>
		  <div class="form-group" >
		  		Term Condition
			  	<div style="border:1px solid #ccc;">
					<textarea style="height: 120px;width:100%;" name="term_condition" id="term_condition" ></textarea>
				</div>
		 </div>
	</div>
	<div class="col-md-3" >
				<div class="form-group">
                   <label class="control-label col-md-12 col-sm-12 col-xs-12 title-blog bold" ><i class="fa fa-hand-o-right" aria-hidden="true"></i>
                   	<?php echo $tr->translate("អតិថិជន/ការទូទាត់");?> 
                   </label>
                </div>				
                 <div class="form-group">
					<input dojoType="dijit.form.DateTextBox" required="1" constraints="{datePattern:'dd/MM/yyyy'}"
                    class="full_width" value="<?php echo date("Y-m-d");?>" type="text" name="sale_date" id="sale_date" />
				</div>
				<div class="form-group">
					<select class="fullblog" name="branch_id" id="branch_id" dojoType="dijit.form.FilteringSelect" >
						<option value="-1">ជ្រើសរើសសាខា</option>
						<?php if(!empty($this->rs_branch)){ foreach($this->rs_branch as $rs){?>
							<option value="<?php echo $rs['id']?>" <?php if($rs['id']==$branch_id){echo "selected";}?>><?php echo $rs['name'];?></option>
						<?php }}?>
					</select>
				</div>
                <div class="form-group">
					<div class="col-md-8">
						<input type="text" id="customer_id" />
					</div>
					<div class="col-md-4">
						<input iconClass="dijitIconUndo" type="button" label="Refresh" dojoType="dijit.form.Button" onclick="AllRefresh();"/>
					</div>
			    </div>
				<div class="form-group">
					<div class="col-md-12">
						<button style="font-size: 14px;" type="button" name="btnsavenew" onclick="getSuppliyer();" class="btn red btn-block btn-md"><i class="fa fa-users" aria-hidden="true"></i>&nbsp;បន្ថែមអតិថិជន</button>
					</div>
				</div>
				<div class="form-group">
					<div class="col-md-6">JC#</div>
					<div class="col-md-6">
						<input type="text" class="full_width" name="cjnumber"  id="cjnumber"  dojoType="dijit.form.TextBox"/>
					</div>
				</div>
				<div class="form-group">
					<div class="col-md-6">Mileage</div>
					<div class="col-md-6">
						<input type="text" name="mileage" id="mileage"  class="full_width" dojoType="dijit.form.TextBox"/>
					</div>
				</div>
				<div class="form-group">
					<div class="col-md-6">
						អាត្រាប្តូរប្រាក់ 1$=
					</div>
					<div class="col-md-6">
						<input onkeyup="netTotal();" style="background:#d84a38;color:#fff" dojoType="dijit.form.NumberTextBox" class="full_width" value="<?php echo $this->rsrate;?>" type="text" name="exchange_rate" id="exchange_rate" />
					</div>
				</div>
				<div class="form-group">
					<div class="col-md-6">
						សរុបរង $
					</div>
					<div class="col-md-6">
						<input readonly dojoType="dijit.form.NumberTextBox" class="full_width" type="text" name="sub_total" id="sub_total" />
                        <input dojoType="dijit.form.TextBox" onkeyup="netTotal();" class="full_width" type="hidden" name="tax" id="tax" />
					</div>
				</div>
				<div class="form-group">
					<div class="col-md-6">
						បញ្ចុះតម្លៃ
					</div>
					<div class="col-md-6">
						<input dojoType="dijit.form.NumberTextBox" onkeyup="netTotal();" class="full_width" type="text" name="discount" id="discount" />
					</div>
				</div>
				<div class="form-group">
					<div class="col-md-6">
						សរុបរួមជាដុល្លារ
					</div>
					<div class="col-md-6">
						<input readonly type="text" style="" dojoType="dijit.form.NumberTextBox" class="full_width" name="total_dollar" id="total_dollar" />
					</div>
				</div>
				<div class="form-group">
					<div class="col-md-6">
						សរុបរួមជារៀល
					</div>
					<div class="col-md-6">
						<input readonly type="text" style="" dojoType="dijit.form.NumberTextBox" class="full_width" name="total_riel" id="total_riel" />
					</div>
				</div>
				<div class="form-group">
                   		<label class="control-label col-md-12 col-sm-12 col-xs-12 title-blog bold" ><i class="fa fa-hand-o-right" aria-hidden="true"></i>
                   			<?php echo $tr->translate("ការទទួលប្រាក់");?> 
                   		</label>
                </div>
					<div class="form-group">
						<label class="col-md-6">
							ប្រាក់ទទួលសរុប
						</label>
						<div class="col-md-6">
							<input type="hidden" value="0" onkeyup="calCualtepaid();" dojoType="dijit.form.TextBox" class="full_width" name="receive_dollar" id="receive_dollar" />
							<button type="button" name="btnsavenew" onclick="Fullpaid();" class="btn red btn-block btn-md"><i class="fa fa-usd" aria-hidden="true"></i>&nbsp;&nbsp;បង់គ្រប់</button>
							<input type="hidden" value="0"  onkeyup="calCualtepaid();" value="0" dojoType="dijit.form.TextBox" class="full_width" name="receive_riel" id="receive_riel" />
						</div>
					</div>
					<div class="form-group">
						 <div class="col-md-6">
						 </div>
						 <div class="col-md-6">
							<input type="text" required="true" dojoType="dijit.form.NumberTextBox" class="full_width" name="total_paid" id="total_paid" />
						 </div>
					 </div>
					 <div class="form-group">
						 <div class="col-md-6">ប្រាក់អាប់ដុល្លា</div>
						 <div class="col-md-6"><input readonly type="text" value="0" dojoType="dijit.form.NumberTextBox" class="full_width" name="return_amount" id="return_amount" /></div>
					 </div>
					 <div class="form-group">
						 <div class="col-md-6">ជំពាក់ជាដុល្លា</div>
						 <div class="col-md-6"><input readonly type="text" value="0" dojoType="dijit.form.NumberTextBox" class="full_width" name="balance" id="balance" /></div>
					 </div>
                     <div class="form-group">
	                     <div class="col-md-12">
	                     	<button style="background: #c7d7ea;border: 1px solid #8fa9c7;" type="submit" id="btnsavenew" name="btnsavenew" class="btn blue btn-block btn-lg"><i class="fa fa-print"></i> រក្សាទុក/បោះ ពុម្ភ</button>
						 </div>
					 </div>
  			</div>
  			</form>
		</div>
	</div>
</div>
<div class="dijitHidden" style="width: 20cm !important; height: 12cm ; padding: 0px; margin: 0px;">
<div id="invoice" data-dojo-type="dijit.Dialog" style="width:24cm;height: 18cm ;" align="center" data-dojo-props="title:'<?php echo $tr->translate("OFFICIAL_RECEIPT");?>'"  >
	<div id="PrintReceipt" style="border:1px dashed #ccc;width:18cm !important; padding: 0px; margin-bottom:30px; ">
			<style>
		.hearder_table{height:25px !important;}
		.defaulheight{line-height: 22px !important;}
		#PrintReceipt{display: table;}
		#pageFooter {
		    display: table-footer-group;
		}
		
#pageFooter:after {
    counter-increment: page;
    content:"Page " counter(page);
    left: 0; 
    top: 100%;
    white-space: nowrap; 
    z-index: 20px;
    -moz-border-radius: 5px; 
    -moz-box-shadow: 0px 0px 4px #222;  
    background-image: -moz-linear-gradient(top, #eeeeee, #cccccc);  
    background-image: -moz-linear-gradient(top, #eeeeee, #cccccc);  
  }
	</style>
		<table class="print" cellspacing="0"  cellpadding="0" style="width:98%;font-family: 'Khmer OS Battambang' !important; font-size:11px !important; margin-top:0 auto;white-space:nowrap;">
			<tr height="40px;">
			    <td colspan="10"  style="" align="center" valign="top">
					<table width="100%" style="font-size: 10px;margin-bottom: 0px;"   >
						<tr>
							<td width="40%" valign="top" align="center">
								<img style="height:45px" alt="<?php ?>" src="<?php echo $this->baseUrl().'/images/logo.jpg'?>"><br />
								<div style="font-size: 10px;font-family:'Khmer MEF2';text-align: center;width:100%;"><?php echo $tr->translate("COMPANY_CUSTOMER"); ?></div>
							</td>
							<td width="20%" align="center" valign="top" style=""><div style="font-size: 14px;font-family:'Khmer MEF2';">វិក្កយបត្រ</div>INVOICE
							</td>
							<td width="40%" valign="top">
								<div style="white-space: nowrap;"><?php echo $tr->translate("ADDRESS_COMPANY"); ?></div>
								លេខទូរសព្ទ<?php echo $tr->translate("TEL_COMPANY"); ?>
							</td>
						</tr>
					</table>
			    </td>
			</tr>
			<style>
			.bold{
				font-weight:bold;
				}
			.tablesorter td{font-family:'khmer os battambang' !important;}
			.one{line-height: 15px;}
			table { page-break-inside:auto }
			  tr{ page-break-inside:avoid; page-break-after:auto; }
			#header {
			  display: table-header-group;
			  page-break-inside:avoid; page-break-after:auto;
			}
			#footer {
			  display: table-footer-group;
			}
			@page {
			       @bottom-left {
			            content: counter(page) "/" counter(pages);
			        }
			     }
			@media print {
			    footer {page-break-after: always;}
			}
			</style>			
			<tr height="80px">
				<td colspan="6" width="60%" valign="top" >
					<table width="100%" style=" ;font-size: 11px;border: 1px solid #000;" >
						<tr>
							<td width="100px;">&nbsp;ឈ្មោះអតិថិជន</td>
							<td width="1px"> :</td>
							<td style="padding-top:5px;">
								<label id="lbl_customer" class="one" style="font-size: 11px;"></label>
							</td>
						</tr>
						<tr >
							<td>&nbsp;ទូរសព្ទ</td>
							<td colspan="1"> :</td>
							<td><label id="lbl_phone" class="one"></label></td>
						</tr>
						<tr >
							<td>&nbsp;អាសយដ្ឋាន </td>
							<td> :</td>
							<td><label id="lbl_address" class="one"></label></td>
						</tr>
					</table>
				</td>
				<td colspan="4" valign="top">
					<table width="100%" style="margin-left:2px;font-size: 11px;border: 1px solid #000;">
						<tr>
							<td width="90px;" style="white-space: nowrap;">&nbsp;លេខវិក្កយបត្រ</td>
							<td width="1px" style="padding-top:5px;">:</td>
							<td><label id="lb_invoice" class="one"><?php echo $this->invoice;?></label></td>
						</tr>
						<tr >
							<td>&nbsp;ថ្ងៃចេញ</td>
							<td colspan="1"> :</td>
							<td></td>
						</tr>
						<tr>
							<td>&nbsp;អ្នកលក់</td>
							<td colspan="1"> :</td>
							<td>
								<div style="font-weight:bold;color:#000; font-size: 11px;font-family:'Khmer OS Battambang';margin-top: -3px;"> 
								<?php 
								   echo $username;
								?>
								</div>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr>
				<td colspan="10" valign="top">
					<table class='defaulheight' width="100%" border="0" style="font-family: Khmer OS Battambang , Times New Roman;font-size:12px;white-space:nowrap;margin-top:-5px;line-height: 11px;">
						<tr>
							<td colspan="6" valign="top">
								<div id="t_amountmoneytype"></div>
							</td>
						</tr>
						<tr>
							<td colspan="6">
								<table border="0" width="100%" style="font-size:12px; white-space:nowrap;line-height:15px;margin-top:3px;border-collapse:collapse;">
									<tr>
										<td colspan="4">
											<table width="100%" border="0" style="white-space:nowrap;border-collapse:collapse;font-size:12px;line-height:16px;">	
												<tr>
													<td width="25%" align="center">អតិថិជន</td>
													<td width="25%" align="center">អ្នកទទួល</td>
													<td width="25%" align="center">អ្នកដឹក</td>
													<td width="25%" align="center">អ្នកចេញទំនិញ</td>
												</tr>	
											</table>	
										</td>
									</tr>
								</table>
							</td>
						</tr>
					</table>
				</td>
			</tr>
		</table>
    </div>
	<div class="col-md-4">
         <button type="button" onclick="printinvoice();" name="btnsavenew" class="btn red btn-block btn-lg"><i class="fa fa-print"></i> រក្សាទុកនិងបោះពុម្ភ</button>
	</div>
	<div class="col-md-4"></div>
	</div>
</div>
<iframe name=print_frame width=0 height=0 frameborder=0 src=about:blank></iframe>			
<script src="<?php echo $this->baseUrl();?>/js/help.js"  type="text/javascript"></script>
<script>
function getSuppliyer(){
	window.open('<?php echo $this->baseUrl();?>/sales/customer/add?rightclick=true','_blank');
}
dojo.require("dijit.form.NumberTextBox");  
dojo.require("dojo.NodeList-manipulate");
dojo.require("dojo.html");
//dojo.require("dijit.Dialog");
//dojo.require("dojo.number");
dojo.require("dojo.data.ItemFileWriteStore");  
dojo.require("dijit.form.DateTextBox");

var product_store  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode($this->rsproduct));?> );
var client_store  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode($this->rscustomer));?> );

require(["dojo/ready"], function(ready){
	 ready(function(){
		 dijit.byId("product_id").attr("value",'');
			dijit.byId("product_id").focus();
			dijit.byId("customer_id").attr("value",1);
	 });
	 
		new dijit.form.FilteringSelect({
		store: product_store,
		required: false,		           
		name: "product_id",
		id: "product_id",
		searchAttr: "name",
		queryExpr: "*${0}*",
		autoComplete: false,
		class: 'fullside',
		onChange: function() {
			addProductRow();
		}
		}, "product_id");

		new dijit.form.FilteringSelect({
			store: client_store,
			autoComplete: false,
			required: false,		           
			name: "customer_id",
			id: "customer_id",
			searchAttr: "name",
			queryExpr: "*${0}*",
			class: 'fullblog',
			onChange: function() {
				getCustomerInfo();
			}
			}, "customer_id");
});
function showReceipt(){
	if(dijit.byId('office_receipt').validate()){
	balance = dijit.byId("balance").get("value");
	customer_id = dijit.byId("customer_id").get("value");
	if(balance> 0 && (customer_id=='' || customer_id==1)){alert("សូមជ្រើសរើស អតិថិជន");dijit.byId("customer_id").focus();return false;}
	var rowId = $('#identity').val();
	if(rowId==''){alert("មិនមាន ទំនិញ ក្នុងកន្រ្តក");dijit.byId("product_id").focus();return false;}

	dojo.byId("lbl_customer").innerHTML=dijit.byId('customer_id').attr("displayedValue");
	 var rowIDArray = rowId.split(',');
	 temp='<table class="collape tablesorter"  align="center" style=" width: 100%; padding: 0px; margin-top: 3px !important; border-collapse: collapse; border: 1px solid #000; font-size:11px;font-family:Khmer OS Battambang !important;  " id="table">'
		  temp+='<thead><tr class="hearder_table" style="font-family:khmer os battambang;text-align:center;background:#f2f2f2 !important;font-weight:bold;">';
		  temp+='<td style="border:1px solid #000;font-size:12px;">លរ</td>';
	      temp+='<td style="border:1px solid #000;font-size:12px;"><strong style="color:#000;">ឈ្មោះមុខទំនិញ</strong></td>';
		  temp+='<td style="border:1px solid #000;font-size:12px;"><strong style="color:#000;">ចំនួន</strong></td>';
		  temp+='<td style="border:1px solid #000;font-size:12px;"><strong style="color:#000;">តម្លៃរាយ</strong></td>';
		  temp+='<td style="border:1px solid #000;font-size:12px;"><strong style="color:#000;">សរុប</strong></td>';
		  temp+='</tr></thead>';
		  var rowId = $('#identity').val();
		  var rowIDArray = rowId.split(',');
		  i=0;		  	
		for(var n = 0; n < rowIDArray.length; n++) {
			i++;
			  temp+='<tr style=" font-size:12px !important; text-align:center;font-weight:bold;">';
			  temp+='<td style="border:1px solid #000;">'+i+'</td>';
			  temp+='<td style="border:1px solid #000;text-align:left;"><strong style="color:#000;">&nbsp;'+$('#product_name'+rowIDArray[n]).val();+'</strong></td>';
			  label = $('#measur_name'+rowIDArray[n]).val();
			  qtydetail = $('#qtydetail_'+rowIDArray[n]).val();
			  if(qtydetail>0){
					unit_label = $('#unit_label'+rowIDArray[n]).val();
					label = label+" "+qtydetail+""+unit_label;
			  }
			  temp+='<td style="border:1px solid #000;"><strong style="color:#000;">'+dijit.byId('qty_'+rowIDArray[n]).get("value")+' '+label;'</strong></td>';
			  temp+='<td style="border:1px solid #000;"><strong style="color:#000;">$ '+dojo.number.format(dijit.byId('price_'+rowIDArray[n]).get("value"),{places:3});+'</strong></td>';
			  temp+='<td style="border:1px solid #000;"><strong style="color:#000;">$ '+dojo.number.format(dijit.byId('sub_total'+rowIDArray[n]).get("value"),{places:3});+'</strong></td>';
		  temp+='</tr>';
		}
		 
		 for(j=i;i<=13;i++){
			 j++;
	    	 temp+='<tr style="height:25px;;text-align:right;font-weight:bold;">';
			 temp+='<td style="border:1px solid #000;text-align:center;" >'+j+'</td>';
			 temp+='<td style="border:1px solid #000;">&nbsp;</td>';
			 temp+='<td style="border:1px solid #000;" ></td>';
			 temp+='<td style="border:1px solid #000;"></td>';
			 temp+='<td style="border:1px solid #000;" ></td>';
		     temp+='</tr>';
		     }
			 temp+='<tr style=" font-size:12px; text-align:right;font-weight:bold;">';
			 temp+='<td style="border:1px solid #fff;border-right:1px solid #000" colspan="3"> '+dojo.number.format(dijit.byId('total_riel').get("value"),{places:0})+' រៀល&nbsp;</td>';
			 temp+='<td style="border:1px solid #000;><strong style="color:#000;">សរុប</strong>&nbsp;</td>';
			 temp+='<td style="border:1px solid #000;font-size:14px !important;"><strong style="color:#000;font-family:arial;font-weight:bold;" >$ '+dojo.number.format(dijit.byId('sub_total').get('value'),{places:3})+'</strong>&nbsp;</td>';
		     temp+='</tr>';

		     temp+='<tr style=" font-size:12px; text-align:right;font-weight:bold;">';
		     temp+='<td style="border:1px solid #fff;border-right:1px solid #000;text-align:left;" colspan="3">- សូមពិនិត្យទំនិញអោយបានត្រឹមត្រូវ</td>';
			 temp+='<td style="border:1px solid #000;><strong style="color:#000;">ទទួលជាដុលា&nbsp;</strong></td>';
			 temp+='<td style="border:1px solid #000;><strong style="color:#000;">$ '+dojo.number.format(dijit.byId('receive_dollar').get('value'),{places:3})+'</strong>&nbsp;</td>';
		     temp+='</tr>';

		     temp+='<tr style=" font-size:12px; text-align:right;font-weight:bold;">';
		     temp+='<td style="border:1px solid #fff;border-right:1px solid #000;text-align:left;" colspan="3">- ទំនិញដែលទិញហើយមិនអាចប្តូរវិញបានទេ</td>';
			 temp+='<td style="border:1px solid #000;><strong style="color:#000;">ប្រាក់ទទួលសរុប&nbsp;</strong></td>';
			 temp+='<td style="border:1px solid #000;font-size:14px !important;"><strong style="color:#000;font-family:arial;font-weight:bold;">$ '+dojo.number.format(dijit.byId('total_paid').get('value'),{places:3})+'</strong>&nbsp;</td>';
		     temp+='</tr>';
		     
		     temp+='<tr style=" font-size:12px; text-align:right;font-weight:bold;">';
			 temp+='<td style="border:1px solid #fff;border-right:1px solid #000" colspan="3"></td>';
			 temp+='<td style="border:1px solid #000;font-size:12px !important;"><strong style="color:#000;">នៅខ្វះជាដុលា&nbsp;</strong></td>';
			 temp+='<td style="border:1px solid #000;font-size:14px !important;"><strong style="color:#000;font-family:arial;font-weight:bold;">$ '+dojo.number.format(dijit.byId('balance').get('value'),{places:3})+'</strong>&nbsp;</td>';
		     temp+='</tr>';
		     
	temp+='</table>';
	dojo.byId('t_amountmoneytype').innerHTML = temp;
	dijit.byId('invoice').show();
	}
}
function printinvoice(){
	var printContents = document.getElementById('PrintReceipt').innerHTML;
    var originalContents = document.body.innerHTML;
    document.body.innerHTML = printContents;
    window.print();
    document.body.innerHTML = originalContents;
	document.getElementById("office_receipt").submit();
}
<?php $url_add_customer =  $this->url(array('module'=>'sales','controller'=>'customer','action'=>'get-customer')); ?>
function AllRefresh(){	
	loadingBlock();
	dojo.xhrPost({
		url: "<?php echo $url_add_customer;?>",
		handleAs:"json", 
	    load: function(data) {
			customer_store  = getDataStorefromJSON('id','name',data);
			dijit.byId('customer_id').set('store',customer_store);  
			HideloadingBlock(); 
		},		
		error: function(err) {
		}
	});
}
<?php $url_getcustomerinfo =  $this->url(array('module'=>'sales','controller'=>'customer','action'=>'get-customerinfo')); ?>
function getCustomerInfo(){
	customer_id = dijit.byId("customer_id").get("value");
	if(customer_id==-1){
	}else{
		dojo.xhrPost({
		    url: "<?php echo $url_getcustomerinfo;?>",
		    content : { 
		    	'customer_id':customer_id,
			},				    
		   handleAs:"json", 
		   load: function(data) {
			   dojo.byId("lbl_customer").innerHTML=data.cust_name;
			   dojo.byId("lbl_phone").innerHTML=data.contact_phone+'/'+data.phone;
			   dojo.byId("lbl_address").innerHTML=data.address;
		   },		
		  error: function(err) {
		  }
	   });
	}
}
function deleteRecord(index) {	
	var identity = $('#identity').val();
	var arrays = identity.split(',');
	for(var i=0;i<arrays.length;i++) {
		if(arrays[i] == index) arrays.splice(i,1);
	}
	var strings = arrays.join(',');
	$('#identity').val(strings);
	dojo.query("#row"+index).forEach(dojo.destroy);
	netTotal();
}

col=0;
no=0;
title=0;
temp='';
function addProductRow(){
	product_name = dijit.byId("product_id").attr("displayedValue");
	product_id = dijit.byId("product_id").get('value');
	if(product_name=='' ){return false;}
		col++;no++;
		template='';
		if(title!=1){    
			title=1;
			dojo.byId('lbl_noproduct').innerHTML = '';
		}
		template+='<td style="min-width:20px;text-align:center">'+col+'</td>';
		template+='<td style="min-width:180px;font-size:12px;" valign="top"><input type="hidden" value="'+product_name+'" id="product_name'+col+'">'+product_name+'<input type="hidden"  value="'+product_id+'" id="product_id'+col+'" name="product_id'+col+'" /></td>';
		template+='<td style="min-width:130px;font-size:12px;" valign="top"><input class="fullblog" dojoType="dijit.form.TextBox" type="text" name="note'+col+'" id="note'+col+'"/></td>';
		template+='<td style="min-width:80px;font-size:12px;" valign="top"><select queryExpr="*${0}*" autoComplete="false" required="false" dojoType="dijit.form.FilteringSelect" name="staff_'+col+'" id="staff_'+col+'">';<?php if(!empty($this->rs_staff))foreach($this->rs_staff as $rs){ ?>
			template+='<option value="<?php echo $rs["id"];?>"><?php echo $rs["name"];?></option>';
			<?php }?>
		template+='</select></td>';
		
		template+='<td style="min-width:60px" valign="top"><lable style="font-size:12px;" id="lblcurrent_qty'+col+'"></lable><input type="hidden" name="qty_perunit'+col+'" id="qty_perunit'+col+'"/><input type="hidden" readonly dojoType="dijit.form.TextBox" id="current_qty'+col+'" name="current_qty'+col+'" /><input type="hidden" dojoType="dijit.form.TextBox" name="measur_name'+col+'" id="measur_name'+col+'"/></td>';
		template+='<td style="min-width:30px" valign="top"><input type="hidden" dojoType="dijit.form.TextBox" name="unit_label'+col+'" id="unit_label'+col+'"/><input type="text" onkeyup="calCualtePrice('+col+');" name="qty_'+col+'" class="fullblog" id="qty_'+col+'" dojoType="dijit.form.NumberTextBox" placeholder=""/></td>';
		template+='<td style="min-width:30px" valign="top"><input type="text" onkeyup="calCualtePrice('+col+');" name="qtydetail_'+col+'" class="fullblog" id="qtydetail_'+col+'" dojoType="dijit.form.NumberTextBox" placeholder=""/></td>';
		template+='<td style="min-width:30px" valign="top"><input required="1" readonly name="qty_sold'+col+'" class="fullblog" id="qty_sold'+col+'" dojoType="dijit.form.NumberTextBox" placeholder=""/></td>';
		template+='<td style="min-width:30px" valign="top"><input required="1" type="text" tabindex="'+col+'" readonly="true" onkeyup="calCualtePrice('+col+');" name="price_'+col+'" class="fullblog" id="price_'+col+'" dojoType="dijit.form.NumberTextBox" placeholder=""/><input type="hidden" name="cost_price'+col+'" id="cost_price'+col+'" dojoType="dijit.form.TextBox" /></td>';
		template+='<td style="min-width:30px" valign="top"><input type="text"  onkeyup="calCualtePrice('+col+');"  name="discount_'+col+'" class="fullblog" id="discount_'+col+'" dojoType="dijit.form.TextBox" placeholder=""/></td>';
		template+='<td style="min-width:50px" valign="top"><input type="text" name="sub_total'+col+'" class="fullblog" id="sub_total'+col+'" dojoType="dijit.form.NumberTextBox" readonly/></td>';
		template+='<td width="40px" valign="top"><img onclick="deleteRecord('+col+')" src="<?php echo $this->baseUrl();?>/images/Delete_16.png" /></td>';
		tmp='<tr id="row'+col+'" class="hover">';
		tmp+="</tr>";
		dojo.query("#table_row").append(tmp);

		if($("#identity").val()!="") {
			var identity = $("#identity").val();
			$("#identity").val(identity+','+col);
		} else {$("#identity").val(col);}
		dojo.html.set(dojo.byId("row"+col),template , {
		     parseContent: true,
		});
		dijit.byId("product_id").attr("value",'');
		dijit.byId("product_id").focus();
		getProductinfo(col,product_id);
}
function calCualtePrice(index){
	main_qty= $("#qty_"+index).val();
	if(main_qty==''){main_qty=0;}
	detail_qty= $("#qtydetail_"+index).val();//ចំនួនរាយ
	if(detail_qty==''){detail_qty=0;}
	qty_perunit= $("#qty_perunit"+index).val();//ចំនួនក្នុង១ឯកកតា
	if(qty_perunit==''){qty_perunit=0;}
	qty_sold = parseFloat(main_qty) + parseFloat(detail_qty/(qty_perunit));
	$('#qty_sold'+index).val(qty_sold);
	
	price = dijit.byId("price_"+index).get("value");
	dijit.byId("qty_sold"+index).attr("value",qty_sold);

	discount = dijit.byId("discount_"+index).get("value");
	discount = isNaN(tax)?0:discount;

	total = (price*qty_sold)-discount;
	dijit.byId("sub_total"+index).attr("value",total);
	
	netTotal();
}
function netTotal() {//use
	var netTotal=0;
	var rowId = $('#identity').val();
	var rowIDArray = rowId.split(',');
	for(var n = 0; n < rowIDArray.length; n++) {
		netTotal += Number(dijit.byId('sub_total'+rowIDArray[n]).get('value'));
	}
	
	dijit.byId("sub_total").attr("value",netTotal);
	
	discount = dijit.byId("discount").get("value");
	discount = isNaN(discount)?0:discount;
	tax = dijit.byId("tax").get("value");
	tax = isNaN(tax)?0:tax;
	exchange_rate = dijit.byId("exchange_rate").get("value");
	exchange_rate = isNaN(exchange_rate)?0:exchange_rate;

	total_dollar = netTotal+(netTotal*tax/100)-discount;
	dijit.byId('total_dollar').attr('value',total_dollar);
	total_riel = total_dollar*exchange_rate;
	dijit.byId('total_riel').attr('value',total_riel);
	calCualtepaid();
}
function calCualtepaid(){
	receive_dollar = dijit.byId('receive_dollar').get('value');
	receive_dollar = isNaN(receive_dollar)?0:receive_dollar;

	receive_riel = 0;//dijit.byId('receive_riel').get('value');
	receive_riel = isNaN(receive_riel)?0:receive_riel;
	
	exchange_rate = dijit.byId("exchange_rate").get("value");
	exchange_rate = isNaN(exchange_rate)?0:exchange_rate;
	
	total_received = receive_dollar+parseFloat(receive_riel/exchange_rate)
	
	total_dollar = dijit.byId('total_dollar').get('value');
	return_amount = total_received-total_dollar;
	
	dijit.byId('balance').attr('value',0);
	if(return_amount<0){
		return_amount = -return_amount;
		dijit.byId('balance').attr('value',return_amount);
		return_amount=0;
	}
	if(total_received>total_dollar){
		total_received=total_dollar;
	}
	dijit.byId('total_paid').attr('value',total_received);
	dijit.byId('return_amount').attr('value',return_amount);
}
function Fullpaid(){
	total_dollar = dijit.byId('total_dollar').get('value');
	total_dollar = isNaN(total_dollar)?0:total_dollar;
	dijit.byId("receive_dollar").attr("value",total_dollar);
	dijit.byId("total_paid").attr("value",total_dollar);
	dijit.byId("return_amount").attr("value",0);
	dijit.byId("balance").attr("value",0);
}

var url_getproduct = '<?php echo $this->url(array('module'=>'sales','controller'=>'possale','action'=>'getproduct')); ?>';
function getProductinfo(index,product_id){
   customer_id = dijit.byId('customer_id').get('value');
   if(customer_id==-1 || customer_id==''){
	   		dijit.byId('customer_id').focus();
			return false;
		}
   agreement_id = 0;
	dojo.xhrPost({
	    url: url_getproduct,
	    content : { 
	    	'product_id':product_id,
	    	'branch_id':1,
	    	'agreement_id':agreement_id,
	    	'customer_id':customer_id
		},				    
	   handleAs:"json", 
	   load: function(data) {
		    $('#product_name').val(data.item_name);
			dijit.byId("current_qty"+index).attr('value',data.qty);
			dijit.byId("price_"+index).attr('value',data.price);
			dijit.byId("cost_price"+index).attr('value',data.cost_price);
			dijit.byId("measur_name"+index).attr('value',data.measue_name);
			dijit.byId("unit_label"+index).attr('value',data.unit_label);

			dijit.byId("qty_"+index).attr('value',1);
			dijit.byId("qty_sold"+index).attr('value',1);

			qty = data.qty;
			if(qty==null){qty=0;}
			qtyall_detail = qty*(data.qty_perunit);//eg;qty 1.5 and 1unit =24cans; =>1.5*24 =36cans.
			qty_unitlable = qtyall_detail % (data.qty_perunit);//រកចំនួនរាយ
			qty_unitlable = qty_unitlable.toFixed(2)
			if(qty_unitlable>0){qty_unitlable=qty_unitlable+""+data.unit_label;}else{qty_unitlable=""; }
			qty=parseInt(qty);
            measure_name = data.measue_name;
			if(data.measue_name==null){measure_name='';}
			if(qty_unitlable==''){
				qty_unitlable = "";
			}else{
				qty_unitlable = "និង"+qty_unitlable;
				}
			current_stock = qty+""+measure_name;
			if(qty<1){
				current_stock = '0';
			}
			
			dojo.byId("lblcurrent_qty"+index).innerHTML=current_stock+""+qty_unitlable;
			$("#qty_perunit"+index).val(data.qty_perunit);
			calCualtePrice(index);
	   },		
	    error: function(err) {
		    }
		});
}
</script>