<?php 
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$form=$this->form_sale;
	$url_submit = $this->url(array('module'=>'sales','controller'=>'quoatation','action'=>'add'));
?>
<title><?php echo $tr->translate("QUOTATION_ORDER");?></title>
<div class="card pb-10 pt-10 pl-10 pr-10">
	<div class="card-content">
		<div class="card-box">
            <div class="col-sm-12 border-botom">
		    	<div class="col-sm-8 pd-0">
		    		<h4 class="m-b-0"><i class="fa fa-cube" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate("QUOTATION_ORDER")?></h4>
    			</div>
    			<div class="col-sm-4 text-right"></div>
    		</div>
	    </div>
		<div class="card-box">
			<form dojoType="dijit.form.Form" action="<?php echo $url_submit; ?>" class="form-horizontal" enctype="multipart/form-data" method="post">
				<script type="dojo/method" event="onSubmit">	
					if(this.validate()) {
					customer_id=dijit.byId("customer_id").get('value');
					if(customer_id==0 || customer_id=='' || customer_id==-1){
						alert("សូមជ្រើសរើសអតិជន");
						dijit.byId('customer_id').focus();
						return false;	
					}
					
					identity =$("#identity").val();
					if(identity=='' || identity==-1){
						alert("ទិន្នន័យមិនអាចរក្សាទុកបានទេ ។សូមត្រួតពិនិត្យមើលម្តងទៀត");
						dijit.byId('add_item').focus();
						return false;
					}
					credit_term=parseInt(dijit.byId("credit_term").get('value'));
					credit_limit=parseInt(dijit.byId("credit_limit").get('value'));
				
					currentcredit_term=parseInt(dijit.byId("currentcredit_term").get('value'));
					currcredit_limit=parseInt(dijit.byId("currcredit_limit").get('value'));
					all_total = dijit.byId("all_total").get('value');
					loadingBlock();
					return true;
				}else{
					return false;
				}
				</script>
				<div class="col-md-4">
					<div class="form-group">
						<div class="col-md-4">
							<?php echo $tr->translate("BRANCH_NAME");?>
						</div>
						<div class="col-md-8">
							<?php echo $form->getElement('branch_id');?>
						</div>
					</div>
					<div class="form-group">
	                   <label class="control-label col-md-12 col-sm-12 col-xs-12 title-blog bold" ><i class="fa fa-hand-o-right" aria-hidden="true"></i><?php echo $tr->translate("CUSTOMER_INFO");?> 
	                   </label>
	                </div>
	                <div class="form-group">
						<div class="col-md-4"></div>
						<div class="col-md-8">
                           <input iconClass="dijitIconTask" type="button" label="<?php echo $tr->translate("ADD_NEW_CUSTOMER");?>" dojoType="dijit.form.Button" onclick="getcustomer();"/>
						</div>
					</div>
					<div class="form-group">
						<div class="col-md-4">
							<?php echo $tr->translate("CUSTOMER_NAME");?>
						</div>
						<div class="col-md-5">
							<?php echo $form->getElement("customer_id");?>
						</div>
						<div class="col-md-3">
                           <input iconClass="dijitIconUndo" type="button" label="Refresh" dojoType="dijit.form.Button" onclick="AllRefresh();"/>
						</div>
					</div>
					<div class="form-group">
						<div class="col-md-4">
							<?php echo $tr->translate("CREDIT_TERM");?>
						</div>
						<div class="col-md-8">
							<?php echo $form->getElement("credit_term");?>
						</div>
					</div>
					<div class="form-group">
						<div class="col-md-4" style="white-space: nowrap;">
							<?php echo $tr->translate("CREDIT_LIMIT");?>($)
						</div>
						<div class="col-md-8">
							<?php echo $form->getElement("credit_limit");?>
						</div>
					</div>
					<div class="form-group">
						<div class="col-md-4">
							<?php echo $tr->translate("Current");?>
						</div>
						<div class="col-md-8">
							<div class="input-icon right">
								<input type="text" dojoType="dijit.form.TextBox" class='fullside' name="currentcredit_term" id="currentcredit_term" value="" readonly="readonly" style="color:red;">
							</div>
						</div>
					</div>
					<div class="form-group">
						<div class="col-md-4" style="white-space: nowrap;">
							<span title="Current Credit Limit">
							<?php echo $tr->translate("Current");?>(CL)$
							</span>
						</div>
						<div class="col-md-8">
							<input type="text" dojoType="dijit.form.TextBox" class='fullside' name="currcredit_limit" id="currcredit_limit" value="" readonly="readonly" style="color:red;" class="form-control">
						</div>
					</div>
					<div class="form-group">
	                   <label class="control-label col-md-12 col-sm-12 col-xs-12 title-blog bold" ><i class="fa fa-hand-o-right" aria-hidden="true"></i><?php echo $tr->translate("SALE_INFO");?> 
	                   </label>
	                </div>
	                <div class="form-group">
						<div class="col-md-4">
							<?php echo $tr->translate("QUOTATION_NO");?>
						</div>
						<div class="col-md-8">
							<?php echo $form->getElement("txt_order"); ?>
						</div>
					</div>
					<div class="form-group">
						<div class="col-md-4">
							<?php echo $tr->translate("QUOATATION_DATE");?>
						</div>
						<div class="col-md-8">
							<?php echo $form->getElement("order_date");?>
						</div>
					</div>
					<div class="form-group">
						<div class="col-md-4" style="white-space: nowrap;">
							<?php echo $tr->translate("Order Type");?>
						</div>
						<div class="col-md-8">
							<select dojoType="dijit.form.FilteringSelect" name="pre_order" id="pre_order" class="fullside">
								<option value="1">Quotation</option>
								<option value="0">Pre-Order</option>
							</select>
						</div>
					</div>
					<div class="form-group">
						<div class="col-md-4">
							<?php  echo $tr->translate("SALE_AGENT");?>
						</div>
						<div class="col-md-8">
							<?php echo $form->getElement("saleagent_id");?>
						</div>
					</div>
					<div class="form-group">
						<div class="col-md-4">
							<?php echo $tr->translate("TOTAL");?>
						</div>
						<div class="col-md-8">
							<?php echo $form->getElement("totalAmoun");?>
						</div>
					</div>
					<div class="form-group">
						<div class="col-md-4">
							<?php echo $tr->translate("DISCOUNT");?>
						</div>
						<div class="col-md-8">
							<?php echo $form->getElement("dis_value");?>
						    <input type="hidden" name="discount_type" id="discount_type"/>
						</div>	
					</div>
					<div class="form-group">
						<div class="col-md-4">
							<?php echo $tr->translate("TOTAL_AMOUNT");?>​ 
						</div>
						<div class="col-md-8">
							<?php echo $form->getElement("all_total");?>
						</div>
					</div>
					<div class="form-group">
						<div class="col-md-4">
							<?php echo $tr->translate("REMARK");?>
						</div>
						<div class="col-md-8">
							<?php echo $form->getElement("remark");?>
						</div>
					</div>
				</div>
				<div class="col-md-8">
					<div class="form-group">
						<div class="col-md-6">
							<select autoComplete="false" queryExpr='*${0}*' dojoType="dijit.form.FilteringSelect" class='fullside' data-placeholder="Select..." id="add_item" name="add_item" Onchange="getItemOrder();"  style="width:100% ;margin:0 auto;">
								<?php echo $this->items; ?>
							</select>
						</div>
						<div class="col-md-2">
							<button type="button" class="btn delete" style="width:100%; background:#65879A;margin-bottom:5px;">
								<strong style="color:#fff;"><?php echo $tr->translate("SEARCH_PRODUCT");?></strong>
							</button>
						</div>
					</div>
					<div class="form-group">
						<table class="table table-striped table-bordered table-hover" style="font-size:12px;">
							<tr height="33px">
								<th><?php echo $tr->translate("DEL");?></th>
								<th><?php echo $tr->translate("NUM");?></th>
								<th style="white-space:nowrap;"><?php echo $tr->translate("ITEM_NAME");?></th>
								<th><?php echo $tr->translate("CURRENT_QTY");?></th>
								<th><?php echo $tr->translate("QTY_UNIT");?></th>
								<th><?php echo $tr->translate("QTY_PER_UNIT");?></th>
								<th style="white-space: nowrap;"><?php echo $tr->translate("QTY_ORDER");?></th>
								<th><?php echo $tr->translate("UNIT_PRICE_CAP");?></th>
								<th><?php echo $tr->translate("EXTRA_PRICE");?></th>
								<th style="white-space: nowrap;"><?php echo $tr->translate("DISCOUNT");?></th>
								<th><?php echo $tr->translate("SUB_TOTAL_CAP");?></th>
						 </tr>
						 <tbody id="table_row" style="font-size:12px;">
						</tbody>
					 </table>
					 <input type="hidden" id="identity" name="identity" />
					 <input type="hidden" id="identity_term" name="identity_term" />
				  </div>
				  <div class="form-group">
						<div class="col-md-6">
							<select autoComplete="false" queryExpr='*${0}*' dojoType="dijit.form.FilteringSelect" class='fullside' data-placeholder="Select..." id="term_item" name="term_item" Onchange="getTermItem();"  style="margin:0 auto; ">
								<?php echo $this->term_opt; ?>
							</select>
						</div>
						<div class="col-md-2">
							<button type="button" class="btn delete" style="width:100%; background:#65879A;margin-bottom:5px;">
								<strong style="color:#fff;"><?php echo $tr->translate("TERM_CONDITION");?></strong>
							</button>
						</div>
					</div>
					<div class="form-group">
					  	<table class="table table-striped table-bordered table-hover" id="table_termcondition" style="font-size:12px;">
							<tr>
								<td width="80px;" align="center"><?php echo $tr->translate("DEL");?></td>
								<td width="70px" align="center"><?php echo $tr->translate("NUM");?></td>
								<td style="white-space:nowrap;"><?php echo $tr->translate("TERM_CONDITION");?></td>
							</tr>	
					  	</table>
				  	</div>
				</div>
				<div class="card-box">
					<div class="border-top">
						<div class="col-md-4"></div>
						<div class="col-md-5" class='center'>
							<input type="submit" value="btnsavenew" id="btnsavenew" name="save_close" label="<?php echo $tr->translate("SAVE_NEW")?>" dojoType="dijit.form.Button" 
							iconClass="dijitEditorIcon dijitEditorIconSave" />
						</div>
						<div class="col-md-3"></div>
					</div>
				</div>
			</form>
		</div>
	</div>
</div>
<script src="<?php echo $this->baseUrl();?>/js/help.js"  type="text/javascript"></script>
 <script>
 function getcustomer(){
		window.open('<?php echo $this->baseUrl();?>/sales/customer/add?rightclick=true','_blank');
	}
 dojo.require("dojo.data.ItemFileWriteStore");
$( document ).ready(function() {
	getQuotenumber();
	initListTermcondition();
});
<?php $url_add_customer =  $this->url(array('module'=>'sales','controller'=>'customer','action'=>'get-customer')); ?>
function AllRefresh(){	
	loadingBlock();
	dojo.xhrPost({
		url: "<?php echo $url_add_customer;?>",
		handleAs:"json", 
	    load: function(data) {
			customer_store  = getDataStorefromJSON('id','name',data);
			dijit.byId('customer_id').set('store',customer_store);  
			HideloadingBlock(); 
		},		
		error: function(err) {
			alert(err);
		}
	});
}
function initListTermcondition() {
	index1=0;
	term_option = '<?php echo $this->term_opt; ?>';
	<?php if(!empty($this->rsterm)) {
		foreach($this->rsterm AS $i=>$rt){?>
		index1++; 
		template='<tr id="row_term_'+index1+'" style="height:33px;">';
	    template+='<td width="20px" ><img onClick="deleteTermRecord('+index1+')" src="<?php echo BASE_URL; ?>/images/icon/delete.gif" /></td>';
		template+='<td  width="2%">'+index1+'</td>';
		template+='<td><select class="form-control select2me" id="termid_'+index1+'" name="termid_'+index1+'" >'+term_option+'<option></option></select></td>';
		template+="</tr>";
		$('#table_termcondition').append(template);
		if($('#identity_term').val()!="") {
			var identity = $('#identity_term').val();
			$('#identity_term').val(identity+','+index1);
		} else {$('#identity_term').val(index1);}
		$("#termid_"+index1).val("<?php echo $rt['id'];?>");
	<?php } }?>
}

var index5 = 0;num=0;
var option5 = '<?php echo $this->items; ?>';
var baseUrl = '<?php echo BASE_URL; ?>';
var template = '';
var value = '';
pqty = 1;
var index=1;
function addRow(item_id) {
	product_name = dijit.byId("add_item").attr("displayedValue");
	product_id = dijit.byId("add_item").get('value');
	if(product_name=='' ){return false;}
	index5++; 
	index=index+1;
	for(i=1; i<index5; i++){
		new_item=parseInt(item_id);
		items = parseInt($("#item_id_"+i).val());
	}
	var inp = '';
	template='<td width="5"><img onClick="deleteRecord('+index5+')" src="<?php echo BASE_URL; ?>/images/icon/delete.gif" /></td>';
	template+='<td width="5">'+index5+'</td>';
	template+='<td style="min-width:200px;" ><input type="hidden" value="'+product_id+'" id="item_id_'+index5+'" name="item_id_'+index5+'" >'+product_name+'</td>';
	template+='<td><input style="background:#f5e1e1;" readonly type="text" class="form-control" id="lblcurrent_qty'+index5+'" name="lblcurrent_qty'+index5+'" /> <input  type="hidden" class="form-control" id="current_qty'+index5+'" name="current_qty'+index5+'" /></td>';
	template+='<td width="80px"><input class="fullsite" dojoType="dijit.form.NumberTextBox" type="text" onkeyup="calculatePrice('+index5+'),calculateQtyWarning('+index5+',1);"  required="1" value="1" id="qty_unit_'+index5+'" name="qty_unit_'+index5+'" /></td>';
	template+='<td width="80px"><input class="fullsite" dojoType="dijit.form.NumberTextBox" type="text" onkeyup="calculatePrice('+index5+'),calculateQtyWarning('+index5+',1);"  value="0" id="qty_per_unit_'+index5+'" name="qty_per_unit_'+index5+'" /></td>';
	template+='<td width="80px"><input class="fullsite" dojoType="dijit.form.NumberTextBox" class="fullsite" dojoType="dijit.form.NumberTextBox"  type="text" readonly required="1" id="qty'+index5+'" name="qty'+index5+'"/><input type="hidden" readonly  required="1" id="qty_perunit'+index5+'" name="qty_perunit'+index5+'"/></td>';
	template+='<td width="80px"><input class="fullsite" dojoType="dijit.form.NumberTextBox"type="text" onkeyup="calculatePrice('+index5+')" class="validate[required,custom[number]] input form-control" id="price'+index5+'" name="price'+index5+'" /><input type="hidden" id="oldprice_'+index5+'" name="oldprice_'+index5+'"/></td>';
	template+='<td width="80px"><input class="fullsite" dojoType="dijit.form.NumberTextBox"type="text" onkeyup="calculatePrice('+index5+')" class="form-control" id="extra_price'+index5+'" name="extra_price'+index5+'" /></td>';
	template+='<td width="5%"><input class="fullsite" dojoType="dijit.form.NumberTextBox"type="text" onkeyup="calculatePrice('+index5+')" value="0" id="dis_value'+index5+'" name="dis_value'+index5+'"  /><input type="hidden" class="input70px" id="discount_type'+index5+'" name="discount_type'+index5+'" /></td>';
	template+='<td width="80px"><input class="fullsite" dojoType="dijit.form.NumberTextBox" type="text" class="form-control" readonly="readonly" id="total'+index5+'" name="total'+index5+'" /><input type="hidden" name="cost_price_'+index5+'" id="cost_price_'+index5+'" /></td>';

	tmp='<tr id="row'+index5+'">';
	tmp+="</tr>";
	$('#table_row').append(tmp);
	dojo.html.set(dojo.byId('row'+index5),template , {
	     parseContent: true,
	});	
	if($('#identity').val()!="") {
		var identity = $('#identity').val();
		$('#identity').val(identity+','+index5);
	} else {$('#identity').val(index5);}
	getQtyById(product_id,index5);
}
term_option = '<?php echo $this->term_opt; ?>';
index1 = 0;
function addtermcondition(t_id){
	term_label=dijit.byId("term_item").attr('displayedValue');
	index1++; 
	template='<tr id="row_term_'+index1+'" style="height:33px;">';
    template+='<td width="10px" ><img onClick="deleteTermRecord('+index1+')" src="<?php echo BASE_URL; ?>/images/icon/delete.gif" /></td>';
	template+='<td  width="10px">'+index1+'</td>';
	template+='<td><input type="hidden" value="'+t_id+'" id="termid_'+index1+'" name="termid_'+index1+'" >'+term_label+'</td>';
	template+="</tr>";
	$('#table_termcondition').append(template);
	if($('#identity_term').val()!="") {
		var identity = $('#identity_term').val();
		$('#identity_term').val(identity+','+index1);
	} else {$('#identity_term').val(index1);}
	$("#term_item").val("");
}
<?php $url_qty =  $this->url(array('module'=>'purchase','controller'=>'index','action'=>'getqtybyid')); ?>
function getQtyById(item_id , index){//use
				qty_unit=$("#qty_unit_"+index).val();
				qty_per_unit=$("#qty_per_unit_"+index).val();

				branch_id = dijit.byId("branch_id").get('value');
				if(branch_id=='' || branch_id==-1){alert("Please Select Branch First ");}
				if(qty_unit==null || qty_unit==""){
					if(qty_per_unit!==null && qty_per_unit!==""){
						$("#qty"+index).val(qty_per_unit);
					}
				}else{
					$.ajax({
						url:"<?php echo $url_qty;?>",
						type:"post",
						data:{'item_id':item_id,'branch_id':branch_id},
						success: function(data){
							
							item_qty = $.parseJSON(data);	
							qty = item_qty.qty;
							if(qty==null){qty=0;}
							qtyall_detail = qty*(item_qty.qty_perunit);
							qty_unitlable = qtyall_detail % (item_qty.qty_perunit);//រកចំនួនរាយ
							qty_unitlable = qty_unitlable.toFixed(2)
							if(qty_unitlable>0){qty_unitlable=qty_unitlable+""+item_qty.unit_label;}else{qty_unitlable=""; }
							qty=parseInt(qty);
							current_stock = qty+""+item_qty.measue_name+"និង";
							if(qty<1){
								current_stock = '';
							}
							$("#lblcurrent_qty"+index).val(current_stock+""+qty_unitlable);
							
							$("#current_qty"+index).val(item_qty.qty);
							main_qty =$("#qty_unit_"+index).val();
							detail_qty =  $("#qty_per_unit_"+index).val();
							
							total_qty = parseFloat(main_qty) + parseFloat(detail_qty/(item_qty.qty_perunit));
							$("#qty"+index).val(total_qty.toFixed(3));
							
							$("#qty_perunit"+index).val(item_qty.qty_perunit);
							getProductPrice(item_id,index);
						},
						error:function(e){
						}
				});
			}
}
<?php $url_price =  $this->url(array('module'=>'sales','controller'=>'index','action'=>'getproductprice')); ?>
function getProductPrice(product_id,recordid){
	customer_id=dijit.byId("customer_id").get('value');
	if(customer_id==null || customer_id=="" || customer_id==-1){
		alert("Please Select Customer First !");
		return fale;
		dijit.byId("customer_id").focus();
	}else{
		$.ajax({
			url:"<?php echo $url_price;?>",
			type:"post",
			data:{'customer_id':customer_id,'product_id':product_id},
			success: function(data){
				data = $.parseJSON(data);			
				$("#price"+recordid).val(data.price);
				$("#oldprice_"+recordid).val(data.price);
			},
			error:function(e){
			}
	});
  }
}
function getItemOrder(){
	customer_id=dijit.byId("customer_id").get('value');
	if(customer_id==0 || customer_id=="" || customer_id==-1){
		alert("Please Select Customer");
		$("#add_item").val("");
		dijit.byId("customer_id").focus();
		return false;
	}
	branch_id = dijit.byId("branch_id").get('value');
	if(branch_id=='' || branch_id==-1){
		alert("Please Select Branch");
		$("#add_item").val("");
		dijit.byId("branch_id").focus();
		return false;
	}
	
	item_ids=dijit.byId("add_item").get('value');
	if(item_ids==-1){
		return false;
	}
	addRow(item_ids);
	//getProductPrice(item_ids);
	$("#add_item").val("");
}
function getTermItem(){
	termid=dijit.byId("term_item").get('value');
	if(termid==-1){
		return false;
	}
	addtermcondition(termid);
}
var record_index= 1;
function deleteRecord(index) {
	var identity = $('#identity').val();
	var arrays = identity.split(',');
	for(var i=0;i<arrays.length;i++) {
		if(arrays[i] == index) arrays.splice(i,1);
	}
	var strings = arrays.join(',');
	$('#identity').val(strings);
	$("#row"+index).remove();
	netTotal();
}
function deleteTermRecord(termid){
	var identity = $('#identity_term').val();
	var arrays = identity.split(',');
	for(var i=0;i<arrays.length;i++) {
		if(arrays[i] == termid) arrays.splice(i,1);
	}
	var strings = arrays.join(',');
	$('#identity_term').val(strings);
	$("#row_term_"+termid).remove();
}
function netTotal() {//use
	var cur_type = $('#currency').val();
	var netTotal=0;
	var rowId = $('#identity').val();
	var rowIDArray = rowId.split(',');
	var status = $('#status').val();
	for(var n = 0; n < rowIDArray.length; n++) {
		netTotal += Number($('#total'+rowIDArray[n]).val());
	}
	$('#totalAmoun').val(netTotal.toFixed(2));
	calculateDiscount();
}
function calculateDiscount(){//use
	var discountValue = $('#dis_value').val();
	$('#discount_type').val(0);
	if(discountValue.length!=0){
		if(discountValue.indexOf("%")!==-1){
			var pds=discountValue.split("%");
			    alltotal = $("#totalAmoun").val();
				var discount=(alltotal*parseFloat(pds[0]))/100;
				totalpayment = alltotal - discount;
				$('#all_total').val(totalpayment);
				$('#discount_type').val(1);
				
		}else{
			    $('#discount_type').val(0);
				alltotal = $("#totalAmoun").val();
				totalpayment = alltotal - discountValue;
				$('#all_total').val(totalpayment);				
		}
	}else{
		alltotal = $("#totalAmoun").val();
		totalpayment = alltotal - 0;
		$('#all_total').val(totalpayment);
	}
}
function totalQty(index){
	getQtyById(index);
}
function calculatePrice(index) {
	main_qty= $("#qty_unit_"+index).val();
	if(main_qty==''){main_qty=0;}
	detail_qty= $("#qty_per_unit_"+index).val();
	if(detail_qty==''){detail_qty=0;}
	qty_perunit= $("#qty_perunit"+index).val();//ចំនួនក្នុង១ឯកកតា
	if(qty_perunit==''){qty_perunit=0;}

	qty = parseFloat(main_qty) + parseFloat(detail_qty/(qty_perunit));
	$('#qty'+index).val(qty);
	current_qty = $("#current_qty").val();
	if(current_qty<qty){alert("សូមបញ្ចូលចំនួនផលិតផលលក់ តូចជាងឫស្មើរ ចំនួននៅក្នុងស្តុក !");$('#qty'+index).focus();}
 	
	var price = $('#price'+index).val();
	var extra_price = parseFloat($('#extra_price'+index).val());
	if(price==""){price=0;}
	if(qty==""){qty=0;}
	if(extra_price==""){extra_price=0;}
	if(isNaN(extra_price)){extra_price=0;};
	var total = (parseFloat(price)+parseFloat(extra_price)) * parseFloat(qty);
	$('#discount_type'+index).val(0);
	var ds = $('#dis_value'+index).val();
	
	if(ds.length!=0){
		if(ds.indexOf("%")!==-1){//if have %
			var pds=ds.split("%");
			if(!isNaN(pds[0])){
				var discount=(total*parseFloat(pds[0]))/100;
				after_discount = total - discount;
				
			}else{
				after_discount = total - discount;
			}
			$('#total'+index).val(after_discount.toFixed(2));
			$('#discount_type'+index).val(1);
		}else{
			after_discount=0;
			if(!isNaN(ds)&&ds!=0){
				discount = parseFloat(ds).toFixed(2);
				after_discount = total - discount;
			}else{
				after_discount = total;
			}
			$('#total'+index).val(parseFloat(after_discount).toFixed(2));
			$('#discount_type'+index).val(0);
		}
	}else{
		$('#total'+index).val(parseFloat(total).toFixed(2));
	}
	netTotal();
}
 var record_id = 1;
<?php $url_getcustomerinfo =  $this->url(array('module'=>'sales','controller'=>'customer','action'=>'get-customerinfo')); ?>
function getCustomerInfo(){
	customer_id = dijit.byId("customer_id").get('value');
	if(customer_id==-1){
		return false;
	}else{
		$("#credit_term").val(0);
		$("#credit_limit").val(0);
		$("#currcredit_limit").val(0);
		$("#currentcredit_term").val(0);
		$.ajax({
				url:"<?php echo $url_getcustomerinfo;?>",
				type:"post",
				data:{'customer_id':customer_id},
				success: function(data){
					data = $.parseJSON(data);
					$("#credit_term").val(data.credit_team);
					$("#credit_limit").val(data.credit_limit);

					total_credit = data.total_credit;
					if(total_credit==null){total_credit=0;}
					total_credit = parseFloat(total_credit).toFixed(2);
					$("#currcredit_limit").val(total_credit);
					var oneDay = 24*60*60*1000; // hours*minutes*seconds*milliseconds
					var firstDate = new Date();
					secondDate = data.current_creditterm;
				
					if(secondDate==null){
						secondDate = new Date();
					}else{
						secondDate = new Date( secondDate );
					}
					
					var diffDays = Math.round(Math.abs((firstDate.getTime() - secondDate.getTime())/(oneDay)));
					$("#currentcredit_term").val(diffDays);
				},
				error:function(e){
				}
			});
	}
}
function filterBranch(){
 	getQuotenumber();
}
<?php $url_code =  $this->url(array('module'=>'sales','controller'=>'quoatation','action'=>'getquoteno')); ?>
function getQuotenumber(){
	$("#txt_order").val("");
	branch_id=$("#branch_id").val();
	if(branch_id=="" || branch_id ==null || branch_id==-1){
		return false;
	}
	else{
	$.ajax({
			url:"<?php echo $url_code;?>",
			type:"post",
			data:{'branch_id':branch_id},
			success: function(data){
				qo = $.parseJSON(data);
				$("#txt_order").val(qo);
			},
			error:function(){
			}
		});
	}	
}
function calculateQtyWarning(index,type){//type=1 from main qty,2 from qty detail
	current_so = parseFloat($("#qty"+index).val()).toFixed(2);
	current_qty = parseFloat($("#current_qty"+index).val());
	pre_order = parseFloat($("#pre_order").val());
	if(pre_order==1){//qo
		if(current_so>current_qty){
			alert("ចំនួនក្នុងស្តុកមិនគ្រប់គ្រាន់សំរាប់ការលក់ទេ ។ សូមទំនាក់ទំនងទៅកាន់ផ្នែកស្តុកដើម្បីផ្ទៀងផ្ទាត់ !");
			if(type==1){
            $("#qty"+index).val(current_qty);
            }
			else{
          }
			user_access='<?php echo $this->userinfo['level'];?>';
			if(user_access!=1){
	        $("#qty_unit_"+index).val(0);
	        $("#qty_per_unit_"+index).val(0);
	        $("#qty"+index).val(0);
	        $("#total"+index).val(0);
			}
		}
	}
}
function getsaleOrderNumber(){
}
	dojo.require("dijit.form.DateTextBox");
	dojo.require("dijit.form.NumberTextBox");
</script>	