<?php
	$form=$this->form;
	Application_Model_Decorator::removeAllDecorator($form); 
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$url_cancel = $this->url(array('module'=>'rsvacl','controller'=>'user','action'=>'index'));
	$user_info = new Application_Model_DbTable_DbGetUserInfo();
	$result = $user_info->getUserInfo();
	$level = $result["level"];
?>
<title><?php echo $tr->translate("CHANGE_PASSWORD");?></title>
<script>
	jQuery(document).ready(function(){
		jQuery("#frm").validationEngine('attach', {promptPosition : "centerRight"});
		});
		function validatePassword(field)
        {
            var com=$('#confirm_password').val();
            var pwd=$('#password').val();
        	if(com!=pwd) return '*Password mismatch!';
    }
</script>
<?php echo $this->msg; ?>
<div class="card pb-10 pt-10 pl-10 pr-10">
	<div class="card-content">
		<div class="card-box">
            <div class="col-sm-12 border-botom">
		    	<div class="col-sm-8 pd-0">
		    		<h4 class="m-b-0"><i class="fa fa-cube" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('CHANGE_PASSWORD');?></h4>
    			</div>
    			<div class="col-sm-4 text-right"></div>
    		</div>
    	</div>
		<div class="card-box">
			<form dojoType="dijit.form.Form" action="" class="form-horizontal" enctype="multipart/form-data" method="post">
				<script type="dojo/method" event="onSubmit">			
					if(this.validate()) {
               			loadingBlock();
						return true;
					}else{
						return false;
					}
				</script>
				<div class="form-group">
					<div class="col-md-2">
						<?php echo $tr->translate('OLD_PASSWORD');?>
					</div>
					<div class="col-md-3">
						<?php echo $form->getElement('current_password');?>
					</div>
				</div>
				<div class="form-group">
					<div class="col-md-2">
						<?php echo $tr->translate('NEW_PASSWORD');?>
					</div>
					<div class="col-md-3">
						<?php echo $form->getElement('password');?>
					</div>
				</div>
				<div class="form-group">
					<div class="col-md-2">
						<?php echo $tr->translate('RE_PASSWORD');?>
					</div>
					<div class="col-md-3">
						<?php echo $form->getElement('confirm_password');?>
					</div>
				</div>
				 <div class="form-group">
					<div class="col-md-2"></div>
					<div class="col-md-4">
						<input type="submit" value="SAVE_NEW" tabindex="1" label="<?php echo $tr->translate("SAVE")?>" id="save_new" dojoType="dijit.form.Button" name="save_new"
							iconClass="dijitEditorIcon dijitEditorIconSave"/> 
					</div>
					<div class="col-md-6"></div>
				</div>
			</form>
		</div>
	</div>
</div>