<?php 
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$formfilter=$this->formfilter;
?>
<title><?php echo $tr->translate("USER_LIST");?></title>
<div class="card pb-10 pt-10 pl-10 pr-10">
	<div class="card-content">
		<div class="card-box">
			<form method="post" action="" autocomplete="off">
					<div class="form-group">
						<label class="control-label col-md-1"></label>
						<label class="control-label col-md-2"><?php echo $formfilter->getElement('ad_search');?></label>
						<label class="control-label col-md-2"><?php echo $formfilter->getElement('location');?></label>
						<label class="control-label col-md-2"><?php echo $formfilter->getElement('user_type_filter');?></label>
						<label class="control-label col-md-2"><?php echo $formfilter->getElement('status_se');?></label>
						<label class="control-label col-md-2">
							<input type="submit" value="btnsavenew" id="btnsavenew" name="save_close" label="<?php echo $tr->translate("REFRESH")?>" dojoType="dijit.form.Button" 
								iconClass="dijitIconSearch" />
						</label>
					</div>			
				</form> 
			</div>
			<div class="card-box">
			<?php echo $this->form;?>
		</div>
	</div>
</div>