<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$frm = $this->Form;
	$url_new = $this->url(array('module'=>'product','controller'=>'other','action'=>'edit',));
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
?>
<title> <?php echo $tr->translate("OTHER")?></title>
<div class="card pb-10 pt-10 pl-10 pr-10">
	<div class="card-content">
		<div class="card-box">
            <div class="col-sm-12 border-botom">
		    	<div class="col-sm-8 pd-0">
		    		<h4 class="m-b-0"><i class="fa fa-cube" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('ADD_NEW_LOCATION');?></h4>
    			</div>
    			<div class="col-sm-4 text-right">
    			</div>
    		</div>
    	</div>
		<div class="card-box">	
				<form class="form-horizontal" method="post" action="<?php echo $url_new;?>" >
					<div class="col-md-6">
						<div class="form-group">
							<label class="col-md-4"><?php echo $tr->translate("TITLE");?></label>
							<div class="col-md-8">
								<?php echo $frm->getElement('title_en');?>
							</div>
						</div>
						<div class="form-group">
							<label class="col-md-4"><?php echo $tr->translate("TYPE");?></label>
							<div class="col-md-8">
								<?php echo $frm->getElement('type');?>
							</div>
						</div>
						<div class="form-group">
							<label class="col-md-4"><?php echo $tr->translate("STATUS");?></label>
							<div class="col-md-8">
								<?php echo $frm->getElement('status');?>
							</div>
						</div>
						<div class="form-group">
                           <label  class="col-md-12 col-md-offset-4 col-md-8">
                                <button type="submit" name="save_new" class="btn btn-primary"><?php echo $tr->translate("SAVE_NEW");?></button>
                                <button type="submit" name="save_close" class="btn btn-primary"><?php echo $tr->translate("SAVE_CLOSE");?></button>
                            </label>
					</div>
				</div>	
			</form>
		</div>
	</div>
</div>
