<?php 
	$url_edit = $this->url(array('module'=>'product','controller'=>'other','action'=>'edit',));
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$formFilter = $this->Form;
	$rs = $this->rs;
?>
<title><?php echo $tr->translate("OTHER");?></title>
<div class="card pb-10 pt-10 pl-10 pr-10">
	<div class="card-content">
		<div class="card-box">	
			<form class="form-horizontal" method="post" action="" >
				<div class="form-body">
					<div class="form-group">
						<div class="col-md-3">
							<?php echo $formFilter->getElement('adv_search');?>
						</div>
						<div class="col-md-3">
							<?php echo $formFilter->getElement('type');?>
						</div>
						<div class="col-md-3">
							<?php echo $formFilter->getElement('status_search');?>
						</div>
						<div class="col-md-3">
							<input type="submit" value="btnsavenew" id="btnsavenew" name="save_close" label="<?php echo $tr->translate("REFRESH")?>" dojoType="dijit.form.Button" 
								iconClass="dijitIconSearch" />
						</div>
					</div>
				</div>
			</form>
			</div>
				<div class="card-box">
					<table style="font-size: 12px;" class="table table-striped table-bordered table-hover" id="sample_2">
					<thead>
						<tr>
							<th><?php echo $tr->translate("NO");?></th>
							<th><?php echo $tr->translate("NAME");?></th>
							<th><?php echo $tr->translate("TYPE");?></th>
							<th><?php echo $tr->translate("STATUS");?></th>
							<th><?php echo $tr->translate("ACTION");?></th>
						</tr>
					</thead>
					<tbody>
						<?php if(!empty($rs)){ foreach ($rs as $key => $row){?>
						<tr class="odd gradeX">
							<td><?php echo $key+1?></td>
							<td><?php echo $row["name_en"]?></td>
							<td class="center">
								<?php 
									if($row["type"]==2){
										$type = "Model";
									}elseif ($row["type"]==3){
										$type = "Size";
									}elseif ($row["type"]==4){
										$type = "Color";
									}elseif($row["type"]==6){
										$type = "Customer Type";
									}
									 echo $type;
								?>
							</td>
							<td>
								<?php if($row["status"] == 1){?>
								<span class="label label-sm label-success"><?php echo $tr->translate("ACTIVE");?> </span>
								<?php }else{?>
								<span class="label label-sm label-danger"><?php echo $tr->translate("DEACTIVE");?> </span>
								<?php }?>
							</td>
							<td>
								<a href="<?php echo $url_edit;?>/id/<?php echo $row["id"]?>"><?php echo $tr->translate("EDIT");?></a>
							</td>
						</tr>
						<?php }}?>
				</tbody>
			</table>
		</div>
	</div>
</div>