<?php 
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$form=$this->form_purchase;
	$url_submit = $this->url(array('module'=>'purchase','controller'=>'index','action'=>'add'));
?>
<title><?php echo $tr->translate("ADD_VENDOR");?></title>
<div class="card pb-10 pt-10 pl-10 pr-10">
	<div class="card-content">
		<div class="card-box">
            <div class="col-sm-12 border-botom">
		    	<div class="col-sm-8 pd-0">
		    		<h4 class="m-b-0"><i class="fa fa-cube" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('ADD_VENDOR');?></h4>
    			</div>
    			<div class="col-sm-4 text-right"></div>
    		</div>
    	</div>
		<div class="card-box">
			<form dojoType="dijit.form.Form" autocomplete="off" class="form-horizontal" novalidate="novalidate" action="<?php echo $url_submit; ?>" enctype="multipart/form-data" method="post">
				<script type="dojo/method" event="onSubmit">			
					if(this.validate()) {
					customer_id=dijit.byId("v_name").get('value');
					if(customer_id=='' || customer_id==-1 || customer_id==0){
						alert("Please select vendor name");
						dijit.byId('v_name').focus();
						return false;	
					}
					identity =$("#identity").val();
					if(identity=='' || identity==-1){
						alert("Please add product row");
						dijit.byId('add_item').focus();
						return false;
					}
						loadingBlock();
						return true;

					}else{
						return false;
					}
				</script>
				<div class="col-md-4">
					<div class="form-group">
						<div class="col-md-4"><?php echo $tr->translate("LOCATION_NAME");?></div>
						<div class="col-md-8">
							<?php echo $form->getElement('LocationId');?>
						</div>
					</div>
					<div class="form-group">
						<div class="col-md-4"><?php echo $tr->translate("VENDOR_NAME");?></div>
						<div class="col-md-6">
							<?php echo $form->getElement("v_name");?>
						</div>
						<div class="col-md-2">
							<input class='fullside' iconClass="dijitIconUndo" type="button" dojoType="dijit.form.Button" onclick="refresh();"/>
						</div>
					</div>
					<div class="form-group">
						<div class="col-md-4"><?php echo $tr->translate("ORDER_DATE");?></div>
						<div class="col-md-8">
							<?php echo $form->getElement("order_date");?>
						</div>
					</div>
					<div class="form-group">
						<div class="col-md-4">
							<?php echo $tr->translate("DATE_IN");?>
						</div>
						<div class="col-md-8">
							<?php echo $form->getElement("date_in");?>
						</div>
					</div>
					<div class="form-group">
						<div class="col-md-4">
							<?php echo $tr->translate("PO_NUM");?>
						</div>
						<div class="col-md-8">
							<?php echo $form->getElement("txt_order"); ?>
						</div>
					</div>
					<div class="form-group">
						<div class="col-md-4">
							<?php echo $tr->translate("INVOICE_NO");?>
						</div>
						<div class="col-md-8">
							<?php echo $form->getElement("invoice_no"); ?>
						</div>
					</div>
					<div class="form-group" >
						<div class="col-md-4"><?php echo $tr->translate("STATUS");?></div>
						<div class="col-md-8">
							<?php echo $form->getElement("status");?>
						</div>
					</div>
					<div class="form-group">
						<div class="col-md-4">
							<?php echo $tr->translate("REMARK");?>
						</div>
						<div class="col-md-8">
							<?php echo $form->getElement("remark");?>
						</div>
					</div>
				</div>
				<div class="col-md-8">
					<div class="form-group">
						<div class="col-md-12">
							<div class="col-md-8">
								<select placeHolder="Choose Product here" autoComplete="false" queryExpr="*${0}*" dojoType="dijit.form.FilteringSelect" class='fullside' style="text-align: left;" id="add_item" name="add_item" Onchange="getItemOrder();" required='false' >
									<?php echo $this->items; ?>
								</select>
							</div>
							<div class="col-md-4">
								<input title='Refresh product'  iconClass="dijitIconUndo" type="button" dojoType="dijit.form.Button" onclick="refreshProduct();"/>
								<input type="button" onclick="window.open('<?php echo $this->baseUrl();?>/product/index/add?rightclick=true','_blank');;" value="btnsavenew"  label="<?php echo $tr->translate("ADD_NEW")?>" dojoType="dijit.form.Button" 
									iconClass="dijitIconSearch" />
							</div>
						</div>
					</div>
					<div class="form-group">
						<div class="portlet-body">
							<table class="table table-striped table-bordered table-hover" style="font-size:12px;">
								<tr height="33px">
									<th><?php echo $tr->translate("DEL");?></th>
									<th><?php echo $tr->translate("NUM");?></th>
									<th style="white-space:nowrap;"><?php echo $tr->translate("ITEM_NAME");?></th>
									<th><?php echo $tr->translate("QTY_ORDER");?></th>
									<th><?php echo $tr->translate("UNIT_PRICE_CAP");?></th>
									<th style="white-space:nowrap;"><?php echo $tr->translate("DISCOUNT");?></th>
									<th><?php echo $tr->translate("SUB_TOTAL_CAP");?>
										<input type="hidden" id="identity" name="identity" />
									</th>
								</tr>
								<tbody id="table_row" style="font-size:12px;">
								</tbody>
							 </table>
						</div>
					</div>
				</div>
				<div class="card-box">
					<div class="col-md-4">
						<div class="form-group">
		                   <label class="control-label col-md-12 col-sm-12 col-xs-12 title-blog bold" ><i class="fa fa-dollar" aria-hidden="true"></i> ព៌ត័មានការទូទាត់ប្រាក់ 
		                   </label>
		                </div>
						<div class="form-group">
							<div class="col-md-4"><?php echo $tr->translate("TOTAL");?></div>
							<div class="col-md-8">
								<?php echo $form->getElement("totalAmoun");?>
							</div>
						</div>
						<div class="form-group">
							<div class="col-md-4"><?php echo $tr->translate("DISCOUNT");?></div>
							<div class="col-md-8">
								<?php echo $form->getElement("dis_value");?>
								<input type="hidden" name="global_disc" id="global_disc"/>
							</div>
						</div>
						<div class="form-group">
							<label class="col-md-4"><?php echo $tr->translate("TOTAL_AMOUNT");?></label>
							<div class="col-md-8">
								<?php echo $form->getElement("all_total");?>
								<?php echo $form->getElement("all_totalpayment");?>
							</div>
						</div>
						<div class="form-group">
							<label class="col-md-4"><?php echo $tr->translate("PAID");?></label>
							<div class="col-md-8">
								<?php echo $form->getElement("paid");?>
							</div>
						</div>
						<div class="form-group">
							<div class="col-md-4"><?php echo $tr->translate("BALANCE");?></div>
							<div class="col-md-8">
								<?php echo $form->getElement("remain");?>
							</div>
						</div>
					</div>
					<div class="col-md-8"></div>
						<div class="form-group">
						    <div class="card-box">
								<div class="border-top" >
									<div class="col-md-4"></div>
									<div class="col-md-5" class='center'>
										<input type="submit" value="btnsavenew" id="btnsavenew" name="save_close" label="<?php echo $tr->translate("SAVE_NEW")?>" dojoType="dijit.form.Button" 
										iconClass="dijitIconSearch" />
									</div>
									<div class="col-md-4"></div>
								</div>
							</div>
						</div>
				</div>
			</form>
		</div>
	</div>
</div>
<script src="<?php echo $this->baseUrl();?>/js/help.js"  type="text/javascript"></script>
<script>
	dojo.require("dojo.data.ItemFileWriteStore");  
	var index5 = 0;
	var template = '';
	var index=1;
function addRow(item_id) {
	item_title=dijit.byId("add_item").attr('displayedValue');
	index5++;
	for(i=1; i<index5; i++){
		new_item=parseInt(item_id);
		items = parseInt($("#item_id_"+i).val());
	}
	template='<td><img onClick="deleteRecord('+index5+')" src="<?php echo BASE_URL; ?>/images/icon/delete.gif" /></td>';
	template+='<td width="10px">'+index5+'</td>';
	template+='<td style="min-width:200px;"><input type="hidden" id="item_id_'+index5+'" name="item_id_'+index5+'" value="'+item_id+'" />'+item_title+'</td>';
	template+='<td width="80px"><input class="fullsite" type="text" dojoType="dijit.form.NumberTextBox" onkeyup="calculatePrice('+index5+')" required="1" id="qty'+index5+'" name="qty'+index5+'"/></td>';
	template+='<td width="80px"><input class="fullsite" type="text" dojoType="dijit.form.NumberTextBox" onkeyup="calculatePrice('+index5+')" required="1"  id="price'+index5+'" name="price'+index5+'" /><input type="hidden" id="oldprice_'+index5+'" name="oldprice_'+index5+'"/></td>';
	template+='<td width="80px"><input class="fullsite" type="text" dojoType="dijit.form.TextBox" onkeyup="calculatePrice('+index5+')" value="0" id="dis_value'+index5+'" name="dis_value'+index5+'"  /></td>';
	template+='<td width="80px"><input type="text" class="fullsite" dojoType="dijit.form.NumberTextBox" class="form-control" readonly="readonly" id="total'+index5+'" name="total'+index5+'" /></span></td>';
	tmp='<tr id="row'+index5+'">';
	tmp+="</tr>";
	$('#table_row').append(tmp);
	dojo.html.set(dojo.byId('row'+index5),template , {
	     parseContent: true,
	});
	if($('#identity').val()!="") {
		var identity = $('#identity').val();
		$('#identity').val(identity+','+index5);
	} else {$('#identity').val(index5);}
	$("#item_id_"+index5).val(item_id);
	
	$('#global_disc').val(0);
	$("#paid").val(0);
	$("#row_order_0").remove();
	$("#add_item").val("");
	getProductById(item_id,index5);
}
<?php $url_qty =  $this->url(array('module'=>'purchase','controller'=>'index','action'=>'getqtybyid')); ?>
function getProductById(item_id,index){//use
	branch_id = dijit.byId("LocationId").get('value');
	if(branch_id=='' || branch_id==-1){
		alert("Please Select Branch First ");
		return false;
	}
	$.ajax({
		url:"<?php echo $url_qty;?>",
		type:"post",
		data:{'item_id':item_id,'branch_id':branch_id},
		success: function(data){
			data = $.parseJSON(data);			
			dijit.byId('price'+index).attr('value',data.price);
			$('#oldprice_'+index).attr('value',data.price);
		},
		error:function(e){
		}
	});
}
<?php $url_getsupplier =  $this->url(array('module'=>'purchase','controller'=>'vendor','action'=>'get-vendor')); ?>
function getSuppliyer(){
	supplier_id=dijit.byId('v_name').get('value');
	if(supplier_id==-1){
		window.open('<?php echo $this->baseUrl();?>/purchase/vendor/add?rightclick=true','_blank');
	}
}
function refresh(){
	loadingBlock();
	dojo.xhrPost({
		url: "<?php echo $url_getsupplier;?>",
		handleAs:"json", 
	    load: function(data) {
			supplier_store  = getDataStorefromJSON('id','name',data);
			dijit.byId('v_name').set('store',supplier_store);  
			HideloadingBlock(); 
		},		
		error: function(err) {
		}
	});
}
<?php $url_getproduct =  $this->url(array('module'=>'product','controller'=>'index','action'=>'get-allproduct')); ?>
function refreshProduct(){
	loadingBlock();
	dojo.xhrPost({
		url: "<?php echo $url_getproduct;?>",
		handleAs:"json", 
	    load: function(data) {
			supplier_store  = getDataStorefromJSON('id','name',data);
			dijit.byId('add_item').set('store',supplier_store);  
			HideloadingBlock(); 
		},		
		error: function(err) {
			HideloadingBlock(); 
		}
	});
}
function getItemOrder(){
	item_ids=dijit.byId("add_item").get('value');
	if(item_ids==-1){
	}else{
		branch_id = dijit.byId("LocationId").get('value');
		if(branch_id=='' || branch_id==-1){
				alert("Please Select Branch First ");
				dijit.byId("add_item").attr('value','');
				dijit.byId("LocationId").focus();
				return false;
		}else{
			if(item_ids==''){
				return false;
			}
			addRow(item_ids);
		}
	}
}
function deleteRecord(index) {
	var identity = $('#identity').val();
	var arrays = identity.split(',');
	for(var i=0;i<arrays.length;i++) {
		if(arrays[i] == index) arrays.splice(i,1);
	}
	var strings = arrays.join(',');
	$('#identity').val(strings);
	$("#row"+index).remove();
	netTotal();
}
function netTotal() {
	var cur_type = 1;
	var netTotal=0;
	var rowId = $('#identity').val();
	var rowIDArray = rowId.split(',');
	var status = $('#status').val();
	for(var n = 0; n < rowIDArray.length; n++) {
		netTotal += Number($('#total'+rowIDArray[n]).val());
	}
	$('#totalAmoun').val(netTotal.toFixed(2));
	calculateDiscount();
}
function calculateDiscount(){//use
	var discountValue = $('#dis_value').val();
	if(discountValue.length!=0){
		if(discountValue.indexOf("%")!==-1){
			var pds=discountValue.split("%");
		    alltotal = $("#totalAmoun").val();
			var discount=(alltotal*parseFloat(pds[0]))/100;
			totalpayment = alltotal - discount;
			$('#all_total').val(totalpayment);
			dijit.byId('all_totalpayment').attr('value',totalpayment);
		}else{
			alltotal = $("#totalAmoun").val();
			totalpayment = alltotal - discountValue;
			$('#all_total').val(totalpayment);
			dijit.byId('all_totalpayment').attr('value',totalpayment);
		}
	}else{
		alltotal = $("#totalAmoun").val();
		totalpayment = alltotal - 0;
		$('#all_total').val(totalpayment);
	}
	doRemain();
}
function doRemain() {
	var all_total = parseFloat($('#all_total').val());
	all_total = Number(all_total);
	var paid = parseFloat($('#paid').val());
	paid = Number(paid);
	if(isNaN(paid)){paid=0;}
	
	if(paid>all_total){
		alert("Paid Value can not biger then total amount !");
		$('#remain').val(all_total.toFixed(2));
   }else{
	   remain = parseFloat(all_total)-parseFloat(paid);
	   $('#remain').val(remain.toFixed(2));
	}
}
function AddLocation(){
}
function calculatePrice(index) {
	var qty = $('#qty'+index).val();
	var price = $('#price'+index).val();
	var total = price * qty;	
	var ds = $('#dis_value'+index).val();
	if(ds.length!=0){
		if(ds.indexOf("%")!==-1){//if have %
			var pds=ds.split("%");
			if(!isNaN(pds[0])){
				var discount=(total*parseFloat(pds[0]))/100;
				after_discount = total - discount;
			}else{
				after_discount = total - discount;
			}
			$('#total'+index).val(after_discount.toFixed(2));
		}else{
			after_discount=0;
			if(!isNaN(ds)&&ds!=0){
				discount = parseFloat(ds).toFixed(2);
				after_discount = total - discount;
			}else{
				discount=$('#dis_value'+index).val(0);
				after_discount = total;
			}
			$('#total'+index).val(parseFloat(after_discount).toFixed(2));
		}
	}else{
			$('#total'+index).val(parseFloat(total).toFixed(2));		
		}
		netTotal();
}
	dojo.require("dijit.form.DateTextBox");
	dojo.require("dijit.form.NumberTextBox");
</script>	