<?php 					
	$url_new = $this->url(array('module'=>'purchase','controller'=>'index','action'=>'add',));
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$formFilter = $this->formFilter;
?>
<title><?php echo $tr->translate("MENU_PURCHASE_ADVANCE_INDEX");?></title>
<div class="card pb-10 pt-10 pl-10 pr-10">
	<div class="card-content">
		<div class="card-box">
			<form method="post" action="<?php echo $formFilter->getAction(); ?>" autocomplete="off">
				<div class="form-group">
					<div class=" col-md-3"><?php echo $formFilter->getElement('text_search');?></div>
					<div class=" col-md-3"><?php echo $formFilter->getElement('branch_id');?></div>
					<div class=" col-md-3"><?php echo $formFilter->getElement('suppliyer_id');?></div>
					<div class=" col-md-3"><?php echo $formFilter->getElement('status_paid');?></div>
				</div>
				<div class="form-group">
					<div class=" col-md-3"><?php echo $formFilter->getElement('purchase_status');?></div>
					<div class=" col-md-3"><?php echo $formFilter->getElement('start_date');?></div>
					<div class=" col-md-3"><?php echo $formFilter->getElement('end_date');?></div>
					<div class=" col-md-2">
						<input type="submit" value="btnsavenew" id="btnsavenew" name="save_close" label="<?php echo $tr->translate("REFRESH")?>" dojoType="dijit.form.Button" 
							iconClass="dijitIconSearch" />
					</div>
				</div>				
			</form> 
			</div>
			<div class="card-box">
			<?php echo $this->list;?>
		</div>
	</div>
</div>
<script>
	dojo.require("dijit.form.DateTextBox");
</script>