<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$url_submit =  $this->url(array('module'=>'product','controller'=>'adjust','action'=>'add'));
	$url_getcurrentitem =  $this->url(array('module'=>'product','controller'=>'adjust-stock','action'=>'get-current-quantity'));
	$url_getProduct =  $this->url(array('module'=>'product','controller'=>'transfer','action'=>'getproduct'));
	$formFilter = $this->formFilter;
?>
<title><?php echo $tr->translate("EDIT_REQUEST_STOCK");?></title>
<div class="card pb-10 pt-10 pl-10 pr-10">
	<div class="card-content">
		<div class="card-box">
            <div class="col-sm-12 border-botom">
		    	<div class="col-sm-8 pd-0">
		    		<h4 class="m-b-0"><i class="fa fa-cube" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('EDIT_REQUEST_STOCK');?></h4>
    			</div>
    			<div class="col-sm-4 text-right">
    			</div>
    		</div>
    	</div>
		<div class="card-box">	
			<form dojoType="dijit.form.Form" class="form-horizontal" method="post" action="" >
				<script  type="dojo/method" event="onSubmit">	
				if(this.validate()) {
				from_loc = dijit.byId("from_loc").get('value');
				to_loc = dijit.byId("to_loc").get('value');
				if(from_loc=='' || to_loc=='' || from_loc ==to_loc){
					alert("please check location");
					dijit.byId("to_loc").focus();
					return false;
				}
			    identity = $("#identity").val();
			    if(identity==''){
				 	alert("សូមបញ្ចូលបរិមាណទំនិញ");
				 	dijit.byId('pro_name').focus();
				    return false;
			     }
						loadingBlock();
						return true;
				}else{
					return false;
				}
			     </script>
				<div class="col-md-4">	
					<div class="form-group">
						<div class="col-md-4"><?php echo $tr->translate("TRANSFER_NUM");?></div>
						<div class="col-md-8">
							<?php echo $formFilter->getElement('tran_num');?>
						</div>
					</div>
					<div class="form-group">
						<div class="col-md-4 control-label"><?php echo $tr->translate("REQUEST_DATE");?></div>
						<div class="col-md-8"><?php echo $formFilter->getElement('date_request');?>
						</div>
					</div>
					<div class="form-group">
						<div class="col-md-4 control-label"><?php echo $tr->translate("DATE_IN");?></div>
						<div class="col-md-8">
							<?php echo $formFilter->getElement('date_in');?>
						</div>
					</div>
					<div class="form-group">
						<div class="col-md-4"><?php echo $tr->translate("REQUET_TO_FROM");?></div>
						<div class="col-md-8">
							<?php echo $formFilter->getElement('from_loc');?>
						</div>
					</div>
					<div class="form-group">
						<div class="col-md-4"><span id="lb_br"></span><?php echo $tr->translate("REQUET_TO_BRANCH");?></div>
						<div class="col-md-8">
							<?php echo $formFilter->getElement('to_loc');?>
						</div>							
					</div>
					<div class="form-group">
						<div class="col-md-4"><?php echo $tr->translate("REMARK");?></div>
						<div class="col-md-8">
							<?php echo $formFilter->getElement('remark');?>
						</div>	
					</div>
					<div class="form-group">
						<div class="col-md-4"><?php echo $tr->translate("STATUS");?></div>
						<div class="col-md-8">
							<?php echo $formFilter->getElement('status');?>
						</div>
					</div>
					<div class="form-group" style="padding-top: 6px;">
						<label class="col-md-4 control-label"></label>
						<div class="col-md-8">
							<button type="submit" name="btnsavenew" class="btn btn-primary"><i class="fa fa-save"></i> <?php echo $tr->translate("GO_EDIT")?> </button>
						</div>
					</div>
				</div>
				<div class="col-md-8">	
					<div class="portlet box blue">
						<div class="portlet-title">
							<div class="caption" style="width:100%">
								<?php echo $formFilter->getElement('pro_name');?>
							</div>
						</div>
					</div>
					<div class="form-group">
						<div class="portlet-body">
							<div class="table-responsive">
								<table class="table table-bordered">
									<thead>
										<tr>
											<th>#</th>
											<th><?php echo $tr->translate("PRODUCT_NAME");?></th>
											<th><?php echo $tr->translate("UNIT_QTY");?></th>
											<th><?php echo $tr->translate("QTY_PER_UNIT");?></th>
											<th><?php echo $tr->translate("QTY_TRANSFER");?></th>
											<th><?php echo $tr->translate("REMARK");?></th>
											<th><?php echo $tr->translate("ACTION");?></th>
										</tr>
									</thead>
									<tbody id="tr_location" style="font-size:12px;">
									</tbody>
								</table>
							</div>
							<input type="hidden" name="identity" id="identity" value="" >
						</div>
					</div>
				</div>
			</form>
		</div>
	</div>
</div>
<script type="text/javascript">
	dojo.require("dijit.form.DateTextBox");
	dojo.require("dijit.form.NumberTextBox");

jQuery(document).ready(function(){
	oldRow();
});
function oldRow(){
	<?php if(!empty($this->rs_detail)){
			foreach( $this->rs_detail as $rs){
	?>
			index++;
			template='<tr id="row_location_'+index+'">';
			template+='<td>'+index+'</td>';
			template+='<td style="white-space: nowrap;"><?php echo $rs["item_name"];?><input type="hidden" id="pro_id_'+index+'" name="pro_id_'+index+'" value="<?php echo $rs["pro_id"]?>" </td>';
			template+='<td width="80px"><input dojoType="dijit.form.NumberTextBox" class="fullside" type="text" id="qty_unit_'+index+'" onKeyup="TotalQty('+index+')" name="qty_unit_'+index+'" value="<?php echo $rs['qty_unit']?>" class="validate[required,custom[number]] input form-control" /></td>'; 
			template+='<td width="80px"><input dojoType="dijit.form.NumberTextBox" class="fullside" type="text" id="qty_per_unit_'+index+'" onKeyup="TotalQty('+index+')" name="qty_per_unit_'+index+'" value="<?php echo $rs['qty_per_unit']?>" class="validate[required,custom[number]] input form-control" /></td>'; 
			template+='<td width="80px"><input dojoType="dijit.form.NumberTextBox" class="fullside" type="text" id="qty_tran_'+index+'" readOnly="readOnly" name="qty_tran_'+index+'" value="<?php echo $rs['qty']?>" class="form-control" /> <input type="hidden" id="old_qty_trans_'+index+'" readOnly="readOnly" name="old_qty_tran_'+index+'" value="<?php echo $rs['qty']?>" class="form-control" /> <input type="hidden" name="qty_measure_'+index+'" id="qty_measure_'+index+'" value="<?php echo $rs['qty_measure']?>"/></td>'; 
			template+='<td><input type="text" id="remark_'+index+'" name="remark_'+index+'" class="form-control"></td>';
			template+='<td><button type="button" onClick="deleteRecord('+index+',1)" name="save_close" class="btn default"><?php echo $tr->translate("DELETE");?></button></td>';
			template+='</tr>';
			$('#tr_location').append(template);
			if($('#identity').val()!="") {
				var identity = $('#identity').val();
				$('#identity').val(identity+','+index);
			} else {$('#identity').val(index);}
	<?php }}?>
}
var index=0;
function addNew(){
	id = dijit.byId("pro_name").get('value');
	branch_id = dijit.byId("to_loc").get('value');	
	if(branch_id==''){return false;}
	index++;
	$.ajax({
        url: "<?php echo $url_getProduct;?>",
        type: "post",
        data: {'id':id,'location_ids':branch_id},
        success: function(val){
			for(i=1; i<index; i++){
				new_item=parseInt(id);
				items = parseInt($("#pro_id_"+i).val());
				if(new_item==items){		
					newqty = parseInt($("#qty_tran_"+i).val());
					newqty = newqty+1;
					$("#qty_unit_"+i).val(newqty);
					$("#qty_tran_"+i).val(newqty);
					checkQTY(i);
					return false;
					
				}
			}
			 data = $.parseJSON(val);
			template='<tr id="row_location_'+index+'">';
			template+='<td>'+index+'</td>';
			template+='<td style="white-space: nowrap;">'+data.item_name+'<input type="hidden" id="pro_id_'+index+'" name="pro_id_'+index+'" value="'+data.id+'" </td>';
			template+='<td width="80px"><input type="text" id="qty_unit_'+index+'" onKeyup="TotalQty('+index+')" name="qty_unit_'+index+'" value="1" class="validate[required,custom[number]] input form-control" /></td>'; 
			template+='<td width="80px"><input type="text" id="qty_per_unit_'+index+'" onKeyup="TotalQty('+index+')" name="qty_per_unit_'+index+'" value="0" class="validate[required,custom[number]] input form-control" /></td>'; 
			template+='<td width="80px"><input type="text" id="qty_tran_'+index+'" readOnly="readOnly" name="qty_tran_'+index+'" value="1" class="form-control" /><input type="hidden" id="old_qty_tran_'+index+'" readOnly="readOnly" name="old_qty_tran_'+index+'" value="1" class="form-control" /> <input type="hidden" name="qty_measure_'+index+'" id="qty_measure_'+index+'" value="'+data.qty_perunit+'"/></td>'; 
			template+='<td><input type="text" id="remark_'+index+'" name="remark_'+index+'" class="form-control"></td>';
			template+='<td><button type="button" onClick="deleteRecord('+index+',1)" name="save_close" class="btn default"><?php echo $tr->translate("DELETE");?></button></td>';
			template+='</tr>';
			$('#tr_location').append(template);
			if($('#identity').val()!="") {
				var identity = $('#identity').val();
				$('#identity').val(identity+','+index);
			} else {$('#identity').val(index);}
        },
        error:function(){
        }
    });
}

function TotalQty(index){
		main_qty =$("#qty_unit_"+index).val();
		detail_qty =  $("#qty_per_unit_"+index).val();
		qty_measure = $("#qty_measure_"+index).val();
		if(qty_measure==0){
			qty_measure=1;
		}else{
			qty_measure = qty_measure;
		}
		total_qty = parseFloat(main_qty) + (parseFloat(detail_qty)/parseFloat(qty_measure));
		$("#qty_tran_"+index).val(total_qty.toFixed(3));
		$("#old_qty_tran_"+index).val(total_qty.toFixed(3));
	}
	function checkQTY(index){
		qty = parseFloat($('#qty_'+index).val());
		qty_tran = parseFloat($('#qty_tran_'+index).val());
		translate = "This Product is remain "+qty+" Only";
		if(qty_tran>qty){
			alert("This Product is remain "+qty+" Only");
			$('#qty_tran_'+index).val(qty)
		}
	}
function deleteRecord(index,type) {
		var identity = $('#identity').val();
		var arrays = identity.split(',');
		
		for(var i=0;i<arrays.length;i++) {
			if(arrays[i] == index) arrays.splice(i,1);
		}
		var strings = arrays.join(',');
		$('#identity').val(strings);
		$("#row_location_"+index).remove();
	}
</script>