<?php 
	$form=$this->form;
	Application_Model_Decorator::removeAllDecorator($form);
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
?>
<title><?php echo $tr->translate("USER_TYPE");?></title>
<script type="text/javascript">
$(document).ready(function() { 
	jQuery('#frm').validationEngine('attach', {promptPosition : "centerRight"});
});
</script>
<script language="javascript">
     var temp=-1;
	function validateUser(field)
	{
		if(temp==1) return '* User type already exist!';
		else temp==-1;
	}
</script>
<?php 
	$url_cancel = $this->url(array('module'=>'rsvacl','controller'=>'usertype','action'=>'index'));
?>
<div class="portlet box blue">
	<div class="portlet-title">
		<div class="caption">
		<i class="icon-home"></i><?php echo $tr->translate("USER_TYPE")?>
	</div>
	<div class="tools" >
		<a href="<?php echo $url_cancel;?>" class="btn btn-sm pull-right" style="color:white;">
			<i class="fa fa-undo"></i>	&nbsp;<?php echo $tr->translate("GO_BACK");?>
		</a>
	</div>
</div>
<div class="portlet-body">
	<div class="tabbable-custom">
		<div class="portlet-body form">
				<div class="form-body">
					<form id="frm"  class="form-horizontal" enctype="multipart/form-data" method="post">
							<div class="col-md-6">
								<div class="form-group">
									<label class="control-label col-md-4"><?php echo $tr->translate('USER_TYPE');?><span class="required">
										</span>
									</label>
									<div class="col-md-8">
										<div class="input-icon right">
											<i class="fa"></i>
											<?php echo $form->getElement('user_type');?>
										</div>
									</div>
								</div>
								<div class="form-group">
									<label class="control-label col-md-4"><?php echo $tr->translate('PARENT');?>
										<span class="required"></span>
									</label>
									<div class="col-md-8">
										<div class="input-icon right">
											<i class="fa"></i>
											<?php echo $form->getElement('parent_id');?>
										</div>
									</div>
								</div>
								<div class="form-group">
									<div class="col-md-4">
										<div class="input-icon right"></div>
									</div>
									<div class="col-md-8">
										<button type="submit" name="btnsavenew" class="btn blue btn-block btn-lg"><i class="fa fa-save"></i> <?php echo $tr->translate("SAVE_NEW")?> </button>
									</div>
								</div>
							</div>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>