<?php 
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$url_new = $this->url(array('module'=>'rsvacl','controller'=>'usertype','action'=>'add',));
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
?>
<title><?php echo $tr->translate("USER_TYPE");?></title>
<meta charset="utf-8" />
<div class="card pb-10 pt-10 pl-10 pr-10">
	<div class="card-content">
		<div class="card-box">
				<form method="post" autocomplete="off">
					<div class="form-group" style="padding-top: 6px;"></div>		
				</form> 
			</div>
			<div class="card-content">
				<?php echo $this->form; ?>
			</div>
	</div>
</div>