<?php 
	$tr=Application_Form_FrmLanguages::getCurrentlanguage();
?>
<title><?php echo $tr->translate("RPT_PURCHASE");?></title>
<div class="row">
	<div class="col-md-12">
		<div class="portlet box blue">
			<div class="portlet-title">
				<div class="caption">
					<i class="fa fa-globe"></i><?php echo $tr->translate("RPT_PURCHASE");?>
				</div>
				<?php echo $this->getHeader;?>
			</div>
            <div class="portlet-body form frmfilter">
				<form method="post" autocomplete="off">
					<?php $formFilter = $this->form_purchase; ?>
						<div class="form-group" style="padding-top: 6px;">
						<label class="control-label col-md-3"><?php echo $formFilter->getElement('text_search');?></label>
						<label class="coontrol-label col-md-3"><?php echo $formFilter->getElement('suppliyer_id');?></label>
						<label class="conntrol-label col-md-3"><?php echo $formFilter->getElement('branch_id');?></label>
						<label class="ctrol-label col-md-3"><?php echo $formFilter->getElement('status_paid');?></label>
					</div>
					<div class="form-group">
						<label class="control-label col-md-3"><?php echo $formFilter->getElement('purchase_status');?></label>
						<label class="control-label col-md-3"><div class="input-icon right"><i class="fa fa-calendar"></i><?php echo $formFilter->getElement('start_date');?></div></label>
						<label class="control-label col-md-3"><div class="input-icon right"><i class="fa fa-calendar"></i><?php echo $formFilter->getElement('end_date');?></div></label>
						<label class="control-label col-md-3">
							<button class="btn btn-primary col-md-12" value="" ><i class="fa fa-save"></i>&nbsp;<?php echo $tr->translate("REFRESH");?></button>
						</label>
					</div>
					<div style="clear:both;"></div>	
				</form> 
	<div style=" min-height:28cm; margin:0 auto; border: 1px dotted #ccc; padding:0px 0.2cm">
	<div id="divPrint" style="width: 100%;">
	<style>
		.style{
			line-height: 25px;font-size: 14px !important;
			font-family: 'Khmer OS Battambang';
		}
		ul{margin: 0;padding:0;}
		table tr td ul li{text-align: center;list-style: none;line-height: 25px; font-weight: bold;}
		th{padding: 5px;}
		.hover:hover{background: #ccc;}
		table { page-break-inside:auto }
		tr{ page-break-inside:avoid; page-break-after:auto; }
		#header {
		  display: table-header-group;
		  page-break-inside:avoid; page-break-after:auto;
		}
		
	</style>
		<table style="font-family: 'Khmer OS Content'; width:100%;">
			<tbody>
			<tr>
		    	<td align="center">
		        	<table width="100%" style="font-family: 'Khmer OS Battambang';" cellpadding="0" cellpadding="0">
			            <tbody>
			            	<tr>
			                	<td width="20%" valign="top"></td>
			                	<td width="60%" valign="top">
			                		<ul>
			                			<li style="text-align:center; font-size:16px; font-family:'Khmer MEF2'"><?php echo $tr->translate("COMPANY_CUSTOMER");?></li>
			                			<li style="text-align:center; font-size:16px; font-family:'Khmer MEF2'"><?php echo $tr->translate("RPT_PURCHASE_VENDOR");?></li>
			                			<li style="text-align:center; font-size:14px;"><?php echo date("d/m/Y",strtotime($this->rssearch['start_date']));?> ដល់ <?php echo date("d/m/Y",strtotime($this->rssearch['end_date']));?></li>
			                		</ul>
			                	</td>
			                    <td width="20%"></td>
			                </tr> 
			            </tbody>
		            </table>
		        </td>
		    </tr>
		    <tr>
		    	<td class="table2excel" id="exportExcel">
		            <table border="1" style="border-collapse:collapse;border:1px solid #000; font-size:14px;" width="100%" cellspacing="0">
		               <thead>
		                 <tr bgcolor="#b0bdfd" class="style" align="center" style="font-weight:bold; line-height: 25px; font-size:12px; padding:1px 0px; white-space: nowrap; ">
			                <td>&nbsp;<?php echo $tr->translate("NUM");?></td>
							<td>&nbsp;<?php echo $tr->translate("VENDOR_NAME");?></td>
							<td>&nbsp;<?php echo $tr->translate("CONTACT_NUMBER");?></td>
							<td>&nbsp;<?php echo $tr->translate("AMOUNT");?></td>
							<td width="12%">&nbsp;<?php echo $tr->translate("PAID");?></td>
							<td>&nbsp;<?php echo $tr->translate("BALANCE");?></td>
		               	 </tr>
		               <thead>
		                <?php 
			                $num=1; 
			                $d_netotal = 0;$d_paid = 0; $d_balance = 0;
		                if(!empty($this->repurchase))foreach ($this->repurchase AS $index => $rs){?>
						<tr class='row-format<?php echo $num; $num=1-$num;?> hover' style="border:1px solid #000; <?php if($rs["balance_after"]<=0){echo"background:#d5daff;";}?>">
						   <td align="center" style="white-space: nowrap;">&nbsp;<?php echo $index+1?></td>
						   <td style="white-space: nowrap;"><a style="color:#000;text-decoration: none;" target="_blank" href="<?php echo $this->baseUrl()."/report/purchase/purproductdetail/id/".$rs["id"];?>">&nbsp;<?php echo $rs["vendor_name"];?></a></td>
						   <td style="white-space: nowrap;text-align:right;"><a style="color:#000;text-decoration: none;" target="_blank" href="<?php echo $this->baseUrl()."/report/purchase/purproductdetail/id/".$rs["id"];?>">&nbsp;<?php echo $rs["v_phone"];?></a></td>
						   <td style="white-space: nowrap;text-align:right;">&nbsp;<?php echo number_format($rs["net_total"],2);?></td>
						   <td style="white-space: nowrap;text-align:right;">&nbsp;<?php echo number_format($rs["paid"],2);?></td>
						   <td style="white-space: nowrap;text-align:right;">&nbsp;<?php echo number_format($rs["balance_after"],2);?></td>
						</tr>
						   <?php 
								$d_netotal = $d_netotal+$rs["net_total"];
								$d_paid = $d_paid+$rs["paid"];
								$d_balance = $d_balance+$rs["balance_after"];
                    		}?>
			                <tr class="style" style=" line-height: 24px; font-size:11px;">
			                    <td colspan="3" align="center"><strong>សរុបចំណាយរួម</strong></td>
			                    <td style="font-family:Times New Roman;font-weight: bold;text-align: right">$&nbsp;<?php echo number_format($d_netotal,2);?>&nbsp;</td>
			                    <td style="font-family:Times New Roman;font-weight: bold;text-align: right">$&nbsp;<?php echo number_format($d_paid,2);?>&nbsp;</td>
			                    <td style="font-family:Times New Roman;font-weight: bold;text-align: right">$&nbsp;<?php echo number_format($d_balance,2);?>&nbsp;</td>
			                 </tr>
		                </tbody>
		           </table>
		              <?php echo $this->getFooter;?>
		    		</td>
		    	</tr>
			</tbody>
		</table>
		</div>
	  </div>		
	</div>
	 </div>
   </div>
</div>
<iframe name=print_frame width=0 height=0 frameborder=0 src=about:blank></iframe>
<script>
function doPrint() {var divToPrint = document.getElementById('divPrint');var htmlToPrint = '' +'<style type="text/css">' +'</style>';htmlToPrint += divToPrint.outerHTML;window.document.write(htmlToPrint);window.print();window.close();}
</script>
