<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
?>
<title><?php echo $tr->translate("RPT_EXPENSE_TYPE");?></title>
<style>
.hover:hover{ background: #ddd;}
</style>
<div class="card pb-10 pt-10 pl-10 pr-10">
	<div class="card-content">
		<div class="card-box">
			<form method="post" autocomplete="off">
				<div class="form-group" style="padding-top: 6px;">
					<?php $formFilter = $this->formFilter; ?>
					<div class="col-md-2"><?php echo $formFilter->getElement('text_search');?></div>
					<div class="col-md-2"><?php echo $formFilter->getElement('branch_id');?></div>
					<div class="col-md-2"><?php echo $formFilter->getElement('title');?></div>
					<div class="col-md-2"><?php echo $formFilter->getElement('start_date');?></div>
					<div class="col-md-2"><?php echo $formFilter->getElement('end_date');?></div>
					<div class="col-md-2">
						<input type="submit" value="SAVE_NEW" tabindex="1" label="<?php echo $tr->translate("REFRESH")?>" id="save_new" dojoType="dijit.form.Button" name="save_new"
						iconClass="dijitEditorIcon dijitEditorIconSave"/> 
					</div>
				</div>
			</form> 
		<div id="divPrint"  >
			<table style="background:#fff; margin: 0 auto; width: 100%; padding: 0px 10px 1cm 10px;font-family: 'khmer os battambang';">
							<tr style="font-size: 12px;">
								<td colspan="3" align="center">
									<span style="font-weight:bold;font-family: Arial Black;color:#000; font-size: 14px;font-family:'Khmer OS Muol Light';"><?php echo $tr->translate("COMPANY_CUSTOMER");?></span><br />
									<span style="font-weight:bold;font-family: Arial Black;color:#000; font-size: 14px;font-family:'Khmer OS Muol Light';"><?php echo $tr->translate("RPT_EXPENSE_TYPE");?></span><br />
									<span style="font-weight:bold;font-family: Arial Black;color:#000; font-size: 14px;font-family:'Khmer OS Muol Light';">For Date <?php echo date("d-M-Y",strtotime($this->search["start_date"]))?> to <?php echo date("d-M-Y",strtotime($this->search["end_date"]));?></span>
								</td>
							</tr>
							<tr>
								<td width="20%" align="left"></td>
								<td align="center">
									<span style="font-weight:bold;font-family: Arial Black;color:#000; font-size: 13px;font-family:'Khmer OS Muol Light';"></span>
								</td>
								<td align="right" width="20%">&nbsp;</td>
							</tr>
							<?php 
								$total_expense_dollar=0;
							?>
							<tr>
								<td colspan="3">
									<table class="table2excel" border="1" style="border-collapse:collapse;border:1px solid #000; font-size:12px;" width="100%" cellspacing="0">
		            					<tr style="font-size:12px; height: 20px;border: 1px solid #000;white-space: nowrap;background:#ccd9ff;line-height:30px;font-weight: bold;" align="center" >
											<td style="border: 1px solid #000;"><?php echo $tr->translate('NUM')?></td>
											<td style="border: 1px solid #000;"><?php echo $tr->translate('BRANCH_NAME')?></td>
											<td style="border: 1px solid #000;"><?php echo $tr->translate('EXPENSE_TITLE')?></td>
											<td style="border: 1px solid #000;"><?php echo $tr->translate('NAME_ENTITLE')?></td>
											<td style="border: 1px solid #000;"><?php echo $tr->translate('TOTAL')?></td>
										</tr>
										 <style> td{padding:0 3px; }</style>
									<?php $i=0;if(!empty($this->expense))foreach($this->expense as $row){ $i++;?>
										<tr class="hover" style="font-size:12px; height: 20px;border: 1px solid #000; white-space: nowrap;" align="center" >
											<td style="border: 1px solid #000;"><?php echo $i;?></td>
											<td style="border: 1px solid #000;"><?php echo $row['branch_name'];?></td>
											<td style="border: 1px solid #000;text-align: left;"><span style="width:120px;font-family:'Khmer OS Content'"></span><?php echo $row['title'];?></td>
											<td align="canter" style="border: 1px solid #000;"><?php echo $row['title_en'];?></td>
											<td style="border: 1px solid #000;background: #c6e2fb;"><?php echo number_format($row['total_amount'],2);?></td>
										</tr>
											<?php 
												$total_expense_dollar = $total_expense_dollar + $row['total_amount'];
											?> 
										 <?php } ?>
										  <?php if(!empty($this->expense_po))foreach($this->expense_po as $row){ $i++;?>
										<tr class="hover" style="font-size:12px; height: 20px;border: 1px solid #000; white-space: nowrap;" align="center" >
											<td style="border: 1px solid #000;"><?php echo $i;?></td>
											<td style="border: 1px solid #000;"><?php echo $row['branch_name'];?></td>
											<td style="border: 1px solid #000;text-align: left;"><span style="width:120px;font-family:'Khmer OS Content'"></span><?php echo "ចំណាយលើអ្នកផ្គត់ផ្គង់".$row['title_kh'];?></td>
											<td align="center" style="border: 1px solid #000;"><?php echo "Supplier's Expense".$row['title_en'];?></td>
											<td style="border: 1px solid #000;background: #c6e2fb;"> <?php echo number_format($row['total_paid'],2);?>&nbsp;</td>
										</tr>
											<?php 
												$total_expense_dollar = $total_expense_dollar + $row['total_paid'];
											?> 
										 <?php } ?>
										 <tr class="hover" style="font-size:12px; height: 30px;border: 1px solid #000;" align="center" >
											<td style="border: 1px solid #fff;border-right: 1px solid #000;" colspan="3"></td>
											<td style="border: 1px solid #000;white-space: nowrap;">សរុបរួម/Grand Total</td>
											<td style="border: 1px solid #000;">$ <?php echo  number_format($total_expense_dollar,2);?></td>
										</tr>
										</table>
									</td>
								</tr>
			</table>
			<?php echo $this->getFooter;?>
			</div>	
		</div>
	</div>
</div>
<iframe name=print_frame width=0 height=0 frameborder=0 src=about:blank></iframe>
<script type="text/javascript">
	function doPrint() {var divToPrint = document.getElementById('divPrint');var htmlToPrint = '' +'<style type="text/css">' +'</style>';htmlToPrint += divToPrint.outerHTML;window.document.write(htmlToPrint);window.print();window.close();}
	dojo.require("dijit.form.DateTextBox");
</script>
