<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$session_user=new Zend_Session_Namespace('auth');
	$user_id=$session_user->user_id;
	$originalDate = "2012-10-31";
	$newDate = date("m/d/Y", strtotime($originalDate));
?>

<style>
.hover:hover{ background: #ddd;}
</style>
<title><?php echo $tr->translate("RPT_EXPENSE");?></title>
<div class="card pb-10 pt-10 pl-10 pr-10">
	<div class="card-content">
		<div class="card-box">
			<form method="post" autocomplete="off">
				<div class="form-group" style="padding-top: 6px;">
					<?php $formFilter = $this->formFilter; ?>
					<div class="col-md-2"><?php echo $formFilter->getElement('text_search');?></div>
					<div class="col-md-2"><?php echo $formFilter->getElement('branch_id');?></div>
					<div class="col-md-2"><?php echo $formFilter->getElement('title');?></div>
					<div class="col-md-2"><?php echo $formFilter->getElement('start_date');?></div>
					<div class="col-md-2"><?php echo $formFilter->getElement('end_date');?></div>
					<div class="col-md-2">
						<input type="submit" value="btnsavenew" id="btnsavenew" name="save_close" label="<?php echo $tr->translate("REFRESH")?>" dojoType="dijit.form.Button" 
							iconClass="dijitIconSearch" />
					</div>
				</div>
			</form> 
	<div id="divPrint"  >
		<table class="table2excel" style="background:#fff; margin: 0 auto; width: 100%; padding: 0px 2px 1cm 2px;font-family: 'Hanuman';">
		<tr style="font-size: 13px;">
			<td colspan="3" align="center">
				<strong style="font-weight:bold;font-family: Arial Black;color:#000; font-size: 13px;font-family:'Khmer MEF2';"><?php echo $tr->translate("COMPANY_CUSTOMER");?></strong><br />
				<strong style="font-weight:bold;font-family: Arial Black;color:#000; font-size: 13px;font-family:'Khmer MEF2';"><?php echo $tr->translate("RPT_EXPENSE");?></strong><br />
				<strong style="font-weight:bold;font-family: Arial Black;color:#000; font-size: 13px;font-family:'Khmer MEF2';">For Date <?php echo date("d-M-Y",strtotime($this->search["start_date"]))?> to <?php echo date("d-M-Y",strtotime($this->search["end_date"]));?></strong>
			</td>
		</tr>
		<tr>
			<td width="20%" align="left">
			</td>
			<td align="center">
				<strong style="font-weight:bold;font-family: Arial Black;color:#000; font-size: 13px;font-family:'Khmer MEF2';"></strong>
			</td>
			<td align="right" width="20%">&nbsp;</td>
		</tr>
		<?php 
			$total_income_kh=0;
			$total_income_dollar=0;
			$total =0;
			$total_paid =0;
			$total_expense_kh=0;
			$total_expense_dollar=0;
		?>
		<tr>
			<td colspan="3">
				<table border="1" style="border-collapse:collapse;border:1px solid #000; font-size:12px;" width="100%" cellspacing="0">
            			<tr style="font-size:12px; height: 20px;border: 1px solid #000;white-space: nowrap;background-color: #ccc;line-height:30px;font-weight: bold;" align="center" >
						<td style="border: 1px solid #000;"><?php echo $tr->translate('NUM')?></td>
						<td style="border: 1px solid #000;"><?php echo $tr->translate('BRANCH_NAME')?></td>
						<td style="border: 1px solid #000;"><?php echo $tr->translate('EXPENSE_TITLE')?></td>
						<td style="border: 1px solid #000;"><?php echo $tr->translate('NAME_ENTITLE')?></td>
						<td style="border: 1px solid #000;"><?php echo $tr->translate('INVOICE_NO')?></td>
						<td style="border: 1px solid #000;"><?php echo $tr->translate('TOTAL')?></td>
						<td style="border: 1px solid #000;"><?php echo $tr->translate('Actual Payment Date')?></td>
						<td style="border: 1px solid #000;"><?php echo $tr->translate('NOTE')?></td>
						<td style="border: 1px solid #000;"><?php echo $tr->translate('USER')?></td>
					</tr>
					 <style> td{padding:0 3px; }</style>
				<?php $i=0;foreach($this->expense as $row){ $i++;?>
					<tr class="hover" style="font-size:12px; height: 20px;border: 1px solid #000; white-space: nowrap;" align="center" >
						<td style="border: 1px solid #000;"><?php echo $i;?></td>
						<td style="border: 1px solid #000;"><?php echo $row['branch_name'];?></td>
						<td style="border: 1px solid #000;text-align: left;"><span style="white-space:normal !important;font-family:'Khmer OS Content';line-height:17px;width:180px;!important; display: block;padding-left: 1px; padding: 2px 1px;"><?php echo $row['title'];?></span></td>
						<td align="canter" style="border: 1px solid #000;"><span style="white-space:normal !important;width:120px;!important;"><?php echo $row['title_en'];?></span></td>
						<td style="border: 1px solid #000;"><?php echo $row['invoice'];?></td>
						<td style="border: 1px solid #000;background:#c6e2fb"><?php echo number_format($row['total_amount'],2);?><?php if($row['curr_type']==1){echo ' $';}else{echo ' រៀល​ ';}?></td>
						<td style="border: 1px solid #000;"><?php echo date('d-M-Y',strtotime($row['for_date']));?></td>
						<td style="border: 1px solid #000;"><?php echo $row['desc'];?></td>
						<td style="border: 1px solid #000;font-size: 10px;"><?php echo $row['user_name'];?></td>
					</tr>
						<?php 
							$total_expense_dollar = $total_expense_dollar + $row['total_amount'];
						?> 
					 <?php } ?>
					 <?php if(!empty($this->expense_po))foreach($this->expense_po as $row){ $i++;?>
					<tr class="hover" style="font-size:12px; height: 20px;border: 1px solid #000; white-space: nowrap;" align="center" >
						<td style="border: 1px solid #000;"><?php echo $i;?></td>
						<td style="border: 1px solid #000;"><?php echo $row['branch_name'];?></td>
						<td style="border: 1px solid #000;text-align: left;"><span style="width:120px;font-family:'Khmer OS Content'"></span><?php echo "ចំណាយលើអ្នកផ្គត់ផ្គង់(".$row['vendor'].")";?></td>
						<td align="center" style="border: 1px solid #000;"><?php echo "Supplier's Expense(".$row['vendor'].")";?></td>
						<td style="border: 1px solid #000;"><?php echo $row['receipt_no'];?></td>
						<td style="border: 1px solid #000;background: #c6e2fb;"><?php echo number_format($row['total_paid'],2);?>&nbsp;$<?php //if($row['curr_type']==1){echo ' $';}else{echo ' រៀល​ ';}?></td>
						<td style="border: 1px solid #000;"><?php echo date("d-M-Y",strtotime($row['expense_date']));?></td>
						<td style="border: 1px solid #000;"><?php echo $row['remark'];?></td>
						<td style="border: 1px solid #000;"><?php echo $row['user'];?></td>
					</tr>
						<?php 
								$total_expense_dollar = $total_expense_dollar + $row['total_paid'];
						?> 
					 <?php } ?>
					 <tr class="hover" style="font-size:11px; height: 20px;border: 1px solid #000;" align="center" >
						<td style="border: 1px solid #fff;border-right: 1px solid #000;" colspan="7"></td>
						<td style="border: 1px solid #000; white-space: nowrap;">សរុបរួម/Grand Total</td>
						<td style="border: 1px solid #000;"><?php echo number_format($total_expense_dollar,2);?></td>
					</tr>
					</table>
				</td>
			</tr>
		</table>
			<?php echo $this->getFooter;?>
			</div>	
		</div>
	</div>
</div>
<iframe name=print_frame width=0 height=0 frameborder=0 src=about:blank></iframe>
<script type="text/javascript">
function doPrint() {var divToPrint = document.getElementById('divPrint');var htmlToPrint = '' +'<style type="text/css">' +'</style>';htmlToPrint += divToPrint.outerHTML;window.document.write(htmlToPrint);window.print();window.close();}
dojo.require("dijit.form.DateTextBox");
</script>
