<?php 
$tr=Application_Form_FrmLanguages::getCurrentlanguage();
$brach_name =  $this->branch;
?>
<div class="card pb-10 pt-10 pl-10 pr-10">
	<div class="card-content">
		<div class="card-box">
			<form method="post" autocomplete="off">
				<div class="form-group" style="padding-top: 6px;">
					<?php $formFilter = $this->form_purchase; ?>
					<div class="col-md-2"><?php echo $formFilter->getElement('text_search');?></div>
					<div class="col-md-2"><?php echo $formFilter->getElement('branch_id');?></div>
					<div class="col-md-2"><?php echo $formFilter->getElement('suppliyer_id');?></div>
					<div class="col-md-2"><?php echo $formFilter->getElement('start_date');?></div>
					<div class="col-md-2"><?php echo $formFilter->getElement('end_date');?></div>
					<div class="col-md-2">
						<input type="submit" value="btnsavenew" id="btnsavenew" name="save_close" label="<?php echo $tr->translate("REFRESH")?>" dojoType="dijit.form.Button" 
							iconClass="dijitIconSearch" />
					</div>
				</div><div style="clear:both;"></div>	
			</form> 
	<div id="divPrint" style="width: 100%;">
	<style>
		.style{
			line-height: 20px;font-size: 11px !important;
			font-family: 'Khmer OS Battambang';
		}
		ul{margin: 0;padding:0;}
		table tr td ul li{text-align: center;list-style: none;line-height: 25px;}
		th{padding: 5px;}
		.hover:hover{background: #ccc;}
	</style>
		<table style="font-family: 'Khmer OS Content'; width:100%;">
			<tbody>
			<tr>
		    	<td align="center">
		        	<table width="100%" style="font-family: 'Khmer OS Battambang';" cellpadding="0" cellpadding="0">
		            	<tbody>
		            		<tr>
			                	<td width="20%" valign="top"></td>
			                	<td width="60%" valign="top">
			                		<ul>
			                			<li style="text-align:center; font-size:14px; font-family:'Khmer OS Muol Light'">របាយការណ៏ ទិញចូលមិនទាន់ទូទាត់(ជំពាក់)</li>
			                			<li style="text-align:center; font-size:14px;"><?php if(!empty($this->rssearch['start_date'])){echo date("d/m/Y",strtotime($this->rssearch['start_date']));?> ដល់ <?php } echo date("d/m/Y",strtotime($this->rssearch['end_date']));?></li>
			                		</ul>
			                	</td>
			                    <td width="20%"></td>
			                </tr> 
			            </tbody>
		            </table>
		        </td>
		    </tr>
		    <tr>
		    	<td class="table2excel" id="exportExcel">
		            <table border="1" style="border-collapse:collapse;border:1px solid #000; font-size:12px;" width="100%" cellspacing="0">
		                 <tbody><tr class="style" align="center" style="background:#ccd9ff;font-weight:bold; line-height: 25px; font-size:12px; padding:1px 0px; white-space: nowrap;">
		                    <td>&nbsp;<?php echo $tr->translate("NUM");?></td>
							<td><?php echo $tr->translate("BRANCH_NAME");?></td>
							<td>&nbsp;<?php echo $tr->translate("VENDOR_NAME");?></td>
							<td>&nbsp;<?php echo $tr->translate("PO_NUM");?></td>
							<td>&nbsp;<?php echo $tr->translate("Invoice");?></td>
							<td width="10%">&nbsp;<?php echo $tr->translate("ORDER_DATE");?></td>
							<td><?php echo $tr->translate("DATE_IN");?></td>
							<td>&nbsp;<?php echo $tr->translate("GRAND_TOTAL");?></td>
							<td>&nbsp;<?php echo $tr->translate("PAID");?></td>
							<td >&nbsp;<?php echo $tr->translate("BALANCE");?></td>
							<td>&nbsp;<?php echo $tr->translate("BY_USER");?></td>
		                </tr>
		                <?php $num=1; 
		                $r_netotal = 0;$r_paid = 0; $r_balance = 0;
		                $d_netotal = 0;$d_paid = 0; $d_balance = 0;
		                $b_netotal = 0;$b_paid = 0; $b_balance = 0;
		                if(!empty($this->repurchase))foreach ($this->repurchase AS $index => $rs){?>
						<tr class='row-format<?php echo $num; $num=1-$num;?> hover' style="border:1px solid #000; white-space: nowrap;">
						   <td align="center" style="white-space: nowrap;">&nbsp;<?php echo $index+1?></td>
						   <td style="white-space: nowrap;"><a style="color:#000;text-decoration: none;" target="_blank" href="<?php echo $this->baseUrl()."/report/purchase/purproductdetail/id/".$rs["id"];?>">&nbsp;<?php echo $rs["branch_name"];?></a></td>
						   <td style="white-space: nowrap;"><a style="color:#000;text-decoration: none;" target="_blank" href="<?php echo $this->baseUrl()."/report/purchase/purproductdetail/id/".$rs["id"];?>">&nbsp;<?php echo $rs["vendor_name"];?></a></td>
						   <td style="white-space: nowrap;"><a style="color:#000;text-decoration: none;" target="_blank" href="<?php echo $this->baseUrl()."/report/purchase/purproductdetail/id/".$rs["id"];?>">&nbsp;<?php echo $rs["order_number"];?></a></td>
						   <td style="white-space: nowrap;"><a style="color:#000;text-decoration: none;" target="_blank" href="<?php echo $this->baseUrl()."/report/purchase/purproductdetail/id/".$rs["id"];?>">&nbsp;<?php echo $rs["invoice_no"];?></a></td>
						   <td style="white-space: nowrap;">&nbsp;<?php echo date("d/m/Y",strtotime($rs["date_order"]));?></td>
						   <td style="white-space: nowrap;">&nbsp;<?php echo date("d/m/Y",strtotime($rs["date_in"]));?></td>
						   <td style="white-space: nowrap;font-family:'Open Sans', sans-serif;font-size: 12px; font-weight: bold;">&nbsp;<?php echo number_format($rs["net_total"],2);?></td>
						   <td style="white-space: nowrap;font-family:'Open Sans', sans-serif;font-size: 12px; font-weight: bold;">&nbsp;<?php echo number_format($rs["paid"],2);?></td>
						   <td style="white-space: nowrap;font-family:'Open Sans', sans-serif;font-size: 12px; font-weight: bold;">&nbsp;<?php echo number_format($rs["balance_after"],2);?></td>
						   <td>&nbsp;<?php echo $rs["user_name"];?></td>
						</tr>
						   <?php 
								$d_netotal = $d_netotal+$rs["net_total"];
								$d_paid = $d_paid+$rs["paid"];
								$d_balance = $d_balance+$rs["balance"];
                    }?>
		                </tbody>
		                <tr style="height: 30px; font-weight:bold; text-align: center;font-size: 14px; background:#87acff;">
		                	<td colspan="7"></td>
		                	<td>
		                		<?php echo number_format($d_netotal,2);?>
		                	</td>
		                	<td>
		                		<?php echo number_format($d_paid,2);?>
		                	</td>
		                	<td>
		                		<?php echo number_format($d_balance,2);?>
		                	</td>
		                	<td></td>
		                </tr>
		           	</table>
		           	<br />
		              <?php echo $this->getFooter;?>
		    		</td>
		    	</tr>
			</tbody>
		</table>
		</div>
	  </div>		
	</div>
</div>
<iframe name=print_frame width=0 height=0 frameborder=0 src=about:blank></iframe>
<script>
	function doPrint() {var divToPrint = document.getElementById('divPrint');var htmlToPrint = '' +'<style type="text/css">' +'</style>';htmlToPrint += divToPrint.outerHTML;window.document.write(htmlToPrint);window.print();window.close();}
	dojo.require("dijit.form.DateTextBox");
</script>