	<?php
	$tr=Application_Form_FrmLanguages::getCurrentlanguage();
	$request=Zend_Controller_Front::getInstance()->getRequest();
	$action = $request->getActionName();
	$baseurl  = $this->baseUrl();
	$session_user=new Zend_Session_Namespace('auth');
	$arr_module = $session_user->arr_acl;
	$menu = array();
	$module = '';
	$controller=array();
	$newarray=array();
	if(!empty($arr_module)){
		foreach ($arr_module as $key => $rs){
// 			if($rs['module']=='report' AND $rs['controller']!='loan'){
// 				continue;
// 			}
			$lblcontroller = $rs['label'];
			if($module!=$rs['module']){
				$newarray= array($rs['controller']=>$tr->translate(strtoupper($lblcontroller)));
				$menu[$rs['module']]= $newarray;
				$old_module=$rs['module'];
			}else{
				$newarray= array_merge($newarray,array($rs['controller']=>$tr->translate(strtoupper($lblcontroller))));
			    $menu[$rs['module']] = $newarray;
			}
			$module=$rs['module'];
		}
	}
	$arr_param_menu = $menu;
	$module = $request->getModuleName();
	$controller = $request->getControllerName();
	?>
	<?php 
	$array_icon = array(
      		'home'=>'<i class="fa fa-home" aria-hidden="true"></i>',
      		'product'=>'<i class="fa fa-server" aria-hidden="true"></i>',
			'purchase'=>'<i class="fa fa-shopping-cart" aria-hidden="true"></i>',
      		'sales'=>'<i class="fa fa-money" aria-hidden="true"></i>',
      		'report'=>'<i class="fa  fa-file-text" aria-hidden="true"></i>',
      		'rsvacl'=>'<i class="fa  fa-cog" aria-hidden="true"></i>',
      );
	
	$arr_module = $session_user->arr_module;
	$arr_acl = $session_user->arr_acl;
	?>
	<!-- sidebar menu -->
            <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
              <div class="menu_section">
	               &nbsp;
	              <div class="button-make-loan mb-10">
						<a href="<?php echo $this->baseUrl()."/sales/possale/add"?>"  class="closebtn-makesale"  ><i class="fa fa-plus" aria-hidden="true"></i> <?php echo $tr->translate("ADD_SALE");?> </a>
					</div>
                <ul class="nav side-menu">
                	<?php if(!empty($arr_module)){ foreach ($arr_module as $rs){
                		$url =$this->url(array('module'=>$rs,'controller'=>'index','action'=>'index'), null, true);
                		$title = $rs;
                		if ($title=="purchase"){
                			$title='PURCHASING';
                		}
                		elseif($title=="product"){
                			$title='STOCK_MNG';
                		}	
                		$title=$tr->translate(strtoupper($rs));
                	?>
                	<li <?php if ($rs==$module ){ echo 'class="active"';}?>>
                			<?php if (count($arr_param_menu[$rs])>1){?>
		                		<a><?php echo $array_icon[$rs];?> <?php echo $title;?>			
		                		<?php if (!empty($arr_param_menu[$rs])){?><span class="fa fa-chevron-down"></span><?php }?>
		                		</a>
		                		<?php if (!empty($arr_param_menu[$rs])){?>
			                    <ul class="nav child_menu" <?php if ($rs==$module ){ echo 'style="display: block;"';}?>>
			                       <?php  foreach ($arr_param_menu[$rs] as $key => $sub){
			                       	$urlsub = $this->url(array('module'=>$rs,'controller'=>$key,'action'=>'index'), null, true);
			                       	?>
			                      <li <?php if ($rs==$module AND $key==$controller){ echo 'class="current-page"';}?>><a href="<?php echo $urlsub;?>"><?php echo $sub;?></a></li>
			                       <?php }?>
			                    </ul>
			                    <?php }?>
		                    <?php }else{?>
		                    	<?php  foreach ($arr_param_menu[$rs] as $key => $sub){
			                       	$urlsub = $this->url(array('module'=>$rs,'controller'=>$key,'action'=>'index'), null, true);
			                       	$title=$tr->translate(strtoupper($key));
			                       	if ($rs=="home" and $key=="index" ){
			                       		$title=$tr->translate(strtoupper($rs));
			                       	}
			                       	?>
			                    <a href="<?php echo $urlsub;?>">
	                			<?php echo $array_icon[$rs];?> <?php echo $title;?> 
		                		</a>
		                		<?php }?>
		                    <?php }?>
                 	 </li>
                	<?php }
                	}?>
                </ul>
              </div>
            </div>
            <!-- /sidebar menu -->
            <!-- /menu footer buttons -->
            <div class="sidebar-footer hidden-small">
              <a data-toggle="tooltip" data-placement="top" onClick="toggleFullScreen(document.body)" title="<?php echo $tr->translate("FullScreen");?>">
                <span class="glyphicon glyphicon-fullscreen" aria-hidden="true"></span>
              </a>
              <a data-toggle="tooltip" data-placement="top" title="<?php echo $tr->translate("SIGN_OUT");?>" href="<?php echo $this->url(array('module'=>'','controller'=>'index','action'=>'logout','value'=>'1')); ?>">
                <span class="glyphicon glyphicon-off" aria-hidden="true"></span>
              </a>
            </div>