<?php 
	$url_new = $this->url(array('module'=>'product','controller'=>'branch','action'=>'add',));
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$formFilter = $this->frmAdd;
?>
<title><?php echo $tr->translate("ADD_NEW_LOCATION");?></title>		
<div class="card pb-10 pt-10 pl-10 pr-10">
	<div class="card-content">
		<div class="card-box">
            <div class="col-sm-12 border-botom">
		    	<div class="col-sm-8 pd-0">
		    		<h4 class="m-b-0"><i class="fa fa-cube" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('ADD_NEW_LOCATION');?></h4>
    			</div>
    			<div class="col-sm-4 text-right">
    			</div>
    		</div>
    	</div>
		<div class="card-box">		
			<form dojoType="dijit.form.Form" class="form-horizontal" method="post" action="<?php echo $url_new;?>" enctype="multipart/form-data"  >
				 <script type="dojo/method" event="onSubmit">			
					if(this.validate()) {
               			loadingBlock();
						return true;
					}else{
						return false;
					}
				</script>
				<div class="form-body">
					<div class="form-group">
						<label class="col-md-2 control-label"><?php echo $tr->translate("BRANCH_NAME");?></label>
						<div class="col-md-4">
							<?php echo $formFilter->getElement('branch_name');?>
						</div>
						<label class="col-md-2 control-label"><?php echo $tr->translate("COMPANY_NAME");?></label>
						<div class="col-md-4">
							<?php echo $formFilter->getElement('code');?>
						</div>
					</div>
					<div class="form-group">
						<label class="col-md-2 control-label"><?php echo $tr->translate("CON_NAME");?></label>
						<div class="col-md-4">
							<?php echo $formFilter->getElement('contact');?>
						</div>
						<label class="col-md-2 control-label"><?php echo $tr->translate("PREFIX");?></label>
						<div class="col-md-4">
							<?php echo $formFilter->getElement('prefix');?>
						</div>
					</div>
					<div class="form-group">					
						<label class="col-md-2 control-label"><?php echo $tr->translate("PHONE_NUM");?></label>
						<div class="col-md-4">
							<?php echo $formFilter->getElement('contact_num');?>
						</div>
						<label class="col-md-2 control-label"><?php echo $tr->translate("Office Phone");?></label>
						<div class="col-md-4">
							<?php echo $formFilter->getElement('office_num');?>
						</div>
					</div>
					<div class="form-group">
						<label class="col-md-2 control-label"><?php echo $tr->translate("EMAIL");?></label>
						<div class="col-md-4">
							<?php echo $formFilter->getElement('email');?>
						</div>
										
						<label class="col-md-2 control-label"><?php echo $tr->translate("FAX");?></label>
						<div class="col-md-4">
							<?php echo $formFilter->getElement('fax');?>
						</div>
					</div>
					<div class="form-group">
						<label class="col-md-2 control-label"><?php echo $tr->translate("ADD_LOCATION");?></label>
						<div class="col-md-4">
							<?php echo $formFilter->getElement('address');?>
						</div>
						<label class="col-md-2 control-label"><?php echo $tr->translate("REMARK");?></label>
						<div class="col-md-4">
							<?php echo $formFilter->getElement('remark');?>
						</div>
					</div>
					<div class="form-group">
						<label class="col-md-2 control-label"><?php echo $tr->translate("LOGO");?></label>
						<div class="col-md-4">
							<div class="input-group">
							<?php echo $formFilter->getElement('logo');?>
							<?php echo $formFilter->getElement('old_logo');?>
							</div>
						</div>
						<label class="col-md-2 control-label"><?php echo $tr->translate("SHOW_BY");?></label>
						<div class="col-md-4">
							<?php echo $formFilter->getElement('show_by');?>
						</div>
					</div>
					<div class="form-group">
						<label  class="col-md-12 col-md-offset-4 col-md-8">
							<a href="<?php echo $this->baseUrl();?>/branch/index"><button type="button" class="btn red"><i class="fa fa-times"></i> <?php echo $tr->translate("GO_BACK")?></button></a>
							<button type="submit" name="save_close" value="saveclose" class="btn btn-primary" ><i class="glyphicon glyphicon-log-in"></i> <?php echo $tr->translate("SAVE_CLOSE")?></button>
							<button type="submit" name="save_new" class="btn btn-primary"><i class="fa fa-save"></i> <?php echo $tr->translate("SAVE_NEW")?> </button>
						</label>
					</div>
				</div>
			</form>
		</div>
	</div>
</div>