<?php 
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$formFilter = $this->frmAdd;
?>
<title><?php echo $tr->translate("EDIT_LOCATION");?></title>
<div class="card pb-10 pt-10 pl-10 pr-10">
	<div class="card-content">
		<div class="card-box">
            <div class="col-sm-12 border-botom">
		    	<div class="col-sm-8 pd-0">
		    		<h4 class="m-b-0"><i class="fa fa-cube" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('EDIT_LOCATION');?></h4>
    			</div>
    			<div class="col-sm-4 text-right">
    			</div>
    		</div>
    	</div>
		<div class="card-box">				
			<form dojoType="dijit.form.Form" class="form-horizontal" method="post"  enctype="multipart/form-data"  >
				 <script type="dojo/method" event="onSubmit">			
					if(this.validate()) {
               			loadingBlock();
						return true;
					}else{
						return false;
					}
				</script>
				<div class="col-md-6">
					<div class="form-group">
                   			<label class="control-label col-md-12 col-sm-12 col-xs-12 title-blog bold" ><i class="fa fa-hand-o-right" aria-hidden="true"></i> <?php echo $tr->translate("BRANCH_INFO");?> 
                   			</label>
                		</div>
						<div class="form-group">
							<label class="col-md-4 control-label"><?php echo $tr->translate("BRANCH_NAME");?></label>
					<div class="col-md-8">
						<?php echo $formFilter->getElement('branch_name');?>
					</div>
				</div>
				<div class="form-group">	
					<label class="col-md-4 control-label"><?php echo $tr->translate("COMPANY_NAME");?></label>
					<div class="col-md-8">
						<?php echo $formFilter->getElement('code');?>
					</div>
				</div>
				<div class="form-group">
					<label class="col-md-4 control-label"><?php echo $tr->translate("PREFIX");?></label>
					<div class="col-md-8">
						<?php echo $formFilter->getElement('prefix');?>
					</div>
				</div>
				<div class="form-group">
					<label class="col-md-4 control-label"><?php echo $tr->translate("CON_NAME");?></label>
					<div class="col-md-8">
						<?php echo $formFilter->getElement('contact');?>
					</div>
				</div>
				<div class="form-group">	
					<label class="col-md-4 control-label"><?php echo $tr->translate("Office Phone");?></label>
					<div class="col-md-8">
						<?php echo $formFilter->getElement('office_num');?>
					</div>	
				</div>
				<div class="form-group">	
					<label class="col-md-4 control-label"><?php echo $tr->translate("REMARK");?></label>
					<div class="col-md-8">
						<?php echo $formFilter->getElement('remark');?>
					</div>
				</div>
				<div class="form-group">	
					<label class="col-md-4 control-label"><?php echo $tr->translate("LOGO");?></label>
					<div class="col-md-8">
						<div class="input-group">
						<?php echo $formFilter->getElement('logo');?>
						<?php echo $formFilter->getElement('old_logo');?>
						</div>
					</div>
				</div>
			</div>
			<div class="col-md-6">
					<div class="form-group">			
						<label class="col-md-4 control-label"><?php echo $tr->translate("PHONE_NUM");?></label>
						<div class="col-md-8">
							<?php echo $formFilter->getElement('contact_num');?>
						</div>
					</div>
					<div class="form-group">
						<label class="col-md-4 control-label"><?php echo $tr->translate("EMAIL");?></label>
						<div class="col-md-8">
							<?php echo $formFilter->getElement('email');?>
						</div>
					</div>
					<div class="form-group">					
						<label class="col-md-4 control-label"><?php echo $tr->translate("FAX");?></label>
						<div class="col-md-8">
							<?php echo $formFilter->getElement('fax');?>
						</div>
					</div>
					<div class="form-group">
						<label class="col-md-4 control-label"><?php echo $tr->translate("ADDRESS");?></label>
						<div class="col-md-8">
							<?php echo $formFilter->getElement('address');?>
						</div>
					</div>
					<div class="form-group">
						<label class="col-md-4 control-label"><?php echo $tr->translate("SHOW_BY");?></label>
						<div class="col-md-8">
							<?php echo $formFilter->getElement('show_by');?>
						</div>
					</div>
					<div class="form-group">
						<label class="col-md-4 control-label"><?php echo $tr->translate("STATUS");?></label>
						<div class="col-md-8">
							<?php echo $formFilter->getElement('status');?>
						</div>
					</div>
				</div>
				<div class="card-box">
					<div class="border-top">
						<div class="col-md-5"></div>
						<div class="col-md-4" class='center'>
							<input type="submit" value="btnsavenew" id="btnsavenew" name="save_close" label="<?php echo $tr->translate("SAVE_NEW")?>" dojoType="dijit.form.Button" 
							iconClass="dijitEditorIcon dijitEditorIconSave" />
						</div>
						<div class="col-md-3"></div>
					</div>
				</div>
			</form>
		</div>
	</div>
</div>