<?php 
	$url_edit = $this->url(array('module'=>'sales','controller'=>'customertype','action'=>'edit',));
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$formFilter = $this->Form;
	$rs = $this->rs;
?>
<title><?php echo $tr->translate("CUSTOMER_TYPE");?></title>
<div class="card pb-10 pt-10 pl-10 pr-10">
	<div class="card-content">
		<div class="card-box">
			<form class="form-horizontal" method="post" action="" >
				<div class="form-group">
					<div class="col-md-3">
						<?php echo $formFilter->getElement('adv_search');?>
					</div>
					<div class="col-md-3">
						<?php echo $formFilter->getElement('status_search');?>
					</div>
					<div class="col-md-3">
						<input type="submit" value="btnsavenew" id="btnsavenew" name="save_close" label="<?php echo $tr->translate("REFRESH")?>" dojoType="dijit.form.Button" 
							iconClass="dijitIconSearch" />
					</div>
				</div>
			</form>
				<table style="font-size: 12px;" class="table table-striped table-bordered table-hover" id="sample_2">
					<thead>
						<tr>
							<th><?php echo $tr->translate("NO");?></th>
							<th><?php echo $tr->translate("NAME");?></th>
							<th><?php echo $tr->translate("CREDIT_LIMIT");?></th>
							<th><?php echo $tr->translate("CREDIT_TERM");?></th>
							<th><?php echo $tr->translate("STATUS");?></th>
							<th><?php echo $tr->translate("ACTION");?></th>
						</tr>
					</thead>
					<tbody>
						<?php if(!empty($rs)){ foreach ($rs as $key => $row){?>
						<tr class="odd gradeX">
							<td><?php echo $key+1?></td>
							<td><?php echo $row["name_en"]?></td>
							<td class="center"><?php echo $row["credit_limit"]?></td>
							<td class="center"><?php echo $row["credit_term"]?></td>
							<td>
								<?php if($row["status"] == 1){?>
								<span class="label label-sm label-success"><?php echo $tr->translate("ACTIVE");?> </span>
								<?php }else{?>
								<span class="label label-sm label-danger"><?php echo $tr->translate("DEACTIVE");?> </span>
								<?php }?>
							</td>
							<td>
								<a href="<?php echo $url_edit;?>/id/<?php echo $row["id"]?>"><?php echo $tr->translate("EDIT");?></a>
							</td>
						</tr>
						<?php }}?>
					</tbody>
			</table>
		</div>
	</div>
</div>
