<?php 
	$tr=Application_Form_FrmLanguages::getCurrentlanguage();
?>
<title><?php echo $tr->translate('REQUEST_APPROVAL');?></title>
<div class="card pb-10 pt-10 pl-10 pr-10">
	<div class="card-content">
		<div class="card-box">
            <div class="col-sm-12 border-botom">
		    	<div class="col-sm-8 pd-0">
		    		<h4 class="m-b-0"><i class="fa fa-cube" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('REQUEST_APPROVAL');?></h4>
    			</div>
    			<div class="col-sm-4 text-right"></div>
    		</div>
    	</div>
		<div class="card-box">
				<form dojoType="dijit.form.Form" action="" class="form-horizontal" enctype="multipart/form-data" method="post">		   
					<script  type="dojo/method" event="onSubmit">	
				if(this.validate()) {
					loadingBlock();
					return true;
				}else{
					return false;
				}
			     </script>
					<div id="divPrint" style="width: 100%;">
					<style>
						.style{
							line-height: 20px;font-size: 9px !important;
							font-family: 'Khmer OS Battambang';
						}
						ul{margin: 0;padding:0;}
						table tr td ul li{text-align: center;list-style: none;line-height: 25px;}
						th{padding: 5px;}
						ul.pur_info li{line-height:18px; 
								}
						ul.pur_info li strong{font-weight: bold;}
				       .hover:hover{background: #ccc;}
					</style>
						<table style="font-family: 'Khmer OS Content'; width:100%;">
							<tbody>
							<tr>
						    	<td align="center">
						        	<table width="100%" style="font-family: 'Khmer OS Battambang';" cellpadding="0" cellpadding="0">
						            	<tbody><tr>
						                	<td width="20%" valign="top"></td>
						                	<td width="60%" valign="top">
						                		<ul>
						                			<li style="text-align:center; font-size:16px; font-family:'Khmer OS Muol Light'">ប័ណ្ណស្នើផ្ទេរទិញទំនិញ</li>
						                		</ul>
						                	</td>
						                    <td width="20%"></td>
						                </tr> 
						                <tr>
						                	<td colspan="3" valign="top" align="left">
						                		<table width="50%" style="font-size: 12px; font-weight:600;float:right;">
														<tr style="line-height:20px;">
															<td style="text-align: right;white-space: nowrap;"><?php echo $tr->translate("REQUEST_NO");?> :</td>
															<td style="text-align: right;white-space: nowrap;"><?php echo $this->rs['re_no'];?></td>
														</tr>
														<tr style="line-height:20px;">
															<td style="text-align: right;white-space: nowrap;"><?php echo $tr->translate("REQUEST_DATE");?> :</td>
															<td style="text-align: right;white-space: nowrap;"><?php echo date("d/m/Y",strtotime($this->rs['date_request']));?></td>
														</tr>
														<tr style="line-height:20px;">
															<td style="text-align: right;white-space: nowrap;"><?php echo $tr->translate("DATE_IN");?> :</td>
															<td style="text-align: right;white-space: nowrap;"><?php echo date("d/m/Y",strtotime($this->rs['date_in']));?></td>
														</tr>
														<tr style="line-height:20px;">
															<td style="text-align: right;white-space: nowrap;"><?php echo $tr->translate("REQUET_TO_FROM");?> :</td>
															<td style="text-align: right;"><?php echo $this->rs['re_from'];?></td>
														</tr>
														<tr style="line-height:20px;">
															<td style="text-align: right;white-space: nowrap;"><?php echo $tr->translate("REQUET_TO_BRANCH");?> :</td>
															<td style="text-align: right;"><?php echo $this->rs['re_to'];?></td>
														</tr>
													</table>
								              </td>
								           </tr>   
						            </tbody>
						           </table>
						        </td>
						    </tr>
						    <tr>
						    	<td id="exportExcel"><br />
						            <table  style="border-collapse:collapse;border:1px solid #000; font-size:12px;" width="100%" cellspacing="0" border="1">
						                 <tbody>
						                 <tr style="font-size:13px !important; line-height:30px;text-align: center !important;background:#ccd9ff;">
						                    <th>&nbsp;<?php echo $tr->translate("NUM");?></th>
											<th><?php echo $tr->translate("PRODUCT_DISCRIPTION");?></th>
											<th width="10%">&nbsp;<?php echo $tr->translate("SERIAL_NUM");?></th>
											<th>&nbsp;<?php echo $tr->translate("QTY");?></th>
						                <?php $num=1; 
						               
						                if(!empty($this->rs_detail))foreach ($this->rs_detail AS $index => $rs){
											$raw_qty = $rs["qty"];
											$array = explode(".",$rs["qty"]);
											$qty = $array[0];
											$qty_unit = ($raw_qty*$rs["qty_measure"]) - ($rs["qty_measure"]*$array[0]);
											$l_qty = 0;
											if(abs($raw_qty)>0){
												if(abs($qty)>0 and $qty_unit>0){
													$l_qty = $qty." ".$rs["measure"]." & ".round($qty_unit)." ".$rs["unit_label"];
												}elseif(abs($qty)==0 and $qty_unit>0){
													$l_qty = round($qty_unit)." ".$rs["unit_label"];
												}elseif(abs($qty)>0 and $qty_unit==0){
													$l_qty =  $qty." ".$rs["measure"];
												}
											}else{
												$l_qty = 0;
											}
										?>
										<tr class='row-format<?php echo $num; $num=1-$num;?> hover' style="border:1px solid #000;">
										   <td align="center" style="white-space: nowrap;">&nbsp;<?php echo $index+1?></td>
										   <td style="white-space: nowrap;">&nbsp;<?php echo $rs["item_name"];?></td>
										   <td style="white-space: nowrap;">&nbsp;<?php echo $rs["item_code"];?></td>
										   <td style="white-space: nowrap;">&nbsp;<?php echo $l_qty;?></td>
										</tr>
										   <?php 
				                    }?>
						            </tbody>
						           </table>
						              <br>
						    		</td>
						    	</tr>
							</tbody>
						</table>
					</div><!-- end print -->
					<div class="card-box">
						<div class="form-group">
							<div class="col-md-4"></div>
							<div class="col-md-4">
								<textarea name="app_remark" id="app_remark" class="form-control" rows="3" cols="80" placeHolder="Approval Comment Here"></textarea>	
							</div>
							<div class="col-md-4"></div>
						</div>
						<div class="form-group">
							<div class="col-md-4"></div>
							<div class="col-md-4">	
								 <select name="approved_name" id="approved_name" class="form-control select2me">
						        	<option value="1" <?php if($this->rs['appr_status']==1){echo"selected";}?>>Approved</option>
						        	<option value="2" <?php if($this->rs['appr_status']==2){echo"selected";}?>>Rejected</option>
						        </select><input type="hidden" name="id" id="id" value="<?php echo $this->product[0]['id'];?>" />
								<input type="hidden" name="branch_id" id="branch_id" value="<?php echo $this->product[0]['branch_id'];?>" />
							</div>
							<div class="col-md-4"></div>
						</div>
						<div class="form-group">
							<div class="col-md-4"></div>
							<div class="col-md-4" style="text-align: center;">
								<input type="submit" value="btnsavenew" id="btnsavenew" name="save_close" label="<?php echo $tr->translate("SAVE_NEW")?>" dojoType="dijit.form.Button" 
									iconClass="dijitIconSearch" />
							</div>
						</div>
				</div>
		</form>	
	  </div>		
	</div>
</div>
<iframe name=print_frame width=0 height=0 frameborder=0 src=about:blank></iframe>
<script>
$(document).ready(function() {    
  calculateBalance();
 }); 
function calculateBalance(){
	deposit= $("#deposit").val();
	net_total = $('#net_total').val();
	balance = parseFloat(net_total)-parseFloat(deposit);
	if(balance<0){
		balance=0;
		$("#deposit").val(net_total);
	}
	$("#balance").val(balance);
}
function doPrint() {
	window.frames["print_frame"].document.body.innerHTML=document.getElementById('divPrint').innerHTML;
    window.frames["print_frame"].window.focus();
    window.frames["print_frame"].window.print();
}
</script>