<?php 
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$formFilter = $this->formFilter;
	$rs = $this->product;
?>
<title><?php echo $tr->translate("TRANSFER_LIST");?></title>
<div class="card pb-10 pt-10 pl-10 pr-10">
	<div class="card-content">
		<div class="card-box">
			<form dojoType="dijit.form.Form" id="frm" method="post" action="" enctype="multipart/form-data" autocomplete="off" >				
				<div class="form-group">
					<div class="col-md-2">
						<?php echo $formFilter->getElement('avd_search');?>
					</div>
					<div class="col-md-2">
						<?php echo $formFilter->getElement('branch');?>
					</div>
					<div class="col-md-2">
						<?php echo $formFilter->getElement('check_stat');?>
					</div>
					<div class="col-md-2">
						<?php echo $formFilter->getElement('start_date');?>
					</div>
					<div class="col-md-2">
						<?php echo $formFilter->getElement('end_date');?>
					</div>
					<div class="col-md-2">
						<input type="submit" value="btnsavenew" id="btnsavenew" name="save_close" label="<?php echo $tr->translate("REFRESH")?>" dojoType="dijit.form.Button" 
							iconClass="dijitIconSearch" />
					</div>
				</div>
			</form>
			<?php echo $this->list;?>
		</div>
	</div>
</div>
<script>
	dojo.require("dijit.form.DateTextBox");
</script>