<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$url_submit =  $this->url(array('module'=>'product','controller'=>'transfer','action'=>'receiverequest'),null,true);
	$formFilter = $this->formFilter;
?>
<title><?php echo $tr->translate("RECEIVED_TRANSFER");?></title>
<div class="card pb-10 pt-10 pl-10 pr-10">
	<div class="card-content">
		<div class="card-box">
            <div class="col-sm-12 border-botom">
		    	<div class="col-sm-8 pd-0">
		    		<h4 class="m-b-0"><i class="fa fa-cube" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('RECEIVED_TRANSFER');?></h4>
    			</div>
    			<div class="col-sm-4 text-right">
    			</div>
    		</div>
    	</div>
		<div class="card-box">
				<form dojoType="dijit.form.Form" class="form-horizontal" method="post" action="" >
					<script  type="dojo/method" event="onSubmit">	
				if(this.validate()) {
				 	identity = $("#identity").val();
    				if(identity==''){
	 					alert("សូមបញ្ចូលបរិមាណទំនិញ");
	   					 return false;
    				}
						loadingBlock();
						return true;
				}else{
					return false;
				}
			     </script>
				<div class="col-md-4">
					<div class="form-group">
						<div class="col-md-4"><?php echo $tr->translate("RECEIVE_NUM");?></div>
						<div class="col-md-8">
							<?php echo $formFilter->getElement('receive_num');?>
						</div>
					</div>
					<div class="form-group">
						<div class="col-md-4">
							<?php echo $tr->translate("RECEIVE_FROM");?>
						</div>
						<div class="col-md-8">
							<?php echo $formFilter->getElement('from_loc');?>
						</div>
					</div>
					<div class="form-group">
						<div class="col-md-4">
							<?php echo $tr->translate("សាខាទទួល");?>
						</div>
						<div class="col-md-8">
							<?php echo $formFilter->getElement('to_loc');?>
						</div>
					</div>
					<div class="form-group">
						<div class="col-md-4">
							<?php echo $tr->translate("TRANSFER_NUM");?></div>
						<div class="col-md-8">
							<?php echo $formFilter->getElement('tran_num');?>
						</div>
					</div>
					<div class="form-group">
						<div class="col-md-4">
							<?php echo $tr->translate("REQUEST_NUM");?>
						</div>
						<div class="col-md-8">
							<?php echo $formFilter->getElement('re_num');?>
						</div>
					</div>
					<div class="form-group">
						<div class="col-md-4">
							<?php echo $tr->translate("REQUEST_DATE");?>
						</div>
						<div class="col-md-8">
							<?php echo $formFilter->getElement('tran_date');?>
						</div>
					</div>
					<div class="form-group">
						<div class="col-md-4"><span id="lb_br"></span>
							<?php echo $tr->translate("TRANSFER_DATE");?>
						</div>
						<div class="col-md-8">
							<?php echo $formFilter->getElement('re_date');?>
						</div>
					</div>
					<div class="form-group">
						<div class="col-md-4">
							<?php echo $tr->translate("REMARK");?>
						</div>
						<div class="col-md-8">
							<?php echo $formFilter->getElement('remark');?>
						</div>
					</div>
					<div class="form-group">	
						<div class="col-md-4">
							<?php echo $tr->translate("STATUS");?>
						</div>
						<div class="col-md-8">
							<?php echo $formFilter->getElement('status');?>
						</div>
					</div>
				</div>
				<div class="col-md-8">
					<div class="table-responsive">
						<table class="table table-bordered">
							<thead>
								<tr>
									<th>#</th>
									<th><?php echo $tr->translate("PRODUCT_NAME");?></th>
									<th style="white-space: nowrap;"><?php echo $tr->translate("QTY_REQUEST");?></th>
									<th style="white-space: nowrap;"><?php echo $tr->translate("QTY_TRANSFER");?></th>
									<th><?php echo $tr->translate("UNIT_QTY");?></th>
									<th><?php echo $tr->translate("QTY_PER_UNIT");?></th>
									<th><?php echo $tr->translate("QTY_RECEIVE");?></th>
									<th><?php echo $tr->translate("REMARK");?></th>
								</tr>
							</thead>
							<tbody id="tr_location" style="font-size:12px;">
							</tbody>
						</table>
					</div>
				</div>
					<div class="form-group">
						<label  class="col-md-12 col-md-offset-4 col-md-8">
                               <input type="hidden" name="identity" id="identity" value="" >
                               <button type="submit" name="save_close" class="btn btn-primary"><?php echo $tr->translate("SAVE_CLOSE");?></button>
                           </label>
					</div>
			</form>
		</div>
	</div>
</div>
<script type="text/javascript">
jQuery(document).ready(function(){
	oldRow();
});
var index=0;
function oldRow(){
	<?php if(!empty($this->rs_detail)){
			foreach( $this->rs_detail as $rs){
				$raw_qty = $rs["qty_request"];
				$array = explode(".",$rs["qty_request"]);
				$qty = $array[0];
				$qty_unit = ($raw_qty*$rs["qty_measure"]) - ($rs["qty_measure"]*$array[0]);
				$l_qty = 0;
				if(abs($raw_qty)>0){
					if(abs($qty)>0 and $qty_unit>0){
						$l_qty = $qty." ".$rs["measure"]." & ".round($qty_unit)." ".$rs["unit_label"];
					}elseif(abs($qty)==0 and $qty_unit>0){
						$l_qty = round($qty_unit)." ".$rs["unit_label"];
					}elseif(abs($qty)>0 and $qty_unit==0){
						$l_qty =  $qty." ".$rs["measure"];
					}
				}else{
					$l_qty = 0;
				}
	?>
		qty_unit = '<?php echo number_format($rs["qty_unit"],0);?>';
		qty_per_unit = '<?php echo number_format($rs["qty_per_unit"],0);?>';
		if(parseFloat(qty_unit)>0 && parseFloat(qty_per_unit)>0){
			qty_transfer = qty_unit+" <?php echo $rs["measure"]?> & "+qty_per_unit+" <?php echo $rs["unit_label"]?>";
		}else if(parseFloat(qty_unit)<=0 && parseFloat(qty_per_unit)>0){
			qty_transfer = qty_per_unit+" <?php echo $rs["unit_label"]?>";
		}else if(parseFloat(qty_unit)>0 && parseFloat(qty_per_unit)<=0){
			qty_transfer=qty_unit+" <?php echo $rs["measure"]?>";
		}
			index++;
			template='<tr id="row_location_'+index+'">';
			template+='<td>'+index+'</td>';
			template+='<td style="white-space: nowrap;"><?php echo $rs["item_name"];?><input type="hidden" id="pro_id_'+index+'" name="pro_id_'+index+'" value="<?php echo $rs["pro_id"]?>" </td>';
			template+='<td><?php echo $l_qty;?><input type="hidden" id="qty_request_'+index+'" readOnly="readOnly" name="qty_request_'+index+'" value="<?php echo $rs['qty_request']?>" class="form-control"></td>'; 
			template+='<td>'+qty_transfer+'<input type="hidden" id="qty_tran_'+index+'" readOnly="readOnly" name="qty_tran_'+index+'" value="<?php echo $rs['qty']?>" class="form-control"></td>'; 
			template+='<td width="90px"><input dojoType="dijit.form.NumberTextBox" class="fullside" type="text" id="qty_unit_'+index+'" onKeyup="TotalQty('+index+')" name="qty_unit_'+index+'" value="<?php echo $rs['qty_unit']?>" /></td>'; 
			template+='<td width="90px"><input dojoType="dijit.form.NumberTextBox" class="fullside" type="text" id="qty_per_unit_'+index+'" onKeyup="TotalQty('+index+')" name="qty_per_unit_'+index+'" value="<?php echo $rs['qty_per_unit']?>" class="form-control" /></td>'; 
			template+='<td width="90px"><input dojoType="dijit.form.NumberTextBox" class="fullside" type="text" id="qty_receive_'+index+'" readOnly="readOnly" name="qty_receive_'+index+'" value="<?php echo $rs['qty']?>" class="form-control"><input type="hidden" name="qty_measure_'+index+'" id="qty_measure_'+index+'" value="<?php echo $rs['qty_measure']?>"/></td>'; 
			template+='<td><input dojoType="dijit.form.TextBox" class="fullside" type="text" id="remark_'+index+'" name="remark_'+index+'" class="form-control"></td>';
			template+='</tr>';
			$('#tr_location').append(template);
			if($('#identity').val()!="") {
				var identity = $('#identity').val();
				$('#identity').val(identity+','+index);
			} else {$('#identity').val(index);}
	<?php }}?>
}
function TotalQty(index){
		main_qty =$("#qty_unit_"+index).val();
		detail_qty =  $("#qty_per_unit_"+index).val();
		qty_measure = $("#qty_measure_"+index).val();
		if(qty_measure==0){
			qty_measure=1;
		}else{
			qty_measure = qty_measure;
		}
		total_qty = parseFloat(main_qty) + (parseFloat(detail_qty)/parseFloat(qty_measure));
		$("#qty_receive_"+index).val(total_qty.toFixed(3));
	}	
	dojo.require("dijit.form.NumberTextBox");
	dojo.require("dijit.form.DateTextBox");
</script>