<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$url_getcurrentitem =  $this->url(array('module'=>'product','controller'=>'adjust-stock','action'=>'get-current-quantity'));
	$url_getProduct =  $this->url(array('module'=>'product','controller'=>'adjust','action'=>'get-product'));
	$formFilter = $this->formFilter;
?>
<title><?php echo $tr->translate("ADJUST_STOCK");?></title>
<div class="card pb-10 pt-10 pl-10 pr-10">
	<div class="card-content">
		<div class="card-box">
            <div class="col-sm-12 border-botom">
		    	<div class="col-sm-8 pd-0">
		    		<h4 class="m-b-0"><i class="fa fa-cube" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('EDIT_RECEIVED');?></h4>
    			</div>
    			<div class="col-sm-4 text-right">
    			</div>
    		</div>
    	</div>
		<div class="card-box">
			<form class="form-horizontal" method="post" action="" >
				<div class="form-group">
					<label class="col-md-2 control-label"></label>
					<div class="col-md-4">
					</div>
					<label class="col-md-2 control-label"><?php echo $tr->translate("RECEIVE_NUM");?></label>
					<div class="col-md-4">
						<?php echo $formFilter->getElement('receive_num');?>
					</div>
				</div>
				<div class="form-group">
					<label class="col-md-2 control-label"><?php echo $tr->translate("RECEIVE_FROM");?></label>
					<div class="col-md-4">
						<?php echo $formFilter->getElement('from_loc');?>
					</div>
					
					<label class="col-md-2 control-label"><?php echo $tr->translate("RECEIVE_TO");?></label>
					<div class="col-md-4">
						<?php echo $formFilter->getElement('to_loc');?>
					</div>
				</div>
				<div class="form-group">
					<label class="col-md-2 control-label"><?php echo $tr->translate("TRANSFER_NUM");?></label>
					<div class="col-md-4">
						<?php echo $formFilter->getElement('tran_num');?>
					</div>
					
					<label class="col-md-2 control-label"><?php echo $tr->translate("REQUEST_NUM");?></label>
					<div class="col-md-4">
						<?php echo $formFilter->getElement('re_num');?>
					</div>
				</div>
				<div class="form-group">
					<label class="col-md-2 control-label"><?php echo $tr->translate("REQUEST_DATE");?></label>
					<div class="col-md-4">
						<?php echo $formFilter->getElement('re_date');?>
					</div>
					
					<label class="col-md-2 control-label"><span id="lb_br"></span><?php echo $tr->translate("TRANSFER_DATE");?></label>
					<div class="col-md-4">
						<?php echo $formFilter->getElement('tran_date');?>
					</div>
				</div>
				<div class="form-group">
					<label class="col-md-2 control-label"><?php echo $tr->translate("REMARK");?></label>
					<div class="col-md-4">
						<?php echo $formFilter->getElement('remark');?>
					</div>	
					
					<label class="col-md-2 control-label"><?php echo $tr->translate("STATUS");?></label>
					<div class="col-md-4">
						<?php echo $formFilter->getElement('status');?>
					</div>
				</div>
				<div class="form-group">
						<table class="table table-bordered">
							<thead>
								<tr>
									<th>#</th>
									<th><?php echo $tr->translate("PRODUCT_NAME");?></th>
									<th><?php echo $tr->translate("QTY_REQUEST");?></th>
									<th><?php echo $tr->translate("QTY_TRANSFER");?></th>
									<th><?php echo $tr->translate("UNIT_QTY");?></th>
									<th><?php echo $tr->translate("QTY_PER_UNIT");?></th>
									<th><?php echo $tr->translate("QTY_RECEIVE");?></th>
									<th><?php echo $tr->translate("REMARK");?></th>
									<th><?php echo $tr->translate("ACTION");?></th>
								</tr>
							</thead>
							<tbody id="tr_location" style="font-size:12px;">
							</tbody>
						</table>
				</div>
				<div class="form-group">
					<label  class="col-md-12 col-md-offset-4 col-md-8">
						<input type="hidden" name="identity" id="identity" value="" >
                        <button type="submit" name="save_close" class="btn btn-primary"><?php echo $tr->translate("GO_EDIT");?></button>
                    </label>
				</div>
			</form>
		</div>
	</div>
</div>
<script type="text/javascript">
jQuery(document).ready(function(){
	oldRow();
});
var index=0;
function oldRow(){
	<?php if(!empty($this->rs_detail)){
			foreach( $this->rs_detail as $rs){
				
	?>
			index++;
			template='<tr id="row_location_'+index+'">';
			template+='<td>'+index+'</td>';
			template+='<td style="white-space: nowrap;"><?php echo $rs["item_name"];?><input type="hidden" id="pro_id_'+index+'" name="pro_id_'+index+'" value="<?php echo $rs["pro_id"]?>" </td>';
			template+='<td width="110px"><input dojoType="dijit.form.NumberTextBox" class="fullside" type="text" id="qty_request_'+index+'" readOnly="readOnly" name="qty_request_'+index+'" value="<?php echo $rs['qty_request']?>" class="form-control"></td>'; 
			template+='<td width="80px"><input dojoType="dijit.form.NumberTextBox" class="fullside" type="text" id="qty_tran_'+index+'" readOnly="readOnly" name="qty_tran_'+index+'" value="<?php echo $rs['tran_qty']?>" class="form-control"></td>'; 
			template+='<td width="80px"><input dojoType="dijit.form.NumberTextBox" class="fullside" type="text" id="qty_unit_'+index+'" onKeyup="TotalQty('+index+')" name="qty_unit_'+index+'" value="<?php echo $rs['qty_unit']?>" class="form-control" /></td>'; 
			template+='<td width="80px"><input dojoType="dijit.form.NumberTextBox" class="fullside" type="text" id="qty_per_unit_'+index+'" onKeyup="TotalQty('+index+')" name="qty_per_unit_'+index+'" value="<?php echo $rs['qty_per_unit']?>" class="form-control" /></td>'; 
			template+='<td width="80px"><input dojoType="dijit.form.NumberTextBox" class="fullside" type="text" id="qty_receive_'+index+'" name="qty_receive_'+index+'" value="<?php echo $rs['receive_qty']?>" class="form-control"><input type="hidden" id="old_qty_receive_'+index+'" name="old_qty_receive_'+index+'" value="<?php echo $rs['receive_qty']?>" class="form-control"> <input type="hidden" name="qty_measure_'+index+'" id="qty_measure_'+index+'" value="<?php echo $rs['qty_measure']?>"/></td>'; 
			template+='<td width="80px"><input dojoType="dijit.form.TextBox" class="fullside" type="text" id="remark_'+index+'" name="remark_'+index+'" class="form-control"></td>';
			template+='<td width="80px"><button type="button" onClick="deleteRecord('+index+',1)" name="save_close" class="btn default"><?php echo $tr->translate("DELETE");?></button></td>';
			template+='</tr>';
			$('#tr_location').append(template);
			if($('#identity').val()!="") {
				var identity = $('#identity').val();
				$('#identity').val(identity+','+index);
			} else {$('#identity').val(index);}
	<?php }}?>
}
function TotalQty(index){
		main_qty =$("#qty_unit_"+index).val();
		detail_qty =  $("#qty_per_unit_"+index).val();
		qty_measure = $("#qty_measure_"+index).val();
		if(qty_measure==0){
			qty_measure=1;
		}else{
			qty_measure = qty_measure;
		}
		total_qty = parseFloat(main_qty) + (parseFloat(detail_qty)/parseFloat(qty_measure));
		$("#qty_receive_"+index).val(total_qty.toFixed(3));
	}
function addNew(){
	id = $("#pro_name").val();
	index++;
	$.ajax({
        url: "<?php echo $url_getProduct;?>",
        type: "post",
        data: {'id':id},
        success: function(val){
			for(i=1; i<index; i++){
				new_item=parseInt(id);
				items = parseInt($("#pro_id_"+i).val());
				if(new_item==items){		
					newqty = parseInt($("#qty_tran_"+i).val());
					newqty = newqty+1;
					$("#qty_tran_"+i).val(newqty);
					checkQTY(i);
					return false;
				}
			}
			 data = $.parseJSON(val);
			template='<tr id="row_location_'+index+'">';
			template+='<td>'+index+'</td>';
			template+='<td style="white-space: nowrap;">'+data.item_name+" "+data.brand+" "+data.size+" "+data.color+'<input type="hidden" id="pro_id_'+index+'" name="pro_id_'+index+'" value="'+data.id+'" </td>';
			template+='<td><input dojoType="dijit.form.NumberTextBox" class="fullside" type="text" id="qty_tran_'+index+'" onKeyup="checkQTY('+index+')" name="qty_tran_'+index+'" value="1" ><input type="hidden" name="qty_'+index+'" id="qty_'+index+'" value="'+data.qty+'" /></td>'; 
			template+='<td><input dojoType="dijit.form.NumberTextBox" class="fullside" type="text" id="remark_'+index+'" name="remark_'+index+'" ></td>';
			template+='<td><button type="button" onClick="deleteRecord('+index+',1)" name="save_close" class="btn default"><?php echo $tr->translate("DELETE");?></button></td>';
			template+='</tr>';
			$('#tr_location').append(template);
			if($('#identity').val()!="") {
				var identity = $('#identity').val();
				$('#identity').val(identity+','+index);
			} else {$('#identity').val(index);}
        },
        error:function(){
        }
    });
}
	function checkQTY(index){
		qty = parseFloat($('#qty_'+index).val());
		qty_tran = parseFloat($('#qty_tran_'+index).val());
		translate = "This Product is remain "+qty+" Only";
		if(qty_tran>qty){
			alert("This Product is remain "+qty+" Only");
			$('#qty_tran_'+index).val(qty)
		}
	}
	function transferType(){
		var type= $('#type').val();
		if(type==1){
			document.getElementById('lb_br').innerHTML = "From ";
		}else if(type==2){
			document.getElementById('lb_br').innerHTML = "To ";
		}
	}
function deleteRecord(index,type) {
		if(type==1){
			var identity = $('#identity').val();
			var arrays = identity.split(',');
		}else{
			var identity = $('#identity_price').val();
			var arrays = identity.split(',');
		}
		
		for(var i=0;i<arrays.length;i++) {
			if(arrays[i] == index) arrays.splice(i,1);
		}
		var strings = arrays.join(',');
		
		if(type==1){
			$('#identity').val(strings);
			$("#row_location_"+index).remove();
		}else{
			$('#identity_price').val(strings);
			$("#row_price_"+index).remove();
		}
}
	dojo.require("dijit.form.NumberTextBox");
	dojo.require("dijit.form.DateTextBox");
</script>