<?php 
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$formFilter = $this->formFilter;
?>
<title><?php echo $tr->translate("TRANSFER_LIST");?></title>
<div class="card pb-10 pt-10 pl-10 pr-10">
	<div class="card-content">
		<div class="card-box">	
			<form class="form-horizontal" method="post" action="" >
				<div class="form-body">
							<div class="form-group">
								<div class="col-md-3">
									<?php echo $formFilter->getElement('avd_search');?>
								</div>
								<div class="col-md-3">
									<?php echo $formFilter->getElement('branch');?>
								</div>
								<div class="col-md-2">
									<?php echo $formFilter->getElement('start_date');?>
								</div>
								<div class="col-md-2">
									<?php echo $formFilter->getElement('end_date');?>
								</div>
								<div class="col-md-2">
									<input type="submit" value="btnsavenew" id="btnsavenew" name="save_close" label="<?php echo $tr->translate("REFRESH")?>" dojoType="dijit.form.Button" 
										iconClass="dijitIconSearch" />
								</div>
							</div>
					</div>
			</form>
		</div>
		<div class="portlet-body">
			<table class="collape tablesorter" id="table" width="100%">
			<thead>
				<tr>
					<th class="tdheader"><?php echo  $tr->translate("NO");?></th>
					<th class="tdheader"><?php echo  $tr->translate("BRANCH");?></th>
					<th class="tdheader"><?php echo  $tr->translate("REQUEST_NO");?></th>
					<th class="tdheader"><?php echo  $tr->translate("TRANSFER_FROM");?></th>
					<th class="tdheader"><?php echo  $tr->translate("REQUEST_DATE");?></th>
					<th class="tdheader"><?php echo  $tr->translate("APP_STATUS");?></th>
					<th class="tdheader"><?php echo  $tr->translate("PEDDING");?></th>
					<th class="tdheader"><?php echo  $tr->translate("STATUS");?></th>
					<th class="tdheader"><?php echo  $tr->translate("USER");?></th>
					<th class="tdheader"><?php echo  $tr->translate("ACTION");?></th>
				</tr>
			</thead>
		<tbody>
			<?php 
			$id = "table";
			$stringPagination = '<script type="text/javascript">
						$(document).ready(function(){
							$("#'.$id.'").tablesorter();
							$("#'.$id.'").tablesorter().tablesorterPager({container: $("#pagination_'.$id.'"),size:15});
							$("#pagedisplay").focus(function(){ this.blur(); 
						   });
						});
				</script>
				<div id="pagination_'.$id.'" class="pager" >
							<form >
								<table  style="width: 200px;"><tr>
								<td><img src="'.BASE_URL.'/images/first.gif" class="first"/></td>
								<td><img src="'.BASE_URL.'/images/previous.gif" class="prev"/></td>
								<td><input type="text" class="pagedisplay"/></td>
								<td><img src="'.BASE_URL.'/images/next.gif" class="next"/></td>
								<td><img src="'.BASE_URL.'/images/last.gif" class="last"/></td>
								<td><select class="pagesize" >
									<option selected="selected"  value="10">10</option>
									<option value="20">20</option>
									<option value="30">30</option>
									<option value="40">40</option>
									<option value="50">50</option>
									<option value="60">60</option>
									<option value="70">70</option>
									<option value="80">80</option>
									<option value="90">90</option>
									<option value="100">100</option>
									</select>
								</td>
								</tr>
								</table>
							</form>
					</div>	';
						$footer="";
						if(!empty($rs)){ foreach ($rs as $key => $row){
								$edit_status = '';
								if($row["ap_pedding"]==4){
									$edit_status = "style='pointer-events: none;cursor: default;color: #ccc;'";
								}									
						?>
						<tr class="odd gradeX">
							<td class="center"><?php echo $key+1;?></td>
							<td><?php echo $row["re_tran"]?></td>
							<td><?php echo $row["tran_no"]?></td>
							<td><?php echo $row["to_tran"]?></td>
							<td><?php echo $row["date_tran"]?></td>
							<td><?php echo $row["appr_status"]?></td>
							<td><?php echo $row["appr_pedding"]?></td>
							<td class="center">
								<?php if($row["status"] == 1){?>
								<span class="label label-sm label-success"><?php echo $tr->translate("ACTIVE");?> </span>
								<?php }else{?>
								<span class="label label-sm label-danger"><?php echo $tr->translate("DEACTIVE");?> </span>
								<?php }?>
							</td>
							<td><?php echo $row["user"]?> </td>
							<td class="center">
								<?php if($row["receive_id"]>0){?>
									<a href="<?php echo $this->baseUrl();?>/product/receivetransfer/edit/id/<?php echo $row["receive_id"]?>"><?php echo  $tr->translate("EDIT_RECEIVE");?></a> | 
									<a href="<?php echo $this->baseUrl();?>/product/transfer/viewreceive/id/<?php echo $row["receive_id"];?>"><?php echo  $tr->translate("PRINT");?></a>
								<?php }else{?>
								<a <?php echo $edit_status;?> href="<?php echo $this->baseUrl();?>/product/receivetransfer/add/id/<?php echo $row["is_transfer"]?>"><?php echo  $tr->translate("MAKE_RECEIVE");?></a> |  
								<?php }?>	
							</td>
						</tr>
						<?php $counter='<strong style="float:right;padding:5px">Number of record(s): '.count($this->rs).'</strong>'; 
						$footer = '<div class="footer_list">'.$stringPagination.$counter.'</div>';
					}}?>
					</tbody>
				</table>
			</div>
			<?php echo $footer?>
	</div>
</div>
<script>
	dojo.require("dijit.form.DateTextBox");
</script>