<?php 
	$url_edit = $this->url(array('module'=>'product','controller'=>'category','action'=>'edit',));
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$formFilter = $this->formFilter;
	$rs = $this->resulr;
?>
<title><?php echo $tr->translate("PRODUCT_CATEGORY");?></title>
<div class="card pb-10 pt-10 pl-10 pr-10">
	<div class="card-content">
		<div class="card-box">
			<form class="form-horizontal" method="post" action="" autocomplete="off">
				<div class="form-body">
					<div class="form-group">
						<div class="col-md-3">
							<?php echo $formFilter->getElement('name');?>
						</div>
						<div class="col-md-3">
							<?php echo $formFilter->getElement('parent');?>
						</div>
						<div class="col-md-3">
							<?php echo $formFilter->getElement('status');?>
						</div>
						<div class="col-md-2">
							<input type="submit" value="btnsavenew" id="btnsavenew" name="save_close" label="<?php echo $tr->translate("REFRESH")?>" dojoType="dijit.form.Button" 
								iconClass="dijitIconSearch" />
						</div>
					</div>
				</div>
			</form>
			</div>
			<div class="card-box">
				<table class="table table-striped table-bordered table-hover" id="sample_1">
					<thead>
						<tr>
							<th><?php echo $tr->translate("NUM");?></th>
							<th><?php echo $tr->translate("CATEGORY_NAME");?></th>
							<th><?php echo $tr->translate("PARENT");?></th>
							<th><?php echo $tr->translate("STATUS");?></th>
							<th><?php echo $tr->translate("REMARK");?></th>
							<th><?php echo $tr->translate("ACTION");?></th>
						</tr>
					</thead>
					<tbody style="font-size: 12px;">
						<?php if(!empty($rs)){ foreach ($rs as $key => $row){?>
						<tr class="odd gradeX">
							<td width="3%"><?php echo $key+1;?></td>
							<td><?php echo $row["name"]?></td>
							<td><?php echo $row["parent_id"]?></td>
							<td>
								<?php if($row["status"] == 1){?>
								<span class="label label-sm label-success"><?php echo $tr->translate("ACTIVE");?> </span>
								<?php }else{?>
								<span class="label label-sm label-danger"><?php echo $tr->translate("DEACTIVE");?> </span>
								<?php }?>
							</td>
							<td class="center"><?php echo $row["remark"]?></td>
							<td>
								<a href="<?php echo $url_edit;?>/id/<?php echo $row["id"]?>"><?php echo $tr->translate("EDIT");?></a> 
							</td>
						</tr>
						<?php }}?>
					</tbody>
				</table>
		</div>
	</div>
</div>