<?php 
	$url_submit =  $this->url(array('module'=>'sales','controller'=>'customer','action'=>'edit'));
	$form=$this->form;
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
?>
<title><?php echo $tr->translate("ADD_NEW_CUSTOMER");?></title>
<div class="card pb-10 pt-10 pl-10 pr-10">
	<div class="card-content">
		<div class="card-box">
            <div class="col-sm-12 border-botom">
		    	<div class="col-sm-8 pd-0">
		    		<h4 class="m-b-0"><i class="fa fa-cube" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('EDIT_CUSTOMER');?></h4>
    			</div>
    			<div class="col-sm-4 text-right"></div>
    		</div>
    	</div>
		<div class="card-box">
			<form dojoType="dijit.form.Form"  class="form-horizontal" enctype="multipart/form-data" method="post">
					<script type="dojo/method" event="onSubmit">			
					if(this.validate()) {
						customer_id=dijit.byId("customer_type").get('value');
						if(customer_id=='' || customer_id==-1){
							alert("Please select customer type");
							dijit.byId("customer_type").focus();
							return false;	
						}
               			loadingBlock();
						return true;
					}else{
						return false;
					}
					</script>
				<div class="col-md-6">
					<div class="form-group">
						<div class="col-md-4">
							<?php echo $tr->translate("CU_CODE");?>
						</div>
						<div class="col-md-8">
							<?php echo $form->getElement('cu_code'); ?>
							<?php echo $form->getElement("id");?>
						</div>
					</div>
					<div class="form-group">
						<div class="col-md-4">
							<?php echo $tr->translate("CUSTOMER_NAME");?>
						</div>
						<div class="col-md-8">
							<?php echo $form->getElement('txt_name'); ?>
						</div>
					</div>
					<div class="form-group">
						<div class="col-md-4">
							<?php echo $tr->translate("COMPANY_NUMBER");?>
						</div>
						<div class="col-md-8">
							<?php echo $form->getElement('txt_phone'); ?>
						</div>
					</div>
					<div class="form-group">
						<div class="col-md-4">
							<?php echo $tr->translate("CON_NAME");?>
						</div>
						<div class="col-md-8">
							<?php echo $form->getElement('txt_contact_name'); ?>
						</div>
					</div>
					<div class="form-group">
						<div class="col-md-4">
							<?php echo $tr->translate("CON_NUMBER");?>
						</div>
						<div class="col-md-8">
							<?php echo $form->getElement('contact_phone'); ?>
						</div>
					</div>
					<div class="form-group">
						<div class="col-md-4">
							<?php echo $tr->translate("CUSTOMER_TYPE");?>
						</div>
						<div class="col-md-8">
							<?php echo $form->getElement('customer_type'); ?>
						</div>
					</div>
					<div class="form-group">
						<div class="col-md-4">
								<?php echo $tr->translate("Customer Level");?>
						</div>
						<div class="col-md-8">
							<?php echo $form->getElement('customer_level'); ?>
						</div>
					</div>
					<?php 
						$session_user=new Zend_Session_Namespace('auth');
						$level=$session_user->level;
						$str_display="hidden";
						if($level==1){ 
							$str_display="visible";
						}
					?>
					<div class="form-group">
						<div style="visibility:<?php echo $str_display;?>" >
							<div class="col-md-4">
								<?php echo $tr->translate("CREDIT_LIMIT");?>
							</div>
							<div class="col-md-2">
								<?php echo $form->getElement('credit_limit'); ?>
							</div>
							<div class="control-label col-md-3">
								<?php echo $tr->translate("CREDIT_TEARM");?>
							</div>
							<div class="col-md-3">
								<?php echo $form->getElement("credit_tearm");?>
							</div>
						</div>
					</div>
				</div>
				<div class="col-md-6">
					<div class="form-group">
						<div class="col-md-4">
						<?php echo $tr->translate("ADDRESS");?>
						</div>
						<div class="col-md-8">
							<?php echo $form->getElement("txt_address");?>
						</div>
					</div>
					<div class="form-group">
						<div class="col-md-4">
							<?php echo $tr->translate("Province");?>
						</div>
						<div class="col-md-8">
							<?php echo $form->getElement('province'); ?>
						</div>
					</div>
					<div class="form-group">
						<div class="col-md-4">
							<?php echo $tr->translate("EMAIL");?>
						</div>
						<div class="col-md-8">
							<?php echo $form->getElement('txt_mail'); ?>
						</div>
					</div>
					<div class="form-group">
						<div class="col-md-4">
							<?php echo $tr->translate("FAX");?>
						</div>
						<div class="col-md-8">
							<?php echo $form->getElement('txt_fax'); ?>
						</div>
					</div>
					<div class="form-group">
						<div class="col-md-4">
							<?php echo $tr->translate("WEBSITE");?>
						</div>
						<div class="col-md-8">
							<?php echo $form->getElement('txt_website'); ?>
						</div>
					</div>
					<div class="form-group">
						<div class="col-md-4">
							<?php echo $tr->translate("REMARK");?>
						</div>
						<div class="col-md-8">
							<?php echo $form->getElement("remark");?>
						</div>
					</div>
					<div class="form-group">
						<div class="col-md-4">
							<?php echo $tr->translate("STATUS");?>
						</div>
						<div class="col-md-8">
							<?php echo $form->getElement("status");?>
						</div>
					</div>
				</div>
				<div class="card-box">
					<div class="border-top">
						<div class="col-md-4"></div>
						<div class="col-md-5" class='center'>
							<input type="submit" value="btnsavenew" id="btnsavenew" name="save_close" label="<?php echo $tr->translate("GO_EDIT");?>" dojoType="dijit.form.Button" 
							iconClass="dijitEditorIcon dijitEditorIconSave" />
						</div>
						<div class="col-md-3"></div>
					</div>
				</div>
			</form>
		</div>
	</div>
</div>
<script>

$(document).ready(function() {
	user_level = <?php echo $level;?>;
	if(user_level!=1 && user_level!=2){
		$('#credit_limit').attr('readOnly',true);
		$("#credit_tearm").attr('readOnly',true);
	}
});
<?php $url_customer_limit =  $this->url(array('module'=>'sales','controller'=>'customer','action'=>'getcustomerlimit')); ?>
function getCustomerLimit(){
	dijit.byId('credit_limit').attr('value',0);
	dijit.byId("credit_tearm").attr('value',0);
	customer_type=dijit.byId("customer_type").get('value');
	if(customer_type==''){
		return false;
	}
	$.ajax({
			url:"<?php echo $url_customer_limit;?>",
			type:"post",
			data:{'id':customer_type},
			success: function(data){
				value = $.parseJSON(data);
				if(value!=""){
					dijit.byId('credit_limit').attr('value',value.credit_limit);
					dijit.byId("credit_tearm").attr('value',value.credit_term);
				}
			},
			error:function(e){
			}
		});
}
</script>