<?php 
	$url_new = $this->url(array('module'=>'incomeexpense','controller'=>'expensetitle','action'=>'index',));
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
?>
<title><?php echo $tr->translate("ADD_EXPENSETITLE");?></title>
<div class="card pb-10 pt-10 pl-10 pr-10">
	<div class="card-content">
		<div class="card-box">
            <div class="col-sm-12 border-botom">
		    	<div class="col-sm-8 pd-0">
		    		<h4 class="m-b-0"><i class="fa fa-cube" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('ADD_EXPENSETITLE');?></h4>
    			</div>
    			<div class="col-sm-4 text-right">
    			</div>
    		</div>
    	</div>
		<div class="card-box">
			<form  dojoType="dijit.form.Form" class="form-horizontal" method="post" >
				<script type="dojo/method" event="onSubmit">			
					if(this.validate()) {
						loadingBlock();
						return true;
					}else{
						return false;
					}
				</script>
				<div class="form-body ">
					<div class='col-md-6'>
						<div class="form-group">
							<label class="col-md-4 control-label"><?php echo $tr->translate("NAME_KHMER");?></label>
							<div class="col-md-8">
								<input name="title" id="title" required="1" dojoType="dijit.form.ValidationTextBox" class='fullside' value="<?php echo $this->rs['title'];?>" >
							</div>
						</div>
						<div class="form-group">
							<label class="col-md-4 control-label"><?php echo $tr->translate("NAME_ENTITLE");?></label>
							<div class="col-md-8">
								<input name="name_en" id="name_en" dojoType="dijit.form.TextBox" class='fullside' value='<?php echo $this->rs["title_en"];?>' >
							</div>
						</div>
						<div class="form-group">
					    	<label class="control-label col-md-4 col-sm-4 col-xs-12" for="first-name"><?php echo $tr->translate("PARENT");?> :
					    	</label>
					    <div class="col-md-8 col-sm-8 col-xs-12">
							<select name="parent" id="parent"  dojoType="dijit.form.FilteringSelect" class="fullside" >
								<option value=""></option>
								<?php if(!empty($this->parent)){foreach($this->parent as $parent){?>
								<option value="<?php echo $parent['id']?>"><?php echo $parent['name']?></option>
								<?php }}?>
							</select>
					    </div>
	                </div>
						<div class="form-group">
							<label  class="col-md-12 col-md-offset-4 col-md-8">
								<button type="submit" name="save_close" value="saveclose" class="btn btn-primary" ><i class="glyphicon glyphicon-log-in"></i> <?php echo $tr->translate("SAVE_CLOSE")?></button>
							</label>
						</div>
					</div>
				</div>
			</form>
		</div>
	</div>
</div>