<title>Detail User Right</title>
<style>
fieldset.fifthy {	border-right: 0px;width: 30%;}
fieldset.fifthy table{padding-right: 1px;}
table.user td{vertical-align: top;}
</style>       
<?php 
	 $rs=$this->rs;
	 $acl_name=($this->acl_name=='')? array(): $this->acl_name;
	 $tr = Application_Form_FrmLanguages::getCurrentlanguage();
?>
<?php $df = $this->datafiter;?>
<style>
	.pointer{
		cursor: pointer;	
	}
</style>
<script>
	$(function(){		
		$('#fmod').val('<?php echo $df['fmod']?>');
		$('#fcon').val('<?php echo $df['fcon']?>');
		$('#fact').val('<?php echo $df['fact']?>');
		$('#fstatus').val('<?php echo $df['fstatus']?>');
	});

	function changeStatus(id, user_type){
		url = "<?php echo BASE_URL;?>/rsvacl/useraccess/update-status";
		status = "no";
		none_src = "<?php echo BASE_URL?>/images/icon/none.png";
		tick_src = "<?php echo BASE_URL?>/images/icon/tick.png";

		if( $("#img_" + id).attr("src") == tick_src){
			status = "yes";
		}
		
		$.post( url, { 'acl_id': id, 'status': status, 'user_type_id':user_type},
	      function( data ) {
		     
			 img_src = none_src;
	         if(data == "yes"){
				img_src = tick_src;
	         }	         
	         $("#img_" + id).attr("src", img_src);
	      }
	    );
	}
</script>
<meta charset="utf-8" />
<div class="card pb-10 pt-10 pl-10 pr-10">
	<div class="card-content">
		<div class="card-box">
            <div class="col-sm-12 border-botom">
		    	<div class="col-sm-8 pd-0">
		    		<h4 class="m-b-0"><i class="fa fa-cube" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('USER_ACCESS');?> (<?php echo $rs[0]['user_type'];?>) </h4>
    			</div>
    			<div class="col-sm-4 text-right"></div>
    		</div>
    	</div>
	</div>
</div>
<?php 
	$old_module='';
?>
<div class="col-xs-3"> 
	    <ul class="nav nav-tabs tabs-left">
		    <?php 
		    if(!empty($this->rows))foreach($this->rows as $key =>$rs){
		    	if($old_module!= $rs['module']){ ?>
		      		<li <?php if($key==0){echo"class='active'";}?>><a href="<?php echo "#".$rs['module'];?>" data-toggle="tab"><?php echo $tr->translate(strtoupper($rs['module']));?></a></li>
		     	<?php 
		    	}
		    	$old_module = $rs['module'];
		    }
		    ?>
	    </ul>
</div>	   
   <div class="col-xs-9">
	    <div class="tab-content">
		      <?php $old_module='';
		      if(!empty($this->rows))foreach($this->rows as $key =>$rs){
		     	 if($old_module!= $rs['module']){?>
			      	<?php if( $key>0){?>
			      		</table>
			      	     </div>
		      		<?php }?>
			      	<div class="tab-pane <?php if($key==0){echo"active";}?>" id="<?php echo $rs['module'];?>">
			      		<table width="100%" border="1" style="white-space: nowrap;border: 1px solid #ccc;border-collapse: collapse;font-size: 13px;">
							<tr align="center" style="background: #bcd5f0;">
								<td width="45%">
									<?php echo $tr->translate("USER_ACCESS");?>
								</td>
								<td width="45%">
									<?php echo $tr->translate("URL");?>
								</td>
								<td width="10%">
									<?php echo $tr->translate("STATUS");?>
								</td>
							</tr>
			      <?php }?>
			     <tr>
			     	<td><?php if($rs['is_menu']==1){echo "<strong>".$tr->translate($rs['label'])."</strong>";}else{echo "&nbsp;&nbsp;&nbsp;".$tr->translate($rs['label'])."</strong>";}?></td>
			     	<td><?php echo $rs['url'];?></td>
			     	<td><?php echo $rs['img'];?></td>
			     </tr>
		      <?php 
		       $old_module = $rs['module'];
			  }?>
			</table>
		   </div>
	   </div>