<?php 
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$form=$this->form_purchase;
	$url_submit = $this->url(array('module'=>'purchase','controller'=>'index','action'=>'add'));
?>
<title><?php echo $tr->translate("RECEIVED_ITEM");?></title>
<div class="card pb-10 pt-10 pl-10 pr-10">
	<div class="card-content">
		<div class="card-box">
            <div class="col-sm-12 border-botom">
		    	<div class="col-sm-8 pd-0">
		    		<h4 class="m-b-0"><i class="fa fa-cube" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('RECEIVED_ITEM');?></h4>
    			</div>
    			<div class="col-sm-4 text-right"></div>
    		</div>
    	</div>
		<div class="card-box">
			<form dojoType="dijit.form.Form" class="form-horizontal" enctype="multipart/form-data" method="post">
				<script type="dojo/method" event="onSubmit">			
					loadingBlock();
				</script>
				<div class="col-md-4">
					<div class="form-group">
						<div class="col-md-4">
							<?php echo $tr->translate("BRANCH");?> :
						</div>
						<div class="col-md-8">
							<?php echo $form->getElement("branch");?>
						</div>
					</div>
					<div class="form-group">
						<div class="col-md-4">
							<?php echo $tr->translate("VENDOR_NAME");?>
						</div>
						<div class="col-md-8">
							<?php echo $form->getElement("vendor");?>
						</div>
					</div>
					<div class="form-group">
						<div class="col-md-4">
							<?php echo $tr->translate("PURCHASE_ORDER");?> 
						</div>
						<div class="col-md-8">
							<?php echo $form->getElement("pu_code");?>
							<input type="hidden" name="branch_id" id="branch_id" />
						</div>
					</div>
					<div class="form-group">
						<div class="col-md-4"><?php echo $tr->translate("RECEIVE_NO");?></div>
						<div class="col-md-8">
							<?php echo $form->getElement('recieve_no');?>
						</div>
					</div>
					<div class="form-group">
						<div class="col-md-4">
							<?php echo $tr->translate("ORDER_DATE");?>
						</div>
						<div class="col-md-8">
							<?php echo $form->getElement('date_order');?>
						</div>
					</div>
					<div class="form-group">
						<div class="col-md-4">
							<?php echo $tr->translate("RECEIVE_DATE");?> 
						</div>
						<div class="col-md-8">
							<?php echo $form->getElement('date_in');?>
						</div>
					</div>
					<div class="form-group">
						<div class="col-md-4">
							<?php echo $tr->translate("REMARK");?>
						</div>
						<div class="col-md-8">
							<?php echo $form->getElement("remark");?>
						</div>
					</div>
					<div class="form-group">
						<div class="col-md-4">
							<?php echo $tr->translate("Date Input");?>
						</div>
						<div class="col-md-8">
							<?php echo $form->getElement('date_recieve');?>
							<input type="hidden" name="commission" id="commission" value="<?php echo $this->po['commission']?>" />
							<input type="hidden" name="commission_ensur" id="commission_ensur" value="<?php echo $this->po['commission_ensur']?>" />
							<input type="hidden" name="net_total" id="net_total" value="<?php echo $this->po['all_total']?>" />
						</div>
					</div>
				</div>
				<div class="col-md-8">
					<table class="table table-striped table-bordered table-hover" id="table_order" style="font-size:12px;">
						<tr height="33px">
							<td><?php echo $tr->translate("NUM");?></td>
							<td style="white-space:nowrap;"><?php echo $tr->translate("ITEM_NAME");?></td>
							<td><?php echo $tr->translate("QTY_ORDER");?></td>
							<td><?php echo $tr->translate("RECIEVE_UNIT");?></td>
							<td><?php echo $tr->translate("RECIEVE_PER_UNIT");?></td>
							<td><?php echo $tr->translate("QTY_RECIEVE");?></td>
							<td><?php echo $tr->translate("REMARK");?></td>
						</tr>
					 </table>
					<div class="form-group">
						<input type="hidden" id="identity" name="identity" />
						<?php echo $form->getElement("payment_name");?>
						<?php echo $form->getElement("totalAmoun");?>
						<?php echo $form->getElement("totalAmoun_after");?>
						<?php echo $form->getElement("currency");?>
						<?php echo $form->getElement("dis_value");?>
						<?php echo $form->getElement("total_tax");?>
						<?php echo $form->getElement("all_total");?>
						<?php echo $form->getElement("all_total_after");?>
						<?php echo $form->getElement("paid");?>
						<?php echo $form->getElement("global_disc");?>
						<?php echo $form->getElement("remain");?>
						<?php echo $form->getElement("remain_after");?>
					</div>
				</div>
				  <div class="card-box">
						<div class="border-top">
							<div class="col-md-4"></div>
							<div class="col-md-5" class='center'>
								<input type="submit" value="btnsavenew" id="btnsavenew" name="save_close" label="<?php echo $tr->translate("SAVE_NEW")?>" dojoType="dijit.form.Button" 
								iconClass="dijitEditorIcon dijitEditorIconSave" />
							</div>
							<div class="col-md-3"></div>
						</div>
					</div>
				</form>
			</div>
		</div>
	</div>
<script>
$(document).ready(function() {
	initList();
	$('#pu_code').attr("readOnly",true); 
	$('#vendor').attr("readOnly",true); 
});
index=0;
function initList() {
	index5=0;
	var template;
	var option5 = '<?php echo $this->items;?>';
	<?php if(!empty($this->item)) {
		foreach($this->item AS $i=>$r){?>
	index5++; 
	index=index+1;
	item_name='<?php echo preg_replace("/'/", "\&#39;", $r['item_name']);?>';
		
	template='<tr id="row_order_'+index5+'" style="height:33px;">';
	var inp = '';
	template+='<td  width="1%">'+index5+'</td>';
	template+='<td width="30%">'+item_name+'<input type="hidden" name="item_id_'+index5+'" id="item_id_'+index5+'" /></td>';
	template+='<td ><input type="text" class="form-control" required="1" readOnly="readOnly" value="" id="qty_order_'+index5+'" name="qty_order_'+index5+'" /></td>';
	template+='<td ><input type="text" readOnly="readOnly" onkeyup="doTotalQty('+index5+')" class="validate[required,custom[number]] input form-control" required="1" value="1" id="qty_unit_'+index5+'" name="qty_unit_'+index5+'" /></td>';
	template+='<td ><input type="text" readOnly="readOnly" onkeyup="doTotalQty('+index5+')" class="validate[required,custom[number]] input form-control" value="0" id="qty_per_unit_'+index5+'" name="qty_per_unit_'+index5+'" /><input type="hidden" name="unit_measure_'+index5+'" id="unit_measure_'+index5+'" /></td>';
	template+='<td ><input type="text" class="validate[required,custom[number]] input form-control" onKeyup="calculatePrice('+index5+')" readOnly="readOnly" value="" id="qty_recieve_'+index5+'" name="qty_recieve_'+index5+'" /></td>';
	template+='<td ><input type="hidden" name="cost_price'+index5+'" id="cost_price'+index5+'" value="" /> <input type="text" class="form-control" id="remark_'+index5+'" name="remark_'+index5+'" /> <input type="hidden" name="price_'+index5+'" id="price_'+index5+'" value="" /> <input type="hidden" name="total_after_'+index5+'" id="total_after_'+index5+'" value="" /><input type="hidden" name="total_'+index5+'" id="total_'+index5+'" value="" /><input type="hidden" value="" id="dis_value'+index5+'" name="dis_value'+index5+'" class="form-control" /><input type="hidden" name="sub_total_receive_'+index5+'" id="sub_total_receive_'+index5+'" /> </td>';
	template+="</tr>";
	$('#table_order').append(template);
	<?php 
		$cost_price =$r['sub_total']+(($r['sub_total']*($this->po['commission_ensur']+$this->po['commission']))/$this->po['all_total']);
	?>
	$("#cost_price"+index5).val("<?php echo number_format($cost_price,2);?>");
	$("#qty_recieve_"+index5).val("<?php echo $r['qty_order'];?>");
	$("#item_id_"+index5).val("<?php echo $r['pro_id'];?>");
	$("#qty_order_"+index5).val("<?php echo $r['qty_order'];?>");
	$("#qty_unit_"+index5).val("<?php echo $r['qty_unit'];?>");
	$("#qty_per_unit_"+index5).val("<?php echo $r['qty_detail'];?>");
	$("#qty_recieve_"+index5).val("<?php echo $r['qty_order'];?>");
	$("#total_after_"+index5).val("<?php echo $r['sub_total'];?>");
	$("#sub_total_receive_"+index5).val("<?php echo $r['sub_total'];?>");
	$("#total_"+index5).val("<?php echo $r['sub_total'];?>");
	$("#price_"+index5).val("<?php echo $r['price'];?>");
	$("#oldprice_"+index5).val("<?php echo $r['price'];?>");
	$("#dis_value"+index5).val("<?php echo $r['disc_value'];?>");
	$("#unit_measure_"+index5).val("<?php echo $r['qty_perunit'];?>");
	if($('#identity').val()!="") {
		var identity = $('#identity').val();
		$('#identity').val(identity+','+index5);
	} else {$('#identity').val(index5);}
	<?php } }?>
}

function doTotalQty(index){
	main_qty =$("#qty_unit_"+index).val();
	detail_qty =  $("#qty_per_unit_"+index).val();
	unit_measure = $("#unit_measure_"+index).val();
	total_qty = parseFloat(main_qty) + parseFloat(detail_qty/(unit_measure));
	$("#qty_recieve_"+index).val(total_qty.toFixed(3));
	dis_value =$("#dis_value"+index).val();
	total_price= parseFloat($('#sub_total_receive_'+index).val());
	commission_ensur = $('#commission_ensur').val();
	commission = $('#commission').val();
	total_commission = parseFloat(commission_ensur)+parseFloat(commission);
	all_total = parseFloat($('#net_total').val());
	cost_price = total_price+(total_price*total_commission/all_total);
	$('#cost_price'+index).val(cost_price.toFixed(2));
}
<?php $url_qty =  $this->url(array('module'=>'purchase','controller'=>'index','action'=>'getqtybyid')); ?>
function getQtyById(index){//use
		item_id=$("#item_id_"+index).val();
		qty_unit=$("#qty_unit_"+index).val();
		qty_per_unit=$("#qty_per_unit_"+index).val();
		if(qty_unit==null || qty_unit==""){
			if(qty_per_unit!==null && qty_per_unit!==""){
				$("#qty"+index).val(qty_per_unit);
			}
		}else{
			$.ajax({
				url:"<?php echo $url_qty;?>",
				type:"post",
				data:{'item_id':item_id},
				success: function(data){
					item_qty = $.parseJSON(data);			
					main_qty =$("#qty_unit_"+index).val();
					detail_qty =  $("#qty_per_unit_"+index).val();
					total_qty = parseFloat(main_qty) + parseFloat(detail_qty/(item_qty.qty_perunit));
					$("#qty"+index).val(total_qty.toFixed(3));
				},
				error:function(e){
				}
		});
	}
}

function deleteRecord(index) {
	var identity = $('#identity').val();
	var arrays = identity.split(',');
	for(var i=0;i<arrays.length;i++) {
		if(arrays[i] == index) arrays.splice(i,1);
	}
	var strings = arrays.join(',');
	$('#identity').val(strings);
	$("#row_order_"+index).remove();
	netTotal();
}
function netTotal() {//use
	var cur_type = $('#currency').val();
	var netTotal=0;
	var rowId = $('#identity').val();
	var rowIDArray = rowId.split(',');
	var status = $('#status').val();
	for(var n = 0; n < rowIDArray.length; n++) {
		netTotal += Number($('#total'+rowIDArray[n]).val());
	}
	$('#totalAmoun').val(netTotal.toFixed(2));
	calculateDiscount();
}
function calculateDiscount(){//use
	var discountValue = ($('#dis_value').val());
	if(discountValue==''){$('#dis_value').val(0);discountValue=0;}
	if(discountValue.length!=0){
		if(discountValue.indexOf("%")!==-1){
			var pds=discountValue.split("%");
		    alltotal = $("#totalAmoun").val();
			var discount=(alltotal*parseFloat(pds[0]))/100;
			totalpayment = alltotal - discount;
			$('#all_total').val(totalpayment);
		}else{
			alltotal = $("#totalAmoun").val();
			totalpayment = alltotal - discountValue;
			$('#all_total').val(totalpayment);
		}
		doRemain();
	}
}
function doRemain() {
	var all_total = $('#all_total').val();
	var paid = $('#paid').val();
	if(paid>all_total){
		alert("Paid Value can not biger then total amount !");
		 $('#remain').val(all_total.toFixed(2));
   }else{
	   remain = all_total-paid;
	   $('#remain').val(remain.toFixed(2));
	}
}
function totalQty(index){
	calculatePrice(index);
	getQtyById(index);
}
function calculatePrice(index){
	var qty = $('#qty_recieve_'+index).val();
	var price = $('#price_'+index).val();
	var total = price * qty;
	var ds = $('#dis_value'+index).val();
	if(ds.length!=0){
		if(ds.indexOf("%")!==-1){//if have %
			var pds=ds.split("%");
			if(!isNaN(pds[0])){
				var discount=(total*parseFloat(pds[0]))/100;
				after_discount = total - discount;
			}else{
				after_discount = total - discount;
			}
			$('#total_after_'+index).val(after_discount.toFixed(2));
		}else{
			if(!isNaN(ds)&&ds!=0){
				discount = parseFloat(ds).toFixed(2);
				after_discount = total - discount;
			}else{
				discount=$('#dis_value'+index).val(0);
				after_discount = total;
			}
			$('#total_after_'+index).val(parseFloat(after_discount).toFixed(2));
		}
		netTotal();
	}
}
function calculatePrice(index) {
	var qty = $('#qty_recieve_'+index).val();
	var price = $('#price_'+index).val();
	var total = price * qty;
	var ds = $('#dis_value'+index).val();
	if(ds.length!=0){
		if(ds.indexOf("%")!==-1){//if have %
			var pds=ds.split("%");
			if(!isNaN(pds[0])){
				var discount=(total*parseFloat(pds[0]))/100;
				after_discount = total - discount;
			}else{
				after_discount = total - discount;
			}
			$('#total_after_'+index).val(after_discount.toFixed(2));
		}else{
			if(!isNaN(ds)&&ds!=0){
				discount = parseFloat(ds).toFixed(2);
				after_discount = total - discount;
			}else{
				discount=$('#dis_value'+index).val(0);
				after_discount = total;
			}
			$('#total_after_'+index).val(parseFloat(after_discount).toFixed(2));
		}
		netTotal();
	}
}
function netTotal() {//use
	var cur_type = $('#currency').val();
	var netTotal=0;
	var rowId = $('#identity').val();
	var rowIDArray = rowId.split(',');
	var status = $('#status').val();
	for(var n = 0; n < rowIDArray.length; n++) {
		netTotal += Number($('#total_after_'+rowIDArray[n]).val());
	}
	$('#totalAmoun_after').val(netTotal.toFixed(2));
	$('#all_total_after').val(netTotal.toFixed(2));
	 doRemain();
}
function doRemain() {
	var all_total = $('#all_total_after').val();
	var paid = $('#paid').val();
	if(paid>all_total){
		alert("Paid Value can not biger then total amount !");
		 $('#remain_after').val(all_total.toFixed(2));
   }else{
	   remain = all_total-paid;
	   $('#remain_after').val(remain.toFixed(2));
	}
	
}

	dojo.require("dijit.form.DateTextBox");
</script>