<?php 
	$tr=Application_Form_FrmLanguages::getCurrentlanguage();
?>
<title><?php echo $tr->translate("RECEIVED_ITEM");?></title>
<div class="card pb-10 pt-10 pl-10 pr-10">
	<div class="card-content">
		<div class="card-box">
			<div id="divPrint" style="width: 100%;">
			<style>
				.style{
					line-height: 20px;font-size: 9px !important;
					font-family: 'Khmer OS Battambang';
				}
				ul{margin: 0;padding:0;}
				table tr td ul li{text-align: center;list-style: none;line-height: 25px; font-weight: bold;}
				th{}
				ul.pur_info li{line-height:18px; 
						font-weight: normal !important;}
				ul.pur_info li strong{font-weight: bold;}
		       .hover:hover{background: #ccc;}
			   .center{text-align:center;}
			</style>
				<table style="font-family: 'Khmer OS Content'; width:100%;">
					<tbody>
					<tr>
				    	<td align="center">
				        	<table width="100%" style="font-family: 'Khmer OS Battambang';" cellpadding="0" cellpadding="0">
				            	<tbody>
									<tr>
										<td width="20%" valign="top"></td>
										<td width="60%" valign="top">
											<ul>
												<li style="text-align:center; font-size:20px; font-family:'Khmer MEF2'"><?php echo $this->title_reprot["title_report_kh"]?></li>
												<li style="text-align:center; font-size:20px; font-family:'Khmer MEF2'"><?php echo $this->title_reprot["title_report_en"]?></li>
												<li style="text-align:center; font-size:18px; font-family:'Khmer MEF2'">បណ្ណ័ទទួលទិញទំនិញ</li>
											</ul>
										</td>
										<td width="20%"></td>
									</tr> 
				                	<tr>
					                	<td colspan="3" valign="top">
					                		<table width="100%" cellpadding="0" cellspacing="0">
					                			<tbody>
					                			<tr>
					                				<td style="font-size: 12px;" valign="top" width="30%;">
														<div style="padding-left: 10px;width:100%; background: #244456;display: block;color:#fff;font-size:15px !important;">&nbsp;&nbsp;<?php echo $tr->translate("VENDOR_INFO");?></div>
														<table width="100%" style="font-size: 12px; font-weight:600;">
															<tr style="line-height:20px;">
																<td style="text-align: left;white-space: nowrap;"><?php echo $tr->translate("VENDOR_NAME");?> :</td>
																<td style="text-align: right;white-space: nowrap;"><?php echo $this->product[0]['vendor_name'];?></td>
															</tr>
															<tr style="line-height:20px;">
																<td style="text-align: left;white-space: nowrap;"><?php echo $tr->translate("CONTACT_NAME");?> :</td>
																<td style="text-align: right;white-space: nowrap;"><?php //echo $this->product[0]['contact_name'];?></td>
															</tr>
															<tr style="line-height:20px;">
																<td style="text-align: left;white-space: nowrap;"><?php echo $tr->translate("CONTACT_NUM");?> :</td>
																<td style="text-align: right;white-space: nowrap;"><?php echo $this->product[0]['v_phone'];?></td>
															</tr>
															<tr style="line-height:20px;">
																<td style="text-align: left;white-space: nowrap;"><?php echo $tr->translate("ADDRESS");?> :</td>
																<td style="text-align: right;white-space: nowrap;"><?php echo $this->product[0]['add_name'];?></td>
															</tr>
														</table>
													</td>
													<td width="5%"></td>
					                				<td width="30%" style="text-align: left;font-size: 12px;" valign="top">
														<div style="padding-left: 10px;width:100%; background: #244456;display: block;color:#fff; font-size:15px !important;">&nbsp;&nbsp;<?php echo $tr->translate("PURCHASE_INFO");?></div>
														<table width="100%" style="font-size: 12px; font-weight:600;">
															<tr style="line-height:20px;">
																<td style="text-align: right;white-space: nowrap;"><?php echo $tr->translate("PO_NUM");?> :</td>
																<td style="text-align: right;white-space: nowrap;"><?php echo $this->product[0]['po_no'];?></td>
															</tr>
															<tr style="line-height:20px;">
																<td style="text-align: right;white-space: nowrap;"><?php echo $tr->translate("ORDER_DATE");?> :</td>
																<td style="text-align: right;white-space: nowrap;"><?php echo date("d/m/Y",strtotime($this->product[0]['date_order']));?></td>
															</tr>
															<tr style="line-height:20px;">
																<td style="text-align: right;white-space: nowrap;"><?php echo $tr->translate("RECEIVE_NO");?> :</td>
																<td style="text-align: right;white-space: nowrap;"><?php echo $this->product[0]['recieve_number'];?></td>
															</tr>
															<tr style="line-height:20px;">
																<td style="text-align: right;white-space: nowrap;"><?php echo $tr->translate("RECEIVE_DATE");?> :</td>
																<td style="text-align: right;white-space: nowrap;"><?php echo date("d/m/Y",strtotime($this->product[0]['date_in']));?></td>
															</tr>
														</table>
													</td>
					                			</tr>
							                </tbody>
							              </table>
							            </td>
						           </tr>   
				            </tbody>
				          </table>
				        </td>
				    </tr>
				    <tr>
				    	<td>
				            <table border="1" style="border-collapse:collapse;border:1px solid #000; font-size:12px; margin-top:10px;" width="100%" cellspacing="0">
				                 <tbody>
								 <tr style="background:#a8aeff;text-align: center !important;">
									<th width="3%" style="text-align: center !important;">&nbsp;<?php echo $tr->translate("NUM");?></th>
									<th style="text-align: center !important;"><?php echo $tr->translate("ITEM_CODE");?></th>
									<th style="text-align: center !important;"><?php echo $tr->translate("ITEM_NAME");?></th>
									<th style="text-align: center !important;">&nbsp;<?php echo $tr->translate("QTY_ORDER");?></th>
									<th style="text-align: center !important;">&nbsp;<?php echo $tr->translate("QTY_RECEIVE");?></th>
									<th style="text-align: center !important;">&nbsp;<?php echo $tr->translate("MEASURE");?></th>
								</tr>
								<?php 
									if(!empty($this->product)){ $total = 0;  foreach($this->product as $key=>$rs){$index = $key+1; //$total=$total+$rs["price"]*$rs["qty_receive"];
									$count = count($this->product);
								?>
									<tr>
										<td class="center"><?php echo $index;?></td>
										<td>&nbsp;&nbsp;<?php echo $rs["item_code"];?>&nbsp;&nbsp;</td>
										<td>&nbsp;&nbsp;<?php echo $rs["item_name"];?>&nbsp;&nbsp;</td>
										<td><?php echo $rs["qty_order"];?></td>
										<td>&nbsp;&nbsp;<?php echo $rs["qty_receive"];?>&nbsp;&nbsp;</td>
										<td>&nbsp;&nbsp;<?php echo $rs["measure"];?>&nbsp;&nbsp;</td>
									</tr>
								<?php }}?>
								<?php if($count<10){
										$count_i = 10-$count;
										for($i=1;$i<=$count_i;$i++){
								?>
									<tr>
										<td class="center"><?php echo $index+$i; ?></td>
										<td></td>
										<td></td>
										<td></td>
										<td></td>
										<td></td>
									</tr>
								<?php }}?>
				                </tbody>
				           </table>
				              <br>
				              <table align="center" width="100%" >
								   <tbody>
								   <tr style="font-size: 12px;">
								        <th style="width:20%;text-align:center; font-family:'Khmer MEF2'">ប្រធានឃ្លាំង</th>
								        <th></th>
								        <th style="width:20%;text-align:center; font-family:'Khmer MEF2'">អ្នកប្រគល់</th>
								        <th></th>
								        <th style="width:20%;text-align:center; font-family:'Khmer MEF2'">ប្រធានផ្នែក</th>
										<th></th>
								        <th style="width:20%;text-align:center; font-family:'Khmer MEF2'">អ្នកទទួល</th>
								   </tr>
								    <tr style="font-size: 12px; height: 75px;">
								        <td valign="bottom" style="width:20%;text-align:center;  font-family:'Khmer MEF2'; white-space: nowrap;">ឈ្មោះ  /Name--------------------------</td>
								        <td></td>
								        <td valign="bottom" style="width:20%;text-align:center; font-family:'Khmer MEF2';white-space: nowrap;">ឈ្មោះ  /Name--------------------------</td>
								        <td></td>
								        <td valign="bottom" style="width:20%;text-align:center;font-family:'Khmer MEF2';white-space: nowrap;">ឈ្មោះ  /Name--------------------------</td>
										<td></td>
								        <td valign="bottom" style="width:20%;text-align:center;font-family:'Khmer MEF2';white-space: nowrap;">ឈ្មោះ  /Name--------------------------</td>
								   </tr>
								   <tr style="font-size: 12px; height: 50px;">
								        <td style="width:20%;text-align:center;white-space: nowrap;">ថ្ងៃ  /Date:----------------------------------</td>
								        <td></td>
								        <td style="width:20%;text-align:center;white-space: nowrap;">ថ្ងៃ  /Date:----------------------------------</td>
								        <td></td>
								        <td style="width:20%;text-align:center;white-space: nowrap;">ថ្ងៃ  /Date:----------------------------------</td>
										<td></td>
								        <td style="width:20%;text-align:center;white-space: nowrap;">ថ្ងៃ  /Date:----------------------------------</td>
								   </tr>
								</tbody>
							</table>	
				    		</td>
				    	</tr>
					</tbody>
				</table>
			</div>
	 	 </div>		
	</div>
</div>
<iframe name=print_frame width=0 height=0 frameborder=0 src=about:blank></iframe>
<script>
function doPrint() {
	window.frames["print_frame"].document.body.innerHTML=document.getElementById('divPrint').innerHTML;
    window.frames["print_frame"].window.focus();
    window.frames["print_frame"].window.print();
}
</script>