<?php 
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$formFilter = $this->frmAdd;
?>
<title><?php echo $tr->translate("ADD_TERMCONDICTION");?></title>
<div class="card pb-10 pt-10 pl-10 pr-10">
	<div class="card-content">
		<div class="card-box">
			<form dojoType="dijit.form.Form"  class="form-horizontal" method="post" >
				<script type="dojo/method" event="onSubmit">			
					if(this.validate()) {
               			loadingBlock();
						return true;
					}else{
						return false;
					}
				</script>
				<div class="form-body ">
					<div class="form-group">
						<label class="col-md-2 control-label"><?php echo $tr->translate("NAME_KH");?></label>
						<div class="col-md-8">
							<?php echo $formFilter->getElement('name_kh');?>
						</div>
					</div>
					<div class="form-group">
						<label class="col-md-2 control-label"><?php echo $tr->translate("NAME_EN");?></label>
						<div class="col-md-8">
							<?php echo $formFilter->getElement('name_en');?>
						</div>
					</div>
					<div class="form-group">
						<label class="col-md-2 control-label"><?php echo $tr->translate("TYPE");?></label>
						<div class="col-md-8">
							<?php echo $formFilter->getElement('type');?>
						</div>
					</div>
					
					<div class="form-group">
						<label class="col-md-2 control-label"><?php echo $tr->translate("STATUS");?></label>
						<div class="col-md-8">
							<?php echo $formFilter->getElement('status');?>
						</div>
					</div>
				<div class="form-group">
					<label  class="col-md-12 col-md-offset-4 col-md-8">
						<button type="submit" name="save_close" value="saveclose" class="btn btn-primary" ><i class="glyphicon glyphicon-log-in"></i> <?php echo $tr->translate("SAVE_CLOSE")?></button>
					</label>
				</div>
				</div>
			</form>
		</div>
	</div>
</div>