<?php 					
	$url_new = $this->url(array('module'=>'sales','controller'=>'termcondiction','action'=>'add',));
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$formFilter = $this->formFilter;
?>
<title><?php echo $tr->translate("TERMCONDICTION_LIST");?></title>
<div class="card pb-10 pt-10 pl-10 pr-10">
	<div class="card-content">
		<div class="card-box">
			<?php echo $this->list;?>
		</div>
	</div>
</div>