<?php 
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$user_info = new Application_Model_DbTable_DbGetUserInfo();
	$result = $user_info->getUserInfo();
	$db = new Application_Model_DbTable_DbUsers();
	$report_url = $db->getArrAclReport($result['level'],'index');
?>
<div class="row">
	 <?php
   	   if(!empty($report_url)){
   	   foreach($report_url as $url){
   	   if($url['action']=='index' OR $url['action']=='receipt' OR $url['action']=='rpt-updatepayment' OR $url['action']=='updatereceipt' or $url['action']=='quotadetail'){continue;}
   	   	?>
        <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
			<div class="dashboard-stat blue-madison">
				<a class="more" href="<?php echo $this->url(array('module'=>$url['module'],'controller'=>$url['controller'],'action'=>$url['action'])); ?>">
			<div class="visual">
				<i class="fa fa-comments"></i>
			</div>
			<div class="details">
				<div class="number">
				</div>
				<div class="desc">
					<?php echo $tr->translate($url['label']);?>
					</div>
				</div>
				</a>
				<a class="more" href="javascript:;">
				View more <i class="m-icon-swapright m-icon-white"></i>
				</a>
			</div>
		</div>
        <?php }
	}?>
</div>