<?php 
$tr=Application_Form_FrmLanguages::getCurrentlanguage();
$frm_sales_report = $this->form_search;
?>
<title>Sale Item Detail Report</title>
<div class="card pb-10 pt-10 pl-10 pr-10">
	<div class="card-content">
		<div class="card-box">
			<form method="post" autocomplete="off">
				<div class="form-group" >
					<div class="control-label col-md-3"><?php echo $frm_sales_report->getElement("txt_search");?></div>
					<div class="control-label col-md-3"><?php echo $frm_sales_report->getElement("branch_id");?></div>
					<div class="control-label col-md-3"><?php echo $frm_sales_report->getElement('customer_id');?></div>
					<div class="control-label col-md-3"><?php echo $frm_sales_report->getElement("category_id");?></div>
				</div>
				<div class="form-group" >
					<div class="control-label col-md-3"><?php echo $frm_sales_report->getElement('item');?></div>
					<div class="control-label col-md-3"><?php echo $frm_sales_report->getElement('start_date');?></div>
					<div class="control-label col-md-3"><?php echo $frm_sales_report->getElement("end_date");?></div>
					<div class="control-label col-md-3">
						<input type="submit" value="btnsavenew" id="btnsavenew" name="save_close" label="<?php echo $tr->translate("REFRESH")?>" dojoType="dijit.form.Button" 
							iconClass="dijitIconSearch" />
				</div>
			</form> 
			<div id="divPrint" style="width: 100%;">
			<style>
				.style{
					line-height: 25px;font-size: 12px !important;
					font-family: 'Khmer OS Battambang';
				}
				ul{margin: 0;padding:0;}
				table tr td ul li{text-align: center;list-style: none;line-height: 25px; font-weight: bold;}
				th{padding: 5px;}
				.hover:hover{background: #ccc;}
			</style>
		<table style="font-family: 'Khmer OS Content'; width:100%;">
			<tbody>
				<tr>
			    	<td align="center">
	                	<ul>
	                		<li style="text-align:center; font-size:16px; font-family:'Khmer OS Muol Light'">របាយការណ៏ លក់លម្អិត</li>
	                		<li style="text-align:center; font-size:14px;"><?php echo date("d/m/Y",strtotime($this->rssearch['start_date']));?> ដល់ <?php echo date("d/m/Y",strtotime($this->rssearch['end_date']));?></li>
	                	</ul>
			        </td>
			    </tr>
			    <tr>
			    	<td class="table2excel" id="exportExcel">
			            <table border="1"  style="border-collapse:collapse;border:1px solid #000; font-size:12px;" width="100%" cellspacing="0">
			               <tbody>
			                 <tr bgcolor="#ccc" class="style" align="center" style="font-weight:bold; line-height: 25px; font-size:12px; padding:1px 0px; white-space: nowrap; ">
			                    <td>&nbsp;<?php echo $tr->translate("NUM");?></td>
			                    <td><?php echo $tr->translate("BRANCH_NAME");?></td>
								<td>&nbsp;<?php echo $tr->translate("CUSTOMER_NAME");?></td>
								<td>&nbsp;<?php echo $tr->translate("INVOICE_NO");?></td>
								<td width="10%">&nbsp;<?php echo $tr->translate("ORDER_DATE");?></td>
								<td><?php echo $tr->translate("CATE_NAME");?></td>
								<td><?php echo $tr->translate("ITEM_NAME");?></td>
								<td>&nbsp;<?php echo $tr->translate("QTY");?></td>
								<td>&nbsp;<?php echo $tr->translate("COST_PRICE");?></td>
								<td>&nbsp;<?php echo $tr->translate("សរុបថ្លៃដើម");?></td>
								<td width="10%">&nbsp;<?php echo $tr->translate("ITEM_PRICE");?></td>
								<td><?php echo $tr->translate("TOTAL");?></td>
								<td><?php echo $tr->translate("TOTAL_INCOME");?></td>
			                </tr>
			                <?php 
			                	$num=1; 
			                	$total_sale = 0;
			                	$total_cost = 0;
			                	$d_balance = 0;
			                	$total_netincome = 0;
			                if(!empty($this->product_rs))foreach ($this->product_rs AS $index => $rs){?>
								<tr class='row-format<?php echo $num; $num=1-$num;?> hover' style="border:1px solid #000;">
								   <td align="center" style="white-space: nowrap;">&nbsp;<?php echo $index+1?></td>
								   <td style="white-space: nowrap;">&nbsp;<?php echo $rs["branch_name"];?></td>
								   <td style="white-space: nowrap;">&nbsp;<?php echo $rs["customer_name"];?></td>
								   <td style="white-space: nowrap;">&nbsp;<?php echo $rs["sale_no"];?></td>
								   <td style="white-space: nowrap;">&nbsp;<?php echo date("d/m/Y",strtotime($rs["date_sold"]));?></td>
								   <td style="white-space: nowrap;">&nbsp;<?php echo $rs["cate_name"];?></td>
								   <td style="white-space: nowrap;">&nbsp;<?php echo $rs["item_name"];?></td>
								   <td style="white-space: nowrap;">&nbsp;
									   <?php 
										   $raw_qty = $rs["qty_order"];
										   $array = explode(".",$rs["qty_order"]);
										   $qty = $array[0];
										   $qty_unit = ($raw_qty*$rs["qty_perunit"]) - ($rs["qty_perunit"]*$array[0]);
										   $l_qty = 0;
										   if($raw_qty>0){
											   	if($qty>0 and $qty_unit>0){
											   		$l_qty = $qty." ".$rs["measue_name"]." និង ".round($qty_unit)." ".$rs["unit_label"];
											   	}elseif($qty==0 and $qty_unit>0){
											   		$l_qty = round($qty_unit)." ".$rs["unit_label"];
											   	}elseif($qty>0 and $qty_unit==0){
											   		$l_qty =  $qty." ".$rs["measue_name"];
											   	}
										   }else{
										   		$l_qty = 0;
										   }
											echo $l_qty;
											$net_income = ($rs["price"]-$rs["cost_price"])*$rs["qty_order"];
											$total_netincome = $total_netincome+$net_income;
									 ?>
								   </td>
								   <td style="white-space: nowrap;background: #ccc;">&nbsp;<?php echo $rs["cost_price"];?></td>
								   <td style="white-space: nowrap;background: #ccc;">&nbsp;<?php echo number_format($rs["cost_price"]*$raw_qty,2);?></td>
								   <td>&nbsp;<?php echo number_format($rs["price"],2);?></td>
								   <td>&nbsp;<?php echo number_format($rs["sub_total"],2);?></td>
								   <td>&nbsp;<?php echo number_format($net_income,2);?></td>
								 </tr>
							   <?php 
								$total_sale = $total_sale+$rs["sub_total"];
								$total_cost = $total_cost+($rs["cost_price"]*$raw_qty);
	                    	 }?>
			                </tbody>
			           </table>
			            <br>
			             <table border="1" style="border-collapse:collapse;border:1px solid #000; font-size:12px;" width="100%" cellspacing="0">
			                <tbody>
				                <tr height="30px;" bgcolor="#ccc" class="style" align="center" style="floafont-weight:bold; line-height: 14px; font-size:12px; padding:2px 0px; ">
				                    <td><strong><?php echo $tr->translate("សរុបថ្លៃដើម");?></strong></td>
				                    <td><strong><?php echo $tr->translate("សរុបចំណូលលក់បាន");?></strong></td>
				                    <td><strong><?php echo $tr->translate("TOTAL_INCOME");?></strong></td>
				                </tr>
				                <tr class="style" style=" line-height: 24px; font-size:11px;">
				                	<td>&nbsp;<?php echo number_format($total_cost,2);?>&nbsp;</td>
				                    <td>&nbsp;<?php echo number_format($total_sale,2);?>&nbsp;</td>
				                    <td>&nbsp;<?php echo number_format($total_sale-$total_cost,2);?>&nbsp;</td>
				                 </tr>
			               </tbody>
			             </table>
			             <br>
			             	<?php echo $this->getFooter;?>	
			    		</td>
			    	</tr>
			</tbody>
		</table>
		</div>
	  </div>		
	</div>
</div>
<iframe name=print_frame width=0 height=0 frameborder=0 src=about:blank></iframe>
<script>
	function doPrint() {var divToPrint = document.getElementById('divPrint');var htmlToPrint = '' +'<style type="text/css">' +'</style>';htmlToPrint += divToPrint.outerHTML;window.document.write(htmlToPrint);window.print();window.close();}
	dojo.require("dijit.form.DateTextBox");
</script>