<?php 
$tr=Application_Form_FrmLanguages::getCurrentlanguage();
$frm_sales_report = $this->form_search;
?>
<title><?php echo $tr->translate("RPT_PRODUCT_SOLD");?></title>
<div class="card pb-10 pt-10 pl-10 pr-10">
	<div class="card-content">
		<div class="card-box">
			<form method="post" autocomplete="off">
				<div class="form-group" style="padding-top: 6px;">
					<div class="col-md-3"><?php echo $frm_sales_report->getElement("txt_search");?></div>
					<div class="col-md-3"><?php echo $frm_sales_report->getElement("branch_id");?></div>
					<div class="col-md-3"><?php echo $frm_sales_report->getElement('brand_id');?></div>
					<div class="col-md-3"><?php echo $frm_sales_report->getElement("category_id");?></div>
				</div>
				<div class="form-group" style="padding-top: 6px;">
					<div class="col-md-3"><?php echo $frm_sales_report->getElement('item');?></div>
					<div class="col-md-3"><?php echo $frm_sales_report->getElement('start_date');?></div>
					<div class="col-md-3"><?php echo $frm_sales_report->getElement("end_date");?></div>
					<div class="col-md-3">
						<input type="submit" value="btnsavenew" id="btnsavenew" name="save_close" label="<?php echo $tr->translate("REFRESH")?>" dojoType="dijit.form.Button" 
							iconClass="dijitIconSearch" />
					</div>
				</div>
			</form> 
	<div id="divPrint" style="width: 100%;">
	<style>
		.style{
			line-height: 25px;font-size: 12px !important;
			font-family: 'Khmer OS Battambang';
		}
		ul{margin: 0;padding:0;}
		table tr td ul li{text-align: center;list-style: none;line-height: 25px; font-weight: bold;}
		th{padding: 5px;}
		.hover:hover{background: #ccc;}
		table { page-break-inside:auto }
		  tr{ page-break-inside:avoid; page-break-after:auto; }
		#header {
		  display: table-header-group;
		  page-break-inside:avoid; page-break-after:auto;
		}
	</style>
		<table style="font-family: 'Khmer OS Content'; width:100%;">
			<tbody>
			<tr>
		    	<td align="center">
		        	<table width="100%" style="font-family: 'Khmer OS Battambang';" cellpadding="0" cellpadding="0">
		            	<tbody><tr>
		                	<td width="20%" valign="top"></td>
		                	<td width="60%" valign="top">
		                		<ul>
		                			<li style="text-align:center; font-size:16px; font-family:'Khmer OS Muol Light'"><?php echo $tr->translate("COMPANY_CUSTOMER");?></li>
		                			<li style="text-align:center; font-size:16px; font-family:'Khmer OS Muol Light'"><?php echo $tr->translate("RPT_PRODUCT_SOLD");?></li>
		                			<li style="text-align:center; font-size:16px;"><?php echo date("d/m/Y",strtotime($this->rssearch['start_date']));?> ដល់ <?php echo date("d/m/Y",strtotime($this->rssearch['end_date']));?></li>
		                		</ul>
		                	</td>
		                    <td width="20%"></td>
		                </tr> 
		                <tr>
		                	<td colspan="3" valign="top"></td>
				           </tr>   
		            </tbody></table>
		        </td>
		    </tr>
		    <tr>
		    	<td class="table2excel" id="exportExcel">
		            <table border="1" style="border-collapse:collapse;border:1px solid #000; font-size:12px;" width="100%" cellspacing="0">
		                 <thead><tr bgcolor="#ccc" class="style" align="center" style="font-weight:bold; line-height: 25px; font-size:12px; padding:1px 0px; white-space: nowrap; ">
		                    <td>&nbsp;<?php echo $tr->translate("NUM");?></td>
							<td><?php echo $tr->translate("CATE_NAME");?></td>
							<td>&nbsp;<?php echo $tr->translate("BRAND_NAME");?></td>
							<td><?php echo $tr->translate("ITEM_NAME");?></td>
							<td>&nbsp;<?php echo $tr->translate("ITEM_CODE");?></td>
							<td>&nbsp;<?php echo $tr->translate("MESUER_NAME");?></td>
							<td>&nbsp;<?php echo $tr->translate("QTY");?></td>
		                </tr>
		                </thead>
		                <?php $num=1; 
		                $r_netotal = 0;$r_paid = 0; $r_balance = 0;
		                $d_netotal = 0;$d_paid = 0; $d_balance = 0;
		                $b_netotal = 0;$b_paid = 0; $b_balance = 0;
		                if(!empty($this->product_rs))foreach ($this->product_rs AS $index => $rs){?>
						<tr class='row-format<?php echo $num; $num=1-$num;?> hover' style="border:1px solid #000;">
						   <td align="center" style="white-space: nowrap;">&nbsp;<?php echo $index+1?></td>
						   <td style="white-space: nowrap;">&nbsp;<?php echo $rs["cate_name"];?></td>
						   <td style="white-space: nowrap;">&nbsp;<?php echo $rs["brand_name"];?></td>
						   <td style="max-width:280px;">&nbsp;<?php echo $rs["item_name"];?></td>
						   <td style="white-space: nowrap;">&nbsp;<?php echo $rs["item_code"];?></td>
						   <td style="white-space: nowrap;">&nbsp;<?php echo "1".$rs["measue_name"].'='.$rs["qty_perunit"].$rs["unit_label"];?></td>
						   <?php 
							   $raw_qty = $rs["qty_order"];
							   $array = explode(".",$rs["qty_order"]);
							   $qty = $array[0];
							   $qty_unit = ($raw_qty*$rs["qty_perunit"]) - ($rs["qty_perunit"]*$array[0]);
							   $l_qty = 0;
							   if($raw_qty>0){
							   	if($qty>0 and $qty_unit>0){
							   		$l_qty = $qty." ".$rs["measue_name"]." និង ".round($qty_unit)." ".$rs["unit_label"];
							   	}elseif($qty==0 and $qty_unit>0){
							   		$l_qty = round($qty_unit)." ".$rs["unit_label"];
							   	}elseif($qty>0 and $qty_unit==0){
							   		$l_qty =  $qty." ".$rs["measue_name"];
							   	}
							   }else{
							   	$l_qty = 0;
							   }
						   ?>
						   <td style="white-space: nowrap;">&nbsp;<?php echo $l_qty;//number_format($rs["qty_order"],2);?></td>
						</tr>
						   <?php 
                    }?>
		           </table>
		            	<br>
		              <?php echo $this->getFooter;?>
		    		</td>
		    	</tr>
			</tbody>
		</table>
		</div>
	  </div>		
	</div>
</div>
<iframe name=print_frame width=0 height=0 frameborder=0 src=about:blank></iframe>
<script>
function doPrint() {var divToPrint = document.getElementById('divPrint');var htmlToPrint = '' +'<style type="text/css">' +'</style>';htmlToPrint += divToPrint.outerHTML;window.document.write(htmlToPrint);window.print();window.close();}
dojo.require("dijit.form.DateTextBox");
</script>
