<?php 
	$tr=Application_Form_FrmLanguages::getCurrentlanguage();
	$brach_name =  $this->branch;
?>
<title>Customer Report</title>
<div class="card pb-10 pt-10 pl-10 pr-10">
	<div class="card-content">
		<div class="card-box">
			<form method="post" autocomplete="off">
				<?php $formFilter = $this->formFilter; ?>
				<div class="form-group">
					<div class="col-md-3"><?php echo $formFilter->getElement('text_search');?></div>
					<div class="col-md-3"><?php echo $formFilter->getElement('branch_id');?></div>
					<div class="col-md-3"><?php echo $formFilter->getElement('customer_id');?></div>
					<div class="col-md-3"><?php echo $formFilter->getElement('level');?></div>
				</div>
				<div class="form-group">
					<div class="col-md-3"><?php echo $formFilter->getElement('start_date');?></div>
					<div class="col-md-3"><?php echo $formFilter->getElement('end_date');?></div>
					<div class="col-md-3">
						<input type="submit" value="btnsavenew" id="btnsavenew" name="save_close" label="<?php echo $tr->translate("REFRESH")?>" dojoType="dijit.form.Button" 
							iconClass="dijitIconSearch" />
					</div>
				</div>	
			</form> 
			<div id="divPrint" style="width: 100%;">
				<style>
					.style{
						line-height: 25px;font-size: 12px !important;
						font-family: 'Khmer OS Battambang';
					}
					ul{margin: 0;padding:0;}
					table tr td ul li{text-align: center;list-style: none;line-height: 25px; font-weight: bold;}
					th{padding: 5px;}
					.hover:hover{background: #ccc;}
				</style>
				<table style="font-family: 'Khmer OS Content'; width:100%;">
					<tbody>
						<tr>
					    	<td align="center">
					        	<table width="100%" style="font-family: 'Khmer OS Battambang';" cellpadding="0" cellpadding="0">
					            	<tr>
					                	<td width="20%" valign="top"><img src="<?php echo $this->baseUrl();?>/images/logo.jpg" height="55px"></td>
					                	<td width="60%" valign="top">
					                		<ul>
					                			<li style="text-align:center; font-size:16px; font-family:'Khmer OS Muol Light'"><?php echo $tr->translate("COMPANY_CUSTOMER");?></li>
					                			<li style="text-align:center; font-size:14px; font-family:'Khmer OS Muol Light'"><?php echo $tr->translate("RPT_CUSTOMER");?></li>
					                			<li style="text-align:center; font-size:14px;"><?php if(!empty($this->rssearch['start_date'])){echo date("d/m/Y",strtotime($this->rssearch['start_date']));?> ដល់ <?php } echo date("d/m/Y",strtotime($this->rssearch['end_date']));?></li>
					                		</ul>
					                	</td>
					                    <td width="20%"></td>
					                </tr> 
					           </table>
					        </td>
					    </tr>
					    <tr>
					    	<td class="table2excel" id="exportExcel">
					            <table border="1" style="border-collapse:collapse;border:1px solid #000; font-size:12px;" width="100%" cellspacing="0">
					               <tbody>
					                <tr bgcolor="#ccc" class="style" align="center" style="font-weight:bold; line-height: 25px; font-size:12px; padding:1px 0px; white-space: nowrap; ">
					                    <td>&nbsp;<?php echo $tr->translate("NUM");?></td>
										<td><?php echo $tr->translate("BRANCH_NAME");?></td>
										<td>&nbsp;<?php echo $tr->translate("CUSTOMER_NAME");?></td>
										<td>&nbsp;<?php echo $tr->translate("COMPANY_NUMBER");?></td>
										<td width="10%">&nbsp;<?php echo $tr->translate("CUSTOMER_LEVEL");?></td>
										<td><?php echo $tr->translate("CONTACT_NAME");?></td>
										<td><?php echo $tr->translate("CONTACT_NUMBER");?></td>
										<td>&nbsp;<?php echo $tr->translate("EMAIL");?></td>
										<td>&nbsp;<?php echo $tr->translate("FAX");?></td>
										<td>&nbsp;<?php echo $tr->translate("WEBSITE");?></td>
										<td>&nbsp;<?php echo $tr->translate("ADDRESS");?></td>
										<td>&nbsp;<?php echo $tr->translate("REMARK");?></td>
										<td>&nbsp;<?php echo $tr->translate("BY_USER");?></td>
					                </tr>
					                <?php $num=1; 
					                if(!empty($this->repurchase))foreach ($this->repurchase AS $index => $rs){?>
									<tr class='row-format<?php echo $num; $num=1-$num;?> hover' style="border:1px solid #000;">
									   <td align="center" style="white-space: nowrap;">&nbsp;<?php echo $index+1?></td>
									   <td style="white-space: nowrap;"><a style="color:#000;text-decoration: none;" target="_blank" href="<?php echo $this->baseUrl()."/report/index/purproductdetail/id/".$rs["id"];?>">&nbsp;<?php echo $rs["branch_name"];?></a></td>
									   <td style="white-space: nowrap;"><a style="color:#000;text-decoration: none;" target="_blank" href="<?php echo $this->baseUrl()."/report/index/purproductdetail/id/".$rs["id"];?>">&nbsp;<?php echo $rs["cust_name"];?></a></td>
									   <td style="white-space: nowrap;"><a style="color:#000;text-decoration: none;" target="_blank" href="<?php echo $this->baseUrl()."/report/index/purproductdetail/id/".$rs["id"];?>">&nbsp;<?php echo $rs["phone"];?></a></td>
									   <td style="white-space: nowrap;">&nbsp;<?php echo $rs["level"];?></td>
									   <td style="white-space: nowrap;">&nbsp;<?php echo $rs["contact_name"];?></td>
									   <td style="white-space: nowrap;">&nbsp;<?php echo $rs["contact_phone"];?></td>
									   <td style="white-space: nowrap;">&nbsp;<?php echo $rs["email"];;?></td>
									   <td style="white-space: nowrap;">&nbsp;<?php echo $rs["fax"];;?></td>
									   <td style="white-space: nowrap;">&nbsp;<?php echo $rs["website"];;?></td>
									   <td style="white-space: nowrap;">&nbsp;<?php echo $rs["address"];;?></td>
									   <td style="white-space: nowrap;">&nbsp;<?php echo $rs["remark"];;?></td>
									   <td style="white-space: nowrap;">&nbsp;<?php echo ($rs["user_name"]);?></td>
									</tr>
			                  <?php   }?> 
			                	 </tbody>
					           	</table>
					            <br>
					             	<?php echo $this->getFooter;?>	
					    		</td>
					    	</tr>
						</tbody>
					</table>
				</div>
			</div>		
		</div>
	</div>
<iframe name=print_frame width=0 height=0 frameborder=0 src=about:blank></iframe>
<script>
	function doPrint(){
		var divToPrint = document.getElementById('divPrint');var htmlToPrint = '' +'<style type="text/css">' +'</style>';htmlToPrint += divToPrint.outerHTML;window.document.write(htmlToPrint);
		window.print();
		window.close();
	}
	dojo.require("dijit.form.DateTextBox");
</script>