<?php 
$tr=Application_Form_FrmLanguages::getCurrentlanguage();
$frm_sales_report = $this->form_search;
?>
<title>របាយការណ៍ ទូទាត់សាច់ប្រាក់</title>
<div class="card pb-10 pt-10 pl-10 pr-10">
	<div class="card-content">
		<div class="card-box">
			<form method="post" action="" autocomplete="off">
				<div class="form-group">
					<div class="col-md-3"><?php echo $frm_sales_report->getElement("txt_search");?></div>
					<div class="col-md-3"><?php echo $frm_sales_report->getElement("branch_id");?></div>
					<div class="col-md-3"><?php echo $frm_sales_report->getElement('customer_id');?></div>
					<div class="col-md-3"><?php echo $frm_sales_report->getElement("category_id");?></div>
				</div>
				<div class="form-group">
					<div class="col-md-3"><?php echo $frm_sales_report->getElement('item');?></div>
					<div class="col-md-3"><?php echo $frm_sales_report->getElement('start_date');?></div>
					<div class="col-md-3"><?php echo $frm_sales_report->getElement("end_date");?></div>
					<div class="col-md-3">
						<input type="submit" value="btnsavenew" id="btnsavenew" name="save_close" label="<?php echo $tr->translate("REFRESH")?>" dojoType="dijit.form.Button" 
							iconClass="dijitIconSearch" />
					</div>
				</div>	
			</form> 
			<div id="divPrint" style="width: 100%;">
				<style>
					.style{
						line-height: 25px;font-size: 12px !important;
						font-family: 'Khmer OS Battambang';
					}
					ul{margin: 0;padding:0;}
					table tr td ul li{text-align: center;list-style: none;line-height: 25px; font-weight: bold;}
					th{padding: 5px;}
					.hover:hover{background: #ccc;}
				</style>
		<table style="font-family: 'Khmer OS Content'; width:100%;">
			<tbody>
			<tr>
		    	<td align="center">
                	<ul>
                		<li style="text-align:center; font-size:16px; font-family:'Khmer MEF2'">របាយការណ៍ ទូទាត់សាច់ប្រាក់</li>
                		<li style="text-align:center; font-size:14px;"><?php echo date("d/m/Y",strtotime($this->rssearch['start_date']));?> ដល់ <?php echo date("d/m/Y",strtotime($this->rssearch['end_date']));?></li>
                	</ul>
		        </td>
		    </tr>
		    <tr>
		    	<td class="table2excel" id="exportExcel">
		    		ចំណូលពីការលក់ទំនិញ
		            <table border="1"  style="border-collapse:collapse;border:1px solid #000; font-size:12px;" width="100%" cellspacing="0">
		                 <tbody>
			                 <tr bgcolor="#98a4fa" class="style" align="center" style="font-weight:bold; line-height: 25px; font-size:12px; padding:1px 0px; white-space: nowrap; ">
			                    <td>&nbsp;<?php echo $tr->translate("NUM");?></td>
			                    <td><?php echo $tr->translate("BRANCH_NAME");?></td>
								<td>&nbsp;<?php //echo $tr->translate("CUSTOMER_NAME");?></td>
								<td width="10%">&nbsp;<?php echo $tr->translate("SALE_DATE");?></td>
								<td><?php echo $tr->translate("CATE_NAME");?></td>
								<td><?php echo $tr->translate("ITEM_NAME");?></td>
								<td>&nbsp;<?php echo $tr->translate("ITEM_CODE");?></td>
								<td>&nbsp;<?php echo $tr->translate("QTY");?></td>
								<td width="10%">&nbsp;<?php echo $tr->translate("ITEM_PRICE");?></td>
								<td><?php echo $tr->translate("DISCOUNT");?></td>
								<td><?php echo $tr->translate("TOTAL");?></td>
								<td>&nbsp;<?php echo $tr->translate("BY_USER");?></td>
			                </tr>
		                <?php $num=1; 
		                	$d_netotal = 0;
		                	$net_income = 0;
		                	$total_expense_dollar=0;
		                	$discount_value=0;
		                	$sale_id='';
		                if(!empty($this->product_rs))foreach ($this->product_rs AS $index => $rs){?>
						<tr class='row-format<?php echo $num; $num=1-$num;?> hover' style="border:1px solid #000;">
						   <td align="center" style="white-space: nowrap;">&nbsp;<?php echo $index+1?></td>
						   <td style="white-space: nowrap;">&nbsp;<?php echo $rs["branch_name"];?></td>
						   <td style="white-space: nowrap;">&nbsp;<?php echo $rs["customer_name"];?></td>
						   <td style="white-space: nowrap;">&nbsp;<?php echo date("d/m/Y",strtotime($rs["date_sold"]));?></td>
						   <td style="white-space: nowrap;">&nbsp;<?php echo $rs["cate_name"];?></td>
						   <td style="white-space: nowrap;">&nbsp;<?php echo $rs["item_name"];?></td>
						   <td style="white-space: nowrap;">&nbsp;<?php echo $rs["item_code"];?></td>
						   <td style="white-space: nowrap;">&nbsp;
						   <?php 
						   	   if($sale_id!=$rs['id']){
						   	   }
							   $raw_qty = $rs["qty_order"];
							   $array = explode(".",$rs["qty_order"]);
							   $qty = $array[0];
							   $qty_unit = ($raw_qty*$rs["qty_perunit"]) - ($rs["qty_perunit"]*$array[0]);
							   $l_qty = 0;
							   if($raw_qty>0){
							   	if($qty>0 and $qty_unit>0){
							   		$l_qty = $qty." ".$rs["measue_name"]." និង ".round($qty_unit)." ".$rs["unit_label"];
							   	}elseif($qty==0 and $qty_unit>0){
							   		$l_qty = round($qty_unit)." ".$rs["unit_label"];
							   	}elseif($qty>0 and $qty_unit==0){
							   		$l_qty =  $qty." ".$rs["measue_name"];
							   	}
							   }else{
							   	$l_qty = 0;
							   }
								echo $l_qty;
								$net_income =$net_income+$rs["sub_total"];
						?>
						   </td>
						   <td>&nbsp;<?php echo number_format($rs["price"],2);?></td>
						   <td>&nbsp;<?php echo $rs["disc_value"];?></td>
						   <td>&nbsp;<?php echo number_format($rs["sub_total"],2);?></td>
						   <td>&nbsp;<?php echo $rs["user_name"];?></td>
						 </tr>
						   <?php 
						   $sale_id=$rs['id'];
                    	 }?>
		                </tbody>
		           </table>
		           	ចំណាយផ្សេងៗ
		            <table border="1"  style="border-collapse:collapse;border:1px solid #000; font-size:12px;" width="100%" cellspacing="0">
		                 <tbody>
		                   <tr style="font-family:'khmer os battambang';font-size:12px; height: 20px;border: 1px solid #000;white-space: nowrap;background-color: #98a4fa;line-height:30px;font-weight: bold;" align="center" >
								<td style="border: 1px solid #000;"><?php echo $tr->translate('NUM')?></td>
								<td style="border: 1px solid #000;"><?php echo $tr->translate('BRANCH_NAME')?></td>
								<td style="border: 1px solid #000;"><?php echo $tr->translate('EXPENSE_TITLE')?></td>
								<td style="border: 1px solid #000;"><?php echo $tr->translate('NAME_ENTITLE')?></td>
								<td style="border: 1px solid #000;"><?php echo $tr->translate('TOTAL')?></td>
							</tr>
							<?php $i=0;if(!empty($this->expense))foreach($this->expense as $row){ $i++;?>
							<tr class="hover" style="font-size:12px; height: 20px;border: 1px solid #000; white-space: nowrap;" align="center" >
								<td style="border: 1px solid #000;"><?php echo $i;?></td>
								<td style="border: 1px solid #000;"><?php echo $row['branch_name'];?></td>
								<td style="border: 1px solid #000;text-align: left;padding:0px 2px;"><span style="width:120px;font-family:'Khmer OS Content'"></span><?php echo $row['title'];?></td>
								<td align="canter" style="border: 1px solid #000;padding:1px;"><?php echo $row['title_en'];?></td>
								<td style="border: 1px solid #000;background: #c6e2fb;"><?php echo number_format($row['total_amount'],2);?><?php if($row['curr_type']==1){echo ' $';}else{echo ' រៀល​ ';}?></td>
							</tr>
								<?php 
									$total_expense_dollar = $total_expense_dollar + $row['total_amount'];
								?> 
							 <?php } ?>
							  <?php if(!empty($this->expense_po))foreach($this->expense_po as $row){ $i++;?>
							<tr class="hover" style="font-size:12px; height: 20px;border: 1px solid #000; white-space: nowrap;" align="center" >
								<td style="border: 1px solid #000;"><?php echo $i;?></td>
								<td style="border: 1px solid #000;"><?php echo $row['branch_name'];?></td>
								<td style="border: 1px solid #000;text-align: left;"><span style="width:120px;font-family:'Khmer OS Content'"></span><?php echo "ចំណាយលើអ្នកផ្គត់ផ្គង់".$row['title_kh'];?></td>
								<td align="center" style="border: 1px solid #000;"><?php echo "Supplier's Expense".$row['title_en'];?></td>
								<td style="border: 1px solid #000;background: #c6e2fb;"><?php echo number_format($row['total_paid'],2);?>&nbsp;$<?php //if($row['curr_type']==1){echo ' $';}else{echo ' រៀល​ ';}?></td>
							</tr>
								<?php 
									$total_expense_dollar = $total_expense_dollar + $row['total_paid'];
								?> 
							 <?php } ?>
		              	 </tbody>
		              	 <tr style="border: 1px solid #fff;font-size: 13px;">
		              	 	<td colspan="3" align="right"></td>
		              	 	<td align="right">ចំណូលសរុប</td>
		              	 	<td align="left"><strong><?php echo number_format($net_income,2);?></strong></td>
		              	 </tr>
		              	 <tr style="border: 1px solid #fff;font-size: 13px;">
		              	 	<td colspan="3" align="right"></td>
		              	 	<td align="right">បញ្ចុះតម្លៃ</td>
		              	 	<td align="left"><strong><?php echo number_format($this->rs_totaldiscount,2);?></strong></td>
		              	 </tr>
		              	 <tr style="border: 1px solid #fff;font-size: 13px;">
		              	 	<td colspan="3" align="right"></td>
		              	 	<td align="right">ចំណាយសរុប</td>
		              	 	<td align="left"><strong><?php echo number_format($total_expense_dollar,2);?></strong></td>
		              	 </tr>
		              	 <tr style="border: 1px solid #fff;font-size: 13px;">
		              	 	<td colspan="3" align="right"></td>
		              	 	<td align="right">ប្រាក់សមតុល្យ</td>
		              	 	<td align="left">
		              	 		 <strong><?php echo number_format($net_income-$total_expense_dollar-$this->rs_totaldiscount,2);?></strong>
		              	 	</td>
		              	 </tr>
		              </table>
		              <?php echo $this->getFooter;?>	
		    		</td>
		    	</tr>
			</tbody>
		</table>
		</div>
	  </div>		
	</div>
</div>
<iframe name=print_frame width=0 height=0 frameborder=0 src=about:blank></iframe>
<script>
	function doPrint() {var divToPrint = document.getElementById('divPrint');var htmlToPrint = '' +'<style type="text/css">' +'</style>';htmlToPrint += divToPrint.outerHTML;window.document.write(htmlToPrint);window.print();window.close();}
	dojo.require("dijit.form.DateTextBox");
</script>