<?php 
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$month = array("01"=>"មករា","02"=>"កុម្ភៈ","03"=>"មីនា","04"=>"មេសា","05"=>"ឧសភា","06"=>"មិថុនា","07"=>"កក្កដា","08"=>"សីហា","09"=>"កញ្ញា","10"=>"តុលា","11"=>"វិច្ឆិកា","12"=>"ធ្នូ",);
?>
<script>
	dojo.require("dijit.form.DateTextBox");
</script>
<title><?php echo $tr->translate("របាយការណ៍ចំណូលចំណាយ");?></title>
<div class="card pb-10 pt-10 pl-10 pr-10">
	<div class="card-content">
		<div class="card-box">
			<form method="post" autocomplete="off" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
					<script type="dojo/method" event="onSubmit">   
   						if(this.validate()) {
    						return true;
   						}else {
    						return false;
   						}
					</script>
				<div class="form-group" style="padding-top: 6px;">
					<?php $form = $this->form_search; ?>
					<div class="col-md-2"><?php echo $form->getElement("adv_search");?></div>
					<div class="col-md-2"><?php echo $form->getElement('branch_id');?></div>
					<div class="col-md-2"><?php echo $form->getElement("cate_income");?></div>
					<div class="col-md-2"><?php echo $form->getElement("start_date");?></div>
					<div class="col-md-2"><?php echo $form->getElement("end_date");?></div>
					
						<input type="submit" value="btnsavenew" id="btnsavenew" name="save_close" label="<?php echo $tr->translate("REFRESH")?>" dojoType="dijit.form.Button" 
							iconClass="dijitIconSearch" />
					</div>
				</div>	
			</form> 
	</div>
	<table style="font-family: 'Khmer OS Content'; width:100%;"  >
		<tr>
	    	<td align="center">
	    	 <div id="divPrint">
	    	 			<style>
							tr td.border_bottom{border-bottom: solid 1px #000;}
							tr td.border_double{border-bottom: double #000;}
							.border{border:1px solid #000;}
							.style{
								line-height: 20px;font-size: 14px !important;
								font-family: 'Khmer OS Battambang';
								}
							th{padding: 5px;}
							.border-bottom{border-bottom: 1px dotted #000; vertical-align:  middle;}
						</style>
			        	<table width="100%" style="font-family:'Khmer OS Battambang';" style="margin:0; padding:0;border:none;">
			        	<tr>
			                <td width="18%"></td>
			                <td width="60%" valign="top">
			                <ul style="list-style: none;">
				                <li style="line-height:25px;text-align:center; font-size:14px; font-family:'Khmer OS Muol Light'"><?php //echo $tr->translate("BRAND_TITLE");?></li>
				                <li style="line-height:20px;text-align:center; font-size:14px; font-family:'Khmer OS Muol Light'"><?php echo $tr->translate("របាយការណ៍ចំណូលចំណាយ");?></li>
				                <li style="line-height:20px;text-align:center; font-size:14px; font-family:'Khmer OS Muol Light';display:none;">(គិតជាដុល្លាអាមេរិក)</li>
				                <li style="line-height:25px;text-align:center; font-size:14px; font-family:'Khmer OS Muol Light'"><?php  if (!empty($this->list_end_date['start_date'])){ echo date("d-m-Y",strtotime($this->list_end_date['start_date'])).'/'.date("d-m-Y",strtotime($this->list_end_date['end_date']));}?></li>
			                </ul>
			                </td>
			                <td width="20%"></td>
			             </tr> 
			             	<?php $total_income = 0; $total_expense = 0; $net_income =0;?>
			            </table>
	             		<table  width="100%" style="border-collapse:collapse; font-size: 14px; line-height: 25px;" >  
	             			<tr>
	             				<td width="250px" style="font-size:14px; font-family:'Khmer OS Muol Light'"> <?php echo $tr->translate("ចំណូលពីការលក់");?> </td>
	             				<td colspan="2" class="border-bottom" valign="middle">&nbsp;</td>
	             				<td align="right" valign="bottom" width="250px">&nbsp;<strong style="font-family: Helvetica;">
	             				<?php 
		             				$total_sold = $this->rssale['sale_amount'];
		             				echo number_format($total_sold,2);
		             			?>&nbsp;
		             			</strong></td>
	             				<td>&nbsp;</td>
	             				<td>&nbsp;</td>
	             			</tr>
	             			<?php 
	             				$total_income = $this->rssale['sale_amount']-$this->rssale['discount_amount'];
	             			?>
	             			<tr height="21px">
	             				<td style=" font-size:14px; font-family:'Khmer OS Muol Light'"> <?php echo $tr->translate("ថ្ងៃដើមផលិតផល");?> </td>
	             				<td colspan="2" class="border-bottom" valign="middle">&nbsp;</td>
	             				<td align="right" valign="bottom">&nbsp;
	             					<strong style="font-family: Helvetica;">
			             				<?php 
				             				$cost_price = $this->rscost['total_cost'];
				             				echo number_format($cost_price,2);?>&nbsp;
				             		</strong>
				             	</td>
	             				<td>&nbsp;&nbsp;</td>
	             				<td>&nbsp;&nbsp;</td>
	             			</tr>
							 <tr>
	             				<td colspan="5" style=" font-size:14px; font-family:'Khmer OS Muol Light'"> <?php echo $tr->translate("ប្រភេទចំណូល");?> </td>
	             				<td align="right">&nbsp;&nbsp;</td>
	             			</tr>
	             				<?php 
									$total_income_kh=0;
									$total_income_dollar=0;
									$total =0;
									$total_paid =0;
									$total_income=0;
								?>
								<?php $i=0;
								  if(!empty($this->incomebycate))foreach($this->incomebycate as $row){ $i++;?>
								  
	             				<?php
								
	             					$total_income = $total_income + $row['total_income'];
	             				?>
	             			<tr height="21px">
	             				<td style="font-family:khmer os battambang;">&nbsp;<?php echo $row['cate_income'];?>&nbsp;</td>
	             				<td colspan="2" class="border-bottom" valign="bottom"></td>
	             				<td class="" align="right">&nbsp;<?php echo number_format($row['total_income'],2);?>&nbsp;</td>
	             				<td >&nbsp;</td>
	             				<td>&nbsp;</td>
	             			</tr>
	             			<?php }?>
							
	             			<tr height="25px">
	             				<td>&nbsp;</td>
	             				<td colspan="2" style="text-align:right;font-size:14px; font-family:'Khmer OS Muol Light'"> <?php echo $tr->translate("ប្រាក់ចំណេញដុល");?> </td>
	             				<td align="right">&nbsp;<strong style="font-family: Helvetica;border-bottom: 2px solid #000;"><?php

								$net_sold =$total_sold-$cost_price + $total_income;

								 echo number_format($net_sold,2);?>&nbsp;</strong></td>
	             				<td >&nbsp;</td>
	             				<td>&nbsp;</td>
	             			</tr>

	             			<?php ?>
	             			
<!--------------------------------------------------------------------->
							
	             			

<!--------------------------------------------------------------------->

	             			<tr>
	             				<td colspan="5" style=" font-size:14px; font-family:'Khmer OS Muol Light'"> <?php echo $tr->translate("ប្រភេទចំណាយ");?> </td>
	             				<td align="right">&nbsp;&nbsp;</td>
	             			</tr>
	             				<?php 
									$total_income_kh=0;
									$total_income_dollar=0;
									$total =0;
									$total_paid =0;
									$total_expense_kh=0;
								?>
								<?php $i=0;
								  if(!empty($this->expense))foreach($this->expense as $row){ $i++;?>
	             				<?php
	             					$total_expense = $total_expense + $row['total_amount'];
	             				?>
	             			<tr height="21px">
	             				<td style="font-family:khmer os battambang;">&nbsp;<?php echo $row['title'];?>&nbsp;</td>
	             				<td colspan="2" class="border_bottom" valign="bottom"></td>
	             				<td class="" align="right">&nbsp;<?php echo number_format($row['total_amount'],2);?>&nbsp;</td>
	             				<td >&nbsp;</td>
	             				<td>&nbsp;</td>
	             			</tr>
	             			<?php }?>
	             			<tr height="22px">
	             				<td>&nbsp;</td>
	             				<td colspan="2" style="text-align:right;font-size:14px; font-family:'Khmer OS Muol Light'"> <?php echo $tr->translate("ចំណាយសរុប");?> </td>
	             				<td align="right">&nbsp;<strong style="font-family: Helvetica;border-bottom: 2px solid #000;"><?php echo number_format($total_expense,2);?>&nbsp;</strong></td>
	             				<td >&nbsp;</td>
	             				<td>&nbsp;</td>
	             			</tr>
	             			<?php 
	             				$net_income = $net_sold-$total_expense;
	             			?>
	             			<tr style="padding-top: 100px;">
	             				<td>&nbsp;</td>
	             				<td colspan="2" style=" font-size:14px; font-family:'Khmer OS Muol Light';text-align: right;" width="150px"><?php echo $tr->translate("ប្រាក់ចំណេញ/ខាត​សរុប");?> </td>
	             				<td >&nbsp;</td>
	             				<td style="width:10px;">&nbsp;</td>
	             				<td class="border_double" align="right" ><strong style="font-family: Helvetica;font-weight: bold;">&nbsp;<?php if ($net_income<0){ ?> <strong style="color:red;"><?php echo "(".number_format(abs($net_income),2).")"; ?></strong> <?php }else{ echo number_format($net_income,2);}?>&nbsp;</strong></td>
	             			</tr>
	             		</table>
			    	</td>
			    </tr>
		</table>
	   	<table align="center" width="100%">
		   <tr style="font-size: 14px;">
	        <th style="width:20%;text-align:center;  font-family:'Khmer OS Muol Light';font-weight: normal;"><?php echo $tr->translate('APPROVED BY');?></th>
	        <th></th>
	        <th style="width:20%;text-align:center; font-family:'Khmer OS Muol Light';font-weight: normal;"><?php echo $tr->translate('VERIFYED BY');?></th>
	        <th></th>
	        <th style="width:20%;text-align:center;font-family:'Khmer OS Muol Light';font-weight: normal;"><?php echo $tr->translate('PREPARE BY');?></th>
	   		</tr>
		</table>
	</div>
</div>
<iframe name=print_frame width=0 height=0 frameborder=0 src=about:blank></iframe>
<script type="text/javascript">
	function doPrint() {var divToPrint = document.getElementById('divPrint');var htmlToPrint = '' +'<style type="text/css">' +'</style>';htmlToPrint += divToPrint.outerHTML;window.document.write(htmlToPrint);window.print();window.close();}
dojo.require("dijit.form.DateTextBox");
</script>