<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$this->headTitle('បង្កាន់ដៃបង់ប្រាក់'); 
	echo $this->headTitle();
	$session_user=new Zend_Session_Namespace('auth');
	$user_id=$session_user->user_id;
?>
<style>
.hover:hover{ background: #ddd;}
</style>
<div class="card pb-10 pt-10 pl-10 pr-10">
	<div class="card-content">
		<div class="card-box">
			<form method="post" autocomplete="off" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
					<script type="dojo/method" event="onSubmit">   
   						if(this.validate()) {
    						return true;
   						}else {
    						return false;
   						}
					</script>
					<div class="form-group" >
						<?php $formFilter = $this->form_purchase; ?>
						<div class="col-md-4"><?php echo $formFilter->getElement('text_search');?></div>
						<div class="col-md-4"><?php echo $formFilter->getElement('branch_id');?></div>
						<div class="col-md-4"><?php echo $formFilter->getElement('customer_id');?></div>
					</div>
					<div class="form-group" >
						<div class="col-md-4"><?php echo $formFilter->getElement('start_date');?></div>
						<div class="col-md-4"><?php echo $formFilter->getElement('end_date');?></div>
						<div class="col-md-4"><input type="submit" value="btnsavenew" id="btnsavenew" name="save_close" label="<?php echo $tr->translate("REFRESH")?>" dojoType="dijit.form.Button" iconClass="dijitIconSearch" /></div>
					</div>
			</form> 
		</div>
		<div id="divPrint"  >
			<table class="table2excel" style="background:#fff; margin: 0 auto; width: 100%; padding: 0px 2px 1cm 2px;font-family: 'Hanuman';">
				<tr>
					<td width="20%" valign="top"></td>
                	<td width="60%" valign="top">
                		<ul>
                			<li style="text-align:center; font-size:16px; font-family:'Khmer MEF2'">របាយការណ៏ លក់លម្អិត</li>
                			<li style="text-align:center; font-size:14px;"><?php if(!empty($this->search['start_date'])){echo date("d/m/Y",strtotime($this->search['start_date']));?> ដល់ <?php } echo date("d/m/Y",strtotime($this->search['end_date']));?></li>
	                		</ul>
                	</td>
                    <td width="20%"></td>
				</tr>
				<?php 
					$total =0;
					$total_paid =0;
					$total_paid=0;
				?>
				<style>
					table tr td ul li{
						text-align: center;
						list-style: none;
						line-height: 25px;
						font-weight: bold;
					}
				</style>
				<tr>
					<td colspan="3">
						<table border="1" style="border-collapse:collapse;border:1px solid #000; font-size:12px;" width="100%" cellspacing="0">
            				<tr style="background:#ccd9ff;font-weight:bold; font-size:12px; height: 20px;border: 1px solid #000;white-space: nowrap;line-height:30px;font-weight: bold;" align="center" >
								<td style="border: 1px solid #000;"><?php echo $tr->translate('NUM')?></td>
								<td style="border: 1px solid #000;"><?php echo $tr->translate('BRANCH_NAME')?></td>
								<td style="border: 1px solid #000;"><?php echo $tr->translate('CUSTOMER_NAME')?></td>
								<td style="border: 1px solid #000;"><?php echo $tr->translate('Receipt No.')?></td>
								<td style="border: 1px solid #000;"><?php echo $tr->translate('PAID_DATE')?></td>
								<td style="border: 1px solid #000;"><?php echo $tr->translate('TOTAL_SALE')?></td>
								<td style="border: 1px solid #000;"><?php echo $tr->translate('PAID')?></td>
								<td style="border: 1px solid #000;"><?php echo $tr->translate('BALANCE')?></td>
								<td style="border: 1px solid #000;"><?php echo $tr->translate('NOTE')?></td>
								<td style="border: 1px solid #000;"><?php echo $tr->translate('USER')?></td>
							</tr>
							<style> td{padding:0 3px; }</style>
						<?php $i=0;if(!empty($this->rsreceitp))foreach($this->rsreceitp as $row){ $i++;?>
							<tr class="hover" style="font-size:12px; height: 20px;border: 1px solid #000; white-space: nowrap;" align="center" >
								<td style="border: 1px solid #000;"><?php echo $i;?></td>
								<td style="border: 1px solid #000; text-align: left;"><?php echo $row['branch_name'];?></td>
								<td style="border: 1px solid #000;text-align: left;"><span style="white-space:normal !important;font-family:'Khmer OS Content';line-height:17px;width:180px;!important; display: block;padding-left: 1px; padding: 2px 1px;"><?php echo $row['customer_name'];?></span></td>
								<td align="canter" style="border: 1px solid #000;"><span style="white-space:normal !important;width:120px;!important;"><?php echo $row['receipt_no'];?></span></td>
								<td style="border: 1px solid #000;"><?php echo date('d-m-Y',strtotime($row['receipt_date']));?></td>
								<td style="border: 1px solid #000;background:#c6e2fb"><?php echo number_format($row['total'],2);?></td>
								<td style="border: 1px solid #000;background:#c6e2fb"><?php echo number_format($row['paid'],2);?></td>
								<td style="border: 1px solid #000;background:#c6e2fb"><?php echo number_format($row['balance'],2);?></td>
								<td style="border: 1px solid #000; width:200px; white-space: normal; text-align: left;"><?php echo $row['remark'];?></td>
								<td style="border: 1px solid #000; width:200px; white-space: normal; text-align: left;"><?php echo $row['user_name'];?></td>
							</tr>
								<?php 
									$total_paid = $total_paid + $row['paid'];
								?> 
							 <?php } ?>
							 <tr class="hover" style="font-size:14px; height:20px;border: 1px solid #000;" align="center" >
								<td style="border: 1px solid #fff;border-right: 1px solid #000;" colspan="5"></td>
								<td style="border: 1px solid #000; white-space: nowrap;">សរុបរួម</td>
								<td style="border: 1px solid #000;border-bottom:"><?php echo number_format($total_paid,2);?></td>
								<td colspan="3" style="border: 1px solid #000;border-bottom:1px solid #fff;border-right:1px solid #fff;"></td>
							</tr>
						</table>
					</td>
				</tr>
			</table>
			<?php echo $this->getFooter;?>
		</div>	
	</div>
</div>
<iframe name=print_frame width=0 height=0 frameborder=0 src=about:blank></iframe>
<script type="text/javascript">
	function doPrint() {var divToPrint = document.getElementById('divPrint');var htmlToPrint = '' +'<style type="text/css">' +'</style>';htmlToPrint += divToPrint.outerHTML;window.document.write(htmlToPrint);window.print();window.close();}
	dojo.require("dijit.form.DateTextBox");
</script>