<?php 
$tr=Application_Form_FrmLanguages::getCurrentlanguage();
$brach_name =  $this->branch;
?>
<title>Sale Report</title>
<div class="card pb-10 pt-10 pl-10 pr-10">
	<div class="card-content">
		<div class="card-box">
			<form method="post" autocomplete="off" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
					<script type="dojo/method" event="onSubmit">   
   						if(this.validate()) {
    						return true;
   						}else {
    						return false;
   						}
					</script>
				<div class="form-group">
					<?php $formFilter = $this->form_purchase; ?>
					<div class="control-label col-md-3"><?php echo $formFilter->getElement('text_search');?></div>
					<div class="control-label col-md-3"><?php echo $formFilter->getElement('branch_id');?></div>
					<div class="control-label col-md-3"><?php echo $formFilter->getElement('customer_id');?></div>
					<div class="control-label col-md-3"></div>
				</div>
				<div class="form-group">	
					<div class="control-label col-md-3"><?php echo $formFilter->getElement('sale_status');?></div>
					<div class="control-label col-md-3"><?php echo $formFilter->getElement('start_date');?></div>
					<div class="control-label col-md-3"><?php echo $formFilter->getElement('end_date');?></div>
					<div class="control-label col-md-3">
						<input type="submit" value="btnsavenew" id="btnsavenew" name="save_close" label="<?php echo $tr->translate("REFRESH")?>" dojoType="dijit.form.Button" 
							iconClass="dijitIconSearch" />
					</div>
				</div><div style="clear:both;"></div>	
			</form> 
	<div id="divPrint" style="width: 100%;">
		<style>
			.style{
				line-height: 25px;font-size: 12px !important;
				font-family: 'Khmer OS Battambang';
			}
			ul{margin: 0;padding:0;}
			table tr td ul li{text-align: center;list-style: none;line-height: 25px; font-weight: bold;}
			th{padding: 5px;}
			.hover:hover{background: #ccc;}
		table { page-break-inside:auto }
		tr{ page-break-inside:avoid; page-break-after:auto; }
		#header {
		  display: table-header-group;
		  page-break-inside:avoid; page-break-after:auto;
		}
		.hidden{display: none;}
		</style>
		<table style="font-family: 'Khmer OS Content'; width:100%;">
			<tbody>
			<tr>
		    	<td align="center">
		        	<table width="100%" style="font-family: 'Khmer OS Battambang';" cellpadding="0" cellpadding="0">
		            	<tbody>
			            	<tr>
			                	<td width="20%" valign="top"></td>
			                	<td width="60%" valign="top">
			                		<ul>
			                			<li style="text-align:center; font-size:16px; font-family:'Khmer OS Muol Light'"><?php echo $tr->translate("COMPANY_CUSTOMER");?></li>
			                			<li style="text-align:center; font-size:14px; font-family:'Khmer OS Muol Light'"><?php echo $tr->translate("SALES_REPORT");?></li>
			                			<li style="text-align:center; font-size:14px;"><?php if(!empty($this->rssearch['start_date'])){echo date("d/m/Y",strtotime($this->rssearch['start_date']));?> ដល់ <?php } echo date("d/m/Y",strtotime($this->rssearch['end_date']));?></li>
			                		</ul>
			                	</td>
			                    <td width="20%"></td>
			                </tr> 
		            	</tbody>
		            </table>
		        </td>
		    </tr>
		    <tr>
		    	<td class="table2excel" id="exportExcel">
		            <table border="1" style="border-collapse:collapse;border:1px solid #000; font-size:12px;" width="100%" cellspacing="0">
		                 <thead>
			                 <tr class="style" align="center" style="font-weight:bold;background:#ccd9ff;font-weight:bold; line-height: 25px; font-size:14px; padding:1px 0px; white-space: nowrap; ">
			                    <td>&nbsp;<?php echo $tr->translate("NUM");?></td>
								<td><?php echo $tr->translate("BRANCH_NAME");?></td>
								<td>&nbsp;<?php echo $tr->translate("CUSTOMER_NAME");?></td>
								<td width="10%">&nbsp;<?php echo $tr->translate("SALE_ORDER");?></td>
								<td><?php echo $tr->translate("SALE_DATE");?></td>
								<td>&nbsp;<?php echo $tr->translate("AMOUNT");?></td>
								<td>&nbsp;<?php echo $tr->translate("DISCOUNT");?></td>
								<td>&nbsp;<?php echo $tr->translate("GRAND_TOTAL");?></td>
								<td width="12%">&nbsp;<?php echo $tr->translate("PAID");?></td>
								<td>&nbsp;<?php echo $tr->translate("BALANCE");?></td>
								<td>&nbsp;<?php echo $tr->translate("BY_USER");?></td>
			                </tr>
		                </thead>
		                <tbody>
		                <?php $num=1; 
			                $d_netotal = 0;$d_paid = 0; $d_balance = 0;
			                $all_total=0;
			                $discount=0;
		                if(!empty($this->repurchase))foreach ($this->repurchase AS $index => $rs){?>
						<tr class='row-format<?php echo $num; $num=1-$num;?> hover' style="border:1px solid #000;">
						   <td align="center" style="white-space: nowrap;">&nbsp;<?php echo $index+1?></td>
						   <td style="white-space: nowrap;"><a style="color:#000;text-decoration: none;" target="_blank" href="<?php echo $this->baseUrl()."/report/index/salesdetail/id/".$rs["id"];?>">&nbsp;<?php echo $rs["branch_name"];?></a></td>
						   <td style="white-space: nowrap;"><a style="color:#000;text-decoration: none;" target="_blank" href="<?php echo $this->baseUrl()."/report/index/salesdetail/id/".$rs["id"];?>">&nbsp;<?php echo $rs["customer_name"];?></a></td>
						   <td style="white-space: nowrap;"><a style="color:#000;text-decoration: none;" target="_blank" href="<?php echo $this->baseUrl()."/report/index/salesdetail/id/".$rs["id"];?>">&nbsp;<?php echo $rs["sale_no"];?></a></td>
						   <td style="white-space: nowrap;">&nbsp;<?php echo date("d/m/Y",strtotime($rs["date_sold"]));?></td>
						   <td style="white-space: nowrap;">&nbsp;<?php echo number_format($rs["net_total"],2);?></td>
						   <td style="white-space: nowrap;">&nbsp;<?php echo number_format($rs["discount_value"],2);?></td>
						   <td style="white-space: nowrap;">&nbsp;<?php echo number_format($rs["all_total"],2);?></td>
						   <td style="white-space: nowrap;">&nbsp;<?php echo number_format($rs["paid"],2);?></td>
						   <td>&nbsp;<?php echo number_format($rs["all_total"]-$rs["paid"],2);?></td>
						   <td>&nbsp;<?php echo $rs["user_name"];?></td>
						</tr>
					<?php 
						$d_netotal = $d_netotal+$rs["net_total"];
						$d_paid = $d_paid+$rs["paid"];
						$all_total = $all_total+$rs["all_total"];
						$d_balance = $d_balance+($rs["all_total"]-$rs["paid"]);
						$discount=$discount +$rs["discount_value"];
                    }?>
		               </tbody>
		               <tr style="background: #87acff; font-weight: bold;font-size: 14px;line-height: 25px;text-align: center;">
		               		<td colspan="5"></td>
		               		<td><label class="hidden">$</label>&nbsp;<?php echo number_format($d_netotal,2);?>&nbsp;</td>
		               		<td><label class="hidden">$</label>&nbsp;<?php echo number_format($discount,2);?>&nbsp;</td>
		               		<td><label class="hidden">$</label>&nbsp;<?php echo number_format($all_total,2);?>&nbsp;</td>
		                    <td><label class="hidden">$</label>&nbsp;<?php echo number_format($d_paid,2);?>&nbsp;</td>
		                    <td colspan="2"><label class="hidden">$</label>&nbsp;<?php echo number_format($d_balance,2);?>&nbsp;</td>
		               </tr>
		           </table>
		              <br>
		              <?php echo $this->getFooter;?>
		    		</td>
		    	</tr>
			</tbody>
		</table>
		</div>
	  </div>		
	</div>
</div>
<iframe name=print_frame width=0 height=0 frameborder=0 src=about:blank></iframe>
<script>
	function doPrint() {var divToPrint = document.getElementById('divPrint');var htmlToPrint = '' +'<style type="text/css">' +'</style>';htmlToPrint += divToPrint.outerHTML;window.document.write(htmlToPrint);window.print();window.close();}
	dojo.require("dijit.form.DateTextBox");
</script>