<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$this->headTitle('របាយការណ៍៍វិក័យបត្រអតិថិជន'); 
	echo $this->headTitle();
	
	$session_user=new Zend_Session_Namespace('auth');
	$user_id=$session_user->user_id;
	$rs = $this->rsreceitp;
	
?>
<style>
.hover:hover{ background: #ddd;}
</style>
<div class="card pb-10 pt-10 pl-10 pr-10">
	<div class="card-content">
		<div class="card-box">
			<div id="divPrint"  >
				<table class="table2excel" style="background:#fff; margin: 0 auto; width: 100%; padding: 0px 2px 1cm 2px;font-family: 'Hanuman';">
					<tr style="font-size: 13px;">
						<td colspan="3" align="center">
							<strong style="font-weight:bold;font-family: Arial Black;color:#000; font-size: 16px;font-family:'Khmer OS Muol Light';">របាយការណ៍៍វិក័យបត្រអតិថិជន</strong><br />
						</td>
					</tr>
					<tr>
						<td width="20%" align="left"></td>
						<td align="center">
							<strong style="font-weight:bold;font-family: Arial Black;color:#000; font-size: 13px;font-family:'Khmer OS Muol Light';"></strong>
						</td>
						<td align="right" width="20%">&nbsp;</td>
					</tr>
						<?php 
							$total =0;
							$total_paid =0;
							$total_balance=0;
						?>
						<tr>
		                	<td colspan="3" valign="top" style="padding-top: 25px;"><br />
		                		<table width="100%" cellpadding="0" cellspacing="0">
		                			<tbody>
			                			<tr>
			                				<td style="font-size: 12px;" valign="top" width="40%;">
			                				<div style="width:100%;display: block;font-size:16px; font-family:'Khmer OS Muol Light';white-space: nowrap;"><u>ពត៌មានអតិថិជន / CUSTOMER INFORMATION</u></div>
			                				    <ul class='pur_info'>
				                					<li style="text-align: left;"><strong>ឈ្មោះក្រុមហ៊ុន / Company Name : </strong><?php echo @$this->rsreceitp[0]['customer'];?></li>
				                					<li style="text-align: left;"><strong>ឈ្មោះអ្នកទំនាក់ទំនង / Contact Person : </strong><?php echo @$this->rsreceitp[0]['contact_name'];?></li>
				                					<li style="text-align: left;"><strong>លេខទូរសព្ទ / Contact Number : </strong><?php echo @$this->rsreceitp[0]['phone'];?></li>
				                					<li style="text-align: left;"><strong>សារអេឡិចត្រូនិច / Email : </strong><?php echo @$this->rsreceitp[0]['email'];?></li>
				                					<li style="text-align: left;"><strong>អាសយដ្ឋាន /  Address: </strong><?php echo @$this->rsreceitp[0]['address']."&nbsp;".@$this->rsreceitp[0]['province'];?></li>
			                					</ul>
			                				</td>
			                				<td width="25"></td>
			                				<td width="35%" style="text-align: left;font-size: 12px;">
			                				</td>
			                			</tr>
				                	</tbody>
				                </table>
				              </td>
				           </tr> 
							<tr>
								<td colspan="3">
									<form name="list">
										<div style="overflow:scroll; max-height: 450px; overflow-x:hidden;" >
											<table border="1" id="table" class="collape tablesorter" width="100%" cellspacing="0">
				            					<tr style="font-size:12px; height: 20px;border: 1px solid #000;white-space: nowrap;background-color: #ccc;line-height:30px;font-weight: bold;" align="center" >
													<td class="tdheader"><?php echo $tr->translate('NUM')?></td>
													<td class="tdheader"><?php echo $tr->translate('BRANCH_NAME')?></td>
													<td class="tdheader"><?php echo $tr->translate('Customer Name')?></td>
													<td class="tdheader"><?php echo $tr->translate('Invoice No')?></td>
													<td class="tdheader"><?php echo $tr->translate('Invoice Date')?></td>
													<td class="tdheader"><?php echo $tr->translate('Total')?></td>
													<td class="tdheader"><?php echo $tr->translate('Paid')?></td>
													<td class="tdheader"><?php echo $tr->translate('Balance')?></td>
													<td class="tdheader"><?php echo $tr->translate('USER')?></td>
													<td class="tdheader"><?php echo $tr->translate('VEIW')?></td>
												</tr>
											 <style> td{padding:0 3px; }</style>
									<?php 
										$id = "table";
										$stringPagination = '<script type="text/javascript">
													$(document).ready(function(){
														$("#'.$id.'").tablesorter();
														$("#'.$id.'").tablesorter().tablesorterPager({container: $("#pagination_'.$id.'"),size:10});
														$("#pagedisplay").focus(function(){ this.blur(); 
													   });
													});
											</script>
											<div id="pagination_'.$id.'" class="pager" >
														<form >
															<table  style="width: 200px;"><tr>
															<td><img src="'.BASE_URL.'/images/first.gif" class="first"/></td>
															<td><img src="'.BASE_URL.'/images/previous.gif" class="prev"/></td>
															<td><input type="text" class="pagedisplay"/></td>
															<td><img src="'.BASE_URL.'/images/next.gif" class="next"/></td>
															<td><img src="'.BASE_URL.'/images/last.gif" class="last"/></td>
															<td><select class="pagesize" >
																<option selected="selected"  value="10">10</option>
																<option value="20">20</option>
																<option value="30">30</option>
																<option value="40">40</option>
																<option value="50">50</option>
																<option value="60">60</option>
																<option value="70">70</option>
																<option value="80">80</option>
																<option value="90">90</option>
																<option value="100">100</option>
																</select>
															</td>
															</tr>
															</table>
														</form>
												</div>	';
										$footer="";
										$cu_id =''; $i=0;if(!empty($this->rsreceitp))foreach($rs as $row){ $i++;
											$total = $total+$row["sub_total"];
											$total_paid  = $total_paid +$row['paid_amount'];
											$total_balance= $total_balance+$row['balance_after'];
									?>
										<tr class="normal" style="font-size:12px; height: 20px; " align="center" >
											<td class="items-no"><?php echo $i;?></td>
											<td class="items"><?php echo $row['branch'];?></td>
											<td class="items"><?php echo $row['customer'];?></td>
											<td class="items"><span style="white-space:normal !important;font-family:'Khmer OS Content';line-height:17px;width:180px;!important; display: block;padding-left: 1px; padding: 2px 1px;"><?php echo $row['invoice_no'];?></span></td>
											<td class="items"><?php echo date("d-M-Y",strtotime($row["invoice_date"]));?></td>
											<td class="items"><?php echo number_format($row["sub_total"],2);?></td>
											<td class="items"><?php echo number_format($row['paid_amount'],2);?></td>
											<td class="items"><?php echo number_format($row['balance_after'],2);?></td>
											<td class="items"><?php echo $row['user_name'];?></td>
											<td class="items"><a href="<?php echo $this->baseUrl();?>/report/index/rptinvoicepaymentdetail/id/<?php echo $row["id"];?>" ><?php echo $row['View'];?></a></td>
										</tr>
									<?php $counter='<strong style="float:right;padding:5px">Number of record(s): '.count($this->rsreceitp).'</strong>'; 
											$footer = '<div class="footer_list">'.$stringPagination.$counter.'</div>';?>
									<?php } ?>
										</table>
									</div>
									</form>
								<?php echo $footer?>
							</td>
						</tr>
				</table>
			</div>	
		</div>
	</div>
</div>
<iframe name=print_frame width=0 height=0 frameborder=0 src=about:blank></iframe>
<script type="text/javascript">
	function doPrint() {var divToPrint = document.getElementById('divPrint');var htmlToPrint = '' +'<style type="text/css">' +'</style>';htmlToPrint += divToPrint.outerHTML;window.document.write(htmlToPrint);window.print();window.close();}
	dojo.require("dijit.form.DateTextBox");
</script>