<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$this->headTitle('របាយការណ៍៍ប្រវត្តិបង់ប្រាក់អតិថិជន'); 
	echo $this->headTitle();
	
	$session_user=new Zend_Session_Namespace('auth');
	$user_id=$session_user->user_id;
	$rs = $this->rsreceitp;
	
?>
<form  id='foundation_class' action=""  method="post" enctype="application/x-www-form-urlencoded">
</form>
<style>
.hover:hover{ background: #ddd;}
</style>
<div class="card pb-10 pt-10 pl-10 pr-10">
	<div class="card-content">
		<div class="card-box">
				<form method="post" autocomplete="off">
					<div class="form-group">
						<?php $formFilter = $this->form_purchase; ?>
						<div class="col-md-3"><?php echo $formFilter->getElement('text_search');?></div>
						<div class="col-md-3"><?php echo $formFilter->getElement('branch_id');?></div>
						<div class="col-md-3"><?php echo $formFilter->getElement('customer_id');?></div>
						<div class="col-md-3">
							<input type="submit" value="btnsavenew" id="btnsavenew" name="save_close" label="<?php echo $tr->translate("REFRESH")?>" dojoType="dijit.form.Button" 
								iconClass="dijitIconSearch" />
						</div>
					</div>
				</form> 
			</div>
		<div id="divPrint"  >
			<table class="table2excel" style="background:#fff; margin: 0 auto; width: 100%; padding: 0px 2px 1cm 2px;font-family: 'Hanuman';">
				<tr style="font-size: 13px;">
					<td colspan="3" align="center">
						<strong style="font-weight:bold;font-family: Arial Black;color:#000; font-size: 16px;font-family:'Khmer OS Muol Light';">របាយការណ៍៍ប្រវត្តិបង់ប្រាក់អតិថិជន</strong><br />
					</td>
				</tr>
				<tr>
					<td width="20%" align="left"></td>
					<td align="center">
						<strong style="font-weight:bold;font-family: Arial Black;color:#000; font-size: 13px;font-family:'Khmer OS Muol Light';"></strong>
					</td>
					<td align="right" width="20%">&nbsp;</td>
				</tr>
				<?php 
					$total =0;
					$total_paid =0;
					$total_balance=0;
				?>
				<tr>
					<td colspan="3">
						<form name="list"><div style="overflow:scroll; max-height: 450px; overflow-x:hidden;" >
							<table border="1" id="table" class="collape tablesorter" style="font-size:12px;" width="100%" cellspacing="0">
	            				<thead>
									<tr style="font-size:12px; height: 20px;line-height:30px;font-weight: bold;" align="center" >
										<td class="tdheader" ><?php echo $tr->translate('NUM')?></td>
										<td class="tdheader" ><?php echo $tr->translate('BRANCH_NAME')?></td>
										<td class="tdheader" ><?php echo $tr->translate('Customer Name')?></td>
										<td class="tdheader" ><?php echo $tr->translate('Contact Name')?></td>
										<td class="tdheader" ><?php echo $tr->translate('Phone')?></td>
										<td class="tdheader" ><?php echo $tr->translate('Email')?></td>
										<td class="tdheader" ><?php echo $tr->translate('Address')?></td>
										<td class="tdheader" ><?php echo $tr->translate('Total')?></td>
										<td class="tdheader" ><?php echo $tr->translate('Paid')?></td>
										<td class="tdheader" ><?php echo $tr->translate('Balance')?></td>
										<td  class="tdheader"><?php echo $tr->translate('USER')?></td>
										<td  class="tdheader"><?php echo $tr->translate('Action')?></td>
									</tr>
								</thead>
								<tbody>
								<?php 
								$id = "table";
								$stringPagination = '<script type="text/javascript">
										$(document).ready(function(){
											$("#'.$id.'").tablesorter();
											$("#'.$id.'").tablesorter().tablesorterPager({container: $("#pagination_'.$id.'"),size:10});
											$("#pagedisplay").focus(function(){ this.blur(); 
										   });
										});
									</script>
									<div id="pagination_'.$id.'" class="pager" >
										<form >
											<table  style="width: 200px;"><tr>
											<td><img src="'.BASE_URL.'/images/first.gif" class="first"/></td>
											<td><img src="'.BASE_URL.'/images/previous.gif" class="prev"/></td>
											<td><input type="text" class="pagedisplay"/></td>
											<td><img src="'.BASE_URL.'/images/next.gif" class="next"/></td>
											<td><img src="'.BASE_URL.'/images/last.gif" class="last"/></td>
											<td><select class="pagesize" >
												<option selected="selected"  value="10">10</option>
												<option value="20">20</option>
												<option value="30">30</option>
												<option value="40">40</option>
												<option value="50">50</option>
												<option value="60">60</option>
												<option value="70">70</option>
												<option value="80">80</option>
												<option value="90">90</option>
												<option value="100">100</option>
												</select>
											</td>
											</tr>
											</table>
										</form>
										</div>	';
								$footer="";
								$cu_id =''; $i=0;if(!empty($this->rsreceitp))foreach($rs as $row){ 
									$total = $total+$row["sub_total"];
									$total_paid  = $total_paid +$row['paid_amount'];
									$total_balance= $total_balance+$row['balance_after'];
								if($cu_id!=$row["customer_id"]){$i++;
									?>
					<tr class="normal" style="font-size:12px; height: 20px;border: 1px solid #000; " align="center" >
						<td class="items-no" ><?php echo $i;?></td>
						<td class="items" ><?php echo $row['branch'];?></td>
						<td class="items" ><span style="white-space:normal !important;font-family:'Khmer OS Content';line-height:17px;width:180px;!important; display: block;padding-left: 1px; padding: 2px 1px;"><?php echo $row['customer'];?></span></td>
						<td class="items" ><span style="white-space:normal !important;font-family:'Khmer OS Content';line-height:17px; display: block;padding-left: 1px; padding: 2px 1px;"><?php echo $row['contact_name'];?></span></td>
						<td class="items"><span style="white-space:normal !important;width:120px;!important;"><?php echo $row['phone'];?></span></td>
						<td class="items" ><?php echo $row['email'];?></td>
						<td class="items" ><?php echo $row['address']."-".$row["province"];?></td>
						<td class="items" ><?php echo number_format($total,2);?></td>
						<td class="items" ><?php echo number_format($total_paid,2);?></td>
						<td class="items" ><?php echo number_format($total_balance,2);?></td>
						<td class="items" style=" white-space: normal; text-align: left;"><?php echo $row['user_name'];?></td>
						<td class="items" style="white-space: normal; text-align: left;"><a href="<?php echo $this->baseUrl();?>/report/index/rptcuinvoicepayment/id/<?php echo $row["customer_id"];?>" ><?php echo $row['View'];?></a></td>
					</tr>
					<?php $cu_id=$row["customer_id"];}?>
					<?php $counter='<strong style="float:right;padding:5px">Number of record(s): '.count($this->rsreceitp).'</strong>'; 
					$footer = '<div class="footer_list">'.$stringPagination.$counter.'</div>';?>
						<?php } ?>
							</table></div></form><?php echo $footer?>
						</td>
					</tr>
			</table>
		</div>	
	</div>
</div>
<iframe name=print_frame width=0 height=0 frameborder=0 src=about:blank></iframe>
<script type="text/javascript">
	function doPrint() {var divToPrint = document.getElementById('divPrint');var htmlToPrint = '' +'<style type="text/css">' +'</style>';htmlToPrint += divToPrint.outerHTML;window.document.write(htmlToPrint);window.print();window.close();}
	dojo.require("dijit.form.DateTextBox");
</script>
