<?php 
	$formFilter = $this->formFilter;
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
?>
<title><?php echo $tr->translate("Expense List");?></title>
<div class="card pb-10 pt-10 pl-10 pr-10">
	<div class="card-content">
		<div class="card-box">
			<form method="post" autocomplete="off">
				<div class="form-group" style="padding-top: 6px;">
					<label class="control-label col-md-2"><?php echo $formFilter->getElement('text_search');?></label>
					<label class="control-label col-md-2"><?php echo $formFilter->getElement('branch_id');?></label>
					<label class="control-label col-md-2"><?php echo $formFilter->getElement('title');?></label>
					<label class="control-label col-md-2"><?php echo $formFilter->getElement('start_date');?></label>
					<label class="control-label col-md-2"><?php echo $formFilter->getElement('end_date');?></label>
					<label class="control-label col-md-2">
						<input type="submit" value="btnsavenew" id="btnsavenew" name="save_close" label="<?php echo $tr->translate("REFRESH")?>" dojoType="dijit.form.Button" 
							iconClass="dijitIconSearch" />
					</label>
				</div>			
			</form> 
		</div>
		<div class="card-box">
			<?php echo $this->list;?>
		</div>
	</div>
</div>
<script>
dojo.require("dijit.form.DateTextBox");
</script>