<?php 
	$url_new = $this->url(array('module'=>'product','controller'=>'brand','action'=>'add',));
	$url_edit = $this->url(array('module'=>'product','controller'=>'brand','action'=>'edit'));
	$url_delete = $this->url(array('module'=>'product','controller'=>'brand','action'=>'delete',));
	$url_cencel = $this->url(array('module'=>'product','controller'=>'brand','action'=>'index'),null,true);
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$formFilter = $this->frmAdd;
?>
<title><?php echo $tr->translate("EDIT_BRAND");?></title>
<div class="card pb-10 pt-10 pl-10 pr-10">
	<div class="card-content">
		<div class="card-box">
            <div class="col-sm-12 border-botom">
		    	<div class="col-sm-8 pd-0">
		    		<h4 class="m-b-0"><i class="fa fa-cube" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('EDIT_BRAND');?></h4>
    			</div>
    			<div class="col-sm-4 text-right">
    			</div>
    		</div>
    	</div>
		<div class="card-box">	
			<form dojoType="dijit.form.Form"  class="form-horizontal" method="post" action="<?php echo $url_edit;?>" >
				<script type="dojo/method" event="onSubmit">			
					if(this.validate()) {
               			loadingBlock();
						return true;
					}else{
						return false;
					}
				</script>
				<div class="col-md-6">
					<div class="form-group">
						<label class="col-md-4 control-label"><?php echo $tr->translate("PARENT");?></label>
						<div class="col-md-8">
								<?php echo $formFilter->getElement('parent');?>
						</div>
					</div>
					<div class="form-group">						
						<label class="col-md-4 control-label"><?php echo $tr->translate("BRAND_NAME");?></label>
						<div class="col-md-8">
							<?php echo $formFilter->getElement('brand_name');?>
						</div>
					</div>
					<div class="form-group">
						<label class="col-md-4 control-label"><?php echo $tr->translate("STATUS");?></label>
						<div class="col-md-8">
								<?php echo $formFilter->getElement('status');?>
						</div>
					</div>
					<div class="form-group">	
							<label class="col-md-4 control-label"><?php echo $tr->translate("REMARK");?></label>
							<div class="col-md-8">
								<?php echo $formFilter->getElement('remark');?>
							</div>
						</div>
						<div class="form-group">
								<label  class="col-md-12 col-md-offset-4 col-md-8">
									<button type="submit" name="saveclose" value="saveclose" class="btn btn-primary" ><i class="glyphicon glyphicon-log-in"></i> <?php echo $tr->translate("SAVE_CLOSE")?></button>
								</label>
						</div>
					</div>
				</div>
			</form>
		</div>
	</div>
</div>